import {createHash,randomUUID} from 'node:crypto';

export type EvidenceMode='OFF'|'ON';
export type VisualTaskType='image'|'blender'|'browser'|'desktop'|'visual-application';
export type EvidenceOutcome='SUCCEEDED'|'FAILED'|'CANCELLED'|'TIMED_OUT';
export interface EvidencePolicy{schema:'agent-control.automatic-evidence-policy/v1';mode:EvidenceMode;captureRequired:boolean;continueWhenUnavailable:boolean;maximumMs:number;maximumBytes:number;retention:'run-history'|'release-evidence';}
export interface EvidenceOverlay{product:'Agent Control';jobId:string;shortJobId:string;task:string;stage:string;worker:string;provider:string|null;status:string;elapsedMs:number;observedAt:string;}
export interface EvidenceCaptureAdvertisement{schema:'agent-control.visual-evidence-provider/v1';id:string;taskTypes:VisualTaskType[];formats:string[];availability:'AVAILABLE'|'UNAVAILABLE';maximumMs:number;maximumBytes:number;supportsOverlay:boolean;}
export interface EvidenceCaptureResult{jobId:string;bytes:Uint8Array;mimeType:string;startedAt:string;endedAt:string;frames:number|null;sourceHashes:string[];}
export interface EvidenceCaptureSession{update(overlay:EvidenceOverlay):Promise<void>|void;stop(outcome:EvidenceOutcome,signal?:AbortSignal):Promise<EvidenceCaptureResult>;cancel?(reason:string):Promise<void>|void;}
export interface EvidenceCapturePort{advertise():EvidenceCaptureAdvertisement;start(input:{jobId:string;taskType:VisualTaskType;overlay:EvidenceOverlay;policy:EvidencePolicy},signal:AbortSignal):Promise<EvidenceCaptureSession>;}
export interface AutomaticEvidenceManifest{schema:'agent-control.automatic-visual-evidence/v1';id:string;jobId:string;taskType:VisualTaskType;provider:string|null;state:'DISABLED'|'CAPTURED'|'UNAVAILABLE'|'FAILED';limitation:string|null;startedAt:string|null;endedAt:string;outcome:EvidenceOutcome|null;mimeType:string|null;sha256:string|null;sizeBytes:number|null;sourceHashes:string[];overlays:EvidenceOverlay[];retention:EvidencePolicy['retention'];}

const hash=(value:Uint8Array|string)=>createHash('sha256').update(value).digest('hex');
const bounded=(value:string,max:number)=>value.replace(/[\r\n]/g,' ').slice(0,max);
export const defaultEvidencePolicy=():EvidencePolicy=>({schema:'agent-control.automatic-evidence-policy/v1',mode:'OFF',captureRequired:false,continueWhenUnavailable:true,maximumMs:90000,maximumBytes:32*1024*1024,retention:'run-history'});

export class AutomaticEvidenceRuntime{
 private policy:EvidencePolicy;private ports:EvidenceCapturePort[]=[];private active=new Map<string,{session:EvidenceCaptureSession;provider:string;taskType:VisualTaskType;startedAt:string;overlays:EvidenceOverlay[]}>();private manifests=new Map<string,AutomaticEvidenceManifest>();
 constructor(policy:EvidencePolicy=defaultEvidencePolicy(),private readonly clock=()=>new Date()){this.policy=validatePolicy(policy);}
 configure(policy:EvidencePolicy){if(this.active.size)throw Error('automatic_evidence_active');this.policy=validatePolicy(policy);return this.projection();}
 register(port:EvidenceCapturePort){const ad=validateAdvertisement(port.advertise());if(this.ports.some(item=>item.advertise().id===ad.id))throw Error('automatic_evidence_provider_exists');this.ports.push(port);return this;}
 projection(){return{schema:'agent-control.automatic-evidence-projection/v1',policy:structuredClone(this.policy),providers:this.ports.map(port=>structuredClone(port.advertise())),active:[...this.active.keys()],records:this.list()};}
 list(){return[...this.manifests.values()].sort((a,b)=>a.endedAt.localeCompare(b.endedAt)).map(item=>structuredClone(item));}
 async begin(input:{jobId:string;taskType:VisualTaskType;task:string;stage:string;worker:string;provider?:string|null;status:string},signal=new AbortController().signal){
  if(!input.jobId.trim()||this.active.has(input.jobId)||this.manifests.has(input.jobId))throw Error('automatic_evidence_job_invalid');const at=this.clock().toISOString();
  if(this.policy.mode==='OFF'){const record=this.record(input.jobId,input.taskType,{state:'DISABLED',limitation:'automatic_evidence_off',endedAt:at});return record;}
  const candidates=this.ports.filter(port=>{const ad=port.advertise();return ad.availability==='AVAILABLE'&&ad.taskTypes.includes(input.taskType)&&ad.supportsOverlay&&ad.maximumMs>=this.policy.maximumMs&&ad.maximumBytes>=this.policy.maximumBytes;});
  if(!candidates.length){const record=this.record(input.jobId,input.taskType,{state:'UNAVAILABLE',limitation:'compatible_capture_provider_unavailable',endedAt:at});if(this.policy.captureRequired||!this.policy.continueWhenUnavailable){const error=Error('automatic_evidence_unavailable');Object.assign(error,{evidenceManifest:record});throw error;}return record;}
  const overlay=this.overlay(input,at,0),selected=candidates[0]!,session=await selected.start({jobId:input.jobId,taskType:input.taskType,overlay,policy:structuredClone(this.policy)},signal);this.active.set(input.jobId,{session,provider:selected.advertise().id,taskType:input.taskType,startedAt:at,overlays:[overlay]});return{state:'ACTIVE',provider:selected.advertise().id,overlay};
 }
 async update(jobId:string,input:{task:string;stage:string;worker:string;provider?:string|null;status:string}){const active=this.active.get(jobId);if(!active)return false;const at=this.clock().toISOString(),overlay=this.overlay({jobId,...input},at,Date.parse(at)-Date.parse(active.startedAt));active.overlays.push(overlay);await active.session.update(overlay);return true;}
 async finish(jobId:string,outcome:EvidenceOutcome,signal=new AbortController().signal){const active=this.active.get(jobId);if(!active)return this.manifests.get(jobId);this.active.delete(jobId);try{const result=await active.session.stop(outcome,signal);if(result.jobId!==jobId||!result.bytes.length||result.bytes.length>this.policy.maximumBytes||!/^video\//.test(result.mimeType)||Date.parse(result.endedAt)<Date.parse(result.startedAt))throw Error('automatic_evidence_result_invalid');return this.record(jobId,active.taskType,{state:'CAPTURED',provider:active.provider,startedAt:active.startedAt,endedAt:result.endedAt,outcome,mimeType:result.mimeType,sha256:hash(result.bytes),sizeBytes:result.bytes.length,sourceHashes:[...new Set(result.sourceHashes)],overlays:active.overlays,bytes:new Uint8Array(result.bytes)});}catch(error){await active.session.cancel?.('capture-finalization-failed');if(this.policy.captureRequired||!this.policy.continueWhenUnavailable)throw error;return this.record(jobId,active.taskType,{state:'FAILED',provider:active.provider,startedAt:active.startedAt,endedAt:this.clock().toISOString(),outcome,limitation:bounded(error instanceof Error?error.message:String(error),160),overlays:active.overlays});}}
 artifact(jobId:string){const record=this.manifests.get(jobId) as (AutomaticEvidenceManifest&{bytes?:Uint8Array})|undefined;return record?.bytes?{manifest:structuredClone({...record,bytes:undefined}),bytes:new Uint8Array(record.bytes)}:undefined;}
 private overlay(input:{jobId:string;task:string;stage:string;worker:string;provider?:string|null;status:string},at:string,elapsedMs:number):EvidenceOverlay{return{product:'Agent Control',jobId:input.jobId,shortJobId:input.jobId.slice(0,12),task:bounded(input.task,160),stage:bounded(input.stage,120),worker:bounded(input.worker,120),provider:input.provider?bounded(input.provider,120):null,status:bounded(input.status,64),elapsedMs:Math.max(0,elapsedMs),observedAt:at};}
 private record(jobId:string,taskType:VisualTaskType,input:Partial<AutomaticEvidenceManifest>&{state:AutomaticEvidenceManifest['state'];endedAt:string;bytes?:Uint8Array}){if(this.manifests.has(jobId))throw Error('automatic_evidence_overwrite_refused');const record:AutomaticEvidenceManifest&{bytes?:Uint8Array}={schema:'agent-control.automatic-visual-evidence/v1',id:`visual-evidence-${randomUUID()}`,jobId,taskType,provider:input.provider??null,state:input.state,limitation:input.limitation??null,startedAt:input.startedAt??null,endedAt:input.endedAt,outcome:input.outcome??null,mimeType:input.mimeType??null,sha256:input.sha256??null,sizeBytes:input.sizeBytes??null,sourceHashes:input.sourceHashes??[],overlays:input.overlays??[],retention:this.policy.retention,...(input.bytes?{bytes:input.bytes}: {})};this.manifests.set(jobId,record);return structuredClone(record);}
}

export function bindAutomaticEvidenceToJobs(jobs:import('./job-runtime.js').JobRuntime,evidence:AutomaticEvidenceRuntime){const taskType=(run:import('./job-types.js').RunRecord):VisualTaskType|null=>{const actions=run.steps.map(step=>step.action);if(actions.some(action=>action.startsWith('image.')))return'image';if(actions.some(action=>action.startsWith('blender.')))return'blender';if(actions.some(action=>action.startsWith('browser.')))return'browser';if(actions.some(action=>/computer|desktop|ui\./.test(action)))return'desktop';return null;};const attach=(runId:string,manifest:AutomaticEvidenceManifest|undefined)=>{if(!manifest)return;const run=jobs.ledger.get(runId);if(!run||jobs.artifacts.list(runId).some(item=>item.name==='automatic-visual-evidence'))return;const step=run.steps.at(-1);if(!step)return;const captured=evidence.artifact(runId),value=captured?{manifest:captured.manifest,encoding:'base64',content:Buffer.from(captured.bytes).toString('base64')}:{manifest};const artifact=jobs.artifacts.create(run,step.id,'agent-control-evidence',{name:'automatic-visual-evidence',type:captured?.manifest.mimeType??'application/json',schema:'agent-control.automatic-visual-evidence/v1',version:'1.0.0',retention:manifest.retention},value);step.artifactIds.push(artifact.id);run.artifacts.push(artifact.id);jobs.ledger.update(run,'run.automatic_evidence_recorded',{artifactId:artifact.id,evidenceState:manifest.state});};jobs.registerDispatchGuard({prepare:async({run,step,worker})=>{const type=taskType(run);if(!type)return;const provider=run.trigger.modelRoute?.providerId??null,task=run.effectiveJob.metadata.name??run.jobId;try{const started=await evidence.begin({jobId:run.id,taskType:type,task,stage:step.id,worker:worker.id,provider,status:'ADMITTED'});if('state'in started&&started.state!=='ACTIVE'){attach(run.id,started as AutomaticEvidenceManifest);return;}return{finish:async outcome=>{const manifest=await evidence.finish(run.id,outcome);attach(run.id,manifest);}};}catch(error){const manifest=(error as {evidenceManifest?:AutomaticEvidenceManifest}).evidenceManifest;if(manifest)attach(run.id,manifest);throw error;}}});return jobs.ledger.subscribe((runId,event,status)=>{const run=jobs.ledger.get(runId),type=run&&taskType(run);if(!run||!type)return;const step=run.steps.find(item=>item.status==='RUNNING')??run.steps.find(item=>!['SUCCEEDED','FAILED','CANCELLED'].includes(item.status))??run.steps.at(-1),worker=step?.attempts.at(-1)?.workerId??run.selectedWorkers.at(-1)??'unassigned',provider=run.trigger.modelRoute?.providerId??null,task=run.effectiveJob.metadata.name??run.jobId;void evidence.update(run.id,{task,stage:step?.id??event,worker,provider,status}).catch(()=>{});});}

function validatePolicy(value:EvidencePolicy){if(value.schema!=='agent-control.automatic-evidence-policy/v1'||!['OFF','ON'].includes(value.mode)||!Number.isSafeInteger(value.maximumMs)||value.maximumMs<1000||value.maximumMs>3600000||!Number.isSafeInteger(value.maximumBytes)||value.maximumBytes<1024||value.maximumBytes>1024*1024*1024||!['run-history','release-evidence'].includes(value.retention))throw Error('automatic_evidence_policy_invalid');return structuredClone(value);}
function validateAdvertisement(value:EvidenceCaptureAdvertisement){if(value.schema!=='agent-control.visual-evidence-provider/v1'||!value.id||!value.taskTypes.length||!value.formats.some(item=>item.startsWith('video/'))||value.maximumMs<1000||value.maximumBytes<1024)throw Error('automatic_evidence_provider_invalid');return value;}
