import {createHash} from 'node:crypto';
export type BlenderCapability='blender.scene.create'|'blender.object.create'|'blender.mesh.create'|'blender.material.apply'|'blender.camera.configure'|'blender.light.configure'|'blender.transform.apply'|'blender.import'|'blender.export'|'blender.render'|'blender.validate'|'blender.python.execute';
export type BlenderTechniqueClass='EPHEMERAL_ACTION'|'REUSABLE_PATTERN'|'SKILL_CANDIDATE'|'QUALIFIED_SKILL';
export interface BlenderSkillRequest{jobId:string;capability:BlenderCapability;targetBlendSha256:string|null;parameters:Record<string,unknown>;pythonSource?:string;inputArtifacts:Array<{id:string;sha256:string}>;expectedArtifacts:string[];validation:string[];rollbackRef:string|null;}
export interface BlenderExecutionReceipt{schema:'agent-control.blender-execution/v1';jobId:string;capability:BlenderCapability;sourceSha256:string|null;targetBlendSha256:string|null;parameterSha256:string;inputArtifacts:Array<{id:string;sha256:string}>;stdout:string;stderr:string;resultingSceneSha256:string;artifacts:Array<{name:string;sha256:string}>;validation:string[];rollbackRef:string|null;}
export interface BlenderExecutionPort{execute(request:BlenderSkillRequest,signal:AbortSignal):Promise<Omit<BlenderExecutionReceipt,'schema'|'jobId'|'capability'|'sourceSha256'|'targetBlendSha256'|'parameterSha256'|'inputArtifacts'|'rollbackRef'>>;}
const hash=(value:string)=>createHash('sha256').update(value).digest('hex');
const stable=(value:unknown):string=>JSON.stringify(value&&typeof value==='object'&&!Array.isArray(value)?Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,JSON.parse(stable(v))])):value);
export async function executeBlenderSkill(request:BlenderSkillRequest,port:BlenderExecutionPort,signal=new AbortController().signal){validate(request);if(signal.aborted)throw new Error('blender_job_cancelled');const output=await port.execute(structuredClone(request),signal);if(signal.aborted)throw new Error('blender_job_cancelled');if(!/^[a-f0-9]{64}$/.test(output.resultingSceneSha256)||request.expectedArtifacts.some(name=>!output.artifacts.some(item=>item.name===name))||request.validation.some(check=>!output.validation.includes(check)))throw new Error('blender_skill_verification_failed');const receipt:BlenderExecutionReceipt={schema:'agent-control.blender-execution/v1',jobId:request.jobId,capability:request.capability,sourceSha256:request.pythonSource?hash(request.pythonSource):null,targetBlendSha256:request.targetBlendSha256,parameterSha256:hash(stable(request.parameters)),inputArtifacts:structuredClone(request.inputArtifacts),stdout:output.stdout.slice(0,65536),stderr:output.stderr.slice(0,65536),resultingSceneSha256:output.resultingSceneSha256,artifacts:structuredClone(output.artifacts),validation:structuredClone(output.validation),rollbackRef:request.rollbackRef};return receipt;}
export function classifyBlenderTechnique(input:{successfulRuns:number;distinctJobs:number;boundedContract:boolean;deterministicOrUnderstood:boolean;validated:boolean;failureHandling:boolean;portable:boolean;hiddenAssumptions:boolean;applicationSpecific:boolean}):BlenderTechniqueClass{if(input.applicationSpecific||input.successfulRuns<1)return'EPHEMERAL_ACTION';if(input.successfulRuns<2||input.distinctJobs<2)return'REUSABLE_PATTERN';if(!input.boundedContract||!input.deterministicOrUnderstood||!input.validated||!input.failureHandling||!input.portable||input.hiddenAssumptions)return'SKILL_CANDIDATE';return'QUALIFIED_SKILL';}
function validate(request:BlenderSkillRequest){if(!request.jobId.trim()||!request.validation.length)throw new Error('blender_skill_contract_invalid');if(request.capability==='blender.python.execute'){if(!request.pythonSource?.trim())throw new Error('blender_python_source_required');if(/\b(os\.system|subprocess|socket|requests\.|urllib\.)/.test(request.pythonSource))throw new Error('blender_python_unsafe_boundary');}else if(request.pythonSource)throw new Error('blender_python_requires_raw_capability');if(request.inputArtifacts.some(item=>!item.id||!/^[a-f0-9]{64}$/.test(item.sha256)))throw new Error('blender_input_artifact_invalid');}
