import {createHash} from 'node:crypto';
import type {BlenderCapability,BlenderExecutionReceipt,BlenderTechniqueClass} from './blender-skill.js';
export interface BlenderProcedureStep{id:string;capability:Exclude<BlenderCapability,'blender.python.execute'>;parameters:Record<string,unknown>;checkpoint:string[];recovery:{onFailure:'STOP'|'RETRY_ONCE';validation:string[]};}
export interface BlenderProcedure{schema:'agent-control.blender-procedure/v1';id:string;version:'1.0.0';sourceJobs:string[];prerequisites:string[];parameters:string[];steps:BlenderProcedureStep[];completionCriteria:string[];cancellation:'STOP_AND_VERIFY_NO_OWNED_PROCESS';limitations:string[];sha256:string;}
export interface BlenderSupervisedTrace{jobId:string;receipt:BlenderExecutionReceipt;decomposition:BlenderProcedureStep[];failures:Array<{stepId:string;reason:string;correction:string|null}>;humanIntervention:boolean;supervisor:string;}
export interface BlenderProcedurePort{execute(step:BlenderProcedureStep,parameters:Record<string,unknown>,signal:AbortSignal):Promise<{validation:string[];artifacts:Array<{name:string;sha256:string}>;sceneSha256:string}>;cancel():Promise<{clean:boolean}>;}
export interface BlenderReplayResult{schema:'agent-control.blender-procedure-replay/v1';jobId:string;procedureSha256:string;status:'SUCCEEDED'|'FAILED'|'CANCELLED';supervisorOperationalActions:number;humanIntervention:boolean;steps:Array<{id:string;attempts:number;validation:string[];sceneSha256:string}>;artifacts:Array<{name:string;sha256:string}>;classification:BlenderTechniqueClass;limitation:string;}
const stable=(value:unknown):string=>JSON.stringify(value&&typeof value==='object'&&!Array.isArray(value)?Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,JSON.parse(stable(item))])):value);
const hash=(value:unknown)=>createHash('sha256').update(stable(value)).digest('hex');
export function extractBlenderProcedure(input:{id:string;traces:BlenderSupervisedTrace[];prerequisites:string[];parameters:string[];completionCriteria:string[];limitations:string[]}):BlenderProcedure{if(!/^[a-z][a-z0-9-]{2,80}$/.test(input.id)||!input.traces.length||input.traces.some(trace=>trace.receipt.jobId!==trace.jobId||trace.decomposition.length<2)||!input.prerequisites.length||!input.completionCriteria.length)throw Error('blender_procedure_source_invalid');const signature=stable(input.traces[0]!.decomposition.map(({id,capability,checkpoint,recovery})=>({id,capability,checkpoint,recovery})));if(input.traces.some(trace=>stable(trace.decomposition.map(({id,capability,checkpoint,recovery})=>({id,capability,checkpoint,recovery})))!==signature))throw Error('blender_procedure_inconsistent_trace');const value={schema:'agent-control.blender-procedure/v1' as const,id:input.id,version:'1.0.0' as const,sourceJobs:[...new Set(input.traces.map(trace=>trace.jobId))],prerequisites:[...input.prerequisites],parameters:[...input.parameters],steps:structuredClone(input.traces[0]!.decomposition),completionCriteria:[...input.completionCriteria],cancellation:'STOP_AND_VERIFY_NO_OWNED_PROCESS' as const,limitations:[...input.limitations]};return{...value,sha256:hash(value)};}
export async function replayBlenderProcedure(input:{jobId:string;procedure:BlenderProcedure;parameters:Record<string,unknown>;port:BlenderProcedurePort;signal?:AbortSignal;humanIntervention?:boolean;supervisorOperationalActions?:number}){const signal=input.signal??new AbortController().signal,{sha256,...payload}=input.procedure;if(hash(payload)!==sha256)throw Error('blender_procedure_integrity_failed');for(const name of input.procedure.parameters)if(!(name in input.parameters))throw Error(`blender_procedure_parameter_missing:${name}`);const result:BlenderReplayResult={schema:'agent-control.blender-procedure-replay/v1',jobId:input.jobId,procedureSha256:input.procedure.sha256,status:'FAILED',supervisorOperationalActions:input.supervisorOperationalActions??0,humanIntervention:input.humanIntervention??false,steps:[],artifacts:[],classification:'SKILL_CANDIDATE',limitation:'One bounded procedure does not establish general Blender autonomy.'};try{for(const step of input.procedure.steps){if(signal.aborted)throw Error('blender_procedure_cancelled');let attempts=0,output;do{attempts++;try{output=await input.port.execute(step,input.parameters,signal);}catch(error){if(step.recovery.onFailure==='RETRY_ONCE'&&attempts===1)continue;throw error;}break;}while(attempts<2);if(!output||step.checkpoint.some(check=>!output.validation.includes(check)))throw Error(`blender_procedure_checkpoint_failed:${step.id}`);result.steps.push({id:step.id,attempts,validation:[...output.validation],sceneSha256:output.sceneSha256});result.artifacts.push(...output.artifacts);}if(input.procedure.completionCriteria.some(check=>!result.steps.some(step=>step.validation.includes(check))))throw Error('blender_procedure_completion_failed');result.status='SUCCEEDED';result.classification=!result.humanIntervention&&result.supervisorOperationalActions===0&&new Set(input.procedure.sourceJobs).size>=2?'QUALIFIED_SKILL':'SKILL_CANDIDATE';return result;}catch(error){if(signal.aborted||String(error).includes('cancelled')){const cleanup=await input.port.cancel();result.status=cleanup.clean?'CANCELLED':'FAILED';result.limitation=cleanup.clean?'Replay cancelled with confirmed cleanup.':'Replay cancellation cleanup unproven.';return result;}throw error;}}
