import type {ImageJobRequest,ImageProviderAdvertisement,ImageProviderPort,ImageProviderResult} from './image-capability.js';

export interface ComfyImageProviderOptions{endpoint:string;providerId:string;model:string;modelRevision:string;host:string;accelerator:string;runtime:string;workflow:(request:ImageJobRequest)=>Record<string,unknown>;outputNode:string;pollIntervalMs?:number;timeoutMs?:number;fetch?:typeof fetch;}
type PromptReply={prompt_id?:unknown;error?:unknown};
type HistoryImage={filename?:unknown;subfolder?:unknown;type?:unknown};
type HistoryEntry={status?:{completed?:unknown;status_str?:unknown};outputs?:Record<string,{images?:HistoryImage[]}>};
const delay=(ms:number,signal:AbortSignal)=>new Promise<void>((resolve,reject)=>{const timer=setTimeout(resolve,ms),abort=()=>{clearTimeout(timer);reject(signal.reason instanceof Error?signal.reason:new Error('image_job_cancelled'));};signal.addEventListener('abort',abort,{once:true});if(signal.aborted)abort();});
function endpoint(value:string){const url=new URL(value);if(url.protocol!=='http:'||!['127.0.0.1','localhost','::1'].includes(url.hostname))throw new Error('comfy_endpoint_must_be_loopback_http');url.pathname=url.pathname.replace(/\/$/,'');return url;}
async function checked(response:Response,label:string){if(!response.ok)throw new Error(`${label}:${response.status}`);return response;}

export class ComfyImageProvider implements ImageProviderPort{
  private readonly base:URL;private readonly request:typeof fetch;private active=0;private readonly jobs=new Map<string,string>();
  constructor(private readonly options:ComfyImageProviderOptions){this.base=endpoint(options.endpoint);this.request=options.fetch??fetch;}
  advertise():ImageProviderAdvertisement{return{schema:'agent-control.image-provider/v1',id:this.options.providerId,model:this.options.model,modelRevision:this.options.modelRevision,host:this.options.host,accelerator:this.options.accelerator,runtime:this.options.runtime,availability:'AVAILABLE',capacity:1,active:this.active,timeoutSeconds:Math.ceil((this.options.timeoutMs??900000)/1000),estimatedCost:0,expectedLatencyMs:null,qualification:'QUALIFIED_WITH_LIMITATIONS',capabilities:{operations:['image.generate'],inputMimeTypes:['image/png','image/jpeg','image/webp'],minimumInputs:0,maximumInputs:0,outputFormats:['image/png'],maximumWidth:1024,maximumHeight:1024,externalProcessing:false,supportsCancellation:true,supportsDeterministicSeed:true,supportsMaskInput:false,supportsControlImage:false,supportsTransparentOutput:false,supportsBatchGeneration:false,maximumBatchSize:1,supportsProgress:false}};}
  async execute(job:ImageJobRequest,signal:AbortSignal):Promise<ImageProviderResult>{if(job.operation!=='image.generate')throw new Error('comfy_operation_unsupported');if(this.active)throw new Error('comfy_capacity_exhausted');this.active++;const started=Date.now(),deadline=started+(this.options.timeoutMs??900000);try{const submitted=await checked(await this.request(new URL('/prompt',this.base),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:this.options.workflow(job),client_id:`agent-control-${job.jobId}`}),signal}),'comfy_submit_failed'),reply=await submitted.json() as PromptReply,promptId=typeof reply.prompt_id==='string'?reply.prompt_id:'',acceptedAt=Date.now();if(!promptId)throw new Error('comfy_prompt_id_missing');this.jobs.set(job.jobId,promptId);while(Date.now()<deadline){if(signal.aborted)throw new Error('image_job_cancelled');const response=await checked(await this.request(new URL(`/history/${encodeURIComponent(promptId)}`,this.base),{signal}),'comfy_history_failed'),history=await response.json() as Record<string,HistoryEntry>,entry=history[promptId];if(entry){if(entry.status?.status_str==='error')throw new Error('comfy_execution_failed');const image=entry.outputs?.[this.options.outputNode]?.images?.[0];if(entry.status?.completed===true&&image&&typeof image.filename==='string'){const completedAt=Date.now(),view=new URL('/view',this.base);view.searchParams.set('filename',image.filename);if(typeof image.subfolder==='string')view.searchParams.set('subfolder',image.subfolder);view.searchParams.set('type',typeof image.type==='string'?image.type:'output');const output=await checked(await this.request(view,{signal}),'comfy_output_failed'),bytes=new Uint8Array(await output.arrayBuffer()),fetchedAt=Date.now();return{bytes,mimeType:output.headers.get('content-type')?.split(';')[0]??'image/png',width:job.width,height:job.height,seed:typeof job.parameters?.seed==='number'?job.parameters.seed:null,loadMs:null,inferenceMs:completedAt-acceptedAt,cost:0,parameters:{providerPromptId:promptId,phaseTiming:{submissionMs:acceptedAt-started,executionAndModelLoadMs:completedAt-acceptedAt,outputFetchMs:fetchedAt-completedAt,totalProviderMs:fetchedAt-started},...job.parameters}};}}await delay(this.options.pollIntervalMs??1000,signal);}throw new Error('comfy_job_timeout');}catch(error){if(signal.aborted)await this.cancel(job.jobId).catch(()=>undefined);throw error;}finally{this.jobs.delete(job.jobId);this.active=Math.max(0,this.active-1);}}
  async cancel(jobId:string){const promptId=this.jobs.get(jobId);await this.request(new URL('/interrupt',this.base),{method:'POST'});if(promptId)await this.request(new URL('/queue',this.base),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({delete:[promptId]})});}
}
