import assert from 'node:assert/strict';
import test from 'node:test';
import {ComputerManagedRunController,routeComputerMachine,validateComputerWorkflow,verifyComputerEventStream,type ComputerManagedRunRequest,type ComputerProviderAdvertisement,type ComputerVerifier,type ComputerWorkflowPrimitive} from './computer-use-managed.js';
import type {ComputerAction,ComputerObservation,ComputerProvider,ComputerSession} from './computer-use.js';
import fs from 'node:fs';

const initial:ComputerObservation={revision:'r1',at:'2026-09-29T00:00:00.000Z',target:{machine:'fixture'},elements:[{id:'save',role:'button',name:'Save'}],text:'draft'};
const final:ComputerObservation={...initial,revision:'r2',at:'2026-09-29T00:00:01.000Z',text:'saved',elements:[{id:'confirmation',role:'status',name:'Saved'}]};
function provider(result=final,delay=0){let observations=0,closed=false,cancelled=false;const session:ComputerSession={observe:async()=>observations++?result:initial,act:async(_action:ComputerAction)=>{if(delay)await new Promise(resolve=>setTimeout(resolve,delay));return{detail:'provider accepted action'};},close:async()=>{closed=true;}};const value:ComputerProvider={id:'fixture-provider',capabilities:()=>({operations:['click'],targeting:['accessibility'],persistentSession:true,screenshots:false}),available:async()=>true,open:async()=>session};return{value,closed:()=>closed,cancelled:()=>cancelled};}
const advertisement:ComputerProviderAdvertisement={id:'fixture-provider',levels:['STEP','MANAGED_RUN'],capabilities:['screen','pointer','files'],streamingObservations:false,cancellation:true,humanTakeover:true,nativeVerification:false,persistentSession:true,externalApi:false,estimatedCost:0};
const action:ComputerWorkflowPrimitive={id:'save',kind:'ACTION',action:{operation:'click',elementId:'save'}};
const verifier=(passed=true):ComputerVerifier=>({id:'deterministic-verifier',verify:async({observation,checks})=>({passed,checks:checks.map(check=>({check,passed:passed&&observation.text?.includes(check.value)===true})),detail:passed?'artifact state matched':'artifact state mismatch'})});
function request(level:'STEP'|'MANAGED_RUN',workflow:ComputerWorkflowPrimitive[],overrides:Partial<ComputerManagedRunRequest>={}):ComputerManagedRunRequest{const p=provider();return{runId:`run-${level.toLowerCase()}`,level,objective:'Save deterministic artifact',target:{machine:'fixture'},workflow,verification:[{kind:'text',value:'saved'}],maximumElapsedMs:10000,maximumProviderSpend:0,provider:p.value,providerAdvertisement:advertisement,verifier:verifier(),authority:{authorize:()=> 'ALLOW'},...overrides};}

test('STEP owns one action then enters independent verification',async()=>{const result=await new ComputerManagedRunController().execute(request('STEP',[action]));assert.equal(result.state,'VERIFIED');assert.equal(result.providerExecutionCompleted,true);assert.equal(result.actions,1);assert.equal(result.verifier,'deterministic-verifier');assert.deepEqual(result.events.filter(event=>['ACTION_COMPLETED','VERIFICATION_STARTED','VERIFICATION_PASSED','JOB_SUCCEEDED'].includes(event.type)).map(event=>event.type),['ACTION_COMPLETED','VERIFICATION_STARTED','VERIFICATION_PASSED','JOB_SUCCEEDED']);assert.equal(verifyComputerEventStream(result.events),true);});

test('MANAGED_RUN keeps provider completion distinct from goal verification',async()=>{const result=await new ComputerManagedRunController().execute(request('MANAGED_RUN',[{id:'task',kind:'TASK',objective:'save',steps:[action,{id:'assert',kind:'ASSERT',checks:[{kind:'text',value:'saved'}]}]}]));assert.equal(result.state,'VERIFIED');assert.equal(result.qualification,'AUTONOMOUS');assert.ok(result.events.some(event=>event.type==='PLAN_CREATED'));});

test('provider success cannot override a deliberately failed verifier',async()=>{const p=provider();const result=await new ComputerManagedRunController().execute(request('STEP',[action],{provider:p.value,verifier:verifier(false)}));assert.equal(result.providerExecutionCompleted,true);assert.equal(result.state,'VERIFICATION_FAILED');assert.equal(result.reason,'verification_failed');assert.ok(result.events.some(event=>event.type==='ACTION_COMPLETED'));assert.ok(result.events.some(event=>event.type==='VERIFICATION_FAILED'));assert.ok(result.events.some(event=>event.type==='JOB_FAILED'));});

test('human takeover is explicit auditable and invalidates autonomous classification',async()=>{const human={intervene:async()=>({reason:'ambiguous application state',startedAt:'2026-09-29T00:00:01.000Z',endedAt:'2026-09-29T00:00:02.000Z',paused:true,before:'AWAITING_HUMAN' as const,after:'RESUMING' as const,changes:['focused authorized window'],takeover:true,actor:'human:operator'})};const result=await new ComputerManagedRunController().execute(request('MANAGED_RUN',[{id:'human',kind:'HUMAN_APPROVAL',reason:'ambiguous application state',takeoverAllowed:true},action],{human}));assert.equal(result.state,'VERIFIED');assert.equal(result.qualification,'HUMAN_TAKEOVER');assert.deepEqual(result.events.filter(event=>event.type.startsWith('HUMAN_')).map(event=>event.type),['HUMAN_REQUIRED','HUMAN_TAKEOVER_STARTED','HUMAN_ACTION_RECORDED','HUMAN_TAKEOVER_ENDED']);});

test('workflow validation prevents transcript-like or unsafe structures',()=>{assert.throws(()=>validateComputerWorkflow([action,action],'STEP'),/computer_workflow_invalid/);assert.throws(()=>validateComputerWorkflow([{id:'parallel',kind:'PARALLEL',steps:[action]}],'MANAGED_RUN'),/parallel_mutation_forbidden/);assert.throws(()=>validateComputerWorkflow([{id:'wait',kind:'WAIT',milliseconds:30001},action],'MANAGED_RUN'),/wait_invalid/);assert.deepEqual(validateComputerWorkflow([action],'STEP'),{steps:1,actions:1});});

test('machine routing is capability budget privacy and verification based, never hostname based',()=>{const result=routeComputerMachine([{id:'z-local',local:true,externalApi:false,estimatedCost:0,available:true,evidenceScopes:['WINDOW'],verification:['deterministic'],capabilities:[{id:'screen',state:'AVAILABLE'},{id:'pointer',state:'SUPPORTED'}]},{id:'a-cloud',local:false,externalApi:true,estimatedCost:0.2,available:true,evidenceScopes:['DESKTOP'],verification:['provider-native'],capabilities:[{id:'screen',state:'AVAILABLE'},{id:'pointer',state:'AVAILABLE'}]}],{capabilities:['screen','pointer'],localOnly:true,noExternalApi:true,evidenceRequired:true,evidenceScope:'WINDOW',verification:'deterministic',maximumProviderSpend:0});assert.equal(result.selected,'z-local');assert.deepEqual(result.rejected[0]?.reasons,['local_only','external_api_forbidden','provider_budget_exceeded','evidence_incompatible','verification_incompatible']);});

test('provider budget is enforced before session execution',async()=>{const result=await new ComputerManagedRunController().execute(request('STEP',[action],{providerAdvertisement:{...advertisement,estimatedCost:1},maximumProviderSpend:0}));assert.equal(result.state,'FAILED');assert.equal(result.actions,0);assert.equal(result.reason,'provider_budget_exceeded');assert.equal(result.events.some(event=>event.type==='ACTION_DISPATCHED'),false);});

test('cancellation closes the provider session and produces a terminal audit event',async()=>{const p=provider();const controller=new AbortController();setTimeout(()=>controller.abort(),5);const result=await new ComputerManagedRunController().execute(request('MANAGED_RUN',[{id:'wait',kind:'WAIT',milliseconds:100},action],{provider:p.value}),controller.signal);assert.equal(result.state,'CANCELLED');assert.equal(p.closed(),true);assert.ok(result.events.some(event=>event.type==='CANCELLATION_REQUESTED'));assert.ok(result.events.some(event=>event.type==='CANCELLED'));});

test('computer-use limitations registry records every unqualified boundary',()=>{const value=JSON.parse(fs.readFileSync('config/computer-use-limitations.json','utf8')) as {schema:string;records:Array<{id:string;status:string;limitation:string}>};assert.equal(value.schema,'agent-control.computer-use-limitations/v1');assert.deepEqual(value.records.map(item=>item.id),['CU-LIM-001','CU-LIM-002','CU-LIM-003','CU-LIM-004','CU-LIM-005']);assert.equal(value.records.every(item=>item.status.length>0&&item.limitation.length>0),true);});
