import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {SkyLifecycleComputerProvider,type WindowsMetadata} from './computer-use-sky-lifecycle.js';

function fixture(t:{after(fn:()=>void):void}){
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'sky-lifecycle-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
 const process={id:17,executable:'C:/Editor.exe',startedAt:new Date().toISOString()},window={id:71,app:'editor',title:'Editor'};
 const metadata:WindowsMetadata={at:new Date().toISOString(),process,foreignForeground:false,windows:[{id:71,owner:0,title:'Editor',windowClass:'App',visible:true,foreground:true,x:0,y:0,width:100,height:100,dpi:96}]};
 let calls=0,tree='0 window Editor\n 1 button Safe',url='data:image/png;base64,YQ==',focus:string|undefined='0 window Editor';
 const sky={list_windows:async()=>[window],get_window:async()=>window,get_window_state:async()=>({window,screenshots:[{id:'shot',url,width:100,height:100}],accessibility:{tree,focused_element:focus}}),click:async()=>{calls++;},press_key:async()=>{calls++;},type_text:async()=>{calls++;},activate_window:async()=>{calls++;}};
 const make=()=>new SkyLifecycleComputerProvider({sky,metadata:async()=>({...metadata,at:new Date().toISOString()}),process:{...process},machine:'local',application:'Editor',appId:'editor',rootNativeId:71,evidenceDir:dir,identityFile:path.join(dir,'ids.json'),allowedKeys:['Return'],allowedText:['allowed']});
 return{metadata,sky,make,get calls(){return calls;},setTree:(v:string)=>tree=v,setImage:(v:string)=>url=v,setFocus:(v:string|undefined)=>focus=v};
}
for(const change of ['resize','move','focus'] as const)test(`provider rejects ${change} between observation and input`,async t=>{const f=fixture(t),p=f.make(),root=await p.root(),s=await p.open({machine:'local',application:'Editor',window:root.key}),o=await s.observe();p.reviewCoordinate(20,20);if(change==='resize')f.metadata.windows[0]!.width=101;else if(change==='move')f.metadata.windows[0]!.x=1;else f.metadata.foreignForeground=true;await assert.rejects(()=>s.act({operation:'click',revision:o.revision,source:{x:20,y:20}}),/window_layout_changed|foreground_changed/);assert.equal(f.calls,0);});
test('coordinate review is one use and is invalidated by changed screenshot',async t=>{const f=fixture(t),p=f.make(),root=await p.root(),s=await p.open({machine:'local',application:'Editor',window:root.key});let o=await s.observe();p.reviewCoordinate(20,20);f.setImage('data:image/png;base64,Yg==');await assert.rejects(()=>s.act({operation:'click',revision:o.revision,source:{x:20,y:20}}),/coordinate_review_stale/);assert.equal(f.calls,0);o=await s.observe();p.reviewCoordinate(20,20);assert.equal((await s.act({operation:'click',revision:o.revision,source:{x:20,y:20}})).fallback,true);o=await s.observe();await assert.rejects(()=>s.act({operation:'click',revision:o.revision,source:{x:20,y:20}}),/coordinate_review_stale/);assert.equal(f.calls,1);});
test('persisted identity survives reconnect but coordinate review does not',async t=>{const f=fixture(t),p=f.make(),root=await p.root();await p.preview(root.key);p.reviewCoordinate(20,20);const reconnected=f.make(),current=await reconnected.root();assert.equal(current.detectedAt,root.detectedAt);const s=await reconnected.open({machine:'local',application:'Editor',window:root.key}),o=await s.observe();await assert.rejects(()=>s.act({operation:'click',revision:o.revision,source:{x:20,y:20}}),/coordinate_review_stale/);assert.equal(f.calls,0);});
test('stale revisions and recycled semantic indexes never trigger input',async t=>{const f=fixture(t),p=f.make(),root=await p.root(),s=await p.open({machine:'local',application:'Editor',window:root.key}),o=await s.observe();await assert.rejects(()=>s.act({operation:'click',revision:'old',elementId:'e1'}),/stale_observation/);f.setTree('0 window Editor\n 1 button Different');await assert.rejects(()=>s.act({operation:'click',revision:o.revision,elementId:'e1'}),/stale_element/);assert.equal(f.calls,0);});
test('process identity and screenshot provenance are mandatory',async t=>{const f=fixture(t),p=f.make();f.metadata.process={...f.metadata.process,startedAt:'2000-01-01T00:00:00Z'};await assert.rejects(()=>p.root(),/process_identity_changed/);});
test('text entry requires a configured literal and a focused element',async t=>{const f=fixture(t),p=f.make(),root=await p.root(),s=await p.open({machine:'local',application:'Editor',window:root.key});let o=await s.observe();await assert.rejects(()=>s.act({operation:'typeText',revision:o.revision,text:'C:/unauthorized'}),/text_or_focus_not_authorized/);o=await s.observe();f.setFocus(undefined);await assert.rejects(()=>s.act({operation:'typeText',revision:o.revision,text:'allowed'}),/text_or_focus_not_authorized/);assert.equal(f.calls,0);});
test('provider cannot route to another machine or application',async t=>{const f=fixture(t),p=f.make(),root=await p.root();assert.equal(await p.available({machine:'other',application:'Editor',window:root.key}),false);assert.equal(await p.available({machine:'local',application:'Other',window:root.key}),false);});
