import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import {ComputerProviderRegistry,ComputerUseCapability,DefaultComputerAuthority} from './computer-use.js';
import {PlaywrightComputerProvider} from './computer-use-browser.js';
import {ComputerManagedRunController,DeterministicComputerVerifier} from './computer-use-managed.js';

test('headless Chromium uses semantic elements and verifies visible local result',async()=>{
  const server=http.createServer((_request,response)=>{response.writeHead(200,{'content-type':'text/html'});response.end('<!doctype html><title>Computer Use Test</title><input aria-label="Name"><button onclick="document.querySelector(\'output\').textContent=\'Done \' + document.querySelector(\'input\').value">Apply</button><output>Waiting</output>');});
  await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));
  try{
    const address=server.address();if(!address||typeof address==='string')throw Error('test_listener_missing');
    const provider=new PlaywrightComputerProvider({executablePath:process.env.AGENT_CONTROL_CHROMIUM_EXECUTABLE,allowedPrivateHosts:['127.0.0.1']});
    const base=`http://127.0.0.1:${address.port}/`;
    const result=await new ComputerUseCapability(new ComputerProviderRegistry().register(provider)).execute({taskId:'local-browser-qualification',requestedOutcome:'Show Done Ada',target:{machine:'fixture-controller',browser:'Chromium'},steps:[{operation:'navigate',url:base},{operation:'newTab'},{operation:'navigate',url:`${base}other`},{operation:'focusTab',tab:base},{operation:'typeText',elementId:'e0',text:'Ada'},{operation:'click',elementId:'e1'}],checks:[{kind:'text',value:'Done Ada'},{kind:'title',value:'Computer Use Test'},{kind:'url',value:base}]});
    assert.equal(result.status,'COMPLETE',JSON.stringify({status:result.status,reason:result.reason,events:result.events}));
    assert.equal(result.actions.length,6);
    assert.ok(result.observations.length>=8);
  }finally{await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));}
});
test('headless adapter refuses an unqualified external destination',async()=>{const provider=new PlaywrightComputerProvider({executablePath:process.env.AGENT_CONTROL_CHROMIUM_EXECUTABLE,allowedPrivateHosts:['127.0.0.1']});const result=await new ComputerUseCapability(new ComputerProviderRegistry().register(provider)).execute({taskId:'external-block-test',requestedOutcome:'Inspect page',target:{machine:'fixture-controller',browser:'Chromium'},steps:[{operation:'navigate',url:'https://example.com/'}],checks:[{kind:'title',value:'Example Domain'}]});assert.equal(result.status,'FAILED');assert.match(result.reason??'',/browser_destination_not_qualified/);assert.equal(result.actions.length,0);});

test('provider-neutral MANAGED_RUN drives a real headless browser then verifies independently',async()=>{const server=http.createServer((_request,response)=>{response.writeHead(200,{'content-type':'text/html'});response.end('<!doctype html><title>Managed Run Test</title><input aria-label="Name"><button onclick="document.querySelector(\'output\').textContent=\'Done \'+document.querySelector(\'input\').value">Apply</button><output>Waiting</output>');});await new Promise<void>(resolve=>server.listen(0,'127.0.0.1',resolve));try{const address=server.address();if(!address||typeof address==='string')throw Error('test_listener_missing');const base=`http://127.0.0.1:${address.port}/`,provider=new PlaywrightComputerProvider({executablePath:process.env.AGENT_CONTROL_CHROMIUM_EXECUTABLE,allowedPrivateHosts:['127.0.0.1']});const result=await new ComputerManagedRunController().execute({runId:'managed-browser-qualification',level:'MANAGED_RUN',objective:'Show Done Ada',target:{machine:'fixture-controller',browser:'Chromium'},workflow:[{id:'navigate',kind:'ACTION',action:{operation:'navigate',url:base}},{id:'type',kind:'ACTION',action:{operation:'typeText',elementId:'e0',text:'Ada'}},{id:'apply',kind:'ACTION',action:{operation:'click',elementId:'e1'}}],verification:[{kind:'text',value:'Done Ada'},{kind:'title',value:'Managed Run Test'},{kind:'url',value:base}],maximumElapsedMs:30000,maximumProviderSpend:0,provider,providerAdvertisement:{id:provider.id,levels:['STEP','MANAGED_RUN'],capabilities:provider.capabilities().operations,streamingObservations:false,cancellation:true,humanTakeover:false,nativeVerification:false,persistentSession:true,externalApi:false,estimatedCost:0},verifier:new DeterministicComputerVerifier(),authority:new DefaultComputerAuthority()});assert.equal(result.state,'VERIFIED',JSON.stringify({state:result.state,reason:result.reason,events:result.events}));assert.equal(result.actions,3);assert.equal(result.providerExecutionCompleted,true);assert.equal(result.verification?.passed,true);}finally{await new Promise<void>((resolve,reject)=>server.close(error=>error?reject(error):resolve()));}});
