import test from 'node:test';
import assert from 'node:assert/strict';
import {ComputerProviderRegistry,ComputerUseCapability,type ComputerProvider,type ComputerObservation,type ComputerTask} from './computer-use.js';
import {registerComputerUseActions} from './computer-use-actions.js';
import fs from 'node:fs';
import {parse as parseYaml} from 'yaml';
import {validateJobManifest} from './job-catalog.js';
import {AgentControlService} from './application-service.js';

const target={machine:'fixture',browser:'test'};
const task=(steps:ComputerTask['steps']=[{operation:'click',elementId:'e0'}]):ComputerTask=>({taskId:'run-1',requestedOutcome:'Show Done',target,steps,checks:[{kind:'text',value:'Done'}]});
function fake(options:{fail?:boolean;complete?:boolean;staleOnce?:boolean}={}){
  let acted=0,observed=0;
  const provider:ComputerProvider={id:'fake',capabilities:()=>({operations:['observe','click','typeText'],targeting:['accessibility'],persistentSession:true,screenshots:false}),available:async()=>true,open:async()=>({observe:async():Promise<ComputerObservation>=>({revision:`r${++observed}`,at:new Date().toISOString(),target,elements:[{id:'e0',role:'button',name:'Go'}],text:acted&&options.complete!==false?'Done':'Waiting'}),act:async()=>{if(options.fail)throw Error('provider_crashed');if(options.staleOnce&&acted++===0)throw Error('stale_element');acted++;return{detail:'clicked'};},close:async()=>{}})};
  return {provider,state:()=>({acted,observed})};
}
test('registry discovers providers and rejects duplicates',()=>{const f=fake();const registry=new ComputerProviderRegistry().register(f.provider);assert.equal(registry.list()[0]?.id,'fake');assert.throws(()=>registry.register(f.provider),/duplicate/);});
test('fresh observation verifies result after acknowledged action',async()=>{const f=fake();const result=await new ComputerUseCapability(new ComputerProviderRegistry().register(f.provider)).execute(task());assert.equal(result.status,'COMPLETE');assert.ok(f.state().observed>=3);assert.equal(result.actions.length,1);assert.equal(result.checks[0]?.passed,true);});
test('acknowledged action without observed result is verification failure',async()=>{const f=fake({complete:false});const result=await new ComputerUseCapability(new ComputerProviderRegistry().register(f.provider)).execute(task());assert.equal(result.status,'VERIFICATION_FAILED');});
test('explicit stale observation blocks before action',async()=>{const f=fake();const result=await new ComputerUseCapability(new ComputerProviderRegistry().register(f.provider)).execute(task([{operation:'click',elementId:'e0',revision:'old'}]));assert.equal(result.status,'BLOCKED');assert.equal(f.state().acted,0);});
test('approval boundary blocks consequential outcome',async()=>{const f=fake();const result=await new ComputerUseCapability(new ComputerProviderRegistry().register(f.provider)).execute({...task(),requestedOutcome:'Publish externally'});assert.equal(result.status,'APPROVAL_REQUIRED');assert.equal(f.state().acted,0);});
test('provider failure retains evidence and never completes',async()=>{const f=fake({fail:true});const result=await new ComputerUseCapability(new ComputerProviderRegistry().register(f.provider)).execute(task());assert.equal(result.status,'FAILED');assert.match(result.reason??'',/provider_crashed/);});
test('provider fallback only before any action',async()=>{const first=fake({fail:true}),second=fake();first.provider.id='first';second.provider.id='second';const result=await new ComputerUseCapability(new ComputerProviderRegistry().register(first.provider).register(second.provider)).execute(task());assert.equal(result.status,'COMPLETE');assert.equal(result.provider,'second');assert.equal(result.providerFallbacks,1);});
test('availability failure falls back and observer errors cannot change outcome',async()=>{const first=fake(),second=fake();first.provider.id='first';first.provider.available=async()=>{throw Error('disconnected');};second.provider.id='second';const result=await new ComputerUseCapability(new ComputerProviderRegistry().register(first.provider).register(second.provider),undefined,()=>{throw Error('observer_failed');}).execute(task());assert.equal(result.status,'COMPLETE');assert.equal(result.provider,'second');});
test('unsupported operation blocks with no action',async()=>{const f=fake();const result=await new ComputerUseCapability(new ComputerProviderRegistry().register(f.provider)).execute(task([{operation:'drag'}]));assert.equal(result.status,'BLOCKED');assert.equal(f.state().acted,0);});
test('requested video mode blocks when recording is unavailable',async()=>{const f=fake();const result=await new ComputerUseCapability(new ComputerProviderRegistry().register(f.provider)).execute({...task(),videoEvidence:true});assert.equal(result.status,'BLOCKED');assert.equal(result.reason,'video_evidence_recording_unavailable');assert.equal(f.state().acted,0);});
test('detected credential text is blocked before provider entry',async()=>{const f=fake();const result=await new ComputerUseCapability(new ComputerProviderRegistry().register(f.provider)).execute(task([{operation:'typeText',elementId:'e0',text:'api_key=example-secret-value'}]));assert.equal(result.status,'BLOCKED');assert.equal(f.state().acted,0);});
test('idempotent text entry can rebind a stable semantic target once',async()=>{const f=fake({staleOnce:true});const result=await new ComputerUseCapability(new ComputerProviderRegistry().register(f.provider)).execute({...task([{operation:'typeText',elementId:'e0',text:'Ada'}]),maxRetries:1});assert.equal(result.status,'COMPLETE');assert.equal(result.retries,1);assert.ok(result.events.some(item=>item.phase==='RECOVERY'));});
test('Job action retains blocked evidence before reporting failure',async()=>{const f=fake(),registry=registerComputerUseActions(undefined,new ComputerProviderRegistry().register(f.provider),'fixture');let retained:unknown;const context:any={run:{id:'run-1'},worker:{id:'fixture'},parameters:{taskJson:JSON.stringify({...task(),requestedOutcome:'Publish externally'})},signal:new AbortController().signal,recordEvidence:(_name:string,value:unknown)=>{retained=value;return{id:'artifact-1'};}};await assert.rejects(()=>registry.handler('computer.use@1.0.0')(context),/approval_required.*artifact-1/);assert.equal((retained as {status:string}).status,'APPROVAL_REQUIRED');assert.equal(f.state().acted,0);});
test('Job action returns verified artifact only after observed completion',async()=>{const f=fake(),registry=registerComputerUseActions(undefined,new ComputerProviderRegistry().register(f.provider),'fixture');const context:any={run:{id:'run-1'},worker:{id:'fixture'},parameters:{taskJson:JSON.stringify(task())},signal:new AbortController().signal};const output=await registry.handler('computer.use@1.0.0')(context);assert.deepEqual(output.verification?.[0],'computer-outcome-observed');assert.equal((output.artifacts?.[0]?.value as {status:string}).status,'COMPLETE');});
test('managed Job action returns evidence only after independent goal verification',async()=>{const f=fake(),registry=registerComputerUseActions(undefined,new ComputerProviderRegistry().register(f.provider),'fixture'),events:string[]=[];const managedJson=JSON.stringify({level:'STEP',objective:'Show Done',workflow:[{id:'click',kind:'ACTION',action:{operation:'click',elementId:'e0'}}],verification:[{kind:'text',value:'Done'}],maximumElapsedMs:10000,maximumProviderSpend:0});const context:any={run:{id:'run-managed'},worker:{id:'fixture'},parameters:{managedJson},signal:new AbortController().signal,recordRunEvent:(type:string)=>events.push(type)};const output=await registry.handler('computer.managed@1.0.0')(context);assert.deepEqual(output.verification,['computer-managed-goal-verified']);const result=output.artifacts?.[0]?.value as {state:string;providerExecutionCompleted:boolean};assert.equal(result.state,'VERIFIED');assert.equal(result.providerExecutionCompleted,true);assert.deepEqual(events.filter(type=>['JOB_ACCEPTED','ACTION_COMPLETED','VERIFICATION_STARTED','VERIFICATION_PASSED','JOB_SUCCEEDED'].includes(type)),['JOB_ACCEPTED','ACTION_COMPLETED','VERIFICATION_STARTED','VERIFICATION_PASSED','JOB_SUCCEEDED']);});
test('managed Job action retains provider completion when independent verification fails',async()=>{const f=fake({complete:false}),registry=registerComputerUseActions(undefined,new ComputerProviderRegistry().register(f.provider),'fixture');const managedJson=JSON.stringify({level:'STEP',objective:'Show Done',workflow:[{id:'click',kind:'ACTION',action:{operation:'click',elementId:'e0'}}],verification:[{kind:'text',value:'Done'}],maximumElapsedMs:10000,maximumProviderSpend:0});let retained:unknown;const context:any={run:{id:'run-managed-negative'},worker:{id:'fixture'},parameters:{managedJson},signal:new AbortController().signal,recordEvidence:(_name:string,value:unknown)=>{retained=value;return{id:'artifact-managed-negative'};}};await assert.rejects(()=>registry.handler('computer.managed@1.0.0')(context),/verification_failed.*artifact-managed-negative/);assert.equal((retained as {state:string}).state,'VERIFICATION_FAILED');assert.equal((retained as {providerExecutionCompleted:boolean}).providerExecutionCompleted,true);});
test('Job action rejects a worker that is not the controller-local execution host',async()=>{const f=fake(),registry=registerComputerUseActions(undefined,new ComputerProviderRegistry().register(f.provider),'controller');const context:any={worker:{id:'remote'},run:{id:'run-1'},parameters:{taskJson:JSON.stringify(task())},signal:new AbortController().signal};await assert.rejects(()=>registry.handler('computer.use@1.0.0')(context),/controller_local_worker_required/);assert.equal(f.state().acted,0);});
test('governed Job manifest binds action and verification',()=>{const raw=parseYaml(fs.readFileSync('config/jobs/computer-use.job.yaml','utf8'));const job=validateJobManifest(raw,new Set(['computer.use@1.0.0']));assert.deepEqual(job.spec.steps[0]?.verification,['computer-outcome-observed']);});
test('managed Job manifest binds governed action and independent verification',()=>{const raw=parseYaml(fs.readFileSync('config/jobs/computer-use-managed.job.yaml','utf8'));const job=validateJobManifest(raw,new Set(['computer.managed@1.0.0']));assert.deepEqual(job.spec.steps[0]?.verification,['computer-managed-goal-verified']);assert.equal(job.spec.retry?.attempts,0);});
test('dashboard overview aggregates authoritative Computer Use artifacts',()=>{const evidence={schema:'agent-control.computer-use/v1',status:'COMPLETE',provider:'fake',target:{browser:'Chromium'},startedAt:'2026-09-26T10:00:00Z',endedAt:'2026-09-26T10:00:02Z',checks:[{passed:true}],retries:1,providerFallbacks:0,approval:{required:false},videoEvidence:{recordingRef:null},observations:[]};const service={mustJobRuntime:()=>({artifacts:{list:()=>[{id:'artifact-1',runId:'run-1',name:'computer-use-evidence'}],read:()=>evidence}})} as any;const summary=AgentControlService.prototype.computerUseOverview.call(service);assert.equal(summary.tasks,1);assert.equal(summary.counts.COMPLETE,1);assert.equal(summary.verificationPassRate,1);assert.equal(summary.averageDurationMs,2000);assert.equal(summary.recent[0]?.artifactId,'artifact-1');});
test('dashboard exposes managed mode provider verifier human evidence retries and budget',()=>{const evidence={schema:'agent-control.computer-managed-run/v1',runId:'run-managed',level:'MANAGED_RUN',state:'VERIFIED',provider:'fake',verifier:'independent',startedAt:'2026-09-29T10:00:00Z',endedAt:'2026-09-29T10:00:03Z',budget:{maximumProviderSpend:1,estimatedProviderSpend:.2},verification:{passed:true,checks:[{passed:true}]},observation:{target:{machine:'fixture',application:'editor'}},actions:2,retries:1,human:[{takeover:true}],qualification:'HUMAN_TAKEOVER',events:[]};const service={mustJobRuntime:()=>({artifacts:{list:()=>[{id:'artifact-managed',runId:'run-managed',name:'computer-managed-run'}],read:()=>evidence}})} as any;const summary=AgentControlService.prototype.computerUseOverview.call(service);assert.equal(summary.counts.VERIFIED,1);assert.equal(summary.executionLevels.MANAGED_RUN,1);assert.equal(summary.humanInterventions,1);assert.equal(summary.providerSpend,.2);assert.equal(summary.recent[0]?.verifier,'independent');assert.equal(summary.recent[0]?.actionCount,2);assert.deepEqual(summary.recent[0]?.budget,evidence.budget);});
