import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {DirectRepositoryReviewExecutor, parseRepositoryReviewResponse} from './direct-repository-review-executor.js';
import {ModelRegistry} from './model-registry.js';
import {repositoryCodeReviewDefinition} from './repository-review-definition.js';
import type {ParameterizedJobRun} from './parameterized-job-types.js';
import {WorkParcelStore} from './work-parcels.js';
import {TokenAwareBatonRuntime} from './token-aware-baton-routing.js';

test('repository review invokes the selected provider directly and persists attributable Work Parcels, usage and response evidence', async () => {
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'agent-control-direct-review-')),originalFetch=globalThis.fetch;let requestBody:Record<string,unknown>|undefined;
  globalThis.fetch=async(_input,init)=>{requestBody=JSON.parse(String(init?.body));return new Response(JSON.stringify({id:'provider-response-secret-id',model:'vendor/reviewer',choices:[{finish_reason:'stop',message:{content:JSON.stringify({schema:'agent-control.repository-review/v1',executiveSummary:'Reviewed one frozen chunk.',findings:[],positiveObservations:['Typed boundary'],areasReviewed:['index.ts'],areasNotReviewed:[],verdict:'PASS'})}}],usage:{prompt_tokens:80,completion_tokens:20,total_tokens:100,cost:.002}}),{status:200,headers:{'content-type':'application/json'}})};
  try{
    const models=new ModelRegistry([{id:'external',kind:'openai-compatible',baseUrl:'https://provider.example/v1',wireApi:'chat-completions',auth:{type:'none'},enabled:true}],[{id:'reviewer',provider:'external',providerModel:'vendor/reviewer',capabilities:['repository-review'],qualification:{state:'QUALIFIED',version:'qualification-7',qualifiedAt:'2026-09-01T00:00:00Z',capabilities:['repository-review'],nodes:['controller']},pricing:{currency:'USD',inputPerMillionTokens:1,outputPerMillionTokens:2,effectiveFrom:'2026-09-01',source:'fixture'}}],{roles:{'review.default':{primary:'reviewer',requires:['repository-review']}}}),route=models.route({modelRole:'review.default',nodeId:'controller',requiredCapabilities:['repository-review']}),store=new WorkParcelStore(path.join(root,'parcels.json')),routing=new TokenAwareBatonRuntime(path.join(root,'token-routing.json')),executor=new DirectRepositoryReviewExecutor(models,store,routing);
    const run:ParameterizedJobRun={schema:'agent-control.job-run/v1',id:'run-1',occurrenceId:'occurrence-1',savedJobId:'saved-1',definition:repositoryCodeReviewDefinition,resolvedParameters:{node:'controller',repository:'/repo',ref:'main',scope:'full'},trigger:{type:'manual',actor:'test'},status:'RUNNING',transitions:[{status:'RUNNING',at:'2026-09-01T00:00:00Z'}],requestedAt:'2026-09-01T00:00:00Z',startedAt:'2026-09-01T00:00:00Z',repository:{identity:'repo-id',name:'repo',nodeId:'controller',sourcePath:'/repo',requestedRef:'main',reviewedSha:'0123456789012345678901234567890123456789',dirty:false,dirtyPaths:[],snapshotPath:'/snapshot',snapshotKind:'local-shared-clone'},context:{profile:'STANDARD',files:['index.ts'],changedFiles:[],omittedFiles:[],chunks:[{id:'context-1',files:['index.ts'],sha256:'abc'}],truncated:false},workParcelIds:[],evidence:[],providerResponseIds:[],usage:{source:'unavailable'},errors:[],fallbackHistory:[],retryHistory:[],immutable:false};
    const result=await executor.execute({run,route,instruction:'Return the governed repository-review-v1 object.',contextChunks:[{id:'context-1',content:'===== index.ts =====\nexport const safe = true;',files:['index.ts'],sha256:'abc'}],maximumOutputTokens:1000,maximumCost:1,signal:new AbortController().signal});
    assert.equal(requestBody?.model,'vendor/reviewer');assert.equal((requestBody?.response_format as {type?:string})?.type,'json_schema');assert.equal(((requestBody?.response_format as {json_schema?:{strict?:boolean}})?.json_schema?.strict),true);assert.equal(JSON.stringify(requestBody).includes('codex'),false);assert.equal(result.result.verdict,'PASS');assert.equal(result.usage.totalTokens,100);assert.equal(result.usage.providerReportedCost,.002);assert.equal(result.usage.calculatedCost,.00012);assert.equal(result.usage.cost,.002);assert.equal(result.usage.source,'provider');assert.match(result.providerResponseIds[0],/^sha256:[a-f0-9]{64}$/);assert.equal(result.providerResponseIds[0].includes('provider-response-secret-id'),false);assert.equal(result.workParcelIds.length,1);const parcel=store.get(result.workParcelIds[0])!;assert.equal(parcel.status,'SUCCEEDED');assert.equal(parcel.stages[0].actualRoute?.provider,'external');assert.equal(parcel.stages[0].actualRoute?.model,'reviewer');assert.equal(parcel.telemetry.totalTokens,100);assert.equal(parcel.telemetry.cost,.002);assert.equal(parcel.audit.invocations[0].providerModel,'vendor/reviewer');assert.equal(parcel.audit.invocations[0].qualificationVersion,'qualification-7');assert.equal(parcel.audit.totals.costBasis,'provider-reported');assert.equal(parcel.provenance.some(item=>item.detail===run.repository?.reviewedSha),true);const thread=routing.projection().threads[0];assert.equal(thread.active,false);assert.equal(thread.latest.cumulative.totalTokens,100);assert.equal(thread.latest.context.authority,'unavailable');assert.equal(routing.parcel(thread.parcelId).totalTokens,100);
  }finally{globalThis.fetch=originalFetch;fs.rmSync(root,{recursive:true,force:true})}
});

test('provider review parsing rejects structurally incomplete findings before validation',()=>{
  const base={schema:'agent-control.repository-review/v1',executiveSummary:'summary',findings:[],positiveObservations:[],areasReviewed:['index.ts'],areasNotReviewed:[],verdict:'PASS'};
  assert.equal(parseRepositoryReviewResponse(JSON.stringify(base)).verdict,'PASS');
  assert.throws(()=>parseRepositoryReviewResponse(JSON.stringify({...base,findings:[{id:'f1',severity:'high',title:'Missing evidence'}],verdict:'PASS_WITH_FINDINGS'})),/repository_review_provider_schema_invalid/);
  assert.throws(()=>parseRepositoryReviewResponse(JSON.stringify({...base,verdict:'MAYBE'})),/repository_review_provider_schema_invalid/);
  assert.throws(()=>parseRepositoryReviewResponse('{not json'),/repository_review_provider_json_invalid/);
});
