export const FACEBOOK_PACKAGE='com.facebook.katana';
export const FACEBOOK_OBSERVATION_DAYS=7;
export interface FacebookEventCandidate{groupTitle:string;displayedAge:string;excerpt:string;signals:string[];evidenceRef:string;observedAt:string;}
export function isCollinghamGroupTitle(title:string){return /(^|[^a-z])collingham([^a-z]|$)/i.test(title.trim());}
export function visibleAgeDays(text:string,now=new Date()):number|null{
  const value=text.trim();if(/^(just now|today)(?:\s*[·•:@].*)?$/i.test(value))return 0;if(/^yesterday(?:\s*[·•:@].*)?$/i.test(value))return 1;
  const relative=value.match(/^(\d+)\s*(m|min|mins|minute|minutes|h|hr|hrs|hour|hours|d|day|days|w|wk|wks|week|weeks)\b/i);if(relative){const n=Number(relative[1]),unit=relative[2].toLowerCase();if(unit.startsWith('m')||unit.startsWith('h'))return 0;if(unit.startsWith('d'))return n;return n*7;}
  const absolute=value.match(/^(\d{1,2})\s+(jan(?:uary)?|feb(?:ruary)?|mar(?:ch)?|apr(?:il)?|may|jun(?:e)?|jul(?:y)?|aug(?:ust)?|sep(?:tember)?|oct(?:ober)?|nov(?:ember)?|dec(?:ember)?)(?:\s+(\d{4}))?(?:\s*[·•:@].*)?$/i);if(!absolute)return null;let year=absolute[3]?Number(absolute[3]):now.getUTCFullYear(),parsed=Date.parse(`${absolute[1]} ${absolute[2]} ${year} UTC`);if(!absolute[3]&&parsed>now.getTime()+86400000){year--;parsed=Date.parse(`${absolute[1]} ${absolute[2]} ${year} UTC`);}return Math.max(0,(now.getTime()-parsed)/86400000);
}
export function eventSignals(text:string){const signals:string[]=[];if(/\b(event|meeting|meet-up|fair|fete|festival|concert|show|talk|workshop|class|session|open day|quiz|market|sale|walk|run|performance|fundraiser|coffee morning|celebration|tickets?)\b/i.test(text))signals.push('event-wording');if(/\b(mon|tue(?:s)?|wed(?:nes)?|thu(?:rs)?|fri|sat(?:ur)?|sun)(?:day)?\b|\b\d{1,2}(?:st|nd|rd|th)?\s+(?:jan|feb|mar|apr|may|jun|jul|aug|sep|oct|nov|dec)[a-z]*\b/i.test(text))signals.push('visible-date');if(/\b\d{1,2}(?::\d{2})?\s*(?:am|pm)\b|\b\d{1,2}:\d{2}\b/i.test(text))signals.push('visible-time');if(/\b(at|venue|hall|church|school|pub|community centre|village centre|playing field|library)\b/i.test(text))signals.push('place-wording');return signals;}
function acceptable(signals:string[]){return signals.includes('event-wording')||(signals.includes('visible-date')&&(signals.includes('visible-time')||signals.includes('place-wording')));}
function tokens(text:string){const stop=new Set(['this','that','with','from','your','have','more','what','when','where','and','the','for']);return new Set((text.toLowerCase().match(/[a-z0-9]{3,}/g)||[]).filter(v=>!stop.has(v)));}
function redact(text:string){return text.replace(/\b[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,}\b/gi,'[email redacted]').replace(/(?:\+?\d[\d\s().-]{7,}\d)/g,'[phone redacted]');}
export function refineCandidates(candidates:FacebookEventCandidate[]){const accepted=candidates.map(c=>({...c,excerpt:redact(c.excerpt),signals:eventSignals(c.excerpt)})).filter(c=>{const age=visibleAgeDays(c.displayedAge,new Date(c.observedAt));return age!==null&&age<=FACEBOOK_OBSERVATION_DAYS&&acceptable(c.signals);}),out:FacebookEventCandidate[]=[];for(const candidate of accepted){const ct=tokens(candidate.excerpt),index=out.findIndex(existing=>{if(existing.groupTitle.toLowerCase()!==candidate.groupTitle.toLowerCase()||existing.displayedAge.replace(/\W/g,'').toLowerCase()!==candidate.displayedAge.replace(/\W/g,'').toLowerCase())return false;const et=tokens(existing.excerpt),overlap=[...ct].filter(v=>et.has(v)).length;return overlap>=Math.min(2,Math.ceil(Math.min(ct.size,et.size)*0.5));});if(index<0)out.push(candidate);else if(candidate.excerpt.length>out[index].excerpt.length)out[index]=candidate;}return out;}
export function candidatesFromVisibleText(groupTitle:string,text:string,evidenceRef:string,now=new Date()):FacebookEventCandidate[]{if(!isCollinghamGroupTitle(groupTitle))return[];const lines=text.split(/\r?\n/).map(v=>v.trim()).filter(Boolean),out:FacebookEventCandidate[]=[];for(let i=0;i<lines.length;i++){const age=visibleAgeDays(lines[i],now);if(age===null||age>FACEBOOK_OBSERVATION_DAYS)continue;let end=Math.min(lines.length,i+14);for(let j=i+1;j<end;j++)if(visibleAgeDays(lines[j],now)!==null){end=j;break;}const excerpt=redact(lines.slice(i+1,end).join(' ').slice(0,1200)),signals=eventSignals(excerpt);if(!acceptable(signals))continue;out.push({groupTitle:groupTitle.trim(),displayedAge:lines[i],excerpt,signals,evidenceRef,observedAt:now.toISOString()});}return out;}
