import assert from 'node:assert/strict';import test from 'node:test';
import {GovernedImageRuntime,ImageProviderRegistry,ingestImageAttachment,type ImageJobRequest,type ImageProviderAdvertisement,type ImageProviderPort} from './image-capability.js';
const ad=(id:string,externalProcessing=false,operations:ImageProviderAdvertisement['capabilities']['operations']=['image.generate','image.edit','image.multi_edit']):ImageProviderAdvertisement=>({schema:'agent-control.image-provider/v1',id,model:`model-${id}`,modelRevision:'sha256:fixture',host:externalProcessing?'api.example':'hpubuntu',accelerator:'fixture-gpu',runtime:'fixture',availability:'AVAILABLE',capacity:1,active:0,timeoutSeconds:30,estimatedCost:externalProcessing?.02:0,expectedLatencyMs:externalProcessing?100:200,qualification:'EXPERIMENTAL',capabilities:{operations,inputMimeTypes:['image/png'],minimumInputs:0,maximumInputs:4,outputFormats:['image/png'],maximumWidth:1024,maximumHeight:1024,externalProcessing,supportsCancellation:true}});
const provider=(value:ImageProviderAdvertisement,fail=false):ImageProviderPort=>({advertise:()=>value,execute:async(_request,signal)=>{if(signal.aborted)throw new Error('cancelled');if(fail)throw new Error('fixture_failure');return{bytes:new Uint8Array([137,80,78,71]),mimeType:'image/png',width:512,height:512,seed:7,loadMs:1,inferenceMs:2,cost:value.estimatedCost,parameters:{seed:7,apiKey:'must-not-leak'}};}});
const request=(overrides:Partial<ImageJobRequest>={}):ImageJobRequest=>({jobId:'job-1',operation:'image.generate',instruction:'create a railway station',attachments:[],width:512,height:512,outputFormat:'image/png',privacy:'PRIVATE',route:{mode:'AUTO'},budget:{maximumCost:1,maximumElapsedMs:1000,allowExternal:false},...overrides});
test('routes private work to a compatible local provider and records governed provenance',async()=>{const runtime=new GovernedImageRuntime(new ImageProviderRegistry().register(provider(ad('local'))).register(provider(ad('external',true))));const value=await runtime.execute(request());assert.equal(value.evidence.provider.id,'local');assert.equal(value.artifact.jobId,'job-1');assert.match(value.artifact.sha256,/^[a-f0-9]{64}$/);assert.equal('apiKey' in value.evidence.parameters,false);});
test('explicit roles, immutable hashes and job ownership govern attachments',async()=>{const attachment=ingestImageAttachment({jobId:'job-1',bytes:new Uint8Array([1,2,3]),mimeType:'image/png',originalFilename:'source.png',width:10,height:10,role:'source'});const runtime=new GovernedImageRuntime(new ImageProviderRegistry().register(provider(ad('local'))));const value=await runtime.execute(request({operation:'image.edit',attachments:[attachment]}));assert.equal(value.evidence.inputArtifacts[0]?.sha256,attachment.sha256);attachment.bytes[0]=9;await assert.rejects(runtime.execute(request({operation:'image.edit',attachments:[attachment]})),/hash_invalid/);});
test('fallback is visible and never changes privacy class',async()=>{const privateRuntime=new GovernedImageRuntime(new ImageProviderRegistry().register(provider(ad('external-only',true))));await assert.rejects(privateRuntime.execute(request()),/inadmissible/);const externalRequest=request({privacy:'EXTERNAL_ALLOWED',budget:{maximumCost:1,maximumElapsedMs:1000,allowExternal:true}});const runtime=new GovernedImageRuntime(new ImageProviderRegistry().register(provider(ad('first',true),true)).register(provider(ad('second',true))));const value=await runtime.execute(externalRequest);assert.equal(value.evidence.provider.id,'second');assert.deepEqual(value.evidence.route.fallbacks,['first:fixture_failure']);});
test('cancellation and malformed multi-image input fail closed',async()=>{const runtime=new GovernedImageRuntime(new ImageProviderRegistry().register(provider(ad('local'))));const abort=new AbortController();abort.abort();await assert.rejects(runtime.execute(request(),abort.signal),/cancelled/);await assert.rejects(runtime.execute(request({operation:'image.multi_edit'})),/multiple_inputs/);});
