import {createHash, randomUUID} from 'node:crypto';

export type ImageOperation='image.generate'|'image.edit'|'image.multi_edit'|'image.inpaint'|'image.outpaint'|'image.upscale'|'image.text_render';
export type ImageArtifactRole='source'|'reference'|'mask'|'style_reference'|'subject_reference';
export type ImagePrivacy='PRIVATE'|'EXTERNAL_ALLOWED';
export type ImageRouteMode='AUTO'|'LOCAL'|'COLAB'|'CHEAPEST'|'FASTEST'|'NAMED_PROVIDER'|'NAMED_MODEL';
export interface ImageAttachment{schema:'agent-control.image-attachment/v1';id:string;jobId:string;sha256:string;mimeType:string;originalFilename:string;sizeBytes:number;width:number;height:number;role:ImageArtifactRole;bytes:Uint8Array;}
export interface ImageProviderCapabilities{operations:ImageOperation[];inputMimeTypes:string[];minimumInputs:number;maximumInputs:number;outputFormats:string[];maximumWidth:number;maximumHeight:number;externalProcessing:boolean;supportsCancellation:boolean;}
export interface ImageProviderAdvertisement{schema:'agent-control.image-provider/v1';id:string;model:string;modelRevision:string;host:string;accelerator:string|null;runtime:string;availability:'AVAILABLE'|'DEGRADED'|'UNAVAILABLE';capacity:number;active:number;timeoutSeconds:number;estimatedCost:number|null;expectedLatencyMs:number|null;capabilities:ImageProviderCapabilities;qualification:'QUALIFIED'|'QUALIFIED_WITH_LIMITATIONS'|'EXPERIMENTAL'|'UNQUALIFIED';}
export interface ImageJobRequest{jobId:string;operation:ImageOperation;instruction:string;attachments:ImageAttachment[];width:number;height:number;outputFormat:string;privacy:ImagePrivacy;route:{mode:ImageRouteMode;provider?:string;model?:string};budget:{maximumCost:number|null;maximumElapsedMs:number|null;allowExternal:boolean};parameters?:Record<string,unknown>;}
export interface ImageProviderResult{bytes:Uint8Array;mimeType:string;width:number;height:number;seed:number|null;loadMs:number|null;inferenceMs:number|null;cost:number|null;parameters?:Record<string,unknown>;}
export interface ImageProviderPort{advertise():ImageProviderAdvertisement;execute(request:ImageJobRequest,signal:AbortSignal):Promise<ImageProviderResult>;cancel?(jobId:string):Promise<void>;}
export interface ImageJobEvidence{schema:'agent-control.image-evidence/v1';jobId:string;operation:ImageOperation;instructionSha256:string;inputArtifacts:Array<{id:string;role:ImageArtifactRole;sha256:string}>;outputArtifact:{id:string;sha256:string;mimeType:string;width:number;height:number};provider:{id:string;model:string;revision:string;host:string;accelerator:string|null;runtime:string;externalProcessing:boolean};route:{mode:ImageRouteMode;fallbacks:string[]};timing:{startedAt:string;completedAt:string;elapsedMs:number;loadMs:number|null;inferenceMs:number|null};accounting:{monetaryCost:number|null};seed:number|null;parameters:Record<string,unknown>;verification:string[];}

const sha256=(value:Uint8Array|string)=>createHash('sha256').update(value).digest('hex');
const imageMime=new Set(['image/png','image/jpeg','image/webp']);
export function ingestImageAttachment(input:{jobId:string;bytes:Uint8Array;mimeType:string;originalFilename:string;width:number;height:number;role:ImageArtifactRole}):ImageAttachment{
  if(!input.jobId.trim()||!input.originalFilename.trim())throw new Error('image_attachment_identity_required');
  if(!imageMime.has(input.mimeType)||!input.bytes.length||!Number.isSafeInteger(input.width)||!Number.isSafeInteger(input.height)||input.width<1||input.height<1)throw new Error('image_attachment_invalid');
  return{schema:'agent-control.image-attachment/v1',id:`image-input-${randomUUID()}`,jobId:input.jobId,sha256:sha256(input.bytes),mimeType:input.mimeType,originalFilename:input.originalFilename,sizeBytes:input.bytes.length,width:input.width,height:input.height,role:input.role,bytes:new Uint8Array(input.bytes)};
}

export class ImageProviderRegistry{
  private readonly providers=new Map<string,ImageProviderPort>();
  register(provider:ImageProviderPort){const ad=validateAdvertisement(provider.advertise());if(this.providers.has(ad.id))throw new Error('image_provider_exists');this.providers.set(ad.id,provider);return this;}
  list(){return[...this.providers.values()].map(value=>structuredClone(value.advertise()));}
  get(id:string){return this.providers.get(id);}
  ports(){return[...this.providers.values()];}
}

export class GovernedImageRuntime{
  constructor(private readonly registry:ImageProviderRegistry,private readonly clock=()=>new Date()){}
  async execute(request:ImageJobRequest,signal=new AbortController().signal){validateRequest(request);const candidates=this.rank(request);if(!candidates.length)throw new Error('image_provider_unavailable_or_inadmissible');const fallbacks:string[]=[];let last:unknown;
    for(const provider of candidates){const ad=provider.advertise();if(signal.aborted)throw new Error('image_job_cancelled');const started=this.clock();try{const result=await provider.execute(structuredClone(request),signal);if(signal.aborted)throw new Error('image_job_cancelled');validateResult(request,result);const completed=this.clock(),bytes=new Uint8Array(result.bytes),output={id:`image-output-${randomUUID()}`,sha256:sha256(bytes),mimeType:result.mimeType,width:result.width,height:result.height};const evidence:ImageJobEvidence={schema:'agent-control.image-evidence/v1',jobId:request.jobId,operation:request.operation,instructionSha256:sha256(request.instruction),inputArtifacts:request.attachments.map(item=>({id:item.id,role:item.role,sha256:item.sha256})),outputArtifact:output,provider:{id:ad.id,model:ad.model,revision:ad.modelRevision,host:ad.host,accelerator:ad.accelerator,runtime:ad.runtime,externalProcessing:ad.capabilities.externalProcessing},route:{mode:request.route.mode,fallbacks},timing:{startedAt:started.toISOString(),completedAt:completed.toISOString(),elapsedMs:completed.getTime()-started.getTime(),loadMs:result.loadMs,inferenceMs:result.inferenceMs},accounting:{monetaryCost:result.cost},seed:result.seed,parameters:sanitize(result.parameters??request.parameters??{}),verification:['output-bytes-present','output-hash-recomputed','job-ownership-matched','provider-capability-admitted']};return{artifact:{...output,jobId:request.jobId,bytes},evidence};}catch(error){last=error;fallbacks.push(`${ad.id}:${safeReason(error)}`);if(signal.aborted)await provider.cancel?.(request.jobId).catch(()=>undefined);}}
    throw new Error(`image_job_failed:${fallbacks.join(',')}`,{cause:last});
  }
  private rank(request:ImageJobRequest){return this.registry.ports().filter(provider=>admissible(provider.advertise(),request)).sort((a,b)=>score(a.advertise(),request)-score(b.advertise(),request));}
}

function admissible(ad:ImageProviderAdvertisement,request:ImageJobRequest){const c=ad.capabilities;if(ad.availability!=='AVAILABLE'||ad.active>=ad.capacity||!c.operations.includes(request.operation)||request.attachments.length<c.minimumInputs||request.attachments.length>c.maximumInputs||request.attachments.some(item=>!c.inputMimeTypes.includes(item.mimeType))||!c.outputFormats.includes(request.outputFormat)||request.width>c.maximumWidth||request.height>c.maximumHeight)return false;if((request.privacy==='PRIVATE'||!request.budget.allowExternal)&&c.externalProcessing)return false;if(request.budget.maximumCost!==null&&(ad.estimatedCost===null||ad.estimatedCost>request.budget.maximumCost))return false;if(request.budget.maximumElapsedMs!==null&&(ad.expectedLatencyMs===null||ad.expectedLatencyMs>request.budget.maximumElapsedMs))return false;if(request.route.mode==='LOCAL'&&c.externalProcessing||request.route.mode==='COLAB'&&ad.host.toLowerCase()!=='colab'||request.route.mode==='NAMED_PROVIDER'&&ad.id!==request.route.provider||request.route.mode==='NAMED_MODEL'&&ad.model!==request.route.model)return false;return true;}
function score(ad:ImageProviderAdvertisement,request:ImageJobRequest){if(request.route.mode==='CHEAPEST')return ad.estimatedCost??Number.MAX_SAFE_INTEGER;if(request.route.mode==='FASTEST')return ad.expectedLatencyMs??Number.MAX_SAFE_INTEGER;return(ad.capabilities.externalProcessing?1000:0)+(ad.expectedLatencyMs??999999)/100000+(ad.estimatedCost??100);}
function validateAdvertisement(ad:ImageProviderAdvertisement){if(ad.schema!=='agent-control.image-provider/v1'||!ad.id||!ad.model||!ad.modelRevision||!ad.host||!ad.runtime||ad.capacity<1||ad.active<0||ad.active>ad.capacity||!ad.capabilities.operations.length)throw new Error('image_provider_advertisement_invalid');return ad;}
function validateRequest(request:ImageJobRequest){if(!request.jobId.trim()||!request.instruction.trim()||request.width<1||request.height<1)throw new Error('image_job_invalid');if(request.attachments.some(item=>item.jobId!==request.jobId||sha256(item.bytes)!==item.sha256))throw new Error('image_attachment_ownership_or_hash_invalid');const count=request.attachments.length;if(request.operation==='image.generate'&&count!==0)throw new Error('image_generate_inputs_not_allowed');if(request.operation==='image.edit'&&count!==1)throw new Error('image_edit_requires_one_input');if(request.operation==='image.multi_edit'&&count<2)throw new Error('image_multi_edit_requires_multiple_inputs');if(request.operation==='image.inpaint'&&!request.attachments.some(item=>item.role==='mask'))throw new Error('image_inpaint_mask_required');}
function validateResult(request:ImageJobRequest,result:ImageProviderResult){if(!result.bytes.length||!imageMime.has(result.mimeType)||result.width<1||result.height<1)throw new Error('image_output_invalid');if(request.budget.maximumCost!==null&&(result.cost===null||result.cost>request.budget.maximumCost))throw new Error('image_budget_exceeded');}
function sanitize(input:Record<string,unknown>){return Object.fromEntries(Object.entries(input).filter(([key])=>!/token|secret|cookie|password|authorization|api.?key/i.test(key)));}
function safeReason(error:unknown){return(error instanceof Error?error.message:String(error)).replace(/[\r\n]/g,' ').slice(0,160);}
