import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {JobCatalog} from './job-catalog.js';
import {ActionFailure, ActionRegistry, ArtifactStore, JobRuntime, ResourceLockManager, RunLedger, WorkerRegistry} from './job-runtime.js';
import type {JobDefinition, ScheduleDefinition, WorkerRegistration} from './job-types.js';
import {registerBrowserActions} from './browser-actions.js';
import {registerReferenceActions} from './reference-actions.js';
import {createInvocationStart, MemoryHarnessEfficiencyLedger, type HarnessEfficiencyLedgerPort} from './harness-efficiency.js';

const worker = (id: string, capabilities: string[], health: WorkerRegistration['health'] = 'healthy', extra: Partial<WorkerRegistration> = {}): WorkerRegistration => ({id, capabilities, health, capacity: 1, active: 0, observedAt: new Date().toISOString(), ...extra});
const job = (steps: JobDefinition['spec']['steps'], extra: Partial<JobDefinition['spec']> = {}): JobDefinition => ({apiVersion: 'agent-control/v1', kind: 'Job', metadata: {id: 'job', name: 'Job', version: '1.0.0'}, spec: {priority: 'normal', concurrency: 'no-overlap', steps, ...extra}});
function runtime(definition: JobDefinition, handlers: (actions: ActionRegistry) => void, workers: WorkerRegistration[], schedule?: ScheduleDefinition, clock?: () => Date, efficiency?: HarnessEfficiencyLedgerPort) { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-control-runtime-')), actions = new ActionRegistry(); handlers(actions); const catalog = new JobCatalog(actions.ids()); catalog.addJob(definition); if (schedule) catalog.addSchedule(schedule); const registry = new WorkerRegistry(); workers.forEach(item => registry.register(item)); return {root, actions, catalog, workers: registry, runtime: new JobRuntime(catalog, actions, registry, new RunLedger(path.join(root, 'ledger.json')), new ArtifactStore(path.join(root, 'artifacts')), new ResourceLockManager(path.join(root, 'locks.json')), {now: clock, approval: () => true, efficiency})}; }

test('manual Run uses capability placement, typed artifact handoff and verified completion', async () => { let consumed = 0; const setup = runtime(job([{id: 'produce', action: 'produce@1.0.0', requires: ['source'], outputs: [{name: 'data', type: 'application/json', schema: 'data/v1', version: '1.0.0'}], verification: ['schema']}, {id: 'consume', action: 'consume@1.0.0', requires: ['sink'], dependsOn: ['produce'], inputs: {data: 'produce.data'}, verification: ['tests']}]), actions => { actions.register('produce@1.0.0', async () => ({artifacts: [{name: 'data', value: {count: 3}}], verification: ['schema']})); actions.register('consume@1.0.0', async context => { consumed = (context.readArtifact(context.inputArtifacts[0].id) as {count: number}).count; return {verification: ['tests']}; }); }, [worker('source-worker', ['source']), worker('sink-worker', ['sink'])]); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); assert.equal(setup.runtime.ledger.get(run.id)?.steps[0].status, 'SUCCEEDED'); await setup.runtime.tick(); const complete = setup.runtime.ledger.get(run.id)!; assert.equal(complete.status, 'SUCCEEDED'); assert.equal(consumed, 3); assert.deepEqual(complete.selectedWorkers, ['source-worker', 'sink-worker']); assert.equal(setup.runtime.artifacts.list(run.id).length, 1); });
test('incapable, offline and expired workers are rejected with visible rationale', async () => { const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['required']}]), actions => { actions.register('one@1.0.0', async () => ({})); }, [worker('incapable', []), worker('offline', ['required'], 'offline'), worker('expired', ['required'], 'healthy', {capabilityExpiresAt: {required: '2020-01-01T00:00:00Z'}})]); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); const step = setup.runtime.ledger.get(run.id)!.steps[0]; assert.equal(step.status, 'WAITING_FOR_WORKER'); assert.deepEqual(step.placement?.rejected.map(item => item.workerId), ['incapable', 'offline', 'expired']); assert.match(step.waitingReason ?? '', /No worker/); });
test('identical worker waits do not churn and resume when capacity is available', async () => { const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['required']}]), actions => actions.register('one@1.0.0', async () => ({})), [worker('worker', ['required'], 'offline')]); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); const eventsFile = path.join(setup.root, 'run-events.jsonl'), firstCount = fs.readFileSync(eventsFile, 'utf8').trim().split('\n').length; assert.equal(setup.runtime.ledger.get(run.id)?.status, 'WAITING'); await setup.runtime.tick(); await setup.runtime.tick(); assert.equal(fs.readFileSync(eventsFile, 'utf8').trim().split('\n').length, firstCount); setup.workers.setHealth('worker', 'healthy'); await setup.runtime.tick(); assert.equal(setup.runtime.ledger.get(run.id)?.status, 'SUCCEEDED'); });
test('resource contention is durable, visible and released after failure', async () => { const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run'], resources: ['exclusive']}], {concurrency: 'allow'}), actions => { actions.register('one@1.0.0', async () => { throw new ActionFailure('permanent', 'configuration'); }); }, [worker('worker', ['run'])]); setup.runtime.locks.acquire(['exclusive'], 'other-run', 'step'); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); assert.equal(setup.runtime.ledger.get(run.id)!.steps[0].status, 'WAITING_FOR_RESOURCE'); assert.match(setup.runtime.queueProjection()[0].reason ?? '', /other-run/); setup.runtime.locks.release('other-run'); await setup.runtime.tick(); assert.equal(setup.runtime.ledger.get(run.id)!.status, 'FAILED'); assert.equal(setup.runtime.locks.list().length, 0); });
test('identical resource waits are transition-driven and resume without ledger churn', async () => { const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run'], resources: ['exclusive']}]), actions => actions.register('one@1.0.0', async () => ({})), [worker('worker', ['run'])]); setup.runtime.locks.acquire(['exclusive'], 'other-run', 'step'); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); const eventsFile = path.join(setup.root, 'run-events.jsonl'), firstCount = fs.readFileSync(eventsFile, 'utf8').trim().split('\n').length; assert.equal(setup.runtime.ledger.get(run.id)?.status, 'WAITING'); await setup.runtime.tick(); await setup.runtime.tick(); assert.equal(fs.readFileSync(eventsFile, 'utf8').trim().split('\n').length, firstCount); setup.runtime.locks.release('other-run'); await setup.runtime.tick(); assert.equal(setup.runtime.ledger.get(run.id)?.status, 'SUCCEEDED'); });
test('retry policy is bounded and every attempt is recorded', async () => { let calls = 0, instant = new Date('2026-01-01T00:00:00Z'); const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run'], verification: ['ok']}], {retry: {attempts: 1, backoffSeconds: 5}}), actions => { actions.register('one@1.0.0', async () => { calls++; if (calls === 1) throw new ActionFailure('temporary', 'execution', true); return {verification: ['ok']}; }); }, [worker('worker', ['run'])], undefined, () => instant); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); assert.equal(setup.runtime.ledger.get(run.id)!.steps[0].status, 'RETRY_PENDING'); instant = new Date(instant.getTime() + 5000); await setup.runtime.tick(); const result = setup.runtime.ledger.get(run.id)!; assert.equal(result.status, 'SUCCEEDED'); assert.equal(result.steps[0].attempts.length, 2); });
test('verification failure is distinct from process completion', async () => { const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run'], verification: ['required-check']}]), actions => { actions.register('one@1.0.0', async () => ({detail: 'process exited zero'})); }, [worker('worker', ['run'])]); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); const result = setup.runtime.ledger.get(run.id)!; assert.equal(result.status, 'DEGRADED'); assert.equal(result.steps[0].attempts[0].errorClass, 'verification'); });
test('upstream failure cancels dependent steps without dispatching them', async () => { let dependentCalls = 0; const setup = runtime(job([{id: 'first', action: 'first@1.0.0', requires: ['run']}, {id: 'second', action: 'second@1.0.0', requires: ['run'], dependsOn: ['first']}]), actions => { actions.register('first@1.0.0', async () => { throw new ActionFailure('bad configuration', 'configuration'); }); actions.register('second@1.0.0', async () => { dependentCalls++; return {}; }); }, [worker('worker', ['run'])]); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); const result = setup.runtime.ledger.get(run.id)!; assert.equal(result.steps[1].status, 'CANCELLED'); assert.equal(result.steps[1].error, 'upstream_failed'); assert.equal(dependentCalls, 0); });
test('approval requirement remains a visible wait until explicitly granted', async () => { const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run'], approval: 'release'}]), actions => actions.register('one@1.0.0', async () => ({})), [worker('worker', ['run'])]); const deniedRuntime = new JobRuntime(setup.catalog, setup.actions, setup.workers, setup.runtime.ledger, setup.runtime.artifacts, setup.runtime.locks, {approval: () => false}), run = deniedRuntime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await deniedRuntime.tick(); assert.equal(deniedRuntime.ledger.get(run.id)!.steps[0].status, 'WAITING_FOR_APPROVAL'); deniedRuntime.approve(run.id, 'release'); await deniedRuntime.tick(); assert.equal(deniedRuntime.ledger.get(run.id)!.status, 'SUCCEEDED'); });
test('approval waits are reported as WAITING and repeated ticks do not duplicate events', async () => { const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run'], approval: 'release'}]), actions => actions.register('one@1.0.0', async () => ({})), [worker('worker', ['run'])]); const deniedRuntime = new JobRuntime(setup.catalog, setup.actions, setup.workers, setup.runtime.ledger, setup.runtime.artifacts, setup.runtime.locks, {approval: () => false}), run = deniedRuntime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await deniedRuntime.tick(); const eventsFile = path.join(setup.root, 'run-events.jsonl'), firstCount = fs.readFileSync(eventsFile, 'utf8').trim().split('\n').length; assert.equal(deniedRuntime.ledger.get(run.id)?.status, 'WAITING'); await deniedRuntime.tick(); await deniedRuntime.tick(); assert.equal(fs.readFileSync(eventsFile, 'utf8').trim().split('\n').length, firstCount); });
test('cancellation aborts execution and retains the exclusive lock until the handler returns', async () => { let release!: () => void; const waiting = new Promise<void>(resolve => { release = resolve; }); const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run'], resources: ['exclusive']}]), actions => { actions.register('one@1.0.0', async () => { await waiting; return {}; }); }, [worker('worker', ['run'])]); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}), executing = setup.runtime.tick(); await new Promise(resolve => setImmediate(resolve)); setup.runtime.cancel(run.id); assert.equal(setup.runtime.locks.list()[0].runId, run.id); release(); await executing; assert.equal(setup.runtime.ledger.get(run.id)?.status, 'CANCELLED'); assert.equal(setup.runtime.locks.list().length, 0); });
test('late cancellation cannot overwrite a successful terminal run', async () => { const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run']}]), actions => actions.register('one@1.0.0', async () => ({})), [worker('worker', ['run'])]); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); const endedAt = setup.runtime.ledger.get(run.id)?.endedAt; assert.equal(setup.runtime.cancel(run.id).status, 'SUCCEEDED'); assert.equal(setup.runtime.ledger.get(run.id)?.endedAt, endedAt); assert.equal(setup.runtime.ledger.get(run.id)?.errors.length, 0); });
test('replace-running links both attempts and keeps the cancelled attempt visible', async () => { let release!: () => void; const waiting = new Promise<void>(resolve => { release = resolve; }); const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run']}], {concurrency: 'replace-running'}), actions => actions.register('one@1.0.0', async () => { await waiting; return {}; }), [worker('worker', ['run'])]); const first = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}), executing = setup.runtime.tick(); await new Promise(resolve => setImmediate(resolve)); const replacement = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); assert.equal(setup.runtime.ledger.get(first.id)?.lineage?.replacedByRunId, replacement.id); assert.equal(replacement.lineage?.replacesRunId, first.id); assert.equal(setup.runtime.ledger.get(first.id)?.status, 'CANCELLED'); release(); await executing; assert.equal(setup.runtime.ledger.list('job').some(item => item.id === first.id), true); });
test('timeout finalizes a retained running efficiency invocation', async () => { const efficiency = new MemoryHarnessEfficiencyLedger(); const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run'], timeoutSeconds: 1}]), actions => actions.register('one@1.0.0', async context => { efficiency.record(createInvocationStart({jobId: context.run.jobId, runId: context.run.id, stepId: context.step.id, taskId: `${context.run.id}:${context.step.id}`, laneId: `job:${context.run.id}`, model: 'configured-model', provider: 'configured-provider', harnessProfile: 'STANDARD', executionStrategy: 'fixture', startedAt: new Date().toISOString(), recipeFingerprint: 'fixture-timeout'})); return new Promise(() => undefined); }), [worker('worker', ['run'])], undefined, undefined, efficiency); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); const invocation = efficiency.list()[0]; assert.equal(setup.runtime.ledger.get(run.id)?.status, 'FAILED'); assert.equal(invocation.state, 'TIMED_OUT'); assert.equal(invocation.verifierResult, 'FAIL'); assert.equal(invocation.finalJobResult, 'FAILED'); assert.equal(invocation.finishReason, 'step_timeout'); });
test('executor error after partial telemetry finalizes rather than leaving UNKNOWN', async () => { const efficiency = new MemoryHarnessEfficiencyLedger(); const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run']}]), actions => actions.register('one@1.0.0', async context => { const id = efficiency.record(createInvocationStart({jobId: context.run.jobId, runId: context.run.id, stepId: context.step.id, taskId: `${context.run.id}:${context.step.id}`, laneId: `job:${context.run.id}`, model: 'configured-model', provider: 'configured-provider', harnessProfile: 'STANDARD', executionStrategy: 'fixture', startedAt: new Date().toISOString(), recipeFingerprint: 'fixture-error'})); const error = new Error('executor_broke_after_response'); Object.assign(error, {efficiencyInvocationIds: [id]}); throw error; }), [worker('worker', ['run'])], undefined, undefined, efficiency); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); const invocation = efficiency.list()[0]; assert.equal(invocation.state, 'FAILED'); assert.equal(invocation.verifierResult, 'FAIL'); assert.equal(invocation.finalJobResult, 'FAILED'); assert.match(invocation.error ?? '', /executor_broke_after_response/); });
test('scheduled and manual triggers share createRun and missed skip is visible without backfill', async () => { let instant = new Date('2026-08-24T06:00:00Z'); const schedule: ScheduleDefinition = {apiVersion: 'agent-control/v1', kind: 'Schedule', metadata: {id: 'daily', name: 'Daily'}, spec: {enabled: true, job: 'job@1.0.0', cron: '0 7 * * *', timezone: 'Europe/London', missedRunPolicy: 'skip'}}; const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: []}]), actions => actions.register('one@1.0.0', async () => ({})), [worker('worker', [])], schedule, () => instant); setup.runtime.setScheduleEnabled('daily', true); instant = new Date('2026-08-25T08:00:00Z'); const created = await setup.runtime.tickSchedules(instant); assert.equal(created.length, 0); assert.equal(setup.runtime.ledger.schedule('daily')?.missedCount, 1); assert.equal(setup.runtime.ledger.list()[0].status, 'MISSED'); const manual = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); assert.equal(manual.steps.length, 1); });
test('a due schedule creates exactly one Run and its next time survives ledger restart', async () => { const instant = new Date('2026-08-24T06:00:00Z'), schedule: ScheduleDefinition = {apiVersion: 'agent-control/v1', kind: 'Schedule', metadata: {id: 'daily', name: 'Daily'}, spec: {enabled: true, job: 'job@1.0.0', cron: '0 7 * * *', timezone: 'Europe/London', missedRunPolicy: 'run-once-immediately'}}; const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: []}]), actions => actions.register('one@1.0.0', async () => ({})), [worker('worker', [])], schedule, () => instant); const state = setup.runtime.ledger.saveSchedule({scheduleId: 'daily', enabled: true, nextScheduledAt: instant.toISOString(), missedCount: 0, updatedAt: instant.toISOString()}); assert.equal(state.enabled, true); assert.equal((await setup.runtime.tickSchedules(instant)).length, 1); assert.equal((await setup.runtime.tickSchedules(instant)).length, 0); const restored = new RunLedger(path.join(setup.root, 'ledger.json')); assert.notEqual(restored.schedule('daily')?.nextScheduledAt, instant.toISOString()); });
test('one invalid due schedule is contained and does not block another due schedule', async () => { const instant = new Date('2026-08-24T07:00:00Z'), first: ScheduleDefinition = {apiVersion: 'agent-control/v1', kind: 'Schedule', metadata: {id: 'invalid', name: 'Invalid'}, spec: {enabled: true, job: 'job@1.0.0', cron: '0 7 * * *', timezone: 'Europe/London', missedRunPolicy: 'run-once-immediately'}}, second: ScheduleDefinition = {...first, metadata: {id: 'valid', name: 'Valid'}}; const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: []}]), actions => actions.register('one@1.0.0', async () => ({})), [worker('worker', [])], first, () => instant); setup.catalog.addSchedule(second); setup.catalog.job('job@1.0.0')!.spec.enabled = false; for (const id of ['invalid', 'valid']) setup.runtime.ledger.saveSchedule({scheduleId: id, enabled: true, nextScheduledAt: instant.toISOString(), missedCount: 0, updatedAt: instant.toISOString()}); const originalCreate = setup.runtime.createRun.bind(setup.runtime); let calls = 0; setup.runtime.createRun = ((...args: Parameters<JobRuntime['createRun']>) => { calls++; if (calls === 1) throw new Error('malformed_scheduled_operation'); setup.catalog.job('job@1.0.0')!.spec.enabled = true; return originalCreate(...args); }) as JobRuntime['createRun']; const created = await setup.runtime.tickSchedules(instant); assert.equal(created.length, 1); assert.equal(setup.runtime.ledger.schedule('invalid')?.lastError, 'malformed_scheduled_operation'); assert.equal(created[0].trigger.id, 'valid'); });
test('a disabled scheduled job records failure and advances instead of rejecting', async () => { const instant = new Date('2026-08-24T07:00:00Z'), schedule: ScheduleDefinition = {apiVersion: 'agent-control/v1', kind: 'Schedule', metadata: {id: 'disabled', name: 'Disabled'}, spec: {enabled: true, job: 'job@1.0.0', cron: '0 7 * * *', timezone: 'Europe/London', missedRunPolicy: 'run-once-immediately'}}, setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: []}], {enabled: false}), actions => actions.register('one@1.0.0', async () => ({})), [worker('worker', [])], schedule, () => instant); setup.runtime.ledger.saveSchedule({scheduleId: 'disabled', enabled: true, nextScheduledAt: instant.toISOString(), missedCount: 0, updatedAt: instant.toISOString()}); assert.deepEqual(await setup.runtime.tickSchedules(instant), []); const state = setup.runtime.ledger.schedule('disabled')!; assert.equal(state.lastError, 'job_disabled'); assert.notEqual(state.nextScheduledAt, instant.toISOString()); });
test('artifact store detects post-write corruption before downstream consumption', () => { const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: []}]), actions => actions.register('one@1.0.0', async () => ({})), [worker('worker', [])]), run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}), artifact = setup.runtime.artifacts.create(run, 'one', 'worker', {name: 'data', type: 'application/json', schema: 'data/v1', version: '1.0.0'}, {safe: true}); fs.writeFileSync(artifact.storageRef, '{}'); assert.throws(() => setup.runtime.artifacts.read(artifact.id), /artifact_checksum_mismatch/); });
test('restart recovery fails closed and retains Git-independent ledger identity and locks', () => { const setup = runtime(job([{id: 'one', action: 'one@1.0.0', requires: ['run'], resources: ['repo']}]), actions => actions.register('one@1.0.0', async () => ({})), [worker('worker', ['run'])]); const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}), changed = setup.runtime.ledger.get(run.id)!; changed.status = 'RUNNING'; changed.steps[0].status = 'RUNNING'; setup.runtime.ledger.update(changed); setup.runtime.locks.acquire(['repo'], run.id, 'one'); const restored = new RunLedger(path.join(setup.root, 'ledger.json')); assert.deepEqual(restored.recoverFailClosed(), [run.id]); assert.equal(restored.get(run.id)?.status, 'DISCONNECTED'); assert.equal(new ResourceLockManager(path.join(setup.root, 'locks.json')).list()[0].runId, run.id); });

function processAlive(pid: number) { try { process.kill(pid, 0); return true; } catch { return false; } }
async function waitForProcessExit(pid: number, timeoutMs = 2500) { const deadline = Date.now() + timeoutMs; while (Date.now() < deadline && processAlive(pid)) await new Promise(resolve => setTimeout(resolve, 25)); return !processAlive(pid); }

test('step timeout permits fast success without erroneous termination', async () => {
  const setup = runtime(job([{id: 'fast', action: 'fast@1.0.0', requires: ['run'], timeoutSeconds: 1}]), actions => actions.register('fast@1.0.0', async () => ({detail: 'fast-success'})), [worker('worker', ['run'])]);
  const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick();
  const result = setup.runtime.ledger.get(run.id)!; assert.equal(result.status, 'SUCCEEDED'); assert.equal(result.steps[0].status, 'SUCCEEDED'); assert.equal(result.steps[0].attempts[0].terminalReason, undefined); assert.equal(setup.workers.list()[0].active, 0);
});

test('step timeout terminates its direct child, records evidence, releases resources and permits lane reuse', async () => {
  const pidFile = path.join(os.tmpdir(), `agent-control-owned-child-${process.pid}.txt`); let calls = 0;
  const setup = runtime(job([{id: 'owned', action: 'owned@1.0.0', requires: ['run'], resources: ['exclusive'], timeoutSeconds: 1}], {concurrency: 'allow'}), actions => actions.register('owned@1.0.0', async context => {
    calls++; if (calls > 1) return {detail: 'lane-reused'};
    await context.ownedExecution.runProcess({command: process.execPath, args: ['-e', `require('node:fs').writeFileSync(${JSON.stringify(pidFile)},String(process.pid));setInterval(()=>{},1000)`]}, context.signal);
    return {};
  }), [worker('worker', ['run'])]);
  try {
    const started = Date.now(), run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); const elapsed = Date.now() - started;
    const result = setup.runtime.ledger.get(run.id)!, attempt = result.steps[0].attempts[0], childPid = Number(fs.readFileSync(pidFile, 'utf8'));
    assert.equal(result.status, 'FAILED'); assert.equal(result.steps[0].status, 'TIMED_OUT'); assert.equal(attempt.timeoutSeconds, 1); assert.equal(attempt.terminalReason, 'step_timeout'); assert.ok((attempt.elapsedMs ?? 0) >= 900); assert.ok(elapsed < 4000); assert.equal(await waitForProcessExit(childPid), true);
    assert.equal(setup.workers.list()[0].active, 0); assert.equal(setup.runtime.locks.list().length, 0);
    const events = fs.readFileSync(path.join(setup.root, 'run-events.jsonl'), 'utf8').trim().split('\n').map(line => JSON.parse(line));
    const timeout = events.find(event => event.type === 'step.timed_out'); assert.deepEqual({jobId: timeout.evidence.jobId, stepId: timeout.evidence.stepId, timeoutSeconds: timeout.evidence.timeoutSeconds, terminalReason: timeout.evidence.terminalReason}, {jobId: 'job', stepId: 'owned', timeoutSeconds: 1, terminalReason: 'step_timeout'}); assert.ok(timeout.evidence.elapsedMs >= 900);
    const retry = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick(); assert.equal(setup.runtime.ledger.get(retry.id)?.status, 'SUCCEEDED'); assert.equal(setup.workers.list()[0].active, 0); assert.equal(setup.runtime.locks.list().length, 0);
  } finally { fs.rmSync(pidFile, {force: true}); }
});

test('step timeout terminates the owned process group including descendants', {skip: process.platform === 'win32'}, async () => {
  const pidFile = path.join(os.tmpdir(), `agent-control-owned-tree-${process.pid}.txt`);
  const setup = runtime(job([{id: 'tree', action: 'tree@1.0.0', requires: ['run'], timeoutSeconds: 1}]), actions => actions.register('tree@1.0.0', async context => {
    const script = '(sleep 30) & grandchild=$!; printf "%s %s" "$$" "$grandchild" > "$1"; wait "$grandchild"';
    await context.ownedExecution.runProcess({command: 'bash', args: ['-c', script, 'owned-tree', pidFile]}, context.signal); return {};
  }), [worker('worker', ['run'])]);
  try {
    const run = setup.runtime.createRun('job@1.0.0', {}, {type: 'manual', actor: 'test'}); await setup.runtime.tick();
    const [parentPid, grandchildPid] = fs.readFileSync(pidFile, 'utf8').split(' ').map(Number); assert.equal(setup.runtime.ledger.get(run.id)?.steps[0].status, 'TIMED_OUT'); assert.equal(await waitForProcessExit(parentPid), true); assert.equal(await waitForProcessExit(grandchildPid), true);
  } finally { fs.rmSync(pidFile, {force: true}); }
});
test('worker registry explains protected-workload capability fencing without hiding safe inspection', () => { const registry = new WorkerRegistry(); registry.register(worker('managed', ['compute.intensive', 'managed-node.inspect'], 'healthy', {blockedCapabilities: ['compute.intensive']})); assert.match(registry.resolve(['compute.intensive']).rationale.rejected[0].reasons.join(','), /workload_blocked:compute\.intensive/); assert.equal(registry.resolve(['managed-node.inspect']).worker?.id, 'managed'); });
test('reference workflow retains discovery artifact while publisher is unavailable then resumes across workers', async () => {
  const actions = registerReferenceActions(); registerBrowserActions(actions);
  actions.register('managed-node.inspect@1.0.0', async () => ({})); actions.register('managed-node.maintain@1.0.0', async () => ({}));
  const catalog = new JobCatalog(actions.ids()).loadDirectory(path.resolve('config/jobs')), root = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-control-events-')), workers = new WorkerRegistry(); workers.register(worker('mobile', ['browser.mobile', 'facebook.authenticated'])); workers.register(worker('publisher', ['localwalks.publisher', 'node', 'git', 'production-access'], 'offline')); workers.register(worker('observer', ['network.read']));
  const runtime = new JobRuntime(catalog, actions, workers, new RunLedger(path.join(root, 'ledger.json')), new ArtifactStore(path.join(root, 'artifacts')), new ResourceLockManager(path.join(root, 'locks.json')), {approval: () => true}); const run = runtime.createRun('events-refresh-qualification@1.0.0', {}, {type: 'manual', actor: 'qualification'});
  await runtime.tick(); await runtime.tick(); let state = runtime.ledger.get(run.id)!; assert.equal(state.steps[0].status, 'SUCCEEDED'); assert.equal(state.steps[1].status, 'WAITING_FOR_WORKER'); const artifactId = state.steps[0].artifactIds[0]; workers.setHealth('publisher', 'healthy'); for (let count = 0; count < 5; count++) await runtime.tick(); state = runtime.ledger.get(run.id)!; assert.equal(state.status, 'SUCCEEDED'); assert.equal(state.steps[0].artifactIds[0], artifactId); assert.equal(state.artifacts.length, 5); assert.deepEqual(state.selectedWorkers, ['mobile', 'publisher', 'observer']); assert.match(JSON.stringify(state.provenance), /preserved 3 existing/);
});
