import {createHash,randomUUID} from 'node:crypto';
import fs from 'node:fs';
import path from 'node:path';
import {assertNoSensitiveMaterial,redactSensitiveValue} from './security-redaction.js';
import {assessScope,sealExecutionScope,type ExecutionScopeEnvelope} from './containment.js';
import type {WorkBoardRuntime,WorkBoardResourceRequirements} from './work-board.js';

export type ImprovementMode='OFF'|'ANALYSE_ONLY'|'CREATE_CANDIDATE'|'AUTO_TEST_CANDIDATE'|'REQUIRE_PROMOTION_APPROVAL';
export type ImprovementState='BASELINE'|'WEAKNESS_DETECTED'|'IMPROVEMENT_PROPOSED'|'EXPERIMENT_APPROVED'|'CANDIDATE_CREATING'|'CANDIDATE_CREATED'|'BENCHMARKING'|'SECURITY_VALIDATION'|'REGRESSION_VALIDATION'|'COMPARISON_READY'|'AWAITING_PROMOTION_APPROVAL'|'PROMOTED'|'REJECTED'|'QUARANTINED'|'INCONCLUSIVE';
export type ImprovementDecision='PROMOTE'|'DO_NOT_PROMOTE'|'INCONCLUSIVE';
export type ImprovementAuthority='MEASURED'|'PROVIDER_REPORTED'|'CALCULATED'|'ESTIMATED'|'UNAVAILABLE';
export type TrainingExampleDecision='ACCEPTED'|'REJECTED'|'NEEDS_REVIEW';

export const IMPROVEMENT_LADDER=[
  'DETERMINISTIC_REMOVAL','PROMPT','CONTEXT_RETRIEVAL','CACHE_EXPERT','HELPER_DECOMPOSITION',
  'SPECULATIVE_DECODING','ROUTING','TEACHER_DATA','LORA_ADAPTER','DEEPER_MODIFICATION',
] as const;
export type ImprovementLevel=typeof IMPROVEMENT_LADDER[number];

export interface ImprovementMetric{name:string;value:number|null;unit:string;direction:'HIGHER_IS_BETTER'|'LOWER_IS_BETTER';authority:ImprovementAuthority;evidence:string[];}
export interface ImprovementOpportunity{schema:'agent-control.model-improvement-opportunity/v1';id:string;model:{id:string;version:string;sha256:string;runtimeId:string};weakness:string;evidenceReferences:string[];frequency:number;baselineReferences:string[];options:Array<{level:ImprovementLevel;expectedBenefit:string;estimatedCost:ImprovementMetric[]}>;proposedExperiment:string;status:'OPEN'|'SELECTED'|'CLOSED'|'REJECTED';createdAt:string;updatedAt:string;}
export interface FrozenImprovementBaseline{schema:'agent-control.model-improvement-baseline/v1';id:string;model:{id:string;version:string;sha256:string};runtime:{id:string;version:string;sha256:string};parameters:Record<string,unknown>;contextSha256:string;promptSha256:string;benchmark:{id:string;version:string;sha256:string};evaluator:{id:string;version:string;sha256:string};hardware:{nodeId:string;deviceIds:string[];resourceSnapshotSha256:string};createdAt:string;sha256:string;}
export interface TrainingExample{schema:'agent-control.training-example/v1';id:string;inputSha256:string;outputSha256:string;source:{kind:'OPERATOR_APPROVED'|'PUBLIC'|'SYNTHETIC_TEACHER'|'HISTORICAL_OPT_IN';reference:string;sha256:string};teacher?:{modelId:string;version:string;invocationId:string};containsSensitiveData:boolean;decision:TrainingExampleDecision;reviewReason:string;evidence:string[];}
export interface CandidateIdentity{parentBaselineSha256:string;datasetSha256:string|null;configurationSha256:string;adapterSha256:string|null;resultSha256:string;runtime:{id:string;version:string};tools:Array<{id:string;version:string}>;teachers:Array<{modelId:string;version:string;invocationIds:string[]}>;experimentId:string;createdAt:string;sha256:string;}
export interface ImprovementComparison{baseline:ImprovementMetric[];candidate:ImprovementMetric[];protectedRegressions:string[];securityFindings:string[];decision:ImprovementDecision;reason:string;economics:{oneTimeCost:ImprovementMetric[];perJobSaving:ImprovementMetric;breakEvenJobs:number|null;};evidence:string[];}
export interface ImprovementTransition{at:string;from:ImprovementState|null;to:ImprovementState;actor:string;reason:string;evidence:string[];}
export interface ImprovementExperiment{schema:'agent-control.model-improvement-experiment/v1';id:string;opportunityId:string;state:ImprovementState;mode:ImprovementMode;baseline:FrozenImprovementBaseline;ladder:{considered:ImprovementLevel[];selected:ImprovementLevel;reason:string};teacherStudent:{studentModelId:string;teacherModelIds:string[];teacherAuthority:'EVIDENCE_ONLY'};scope:ExecutionScopeEnvelope;workBoardId:string|null;workBoardItems:Record<string,string>;trainingExamples:TrainingExample[];datasetSha256:string|null;candidate:CandidateIdentity|null;comparison:ImprovementComparison|null;promotion:{required:true;approved:boolean;actor:string|null;decisionEvidence:string[];previousRouteReference:string|null;candidateRouteReference:string|null;promotedAt:string|null;rolledBackAt:string|null};createdAt:string;updatedAt:string;transitions:ImprovementTransition[];}
interface Snapshot{schema:'agent-control.model-improvement/v1';mode:ImprovementMode;opportunities:ImprovementOpportunity[];experiments:ImprovementExperiment[];}

const TERMINAL=new Set<ImprovementState>(['PROMOTED','REJECTED','QUARANTINED','INCONCLUSIVE']);
const NEXT:Record<ImprovementState,ImprovementState[]>= {
  BASELINE:['WEAKNESS_DETECTED'],WEAKNESS_DETECTED:['IMPROVEMENT_PROPOSED','REJECTED'],IMPROVEMENT_PROPOSED:['EXPERIMENT_APPROVED','REJECTED'],EXPERIMENT_APPROVED:['CANDIDATE_CREATING','INCONCLUSIVE'],CANDIDATE_CREATING:['CANDIDATE_CREATED','QUARANTINED','INCONCLUSIVE'],CANDIDATE_CREATED:['BENCHMARKING','QUARANTINED'],BENCHMARKING:['SECURITY_VALIDATION','QUARANTINED','INCONCLUSIVE'],SECURITY_VALIDATION:['REGRESSION_VALIDATION','REJECTED','QUARANTINED'],REGRESSION_VALIDATION:['COMPARISON_READY','REJECTED','QUARANTINED','INCONCLUSIVE'],COMPARISON_READY:['AWAITING_PROMOTION_APPROVAL','REJECTED','INCONCLUSIVE'],AWAITING_PROMOTION_APPROVAL:['PROMOTED','REJECTED','QUARANTINED'],PROMOTED:['QUARANTINED'],REJECTED:[],QUARANTINED:[],INCONCLUSIVE:[],
};
const required=(value:string,code:string)=>{const text=value.trim();if(!text)throw Error(code);return text;};
const validHash=(value:string)=>/^[a-f0-9]{64}$/.test(value);
const stable=(value:unknown):string=>JSON.stringify(sort(value));
const sort=(value:unknown):unknown=>Array.isArray(value)?value.map(sort):value&&typeof value==='object'?Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>[key,sort(item)])):value;
export const improvementSha256=(value:unknown)=>createHash('sha256').update(typeof value==='string'?value:stable(value)).digest('hex');
const unique=(values:string[])=>[...new Set(values.map(value=>required(value,'model_improvement_value_required')))].sort();

export function freezeImprovementBaseline(input:Omit<FrozenImprovementBaseline,'schema'|'id'|'createdAt'|'sha256'>,createdAt=new Date().toISOString()):FrozenImprovementBaseline{
  for(const hash of [input.model.sha256,input.runtime.sha256,input.contextSha256,input.promptSha256,input.benchmark.sha256,input.evaluator.sha256,input.hardware.resourceSnapshotSha256])if(!validHash(hash))throw Error('model_improvement_baseline_hash_invalid');
  const value={schema:'agent-control.model-improvement-baseline/v1' as const,id:`baseline-${randomUUID()}`,...structuredClone(input),createdAt};
  return{...value,sha256:improvementSha256(value)};
}
export function validateFrozenImprovementBaseline(value:FrozenImprovementBaseline){const{sha256,...base}=value;if(!validHash(sha256)||improvementSha256(base)!==sha256)throw Error('model_improvement_baseline_identity_mismatch');}

export function createImprovementScope(input:{workspace:string;candidateRoot:string;datasetRoot:string;nodeIds:string[];runtimeIds:string[];modelIds:string[];maximum:ExecutionScopeEnvelope['maximum'];createdAt:string}){
  const forbidden=['baseline','governance','benchmark-definition','evaluator','promotion'];
  if(forbidden.some(value=>path.basename(input.candidateRoot).toLowerCase()===value)||path.resolve(input.candidateRoot)===path.resolve(input.datasetRoot))throw Error('model_improvement_scope_unsafe');
  return sealExecutionScope({workspace:input.workspace,repository:null,filesystem:{readable:[input.datasetRoot],writable:[input.candidateRoot]},network:{destinations:[],ports:[]},devices:unique(input.nodeIds),runtimes:unique(input.runtimeIds),credentialReferences:[],tools:['model-improvement-worker'],apis:[],models:unique(input.modelIds),subprocesses:[],maximum:structuredClone(input.maximum),createdAt:input.createdAt});
}

export class ModelImprovementRuntime{
  private state:Snapshot={schema:'agent-control.model-improvement/v1',mode:'OFF',opportunities:[],experiments:[]};
  constructor(readonly file?:string,private readonly clock=()=>new Date().toISOString()){
    if(!file||!fs.existsSync(file))return;const value=JSON.parse(fs.readFileSync(file,'utf8')) as Snapshot;if(value.schema!==this.state.schema)throw Error('model_improvement_snapshot_invalid');this.state=value;for(const experiment of this.state.experiments){validateFrozenImprovementBaseline(experiment.baseline);validateCandidate(experiment.candidate);}
  }
  setMode(mode:ImprovementMode){this.state.mode=mode;this.persist();return mode;}
  observe(input:{model:ImprovementOpportunity['model'];weakness:string;evidenceReferences:string[];frequency:number;baselineReferences:string[];options:ImprovementOpportunity['options'];proposedExperiment:string}){
    if(this.state.mode==='OFF')throw Error('model_improvement_disabled');if(input.evidenceReferences.length<2||input.baselineReferences.length<1||!Number.isSafeInteger(input.frequency)||input.frequency<1)throw Error('model_improvement_evidence_threshold_not_met');
    for(const hash of [input.model.sha256])if(!validHash(hash))throw Error('model_improvement_model_hash_invalid');
    const at=this.clock(),value:ImprovementOpportunity={schema:'agent-control.model-improvement-opportunity/v1',id:`opportunity-${randomUUID()}`,model:structuredClone(input.model),weakness:required(input.weakness,'model_improvement_weakness_required'),evidenceReferences:unique(input.evidenceReferences),frequency:input.frequency,baselineReferences:unique(input.baselineReferences),options:structuredClone(input.options),proposedExperiment:required(input.proposedExperiment,'model_improvement_experiment_required'),status:'OPEN',createdAt:at,updatedAt:at};this.state.opportunities.push(value);this.persist();return structuredClone(value);
  }
  propose(input:{opportunityId:string;baseline:FrozenImprovementBaseline;selected:ImprovementLevel;considered:ImprovementLevel[];reason:string;teacherModelIds?:string[];scope:ExecutionScopeEnvelope;actor:string;workBoard?:WorkBoardRuntime;workBoardWorkspace?:string;requirements?:Partial<WorkBoardResourceRequirements>}){
    if(!['CREATE_CANDIDATE','AUTO_TEST_CANDIDATE','REQUIRE_PROMOTION_APPROVAL'].includes(this.state.mode))throw Error('model_improvement_mode_analysis_only');validateFrozenImprovementBaseline(input.baseline);if(!input.considered.includes(input.selected)||input.considered.some((value,index)=>IMPROVEMENT_LADDER.indexOf(value)>IMPROVEMENT_LADDER.indexOf(input.selected)&&index===0))throw Error('model_improvement_ladder_invalid');
    const opportunity=this.opportunity(input.opportunityId);if(opportunity.status!=='OPEN'||opportunity.model.sha256!==input.baseline.model.sha256)throw Error('model_improvement_baseline_opportunity_mismatch');assessScope(input.scope,{filesystemPath:input.scope.filesystem.writable[0],device:input.scope.devices[0],runtime:input.scope.runtimes[0],model:input.scope.models[0],tool:'model-improvement-worker'});const at=this.clock(),id=`experiment-${randomUUID()}`;
    const experiment:ImprovementExperiment={schema:'agent-control.model-improvement-experiment/v1',id,opportunityId:opportunity.id,state:'IMPROVEMENT_PROPOSED',mode:this.state.mode,baseline:structuredClone(input.baseline),ladder:{considered:unique(input.considered) as ImprovementLevel[],selected:input.selected,reason:required(input.reason,'model_improvement_ladder_reason_required')},teacherStudent:{studentModelId:input.baseline.model.id,teacherModelIds:unique(input.teacherModelIds??[]),teacherAuthority:'EVIDENCE_ONLY'},scope:structuredClone(input.scope),workBoardId:null,workBoardItems:{},trainingExamples:[],datasetSha256:null,candidate:null,comparison:null,promotion:{required:true,approved:false,actor:null,decisionEvidence:[],previousRouteReference:null,candidateRouteReference:null,promotedAt:null,rolledBackAt:null},createdAt:at,updatedAt:at,transitions:[{at,from:null,to:'BASELINE',actor:input.actor,reason:'Immutable production baseline frozen',evidence:[`baseline:${input.baseline.sha256}`]},{at,from:'BASELINE',to:'WEAKNESS_DETECTED',actor:input.actor,reason:opportunity.weakness,evidence:opportunity.evidenceReferences},{at,from:'WEAKNESS_DETECTED',to:'IMPROVEMENT_PROPOSED',actor:input.actor,reason:input.reason,evidence:[`opportunity:${opportunity.id}`]}]};
    if(input.workBoard)this.createWorkBoard(experiment,input.workBoard,input.workBoardWorkspace??input.scope.workspace,input.actor,input.requirements??{});opportunity.status='SELECTED';opportunity.updatedAt=at;this.state.experiments.push(experiment);this.persist();return structuredClone(experiment);
  }
  approve(id:string,input:{actor:string;reason:string;evidence:string[]}){const value=this.experiment(id);if(!input.evidence.length)throw Error('model_improvement_approval_evidence_required');return this.transition(value,'EXPERIMENT_APPROVED',input);}
  beginCandidate(id:string,input:{actor:string;reason:string;evidence?:string[]}){const value=this.experiment(id);if(!['CREATE_CANDIDATE','AUTO_TEST_CANDIDATE','REQUIRE_PROMOTION_APPROVAL'].includes(value.mode))throw Error('model_improvement_candidate_creation_forbidden');return this.transition(value,'CANDIDATE_CREATING',input);}
  addTrainingExample(id:string,example:TrainingExample){const value=this.experiment(id);if(value.state!=='CANDIDATE_CREATING')throw Error('model_improvement_candidate_not_creating');validateTrainingExample(example);if(example.containsSensitiveData&&example.decision==='ACCEPTED')throw Error('model_improvement_sensitive_training_data_forbidden');value.trainingExamples.push(structuredClone(example));value.datasetSha256=improvementSha256(value.trainingExamples.map(item=>({id:item.id,inputSha256:item.inputSha256,outputSha256:item.outputSha256,source:item.source,decision:item.decision})));value.updatedAt=this.clock();this.persist();return structuredClone(value);}
  createCandidate(id:string,input:Omit<CandidateIdentity,'createdAt'|'sha256'|'parentBaselineSha256'|'datasetSha256'|'experimentId'> & {actor:string;reason:string;evidence:string[]}){
    const value=this.experiment(id);if(value.state!=='CANDIDATE_CREATING')throw Error('model_improvement_candidate_not_creating');if(value.trainingExamples.some(item=>item.decision==='NEEDS_REVIEW'))throw Error('model_improvement_training_review_pending');const createdAt=this.clock(),base={parentBaselineSha256:value.baseline.sha256,datasetSha256:value.datasetSha256,configurationSha256:input.configurationSha256,adapterSha256:input.adapterSha256,resultSha256:input.resultSha256,runtime:structuredClone(input.runtime),tools:structuredClone(input.tools),teachers:structuredClone(input.teachers),experimentId:value.id,createdAt};for(const hash of [base.configurationSha256,base.resultSha256,...(base.adapterSha256?[base.adapterSha256]:[])])if(!validHash(hash))throw Error('model_improvement_candidate_hash_invalid');value.candidate={...base,sha256:improvementSha256(base)};return this.transition(value,'CANDIDATE_CREATED',{actor:input.actor,reason:input.reason,evidence:input.evidence});
  }
  beginBenchmark(id:string,input:{actor:string;reason:string;evidence:string[]}){return this.transition(this.experiment(id),'BENCHMARKING',input);}
  recordSecurity(id:string,input:{passed:boolean;actor:string;reason:string;evidence:string[];findings?:string[]}){const value=this.experiment(id);value.comparison=value.comparison??emptyComparison();value.comparison.securityFindings=unique(input.findings??[]);return this.transition(value,input.passed?'SECURITY_VALIDATION':'QUARANTINED',input);}
  recordRegression(id:string,input:{baseline:ImprovementMetric[];candidate:ImprovementMetric[];protectedRegressions:string[];actor:string;reason:string;evidence:string[]}){const value=this.experiment(id);if(value.state!=='SECURITY_VALIDATION')throw Error('model_improvement_lifecycle_transition_invalid');value.comparison=value.comparison??emptyComparison();value.comparison.baseline=metrics(input.baseline);value.comparison.candidate=metrics(input.candidate);value.comparison.protectedRegressions=unique(input.protectedRegressions);return this.transition(value,input.protectedRegressions.length?'REJECTED':'REGRESSION_VALIDATION',input);}
  completeComparison(id:string,input:{decision:ImprovementDecision;reason:string;oneTimeCost:ImprovementMetric[];perJobSaving:ImprovementMetric;evidence:string[];actor:string}){const value=this.experiment(id);if(value.state!=='REGRESSION_VALIDATION'||!value.comparison)throw Error('model_improvement_lifecycle_transition_invalid');value.comparison.decision=input.decision;value.comparison.reason=required(input.reason,'model_improvement_comparison_reason_required');value.comparison.economics={oneTimeCost:metrics(input.oneTimeCost),perJobSaving:metric(input.perJobSaving),breakEvenJobs:breakEven(input.oneTimeCost,input.perJobSaving)};value.comparison.evidence=unique(input.evidence);return this.transition(value,input.decision==='PROMOTE'?'COMPARISON_READY':input.decision==='DO_NOT_PROMOTE'?'REJECTED':'INCONCLUSIVE',{actor:input.actor,reason:input.reason,evidence:input.evidence});}
  requestPromotion(id:string,input:{actor:string;reason:string;evidence:string[];previousRouteReference:string;candidateRouteReference:string}){const value=this.experiment(id);if(value.comparison?.decision!=='PROMOTE')throw Error('model_improvement_not_promotable');value.promotion.previousRouteReference=required(input.previousRouteReference,'model_improvement_previous_route_required');value.promotion.candidateRouteReference=required(input.candidateRouteReference,'model_improvement_candidate_route_required');return this.transition(value,'AWAITING_PROMOTION_APPROVAL',input);}
  decidePromotion(id:string,input:{approved:boolean;actor:string;reason:string;evidence:string[];candidateSha256:string}){const value=this.experiment(id);if(value.state!=='AWAITING_PROMOTION_APPROVAL'||!value.candidate||value.candidate.sha256!==input.candidateSha256)throw Error('model_improvement_promotion_identity_mismatch');if(!input.evidence.length)throw Error('model_improvement_promotion_evidence_required');value.promotion.approved=input.approved;value.promotion.actor=input.actor;value.promotion.decisionEvidence=unique(input.evidence);value.promotion.promotedAt=input.approved?this.clock():null;return this.transition(value,input.approved?'PROMOTED':'REJECTED',input);}
  rollback(id:string,input:{actor:string;reason:string;evidence:string[]}){const value=this.experiment(id);if(value.state!=='PROMOTED'||!value.promotion.previousRouteReference)throw Error('model_improvement_rollback_unavailable');value.promotion.rolledBackAt=this.clock();return this.transition(value,'QUARANTINED',input);}
  projection(){return{schema:'agent-control.model-improvement-projection/v1',observedAt:this.clock(),mode:this.state.mode,opportunities:structuredClone(this.state.opportunities),experiments:structuredClone(this.state.experiments)};}
  private createWorkBoard(value:ImprovementExperiment,boards:WorkBoardRuntime,workspace:string,actor:string,requirements:Partial<WorkBoardResourceRequirements>){const board=boards.create({id:`model-improvement-${value.id}`,title:`Model improvement ${value.baseline.model.id}`,workspace,project:'model-improvement',lanes:[{id:'analysis',label:'Analysis',parallelism:1},{id:'candidate',label:'Candidate',parallelism:1},{id:'validation',label:'Validation',parallelism:2}],actor});value.workBoardId=board.id;let version=board.version;const stages=[['freeze','Freeze baseline','analysis',[]],['candidate','Create isolated candidate','candidate',['freeze']],['benchmark','Run frozen benchmark','validation',['candidate']],['security','Security validation','validation',['candidate']],['regression','Regression validation','validation',['benchmark','security']],['promotion','Promotion approval','analysis',['regression']]] as const;const ids:Record<string,string>={};for(const[key,title,lane,deps]of stages){const current=boards.apply(board.id,version,{type:'CREATE_ITEM',input:{title,description:title,workspace,project:'model-improvement',sourceInstruction:`Governed model improvement stage ${key}`,creator:actor,laneId:lane,dependencies:deps.map(dep=>({itemId:ids[dep]!,kind:'FINISH_TO_START'})),requirements:{...requirements},requiredApprovals:key==='promotion'?['model-improvement-promotion']:[],acceptanceCriteria:['Retained evidence','Immutable identities verified'],parallelismPolicy:key==='benchmark'||key==='security'?'ALLOW_SAFE':'SERIAL_LANE'}},actor,'model-improvement lifecycle');version=current.version;ids[key]=current.items.at(-1)!.id;}value.workBoardItems=ids;}
  private transition(value:ImprovementExperiment,to:ImprovementState,input:{actor:string;reason:string;evidence?:string[]}){if(TERMINAL.has(value.state)||!NEXT[value.state].includes(to))throw Error(`model_improvement_lifecycle_transition_invalid:${value.state}:${to}`);const at=this.clock(),from=value.state;value.state=to;value.updatedAt=at;value.transitions.push({at,from,to,actor:required(input.actor,'model_improvement_actor_required'),reason:required(input.reason,'model_improvement_reason_required'),evidence:unique(input.evidence??[])});this.persist();return structuredClone(value);}
  private opportunity(id:string){const value=this.state.opportunities.find(item=>item.id===id);if(!value)throw Error('model_improvement_opportunity_missing');return value;}
  private experiment(id:string){const value=this.state.experiments.find(item=>item.id===id);if(!value)throw Error('model_improvement_experiment_missing');return value;}
  private persist(){if(!this.file)return;const safe=redactSensitiveValue(this.state) as Snapshot;assertNoSensitiveMaterial(JSON.stringify(safe),'model_improvement_secret_forbidden');fs.mkdirSync(path.dirname(this.file),{recursive:true});const temporary=`${this.file}.${process.pid}.${randomUUID()}.tmp`;fs.writeFileSync(temporary,`${JSON.stringify(safe,null,2)}\n`,{mode:0o600,flag:'wx'});fs.renameSync(temporary,this.file);}
}

function validateCandidate(value:CandidateIdentity|null){if(!value)return;const{sha256,...base}=value;if(!validHash(sha256)||improvementSha256(base)!==sha256)throw Error('model_improvement_candidate_identity_mismatch');}
function validateTrainingExample(value:TrainingExample){for(const hash of [value.inputSha256,value.outputSha256,value.source.sha256])if(!validHash(hash))throw Error('model_improvement_training_hash_invalid');if(value.source.kind==='SYNTHETIC_TEACHER'&&!value.teacher)throw Error('model_improvement_teacher_provenance_required');if(value.teacher&&value.teacher.modelId===value.id)throw Error('model_improvement_teacher_student_invalid');if(!value.evidence.length)throw Error('model_improvement_training_evidence_required');}
function metric(value:ImprovementMetric){if(value.value===null&&value.authority!=='UNAVAILABLE')throw Error('model_improvement_metric_authority_invalid');if(value.value!==null&&!Number.isFinite(value.value))throw Error('model_improvement_metric_value_invalid');return structuredClone(value);}
function metrics(values:ImprovementMetric[]){return values.map(metric);}
function emptyComparison():ImprovementComparison{return{baseline:[],candidate:[],protectedRegressions:[],securityFindings:[],decision:'INCONCLUSIVE',reason:'Not evaluated',economics:{oneTimeCost:[],perJobSaving:{name:'per-job-saving',value:null,unit:'unavailable',direction:'HIGHER_IS_BETTER',authority:'UNAVAILABLE',evidence:[]},breakEvenJobs:null},evidence:[]};}
function breakEven(costs:ImprovementMetric[],saving:ImprovementMetric){if(saving.value===null||saving.value<=0||saving.authority==='UNAVAILABLE')return null;const known=costs.filter(item=>item.value!==null&&item.authority!=='UNAVAILABLE');if(known.length!==costs.length||new Set([...known.map(item=>item.unit),saving.unit]).size!==1)return null;return Math.ceil(known.reduce((sum,item)=>sum+(item.value??0),0)/saving.value);}
