import {Buffer} from 'node:buffer';
import {redactSensitiveValue} from './security-redaction.js';
import type {RuntimeMapProjection} from './runtime-map.js';

export type WorkspaceKind='ESTATE'|'DEVICE'|'ENVIRONMENT'|'RUNTIME'|'WORKER'|'RUN'|'INVOCATION';
export type WorkspaceMode='LIVE'|'HISTORICAL'|'STALE'|'UNAVAILABLE';
export type WorkspaceCapability='STATUS'|'EVIDENCE'|'TOKENS'|'FILES'|'TERMINAL'|'EXECUTE';
export interface WorkspaceReference{kind:WorkspaceKind;parts:string[];}
export interface WorkspaceLink{id:string;kind:WorkspaceKind;label:string;status:string;}
export interface WorkspaceCapabilityState{id:WorkspaceCapability;state:'AVAILABLE'|'REQUIRES_AUTHORIZATION'|'UNAVAILABLE';reason:string;}
export interface WorkspaceProjection{
  schema:'agent-control.navigable-workspace/v1';authority:'DERIVED_FROM_AUTHORITATIVE_AGENT_CONTROL_RECORDS';id:string;kind:WorkspaceKind;label:string;status:string;mode:WorkspaceMode;observedAt:string;
  parent:WorkspaceLink|null;breadcrumbs:WorkspaceLink[];children:WorkspaceLink[];capabilities:WorkspaceCapabilityState[];
  context:Record<string,unknown>;evidence:Array<{kind:string;id:string;sha256?:string}>;targets:{dashboard:string;history:string|null};
  limitations:string[];
}

export interface WorkspaceNodeDashboard{
  observedAt:string;node:{id:string;label:string;state:string;evidence:Array<{kind:string;id:string;sha256?:string}>;detail:Record<string,unknown>};
  executionEnvironments:Array<{id:string;label:string;kind:string|null;parentId:string|null;state:string;availability:unknown;transport:unknown;capabilities:unknown;runtimes:Array<{id:string;kind:string;version?:string|null;state:string;observedAt:string;containers?:unknown[]}>;workerRoute:{id:string;state:string;health:string}|null;lastObservedAt:string;evidence:Array<{kind:string;id:string;sha256?:string}>}>;
  work:Array<{inspectorId:string;label:string;status:string;startedAt:string;endedAt:string|null;nodeId:string}>;
}
export interface WorkspaceRunInspector{
  id:string;title:string;status:string;startedAt:string;endedAt:string|null;observedAt:string;physicalNodes:Array<{id:string;label:string}>;
  executionRoute:{path:Array<{id:string;label:string;kind:string|null}>;worker:{id:string;state:string}|null;runtime:{id:string;kind:string;version?:string|null}|null;transport:string|null;reason:string|null;authority:string;evidence:Array<{kind:string;id:string;sha256?:string}>}|null;
  calls:Array<{id:string;provider?:string|null;model?:string|null;providerModel?:string|null;node?:string|null;startedAt?:string|null;completedAt?:string|null;inputTokens?:number|null;cachedInputTokens?:number|null;outputTokens?:number|null;totalTokens?:number|null;accounting?:{usage?:{inputTokens:number|null;cachedInputTokens:number|null;outputTokens:number|null;totalProcessedTokens:number|null};apiCost?:unknown}|null;exchange?:{input:string;output:string;truncated:boolean}|null}>;
  usage:{totals:{input:{value:number|null};cached:{value:number|null};output:{value:number|null};tokens:{value:number|null};apiCost:unknown}};
  parentUsage?:WorkspaceRunInspector['usage']|null;history?:{sha256:string;entryCount:number;terminal:boolean}|null;historyScope?:string;events:unknown[];context:{records:unknown[]};
  operations:Array<{id:string;label?:string;type?:string;state?:string;startedAt?:string|null;endedAt?:string|null;detail?:Record<string,unknown>;evidence?:Array<{kind:string;id:string;sha256?:string}>}>;
}
export interface WorkspaceSource{estate:RuntimeMapProjection;nodes:WorkspaceNodeDashboard[];runs:WorkspaceRunInspector[];}

const kinds=new Set<WorkspaceKind>(['ESTATE','DEVICE','ENVIRONMENT','RUNTIME','WORKER','RUN','INVOCATION']);
export function workspaceId(reference:WorkspaceReference){if(!kinds.has(reference.kind)||reference.parts.some(part=>!part||part.length>240||part.includes('\0')))throw Error('workspace_reference_invalid');return `acw1.${reference.kind}.${Buffer.from(JSON.stringify(reference.parts)).toString('base64url')}`;}
export function parseWorkspaceId(id:string):WorkspaceReference{if(typeof id!=='string'||id.length>1024)throw Error('workspace_identity_invalid');const match=id.match(/^acw1\.([A-Z]+)\.([A-Za-z0-9_-]+)$/);if(!match||!kinds.has(match[1] as WorkspaceKind))throw Error('workspace_identity_invalid');try{const parts=JSON.parse(Buffer.from(match[2]!,'base64url').toString('utf8'));if(!Array.isArray(parts)||parts.some(part=>typeof part!=='string'||!part||part.length>240||part.includes('\0')))throw Error();return{kind:match[1] as WorkspaceKind,parts};}catch{throw Error('workspace_identity_invalid');}}
const ref=(kind:WorkspaceKind,...parts:string[]):WorkspaceReference=>({kind,parts});
const link=(reference:WorkspaceReference,label:string,status:string):WorkspaceLink=>({id:workspaceId(reference),kind:reference.kind,label,status});
const mode=(status:string,endedAt:string|null|undefined,fresh=true):WorkspaceMode=>!fresh?'STALE':endedAt?'HISTORICAL':['FAILED','BLOCKED','DEGRADED','DISCONNECTED'].includes(status)?'UNAVAILABLE':'LIVE';
const authorised=(id:WorkspaceCapability,available:boolean,reason:string):WorkspaceCapabilityState=>({id,state:available?'REQUIRES_AUTHORIZATION':'UNAVAILABLE',reason});
const baseCapabilities=(evidence:boolean,tokens:boolean):WorkspaceCapabilityState[]=>[
  {id:'STATUS',state:'AVAILABLE',reason:'Read-only projection of authoritative Agent Control records.'},
  {id:'EVIDENCE',state:evidence?'AVAILABLE':'UNAVAILABLE',reason:evidence?'Recorded evidence is linked through the existing Run Inspector.':'No retained evidence is linked to this workspace.'},
  {id:'TOKENS',state:tokens?'AVAILABLE':'UNAVAILABLE',reason:tokens?'Canonical invocation accounting is available.':'Token telemetry is unavailable; missing values are not zero.'},
];
const findNode=(source:WorkspaceSource,id:string)=>source.nodes.find(node=>node.node.id===id);
const findRun=(source:WorkspaceSource,id:string)=>source.runs.find(run=>run.id===id);
const environmentLineage=(node:WorkspaceNodeDashboard,environmentId:string)=>{const values:WorkspaceNodeDashboard['executionEnvironments']=[],seen=new Set<string>();let current=node.executionEnvironments.find(item=>item.id===environmentId);while(current&&!seen.has(current.id)){seen.add(current.id);values.unshift(current);current=current.parentId?node.executionEnvironments.find(item=>item.id===current!.parentId):undefined;}return values;};
const physicalForRun=(run:WorkspaceRunInspector)=>run.physicalNodes[0]??null;
const parentEnvironment=(run:WorkspaceRunInspector)=>[...(run.executionRoute?.path??[])].reverse().find(item=>item.kind&&item.kind!=='PHYSICAL_DEVICE')??null;
const tokens=(run:WorkspaceRunInspector)=>{const usage=(run.parentUsage??run.usage).totals,available=usage.tokens.value!==null;return{input:usage.input.value,cachedInput:usage.cached.value,output:usage.output.value,total:usage.tokens.value,cost:available?usage.apiCost:null,authority:available?'CANONICAL_USAGE_ACCOUNTING':'UNAVAILABLE'};};
const dashboardTarget=(reference:WorkspaceReference)=>reference.kind==='DEVICE'?`?view=runtime-map&mode=estate&resource=${encodeURIComponent(reference.parts[0]!)}`:reference.kind==='RUN'||reference.kind==='INVOCATION'?`?view=runtime-map&parcelId=${encodeURIComponent(reference.parts[0]!)}`:'?view=runtime-map&mode=estate';
function breadcrumbs(source:WorkspaceSource,reference:WorkspaceReference):WorkspaceLink[]{
  const values=[link(ref('ESTATE','estate'),'Estate',source.estate.freshness.state)];
  if(reference.kind==='ESTATE')return values;
  const run=reference.kind==='RUN'||reference.kind==='INVOCATION'?findRun(source,reference.parts[0]!):undefined;
  let nodeId=reference.kind==='DEVICE'||reference.kind==='ENVIRONMENT'||reference.kind==='RUNTIME'||reference.kind==='WORKER'?reference.parts[0]:undefined;
  nodeId=nodeId??(run?physicalForRun(run)?.id:undefined);
  const node=nodeId?findNode(source,nodeId):undefined;
  if(node)values.push(link(ref('DEVICE',node.node.id),node.node.label,node.node.state));
  const directEnvironment=['ENVIRONMENT','RUNTIME','WORKER'].includes(reference.kind)?node?.executionEnvironments.find(item=>item.id===reference.parts[1]):undefined;
  const routedEnvironment=run&&node?parentEnvironment(run):null;
  const environment=directEnvironment??(routedEnvironment?node?.executionEnvironments.find(item=>item.id===routedEnvironment.id):undefined);
  if(environment&&node)for(const item of environmentLineage(node,environment.id))values.push(link(ref('ENVIRONMENT',node.node.id,item.id),item.label,item.state));
  const directRuntime=reference.kind==='RUNTIME'?environment?.runtimes.find(item=>item.id===reference.parts[2]):undefined;
  const routedRuntime=run?.executionRoute?.runtime;
  const runtime=directRuntime??(routedRuntime&&environment?environment.runtimes.find(item=>item.id===routedRuntime.id||item.kind===routedRuntime.kind):undefined);
  if(runtime&&environment&&node)values.push(link(ref('RUNTIME',node.node.id,environment.id,runtime.id),runtime.kind,runtime.state));
  if(run)values.push(link(ref('RUN',run.id),run.title,run.status));
  if(reference.kind==='INVOCATION'){const call=run?.calls.find(item=>item.id===reference.parts[1]);if(call)values.push(link(reference,call.providerModel??call.model??call.id,'RECORDED'));}
  return values;
}
function runsFor(source:WorkspaceSource,predicate:(run:WorkspaceRunInspector)=>boolean){return source.runs.filter(predicate).sort((a,b)=>b.startedAt.localeCompare(a.startedAt)).slice(0,24).map(run=>link(ref('RUN',run.id),run.title,run.status));}

export function projectWorkspace(id:string,source:WorkspaceSource):WorkspaceProjection{
  const reference=parseWorkspaceId(id),observedAt=source.estate.observedAt,fresh=source.estate.freshness.state==='LIVE';let labelValue='',status='',workspaceMode:WorkspaceMode='LIVE',parent:WorkspaceLink|null=null,children:WorkspaceLink[]=[],capabilities:WorkspaceCapabilityState[]=baseCapabilities(false,false),context:Record<string,unknown>={},evidence:Array<{kind:string;id:string;sha256?:string}>=[],history:string|null=null;
  if(reference.kind==='ESTATE'){
    labelValue='Estate';status=source.estate.freshness.state;workspaceMode=fresh?'LIVE':'STALE';children=source.nodes.map(node=>link(ref('DEVICE',node.node.id),node.node.label,node.node.state));context={summary:source.estate.summary,authority:source.estate.authority,mapKind:source.estate.mapKind};evidence=source.estate.nodes.flatMap(node=>node.evidence).slice(0,100);
  }else if(reference.kind==='DEVICE'){
    const node=findNode(source,reference.parts[0]!);if(!node)throw Error('workspace_not_found');labelValue=node.node.label;status=node.node.state;workspaceMode=mode(status,null,fresh);parent=link(ref('ESTATE','estate'),'Estate',source.estate.freshness.state);children=[...node.executionEnvironments.filter(item=>item.parentId===node.node.id||item.parentId===null).map(item=>link(ref('ENVIRONMENT',node.node.id,item.id),item.label,item.state)),...node.work.slice(0,12).map(item=>link(ref('RUN',item.inspectorId),item.label,item.status))];capabilities=baseCapabilities(node.node.evidence.length>0,false);context={physicalDevice:node.node,executionEnvironmentCount:node.executionEnvironments.length,work:node.work};evidence=node.node.evidence;
  }else if(reference.kind==='ENVIRONMENT'){
    const node=findNode(source,reference.parts[0]!),environment=node?.executionEnvironments.find(item=>item.id===reference.parts[1]);if(!node||!environment)throw Error('workspace_not_found');labelValue=environment.label;status=environment.state;workspaceMode=mode(status,null,fresh);const parentEnvironment=environment.parentId?node.executionEnvironments.find(item=>item.id===environment.parentId):undefined;parent=parentEnvironment?link(ref('ENVIRONMENT',node.node.id,parentEnvironment.id),parentEnvironment.label,parentEnvironment.state):link(ref('DEVICE',node.node.id),node.node.label,node.node.state);const childEnvironments=node.executionEnvironments.filter(item=>item.parentId===environment.id);const childWorkerIds=new Set(childEnvironments.filter(item=>item.kind==='WORKER').map(item=>item.workerRoute?.id??item.id));children=[...childEnvironments.map(item=>link(ref('ENVIRONMENT',node.node.id,item.id),item.label,item.state)),...environment.runtimes.map(item=>link(ref('RUNTIME',node.node.id,environment.id,item.id),item.kind,item.state)),...(environment.workerRoute&&!childWorkerIds.has(environment.workerRoute.id)?[link(ref('WORKER',node.node.id,environment.id,environment.workerRoute.id),environment.workerRoute.id,environment.workerRoute.state)]:[]),...runsFor(source,run=>run.executionRoute?.path.some(item=>item.id===environment.id)??false)];const values=Array.isArray(environment.capabilities)?environment.capabilities.map(String):[];capabilities=[...baseCapabilities(environment.evidence.length>0,false),authorised('FILES',values.some(value=>/file|repository/.test(value)),'Workspace discovery does not grant file access.'),authorised('TERMINAL',values.some(value=>/shell|terminal|ssh/.test(value)),'A separately authorised execution-session attachment is required.'),authorised('EXECUTE',values.some(value=>/execute|container/.test(value)),'Opening a workspace never grants execution authority.')];context={environment:{...environment,runtimes:undefined},transport:environment.transport,workerRoute:environment.workerRoute};evidence=environment.evidence;
  }else if(reference.kind==='RUNTIME'){
    const node=findNode(source,reference.parts[0]!),environment=node?.executionEnvironments.find(item=>item.id===reference.parts[1]),runtime=environment?.runtimes.find(item=>item.id===reference.parts[2]);if(!node||!environment||!runtime)throw Error('workspace_not_found');labelValue=`${runtime.kind} runtime`;status=runtime.state;workspaceMode=mode(status,null,fresh);parent=link(ref('ENVIRONMENT',node.node.id,environment.id),environment.label,environment.state);children=runsFor(source,run=>run.physicalNodes.some(item=>item.id===node.node.id)&&Boolean(run.executionRoute?.path.some(item=>item.id===environment.id))&&run.executionRoute?.runtime?.id===runtime.id);capabilities=[...baseCapabilities(true,false),authorised('EXECUTE',runtime.state==='AVAILABLE','Runtime presence does not grant job execution authority.')];context={runtime,environment:{id:environment.id,label:environment.label},physicalDevice:{id:node.node.id,label:node.node.label},transport:environment.transport};evidence=environment.evidence;
  }else if(reference.kind==='WORKER'){
    const node=findNode(source,reference.parts[0]!),environment=node?.executionEnvironments.find(item=>item.id===reference.parts[1]),worker=environment?.workerRoute;if(!node||!environment||!worker||worker.id!==reference.parts[2])throw Error('workspace_not_found');labelValue=worker.id;status=worker.state;workspaceMode=mode(status,null,fresh);parent=link(ref('ENVIRONMENT',node.node.id,environment.id),environment.label,environment.state);children=runsFor(source,run=>run.executionRoute?.worker?.id===worker.id);capabilities=[...baseCapabilities(true,false),authorised('TERMINAL',true,'Terminal attachment remains governed by the existing execution-session policy.'),authorised('EXECUTE',true,'Worker availability is not execution approval.')];context={worker,environment:{id:environment.id,label:environment.label},transport:environment.transport};evidence=environment.evidence;
  }else if(reference.kind==='RUN'){
    const run=findRun(source,reference.parts[0]!);if(!run)throw Error('workspace_not_found');const physical=physicalForRun(run),environment=parentEnvironment(run),runtime=run.executionRoute?.runtime;labelValue=run.title;status=run.status;workspaceMode=mode(status,run.endedAt,true);parent=runtime&&physical&&environment?link(ref('RUNTIME',physical.id,environment.id,runtime.id),runtime.kind,status):environment&&physical?link(ref('ENVIRONMENT',physical.id,environment.id),environment.label,status):physical?link(ref('DEVICE',physical.id),physical.label,status):link(ref('ESTATE','estate'),'Estate',source.estate.freshness.state);const callIds=new Set(run.calls.map(call=>call.id));const operationLinks=run.operations.filter(item=>item.id&&!callIds.has(item.id)&&['job','tool','terminal','model-call','action','verification'].includes(item.type??'')).map(item=>link(ref('INVOCATION',run.id,item.id),item.label??item.type??item.id,item.state??'RECORDED'));children=[...run.calls.map(call=>link(ref('INVOCATION',run.id,call.id),call.providerModel??call.model??call.id,'RECORDED')),...operationLinks];const accounting=tokens(run);capabilities=baseCapabilities(Boolean(run.history),accounting.total!==null);context={run:{id:run.id,title:run.title,status:run.status,startedAt:run.startedAt,endedAt:run.endedAt},route:run.executionRoute,tokens:accounting,batonAndContextRecords:run.context.records.length,history:run.history??null,historyScope:run.historyScope??null};evidence=run.executionRoute?.evidence??[];history=run.history?`/api/observability/runs/${encodeURIComponent(run.id)}`:null;
  }else if(reference.kind==='INVOCATION'){
    const run=findRun(source,reference.parts[0]!),call=run?.calls.find(item=>item.id===reference.parts[1]),operation=run?.operations.find(item=>item.id===reference.parts[1]);if(!run||(!call&&!operation))throw Error('workspace_not_found');workspaceMode='HISTORICAL';parent=link(ref('RUN',run.id),run.title,run.status);if(call){const usage=call.accounting?.usage;labelValue=call.providerModel??call.model??call.id;status='RECORDED';capabilities=baseCapabilities(Boolean(run.history),Boolean(usage&&[usage.inputTokens,usage.cachedInputTokens,usage.outputTokens,usage.totalProcessedTokens].some(value=>value!==null)));context={invocation:{id:call.id,kind:'MODEL_CALL',provider:call.provider??null,model:call.model??null,providerModel:call.providerModel??null,node:call.node??null,startedAt:call.startedAt??null,completedAt:call.completedAt??null},tokens:{input:usage?.inputTokens??call.inputTokens??null,cachedInput:usage?.cachedInputTokens??call.cachedInputTokens??null,output:usage?.outputTokens??call.outputTokens??null,total:usage?.totalProcessedTokens??call.totalTokens??null,cost:call.accounting?.apiCost??null},exchange:call.exchange??null};evidence=run.executionRoute?.evidence??[];}else{labelValue=operation!.label??operation!.type??operation!.id;status=operation!.state??'RECORDED';capabilities=baseCapabilities(Boolean(run.history),false);context={invocation:{id:operation!.id,kind:operation!.type??'OPERATION',startedAt:operation!.startedAt??null,completedAt:operation!.endedAt??null,detail:operation!.detail??{}},tokens:{input:null,cachedInput:null,output:null,total:null,cost:null,authority:'UNAVAILABLE'},exchange:null};evidence=operation!.evidence??run.executionRoute?.evidence??[];}history=run.history?`/api/observability/runs/${encodeURIComponent(run.id)}`:null;
  }else throw Error('workspace_not_found');
  const projection:WorkspaceProjection={schema:'agent-control.navigable-workspace/v1',authority:'DERIVED_FROM_AUTHORITATIVE_AGENT_CONTROL_RECORDS',id,kind:reference.kind,label:labelValue,status,mode:workspaceMode,observedAt,parent,breadcrumbs:breadcrumbs(source,reference),children,capabilities,context,evidence,targets:{dashboard:dashboardTarget(reference),history},limitations:['Workspace navigation grants no terminal, file, execution, deployment, credential or protected-resource authority.','Live, stale and historical modes remain distinct. Transport selection is recorded context, not workspace identity.']};
  return redactSensitiveValue(projection) as WorkspaceProjection;
}

export function listWorkspaceRoots(source:WorkspaceSource){return projectWorkspace(workspaceId(ref('ESTATE','estate')),source);}
