import assert from 'node:assert/strict';
import test from 'node:test';
import {listWorkspaceRoots,parseWorkspaceId,projectWorkspace,workspaceId,type WorkspaceNodeDashboard,type WorkspaceRunInspector,type WorkspaceSource} from './navigable-workspace.js';
import type {RuntimeMapProjection} from './runtime-map.js';

const at='2026-09-14T12:00:00.000Z';
const estate:RuntimeMapProjection={schema:'agent-control.runtime-map/v1',authority:'Agent Control governed discovery inventory',mapKind:'ESTATE',mode:'LIVE',parcelId:'scan',observedAt:at,replayAt:null,range:{startedAt:at,endedAt:at},freshness:{state:'LIVE',lastAuthoritativeAt:at},summary:{nodes:4,edges:3,running:1,waiting:0,succeeded:3,failed:0,degraded:0,groups:0},nodes:[{id:'pixel',type:'device',label:'Pixel 8 Pro',state:'RUNNING',expandable:true,detail:{},evidence:[{kind:'discovery',id:'pixel-proof'}]}],edges:[],events:[],controlRoom:[],limitations:[]};
const node:WorkspaceNodeDashboard={observedAt:at,node:{id:'pixel',label:'Pixel 8 Pro',state:'RUNNING',detail:{platform:'android'},evidence:[{kind:'discovery',id:'pixel-proof'}]},executionEnvironments:[{id:'alpine',label:'Alpine Linux',kind:'GUEST_OS',parentId:'pixel',state:'RUNNING',availability:'AVAILABLE',transport:'ssh',capabilities:['container.execute','tool.shell'],runtimes:[{id:'runtime:podman',kind:'podman',version:'5.8.6',state:'AVAILABLE',observedAt:at,containers:[]}],workerRoute:{id:'mobile-linux-guest',state:'RUNNING',health:'healthy'},lastObservedAt:at,evidence:[{kind:'managed-node-probe',id:'probe'}]}],work:[{inspectorId:'run-one',label:'Nested qualification',status:'SUCCEEDED',startedAt:at,endedAt:at,nodeId:'mobile-linux-guest'}]};
const run:WorkspaceRunInspector={id:'run-one',title:'Nested qualification',status:'SUCCEEDED',startedAt:at,endedAt:at,observedAt:at,physicalNodes:[{id:'pixel',label:'Pixel 8 Pro'}],executionRoute:{path:[{id:'pixel',label:'Pixel 8 Pro',kind:'PHYSICAL_DEVICE'},{id:'alpine',label:'Alpine Linux',kind:'GUEST_OS'}],worker:{id:'mobile-linux-guest',state:'SUCCEEDED'},runtime:{id:'runtime:podman',kind:'podman',version:'5.8.6'},transport:'ssh',reason:'Linux container capability required',authority:'DETERMINISTIC_RECORDED_ROUTE',evidence:[{kind:'route',id:'route-one'}]},calls:[{id:'invocation-one',provider:'openrouter',model:'glm',providerModel:'z-ai/glm-5.3',node:'mobile-linux-guest',startedAt:at,completedAt:at,accounting:{usage:{inputTokens:100,cachedInputTokens:40,outputTokens:20,totalProcessedTokens:120},apiCost:null},exchange:{input:'bounded request',output:'bounded result',truncated:false}}],operations:[{id:'operation-one',label:'Governed container invocation',type:'tool',state:'SUCCEEDED',startedAt:at,endedAt:at,detail:{runtime:'podman'},evidence:[{kind:'artifact',id:'container-output'}]}],usage:{totals:{input:{value:100},cached:{value:40},output:{value:20},tokens:{value:120},apiCost:{currencies:{}}}},history:{sha256:'a'.repeat(64),entryCount:4,terminal:true},historyScope:'Run history',events:[],context:{records:[{kind:'baton'}]}};
const source:WorkspaceSource={estate,nodes:[node],runs:[run]};
const id=(kind:Parameters<typeof workspaceId>[0]['kind'],...parts:string[])=>workspaceId({kind,parts});

test('workspace identity round trips without embedding transport or filesystem paths',()=>{const value=id('ENVIRONMENT','pixel','alpine');assert.deepEqual(parseWorkspaceId(value),{kind:'ENVIRONMENT',parts:['pixel','alpine']});assert.doesNotMatch(value,/ssh|alpine|pixel/);for(const invalid of ['workspace:ssh:host','acw1.DEVICE.bad%value',''])assert.throws(()=>parseWorkspaceId(invalid),/workspace_identity_invalid/);});
test('estate to device to environment to runtime navigation is progressive and transport independent',()=>{const root=listWorkspaceRoots(source);assert.equal(root.children[0]?.label,'Pixel 8 Pro');const device=projectWorkspace(id('DEVICE','pixel'),source);assert.deepEqual(device.children.map(item=>item.kind),['ENVIRONMENT','RUN']);const environment=projectWorkspace(id('ENVIRONMENT','pixel','alpine'),source);assert.ok(environment.children.some(item=>item.kind==='RUNTIME'));assert.ok(environment.children.some(item=>item.kind==='WORKER'));assert.equal(environment.context.transport,'ssh');assert.equal(environment.capabilities.find(item=>item.id==='TERMINAL')?.state,'REQUIRES_AUTHORIZATION');const runtime=projectWorkspace(id('RUNTIME','pixel','alpine','runtime:podman'),source);assert.ok(runtime.children.some(item=>item.kind==='RUN'));assert.equal(runtime.id.includes('ssh'),false);});
test('historical run reconstructs bottom-up route, evidence and canonical usage',()=>{const workspace=projectWorkspace(id('RUN','run-one'),source);assert.equal(workspace.mode,'HISTORICAL');assert.equal(workspace.parent?.kind,'RUNTIME');assert.deepEqual(workspace.breadcrumbs.map(item=>item.kind),['ESTATE','DEVICE','ENVIRONMENT','RUNTIME','RUN']);assert.equal((workspace.context.tokens as {cachedInput:number}).cachedInput,40);assert.equal(workspace.capabilities.find(item=>item.id==='TOKENS')?.state,'AVAILABLE');assert.equal(workspace.children[0]?.kind,'INVOCATION');assert.equal(workspace.targets.history,'/api/observability/runs/run-one');});
test('invocation resolves input output tokens and parent run without granting control',()=>{const workspace=projectWorkspace(id('INVOCATION','run-one','invocation-one'),source),context=workspace.context as {tokens:{input:number;cachedInput:number;output:number};exchange:{input:string;output:string}};assert.deepEqual(context.tokens,{input:100,cachedInput:40,output:20,total:120,cost:null});assert.equal(context.exchange.output,'bounded result');assert.equal(workspace.parent?.kind,'RUN');assert.equal(workspace.capabilities.some(item=>['TERMINAL','EXECUTE'].includes(item.id)&&item.state==='AVAILABLE'),false);});
test('deterministic operation is an invocation with unavailable model telemetry',()=>{const workspace=projectWorkspace(id('INVOCATION','run-one','operation-one'),source),context=workspace.context as {tokens:{input:number|null;total:number|null};invocation:{kind:string}};assert.equal(workspace.label,'Governed container invocation');assert.equal(context.invocation.kind,'tool');assert.equal(context.tokens.input,null);assert.equal(context.tokens.total,null);assert.equal(workspace.capabilities.find(item=>item.id==='TOKENS')?.state,'UNAVAILABLE');assert.equal(workspace.evidence[0]?.id,'container-output');});
test('missing telemetry remains unavailable rather than zero and stale estate remains stale',()=>{const missing:WorkspaceSource={...source,estate:{...estate,freshness:{state:'STALE',lastAuthoritativeAt:at}},runs:[{...run,calls:[],usage:{totals:{input:{value:null},cached:{value:null},output:{value:null},tokens:{value:null},apiCost:{currencies:{},reported:0,total:0}}},history:null}]};const root=listWorkspaceRoots(missing),workspace=projectWorkspace(id('RUN','run-one'),missing),tokenContext=workspace.context.tokens as {total:number|null;cost:unknown};assert.equal(root.mode,'STALE');assert.equal(workspace.capabilities.find(item=>item.id==='TOKENS')?.state,'UNAVAILABLE');assert.equal(tokenContext.total,null);assert.equal(tokenContext.cost,null);});
test('workspace projection redacts credential-like values from untrusted topology metadata',()=>{const unsafe:WorkspaceSource={...source,nodes:[{...node,executionEnvironments:[{...node.executionEnvironments[0]!,transport:'password=do-not-render'}]}]};assert.equal(JSON.stringify(projectWorkspace(id('ENVIRONMENT','pixel','alpine'),unsafe)).includes('do-not-render'),false);});

test('runtime workspace does not attach runs from another device or environment with the same runtime kind',()=>{
 const unrelated:WorkspaceRunInspector={...run,id:'other-run',physicalNodes:[{id:'other-device',label:'Other device'}],executionRoute:{...run.executionRoute!,path:[{id:'other-guest',label:'Other guest',kind:'GUEST_OS'}],runtime:{id:'different-runtime',kind:'podman'}}};
 const sameHost:WorkspaceRunInspector={...unrelated,id:'same-device-other-environment',physicalNodes:run.physicalNodes};
 const sameName:WorkspaceRunInspector={...unrelated,id:'same-runtime-id-other-device',executionRoute:{...unrelated.executionRoute!,runtime:run.executionRoute!.runtime}};
 const value=projectWorkspace(id('RUNTIME','pixel','alpine','runtime:podman'),{...source,runs:[run,unrelated,sameHost,sameName]});
 assert.deepEqual(value.children.map(child=>parseWorkspaceId(child.id).parts[0]),['run-one']);
});
