import assert from 'node:assert/strict';
import test from 'node:test';
import {OpenAICompatibleProviderClient, type FetchLike} from './openai-compatible-provider.js';

const provider = {id: 'external', kind: 'openai-compatible' as const, baseUrl: 'https://models.example/v1', wireApi: 'responses' as const, auth: {type: 'bearer-env' as const, env: 'MODEL_TEST_KEY'}};
const model = {id: 'fast', provider: 'external', providerModel: 'vendor/fast', enabled: true, capabilities: ['coding'], pricing: {currency: 'USD', inputPerMillionTokens: 1, outputPerMillionTokens: 2, cachedInputPerMillionTokens: .5, effectiveFrom: '2026-09-01', source: 'test'}};
const envKey = process.env.MODEL_TEST_KEY;
test.afterEach(() => { if (envKey === undefined) delete process.env.MODEL_TEST_KEY; else process.env.MODEL_TEST_KEY = envKey; });

test('successful OpenAI-compatible response normalizes usage and calculated cost', async () => { process.env.MODEL_TEST_KEY = 'test-secret-not-for-output'; let authorization = ''; const fetcher: FetchLike = async (_url, init) => { authorization = new Headers(init?.headers).get('authorization') ?? ''; return new Response(JSON.stringify({model: 'vendor/fast', status:'completed', output_text: 'ok', usage: {input_tokens: 100, output_tokens: 20, input_tokens_details: {cached_tokens: 40}, total_tokens: 120}}), {status: 200}); }; const result = await new OpenAICompatibleProviderClient(provider, fetcher).invoke(model, 'hello'); assert.equal(result.output, 'ok'); assert.equal(result.finishReason,'completed'); assert.equal(result.usage.cachedInputTokens, 40); assert.equal(result.usage.calculatedCost, .00012); assert.equal(authorization, 'Bearer test-secret-not-for-output'); assert.equal(JSON.stringify(result).includes('test-secret-not-for-output'), false); });
test('Responses-compatible adapters publish start and completion telemetry without inventing current context', async () => { process.env.MODEL_TEST_KEY = 'hidden'; const telemetry: Array<{phase:string; context:string; total:number|null}> = []; await new OpenAICompatibleProviderClient(provider, async () => new Response(JSON.stringify({model: 'vendor/fast', status:'completed', output_text: 'ok', usage: {input_tokens: 10, output_tokens: 2, total_tokens: 12}}), {status: 200})).invoke(model, 'hello', {onTelemetry: event => telemetry.push({phase: event.phase, context: event.context.authority, total: event.usage?.totalTokens ?? null})}); assert.deepEqual(telemetry, [{phase: 'started', context: 'unavailable', total: null}, {phase: 'completed', context: 'unavailable', total: 12}]); });

test('structured schema is sent as a strict JSON Schema on chat completions',async()=>{process.env.MODEL_TEST_KEY='hidden';let request:Record<string,unknown>|undefined;const chat={...provider,wireApi:'chat-completions' as const};const result=await new OpenAICompatibleProviderClient(chat,async(_url,init)=>{request=JSON.parse(String(init?.body));return new Response(JSON.stringify({model:'vendor/fast',choices:[{finish_reason:'stop',message:{content:'{"marker":"ok"}'}}]}),{status:200})}).invoke(model,'x',{structured:true,outputSchema:{type:'object',properties:{marker:{type:'string'}},required:['marker'],additionalProperties:false}});assert.equal(result.finishReason,'stop');assert.equal((request?.response_format as {type?:string}).type,'json_schema');assert.equal((request?.response_format as {json_schema?:{strict?:boolean}}).json_schema?.strict,true);assert.equal(request?.temperature,0)});
test('absent secret fails without making a request', async () => { delete process.env.MODEL_TEST_KEY; let called = false; await assert.rejects(() => new OpenAICompatibleProviderClient(provider, async () => { called = true; return new Response(); }).invoke(model, 'x'), /provider_authentication_required/); assert.equal(called, false); });
test('authentication and rate-limit responses are classified', async () => { process.env.MODEL_TEST_KEY = 'hidden'; await assert.rejects(() => new OpenAICompatibleProviderClient(provider, async () => new Response('', {status: 401})).invoke(model, 'x'), /provider_authentication_failed/); await assert.rejects(() => new OpenAICompatibleProviderClient(provider, async () => new Response('', {status: 429})).invoke(model, 'x'), /provider_rate_limited/); });
test('malformed and streaming-only responses fail safely', async () => { process.env.MODEL_TEST_KEY = 'hidden'; await assert.rejects(() => new OpenAICompatibleProviderClient(provider, async () => new Response('not-json', {status: 200})).invoke(model, 'x'), /provider_malformed_response/); await assert.rejects(() => new OpenAICompatibleProviderClient(provider, async () => new Response('data: partial\n\n', {status: 200, headers: {'content-type':'text/event-stream'}})).invoke(model, 'x'), /provider_malformed_response/); });
test('empty provider output retains sanitized partial usage finish and response-hash evidence',async()=>{process.env.MODEL_TEST_KEY='hidden';const chat={...provider,wireApi:'chat-completions' as const};await assert.rejects(async()=>new OpenAICompatibleProviderClient(chat,async()=>new Response(JSON.stringify({model:'vendor/fast',choices:[{finish_reason:'length',message:{content:null}}],usage:{prompt_tokens:10,completion_tokens:20,total_tokens:30}}),{status:200})).invoke(model,'x'),error=>{const partial=(error as {partialInvocation?:{finishReason?:string;usage?:{totalTokens?:number};responseHash?:string}}).partialInvocation;assert.equal(partial?.finishReason,'length');assert.equal(partial?.usage?.totalTokens,30);assert.match(partial?.responseHash??'',/^sha256:[a-f0-9]{64}$/);assert.equal(JSON.stringify(error).includes('choices'),false);return true})});
test('timeout is bounded', async () => { process.env.MODEL_TEST_KEY = 'hidden'; const fetcher: FetchLike = (_url, init) => new Promise((_resolve, reject) => init?.signal?.addEventListener('abort', () => reject(Object.assign(new Error('aborted'), {name: 'AbortError'})))); await assert.rejects(() => new OpenAICompatibleProviderClient(provider, fetcher).invoke(model, 'x', {timeoutMs: 5}), /provider_timeout/); });
test('Responses function call is normalized without executing it', async () => { process.env.MODEL_TEST_KEY='hidden'; let requested=false; const result=await new OpenAICompatibleProviderClient(provider,async (_url,init)=>{const body=JSON.parse(String(init?.body));requested=body.tool_choice?.name==='qualification_marker';return new Response(JSON.stringify({model:'vendor/fast',output:[{type:'function_call',name:'qualification_marker',arguments:'{"marker":"ok"}'}]}),{status:200})}).invoke(model,'call it',{toolProbe:'qualification_marker'});assert.equal(requested,true);assert.deepEqual(result.toolCall,{name:'qualification_marker',arguments:'{"marker":"ok"}'});assert.equal(result.output,''); });
test('Responses extraction excludes reasoning text and returns only assistant output_text',async()=>{process.env.MODEL_TEST_KEY='hidden';const result=await new OpenAICompatibleProviderClient(provider,async()=>new Response(JSON.stringify({model:'vendor/fast',output:[{type:'reasoning',content:[{type:'reasoning_text',text:'private reasoning'}]},{type:'message',content:[{type:'output_text',text:'{"marker":"ok"}'}]}]}),{status:200})).invoke(model,'x',{structured:true});assert.equal(result.output,'{"marker":"ok"}');assert.equal(result.output.includes('private reasoning'),false)});
