import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import test from 'node:test';
import {normalizeModelUsage, OpenAICompatibleProviderClient, PROMPT_CACHE_EXPLICIT_CAPABILITY, PROMPT_CACHE_KEY_CAPABILITY, type FetchLike} from './openai-compatible-provider.js';
import type {ProviderPrompt} from './provider-prompt.js';

const provider = {id: 'external', kind: 'openai-compatible' as const, baseUrl: 'https://models.example/v1', wireApi: 'responses' as const, auth: {type: 'bearer-env' as const, env: 'MODEL_TEST_KEY'}};
const model = {id: 'fast', provider: 'external', providerModel: 'vendor/fast', enabled: true, capabilities: ['coding'], pricing: {currency: 'USD', inputPerMillionTokens: 1, outputPerMillionTokens: 2, cachedInputPerMillionTokens: .5, effectiveFrom: '2026-09-01', source: 'test'}};
const envKey = process.env.MODEL_TEST_KEY;
test.afterEach(() => { if (envKey === undefined) delete process.env.MODEL_TEST_KEY; else process.env.MODEL_TEST_KEY = envKey; });

test('successful OpenAI-compatible response normalizes usage and calculated cost', async () => { process.env.MODEL_TEST_KEY = 'test-secret-not-for-output'; let authorization = ''; const fetcher: FetchLike = async (_url, init) => { authorization = new Headers(init?.headers).get('authorization') ?? ''; return new Response(JSON.stringify({model: 'vendor/fast', status:'completed', output_text: 'ok', usage: {input_tokens: 100, output_tokens: 20, input_tokens_details: {cached_tokens: 40}, total_tokens: 120}}), {status: 200}); }; const result = await new OpenAICompatibleProviderClient(provider, fetcher).invoke(model, 'hello'); assert.equal(result.output, 'ok'); assert.equal(result.finishReason,'completed'); assert.equal(result.usage.cachedInputTokens, 40); assert.equal(result.usage.calculatedCost, .00012); assert.equal(authorization, 'Bearer test-secret-not-for-output'); assert.equal(JSON.stringify(result).includes('test-secret-not-for-output'), false); });
test('Codex JSONL top-level cached input is normalized without changing total input', () => { const usage = normalizeModelUsage({input_tokens: 100, cached_input_tokens: 40, output_tokens: 20, total_tokens: 120}, model); assert.deepEqual(usage, {inputTokens: 100, outputTokens: 20, cachedInputTokens: 40, cacheWriteTokens: null, totalTokens: 120, providerReportedCost: null, calculatedCost: .00012, currency: 'USD'}); const camel = normalizeModelUsage({input_tokens: 100, cachedInputTokens: 40, output_tokens: 20, total_tokens: 120}, model); assert.equal(camel.cachedInputTokens, 40); });
test('cache writes remain distinct and use their configured price without double-counting fresh input', () => { const priced = {...model, pricing: {...model.pricing, cacheWritePerMillionTokens: 1.25}}; const usage = normalizeModelUsage({input_tokens: 100, input_tokens_details: {cached_tokens: 40, cache_write_tokens: 20}, output_tokens: 20, total_tokens: 120}, priced); assert.equal(usage.cacheWriteTokens, 20); assert.equal(usage.calculatedCost, .000125); const missing = normalizeModelUsage({input_tokens: 100, input_tokens_details: {cached_tokens: 40}, output_tokens: 20, total_tokens: 120}, priced); assert.equal(missing.calculatedCost, null); });
test('discounted cached-input pricing remains unknown when the provider omits the cache split', () => { const usage = normalizeModelUsage({input_tokens: 100, output_tokens: 20, total_tokens: 120}, model); assert.equal(usage.inputTokens, 100); assert.equal(usage.cachedInputTokens, null); assert.equal(usage.calculatedCost, null); const equalRates = normalizeModelUsage({input_tokens: 100, output_tokens: 20, total_tokens: 120}, {...model, pricing: {...model.pricing, cachedInputPerMillionTokens: 1}}); assert.equal(equalRates.calculatedCost, .00014); });
test('Responses-compatible adapters publish start and completion telemetry without inventing current context', async () => { process.env.MODEL_TEST_KEY = 'hidden'; const telemetry: Array<{phase:string; context:string; total:number|null}> = []; await new OpenAICompatibleProviderClient(provider, async () => new Response(JSON.stringify({model: 'vendor/fast', status:'completed', output_text: 'ok', usage: {input_tokens: 10, output_tokens: 2, total_tokens: 12}}), {status: 200})).invoke(model, 'hello', {onTelemetry: event => telemetry.push({phase: event.phase, context: event.context.authority, total: event.usage?.totalTokens ?? null})}); assert.deepEqual(telemetry, [{phase: 'started', context: 'unavailable', total: null}, {phase: 'completed', context: 'unavailable', total: 12}]); });
test('one-shot compatible-provider usage supplies estimated context when a window is configured', async () => { process.env.MODEL_TEST_KEY = 'hidden'; const contexts: unknown[] = [], configured = {...model, limits: {contextTokens: 100}}; await new OpenAICompatibleProviderClient(provider, async () => new Response(JSON.stringify({model: 'vendor/fast', status:'completed', output_text: 'ok', usage: {input_tokens: 40, output_tokens: 10, total_tokens: 50}}), {status: 200})).invoke(configured, 'hello', {onTelemetry: event => contexts.push(event.context)}); assert.deepEqual(contexts.at(-1), {tokens: 50, limitTokens: 100, authority: 'estimated', source: 'ephemeral_single_turn_usage_estimate'}); });

test('structured schema is sent as a strict JSON Schema on chat completions',async()=>{process.env.MODEL_TEST_KEY='hidden';let request:Record<string,unknown>|undefined;const chat={...provider,wireApi:'chat-completions' as const};const result=await new OpenAICompatibleProviderClient(chat,async(_url,init)=>{request=JSON.parse(String(init?.body));return new Response(JSON.stringify({model:'vendor/fast',choices:[{finish_reason:'stop',message:{content:'{"marker":"ok"}'}}]}),{status:200})}).invoke(model,'x',{structured:true,outputSchema:{type:'object',properties:{marker:{type:'string'}},required:['marker'],additionalProperties:false}});assert.equal(result.finishReason,'stop');assert.equal((request?.response_format as {type?:string}).type,'json_schema');assert.equal((request?.response_format as {json_schema?:{strict?:boolean}}).json_schema?.strict,true);assert.equal(request?.temperature,0)});
test('unsupported Responses routes retain the rendered legacy prompt and omit cache controls',async()=>{process.env.MODEL_TEST_KEY='hidden';let request:Record<string,unknown>|undefined;const structured:ProviderPrompt={schema:'agent-control.provider-prompt/v1',cacheScope:'private-repository-scope',blocks:[{type:'text',stability:'stable',text:'stable'},{type:'text',stability:'volatile',text:'-volatile'}]};await new OpenAICompatibleProviderClient(provider,async(_url,init)=>{request=JSON.parse(String(init?.body));return new Response(JSON.stringify({model:'vendor/fast',status:'completed',output_text:'ok'}),{status:200})}).invoke(model,structured);assert.equal(request?.input,'stable-volatile');assert.equal('prompt_cache_key' in (request??{}),false);assert.equal('prompt_cache_options' in (request??{}),false)});
test('Responses explicit cache controls require verified provider and model capabilities',async()=>{process.env.MODEL_TEST_KEY='hidden';let request:Record<string,unknown>|undefined;const capabilities=[PROMPT_CACHE_KEY_CAPABILITY,PROMPT_CACHE_EXPLICIT_CAPABILITY],qualifiedProvider={...provider,capabilities},qualifiedModel={...model,capabilities:['coding',...capabilities]},structured:ProviderPrompt={schema:'agent-control.provider-prompt/v1',cacheScope:'private-repository-scope',blocks:[{type:'text',stability:'stable',text:'stable evidence'},{type:'text',stability:'volatile',text:'\nrun-id'}]};await new OpenAICompatibleProviderClient(qualifiedProvider,async(_url,init)=>{request=JSON.parse(String(init?.body));return new Response(JSON.stringify({model:'vendor/fast',status:'completed',output_text:'ok',usage:{input_tokens:10,input_tokens_details:{cached_tokens:0,cache_write_tokens:10},output_tokens:1,total_tokens:11}}),{status:200})}).invoke(qualifiedModel,structured);const messages=request?.input as Array<{content:Array<Record<string,unknown>>}>;assert.equal(messages[0].content[0].text,'stable evidence');assert.deepEqual(messages[0].content[0].prompt_cache_breakpoint,{mode:'explicit'});assert.equal(messages[0].content[1].text,'\nrun-id');assert.equal(messages[0].content[1].prompt_cache_breakpoint,undefined);assert.deepEqual(request?.prompt_cache_options,{mode:'explicit'});assert.match(String(request?.prompt_cache_key),/^[a-f0-9]{64}$/);assert.equal(JSON.stringify(request).includes('private-repository-scope'),false)});
test('one-sided cache declarations do not send provider-specific fields',async()=>{process.env.MODEL_TEST_KEY='hidden';let request:Record<string,unknown>|undefined;const structured:ProviderPrompt={schema:'agent-control.provider-prompt/v1',cacheScope:'scope',blocks:[{type:'text',stability:'stable',text:'stable'}]};await new OpenAICompatibleProviderClient({...provider,capabilities:[PROMPT_CACHE_EXPLICIT_CAPABILITY]},async(_url,init)=>{request=JSON.parse(String(init?.body));return new Response(JSON.stringify({model:'vendor/fast',status:'completed',output_text:'ok'}),{status:200})}).invoke(model,structured);assert.equal(request?.input,'stable');assert.equal(request?.prompt_cache_options,undefined)});
test('absent secret fails without making a request', async () => { delete process.env.MODEL_TEST_KEY; let called = false; await assert.rejects(() => new OpenAICompatibleProviderClient(provider, async () => { called = true; return new Response(); }).invoke(model, 'x'), /provider_authentication_required/); assert.equal(called, false); });
test('declared file-backed compatibility reference is used when the primary environment reference is absent', async t => { delete process.env.MODEL_TEST_KEY; const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-provider-key-')),file=path.join(root,'credential'); t.after(()=>{delete process.env.MODEL_TEST_KEY_FILE;fs.rmSync(root,{recursive:true,force:true})}); fs.writeFileSync(file,'file-secret',{mode:0o600}); process.env.MODEL_TEST_KEY_FILE=file; let authorization=''; const configured={...provider,credentialEnv:'MODEL_TEST_KEY',credentialFileEnv:'MODEL_TEST_KEY_FILE'}; const result=await new OpenAICompatibleProviderClient(configured,async(_url,init)=>{authorization=new Headers(init?.headers).get('authorization')??'';return new Response(JSON.stringify({model:'vendor/fast',status:'completed',output_text:'ok'}),{status:200})}).invoke(model,'x'); assert.equal(authorization,'Bearer file-secret'); assert.equal(result.output,'ok'); assert.equal(JSON.stringify(result).includes('file-secret'),false); });
test('authentication and rate-limit responses are classified', async () => { process.env.MODEL_TEST_KEY = 'hidden'; await assert.rejects(() => new OpenAICompatibleProviderClient(provider, async () => new Response('', {status: 401})).invoke(model, 'x'), /provider_authentication_failed/); await assert.rejects(() => new OpenAICompatibleProviderClient(provider, async () => new Response('', {status: 429})).invoke(model, 'x'), /provider_rate_limited/); });
test('malformed and streaming-only responses fail safely', async () => { process.env.MODEL_TEST_KEY = 'hidden'; await assert.rejects(() => new OpenAICompatibleProviderClient(provider, async () => new Response('not-json', {status: 200})).invoke(model, 'x'), /provider_malformed_response/); await assert.rejects(() => new OpenAICompatibleProviderClient(provider, async () => new Response('data: partial\n\n', {status: 200, headers: {'content-type':'text/event-stream'}})).invoke(model, 'x'), /provider_malformed_response/); });
test('empty provider output retains sanitized partial usage finish and response-hash evidence',async()=>{process.env.MODEL_TEST_KEY='hidden';const chat={...provider,wireApi:'chat-completions' as const};await assert.rejects(async()=>new OpenAICompatibleProviderClient(chat,async()=>new Response(JSON.stringify({model:'vendor/fast',choices:[{finish_reason:'length',message:{content:null}}],usage:{prompt_tokens:10,completion_tokens:20,total_tokens:30}}),{status:200})).invoke(model,'x'),error=>{const partial=(error as {partialInvocation?:{finishReason?:string;usage?:{totalTokens?:number};responseHash?:string}}).partialInvocation;assert.equal(partial?.finishReason,'length');assert.equal(partial?.usage?.totalTokens,30);assert.match(partial?.responseHash??'',/^sha256:[a-f0-9]{64}$/);assert.equal(JSON.stringify(error).includes('choices'),false);return true})});
test('timeout is bounded', async () => { process.env.MODEL_TEST_KEY = 'hidden'; const fetcher: FetchLike = (_url, init) => new Promise((_resolve, reject) => init?.signal?.addEventListener('abort', () => reject(Object.assign(new Error('aborted'), {name: 'AbortError'})))); await assert.rejects(() => new OpenAICompatibleProviderClient(provider, fetcher).invoke(model, 'x', {timeoutMs: 5}), /provider_timeout/); });
test('caller cancellation remains distinct from provider timeout', async () => { process.env.MODEL_TEST_KEY = 'hidden'; const fetcher: FetchLike = (_url, init) => new Promise((_resolve, reject) => init?.signal?.addEventListener('abort', () => reject(Object.assign(new Error('aborted'), {name: 'AbortError'})))); const controller = new AbortController(), invocation = new OpenAICompatibleProviderClient(provider, fetcher).invoke(model, 'x', {timeoutMs: 30_000, signal: controller.signal}); controller.abort('operator_cancelled'); await assert.rejects(invocation, /provider_cancelled/); });
test('Responses function call is normalized without executing it', async () => { process.env.MODEL_TEST_KEY='hidden'; let requested=false; const result=await new OpenAICompatibleProviderClient(provider,async (_url,init)=>{const body=JSON.parse(String(init?.body));requested=body.tool_choice?.name==='qualification_marker';return new Response(JSON.stringify({model:'vendor/fast',output:[{type:'function_call',name:'qualification_marker',arguments:'{"marker":"ok"}'}]}),{status:200})}).invoke(model,'call it',{toolProbe:'qualification_marker'});assert.equal(requested,true);assert.deepEqual(result.toolCall,{name:'qualification_marker',arguments:'{"marker":"ok"}'});assert.equal(result.output,''); });
test('Responses extraction excludes reasoning text and returns only assistant output_text',async()=>{process.env.MODEL_TEST_KEY='hidden';const result=await new OpenAICompatibleProviderClient(provider,async()=>new Response(JSON.stringify({model:'vendor/fast',output:[{type:'reasoning',content:[{type:'reasoning_text',text:'private reasoning'}]},{type:'message',content:[{type:'output_text',text:'{"marker":"ok"}'}]}]}),{status:200})).invoke(model,'x',{structured:true});assert.equal(result.output,'{"marker":"ok"}');assert.equal(result.output.includes('private reasoning'),false)});
