import assert from 'node:assert/strict';
import test from 'node:test';
import {OpenAICompatibleProviderClient, type FetchLike} from './openai-compatible-provider.js';

const provider = {id: 'external', kind: 'openai-compatible' as const, baseUrl: 'https://models.example/v1', wireApi: 'responses' as const, auth: {type: 'bearer-env' as const, env: 'MODEL_TEST_KEY'}};
const model = {id: 'fast', provider: 'external', providerModel: 'vendor/fast', enabled: true, capabilities: ['coding'], pricing: {currency: 'USD', inputPerMillionTokens: 1, outputPerMillionTokens: 2, cachedInputPerMillionTokens: .5, effectiveFrom: '2026-09-01', source: 'test'}};
const envKey = process.env.MODEL_TEST_KEY;
test.afterEach(() => { if (envKey === undefined) delete process.env.MODEL_TEST_KEY; else process.env.MODEL_TEST_KEY = envKey; });

test('successful OpenAI-compatible response normalizes usage and calculated cost', async () => { process.env.MODEL_TEST_KEY = 'test-secret-not-for-output'; let authorization = ''; const fetcher: FetchLike = async (_url, init) => { authorization = new Headers(init?.headers).get('authorization') ?? ''; return new Response(JSON.stringify({model: 'vendor/fast', output_text: 'ok', usage: {input_tokens: 100, output_tokens: 20, input_tokens_details: {cached_tokens: 40}, total_tokens: 120}}), {status: 200}); }; const result = await new OpenAICompatibleProviderClient(provider, fetcher).invoke(model, 'hello'); assert.equal(result.output, 'ok'); assert.equal(result.usage.cachedInputTokens, 40); assert.equal(result.usage.calculatedCost, .00012); assert.equal(authorization, 'Bearer test-secret-not-for-output'); assert.equal(JSON.stringify(result).includes('test-secret-not-for-output'), false); });
test('absent secret fails without making a request', async () => { delete process.env.MODEL_TEST_KEY; let called = false; await assert.rejects(() => new OpenAICompatibleProviderClient(provider, async () => { called = true; return new Response(); }).invoke(model, 'x'), /provider_authentication_required/); assert.equal(called, false); });
test('authentication and rate-limit responses are classified', async () => { process.env.MODEL_TEST_KEY = 'hidden'; await assert.rejects(() => new OpenAICompatibleProviderClient(provider, async () => new Response('', {status: 401})).invoke(model, 'x'), /provider_authentication_failed/); await assert.rejects(() => new OpenAICompatibleProviderClient(provider, async () => new Response('', {status: 429})).invoke(model, 'x'), /provider_rate_limited/); });
test('malformed and streaming-only responses fail safely', async () => { process.env.MODEL_TEST_KEY = 'hidden'; await assert.rejects(() => new OpenAICompatibleProviderClient(provider, async () => new Response('not-json', {status: 200})).invoke(model, 'x'), /provider_malformed_response/); await assert.rejects(() => new OpenAICompatibleProviderClient(provider, async () => new Response('data: partial\n\n', {status: 200, headers: {'content-type':'text/event-stream'}})).invoke(model, 'x'), /provider_malformed_response/); });
test('timeout is bounded', async () => { process.env.MODEL_TEST_KEY = 'hidden'; const fetcher: FetchLike = (_url, init) => new Promise((_resolve, reject) => init?.signal?.addEventListener('abort', () => reject(Object.assign(new Error('aborted'), {name: 'AbortError'})))); await assert.rejects(() => new OpenAICompatibleProviderClient(provider, fetcher).invoke(model, 'x', {timeoutMs: 5}), /provider_timeout/); });
test('Responses function call is normalized without executing it', async () => { process.env.MODEL_TEST_KEY='hidden'; let requested=false; const result=await new OpenAICompatibleProviderClient(provider,async (_url,init)=>{const body=JSON.parse(String(init?.body));requested=body.tool_choice?.name==='qualification_marker';return new Response(JSON.stringify({model:'vendor/fast',output:[{type:'function_call',name:'qualification_marker',arguments:'{"marker":"ok"}'}]}),{status:200})}).invoke(model,'call it',{toolProbe:'qualification_marker'});assert.equal(requested,true);assert.deepEqual(result.toolCall,{name:'qualification_marker',arguments:'{"marker":"ok"}'});assert.equal(result.output,''); });
