import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import test from 'node:test';
import {ModelRegistry} from './model-registry.js';
import {ParameterizedJobEngine} from './parameterized-job-engine.js';
import {ParameterizedJobError, ParameterizedJobRegistry, ParameterizedRunStore, resolveParameters, SavedJobStore} from './parameterized-job-registry.js';
import {repositoryCodeReviewDefinition} from './repository-review-definition.js';
import {buildRepositoryContext, LocalRepositoryResolver, ReviewBaselineStore} from './repository-review-runtime.js';
import type {RepositoryReviewExecutor, ReviewExecutionRequest, ReviewExecutionResponse, SavedJob} from './parameterized-job-types.js';

function command(cwd: string, ...args: string[]) { return execFileSync(args[0], args.slice(1), {cwd, encoding: 'utf8'}).trim(); }
function repository(root: string) { const repo = path.join(root, 'repo'); fs.mkdirSync(repo); command(repo, 'git', 'init', '-q', '-b', 'main'); command(repo, 'git', 'config', 'user.email', 'test@example.invalid'); command(repo, 'git', 'config', 'user.name', 'Agent Control Test'); fs.writeFileSync(path.join(repo, 'index.ts'), 'export const answer = 41;\n'); command(repo, 'git', 'add', 'index.ts'); command(repo, 'git', 'commit', '-qm', 'initial'); return repo; }
function models(primaryQualified = true) { return new ModelRegistry([{id: 'provider', kind: 'openai-compatible', baseUrl: 'https://provider.invalid', wireApi: 'chat-completions', enabled: true}], [{id: 'fast', provider: 'provider', providerModel: 'glm-5.3-flash', capabilities: ['repository-review'], qualification: {state: primaryQualified ? 'QUALIFIED' : 'FAILED', version: 'q1', qualifiedAt: '2026-09-01T00:00:00Z', evidence: ['fixture'], capabilities: ['repository-review'], nodes: ['controller']}}, {id: 'deep', provider: 'provider', providerModel: 'glm-5.3', capabilities: ['repository-review'], qualification: {state: 'QUALIFIED', version: 'q2', qualifiedAt: '2026-09-01T00:00:00Z', evidence: ['fixture'], capabilities: ['repository-review'], nodes: ['controller']}}], {roles: {'review.default': {primary: 'fast', fallback: ['deep'], requires: ['repository-review']}}}); }
class FixtureExecutor implements RepositoryReviewExecutor {
  requests: ReviewExecutionRequest[] = [];
  verification: Array<{workParcelIds: string[]; verdict: string}> = [];
  beforeReturn?: (request: ReviewExecutionRequest) => void;
  recordVerification(workParcelIds: string[], verdict: 'PASS' | 'PASS_WITH_FINDINGS' | 'REVIEW_REQUIRED' | 'FAILED') { this.verification.push({workParcelIds: [...workParcelIds], verdict}); }
  async execute(request: ReviewExecutionRequest): Promise<ReviewExecutionResponse> { this.requests.push(request); this.beforeReturn?.(request); return {result: {schema: 'agent-control.repository-review/v1', executiveSummary: 'One validated finding.', findings: [{id: 'f1', severity: 'medium', title: 'Incorrect constant', category: 'correctness', file: 'index.ts', startLine: 1, endLine: 1, evidence: 'answer is fixed at 41', reasoning: 'fixture', impact: 'fixture', suggestedRemediation: 'review value', confidence: .9, validation: {state: 'UNVERIFIED', reasons: []}}, {id: 'bad', severity: 'high', title: 'Invented path', category: 'correctness', file: 'missing.ts', startLine: 1, evidence: 'not real', reasoning: 'fixture', impact: 'none', suggestedRemediation: 'none', confidence: .9, validation: {state: 'UNVERIFIED', reasons: []}}], positiveObservations: [], areasReviewed: ['index.ts'], areasNotReviewed: [], verdict: 'PASS_WITH_FINDINGS'}, usage: {inputTokens: 100, outputTokens: 20, totalTokens: 120, cost: .01, currency: 'USD', source: 'provider'}, evidence: ['provider-response:fixture'], providerResponseIds: ['response-1'], workParcelIds: ['parcel-1']}; }
}
function setup<T extends RepositoryReviewExecutor = FixtureExecutor>(root: string, repo: string, executor: T = new FixtureExecutor() as unknown as T, instant = new Date('2026-09-01T00:00:00Z'), registryModels = models()) { const definitions = new ParameterizedJobRegistry(); definitions.register(repositoryCodeReviewDefinition); const clock = () => instant, saved = new SavedJobStore(path.join(root, 'saved.json'), definitions, clock), runs = new ParameterizedRunStore(path.join(root, 'runs.json')), baselines = new ReviewBaselineStore(path.join(root, 'baselines.json')), engine = new ParameterizedJobEngine(definitions, saved, runs, baselines, registryModels, executor, {allowedRepositoryRoots: [root], snapshotsRoot: path.join(root, 'snapshots'), nodeHealthy: id => id === 'controller', clock}); const job = saved.create({id: 'review', name: 'Review', definition: {id: 'repository-code-review', version: 1, follow: 'latest-compatible'}, parameters: {node: 'controller', repository: repo, ref: 'main', scope: 'changes'}, contextProfile: 'STANDARD', concurrency: 'forbid-overlap', enabled: true}); return {definitions, saved, runs, baselines, engine, executor, job, setTime: (value: Date) => { instant = value; }}; }

test('definition parameters are typed, defaulted, versioned and reject unknown or incompatible updates', () => { const registry = new ParameterizedJobRegistry(), definition = registry.register(repositoryCodeReviewDefinition); assert.deepEqual(resolveParameters(definition, {node: 'controller', repository: '/srv/repositories/example'}), {node: 'controller', repository: '/srv/repositories/example', ref: 'main', scope: 'changes'}); assert.equal(resolveParameters(definition,{node:'controller',repository:'https://git.example/team/repo.git'}).repository,'https://git.example/team/repo.git'); assert.throws(() => resolveParameters(definition, {node: 'controller'}), /required_parameter_missing:repository/); assert.throws(() => resolveParameters(definition, {node: 'controller', repository: 'relative'}), /invalid_repository_reference/); assert.throws(() => resolveParameters(definition, {node: 'controller', repository: '/repo', arbitrary: true}), /unknown_parameter/); assert.throws(() => registry.register({...definition,parameters:{...definition.parameters,apiKey:{type:'string',description:'must not persist'}}}),/job_parameter_schema_invalid/); assert.throws(() => registry.register({...definition, displayName: 'Changed'}), /incompatible_definition_update/); assert.throws(() => registry.get('missing'), /unknown_definition/); });

test('saved jobs persist, validate schedules, use optimistic revisions and export no credentials', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ac-saved-')), repo = repository(root), setupResult = setup(root, repo), restored = new SavedJobStore(path.join(root, 'saved.json'), setupResult.definitions); assert.equal(restored.get('review').revision, 1); assert.throws(() => restored.update('review', 2, {name: 'wrong'}), /revision_conflict/); const scheduled = restored.update('review', 1, {schedule: {kind: 'cron', cron: '0 2 * * *', timezone: 'Europe\/London', enabled: true, missedRunPolicy: 'skip'}}); assert.equal(scheduled.revision, 2); assert.doesNotMatch(JSON.stringify(restored.export('review')), /token|credential|password/i); });

test('repository resolver freezes exact SHA in an isolated read-only snapshot and records dirty source state', () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ac-repo-')), repo = repository(root), sha = command(repo, 'git', 'rev-parse', 'HEAD'); fs.writeFileSync(path.join(repo, 'dirty.txt'), 'not reviewed\n'); const resolved = new LocalRepositoryResolver().resolve({nodeId: 'controller', repository: repo, requestedRef: 'main', allowedRoots: [root], snapshotsRoot: path.join(root, 'snapshots')}); assert.equal(resolved.reviewedSha, sha); assert.equal(resolved.dirty, true); assert.equal(command(resolved.snapshotPath, 'git', 'rev-parse', 'HEAD'), sha); assert.equal(fs.existsSync(path.join(resolved.snapshotPath, 'dirty.txt')), false); assert.equal(fs.statSync(path.join(resolved.snapshotPath, 'index.ts')).mode & 0o222, 0); assert.throws(() => new LocalRepositoryResolver().resolve({nodeId: 'controller', repository: repo, requestedRef: 'main', allowedRoots: ['/var'], snapshotsRoot: path.join(root, 'other')}), /outside_policy/); });

test('repository context excludes secret files and reports every unrepresented tracked file',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-context-')),repo=repository(root);fs.writeFileSync(path.join(repo,'secrets.json'),'{"value":"never-send"}\n');fs.writeFileSync(path.join(repo,'notes.txt'),'not selected by THIN\n');command(repo,'git','add','secrets.json','notes.txt');command(repo,'git','commit','-qm','context inputs');const resolved=new LocalRepositoryResolver().resolve({nodeId:'controller',repository:repo,requestedRef:'main',allowedRoots:[root],snapshotsRoot:path.join(root,'snapshots')}),context=buildRepositoryContext(resolved,'THIN',10_000),wire=context.chunks.map(chunk=>chunk.content).join('\n');assert.equal(wire.includes('never-send'),false);assert.equal(wire.includes('secrets.json'),false);assert.equal(context.summary?.omittedFiles.includes('notes.txt'),true);assert.equal(context.summary?.omittedFiles.includes('secrets.json'),true)});

test('repository resolution fails closed for missing, non-Git, unresolved ref and unapproved remote inputs',()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-repo-errors-')),plain=path.join(root,'plain');fs.mkdirSync(plain);const resolver=new LocalRepositoryResolver();assert.throws(()=>resolver.resolve({nodeId:'controller',repository:path.join(root,'missing'),requestedRef:'main',allowedRoots:[root]}),/repository_missing/);assert.throws(()=>resolver.resolve({nodeId:'controller',repository:plain,requestedRef:'main',allowedRoots:[root]}),/repository_not_git/);const repo=repository(root);assert.throws(()=>resolver.resolve({nodeId:'controller',repository:repo,requestedRef:'missing-branch',allowedRoots:[root]}),/repository_ref_unresolved/);assert.throws(()=>resolver.resolve({nodeId:'controller',repository:'https://git.example/team/repo.git',requestedRef:'main',allowedRoots:[root],allowedRemotes:[]}),/repository_remote_outside_policy/);});

test('manual execution routes qualified model, links work parcels, validates findings and advances only successful baseline', async () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ac-run-')), repo = repository(root), setupResult = setup(root, repo), created = setupResult.engine.runNow('review', 'operator'), completed = await setupResult.engine.execute(created.id); assert.equal(completed.status, 'SUCCEEDED_WITH_FINDINGS'); assert.equal(completed.repository?.reviewedSha, command(repo, 'git', 'rev-parse', 'HEAD')); assert.equal(completed.modelRoute?.modelId, 'fast'); assert.deepEqual(completed.workParcelIds, ['parcel-1']); assert.equal(completed.result?.findings.length, 1); assert.equal(completed.result?.findings[0].validation.state, 'VALID'); assert.deepEqual(setupResult.executor.verification, [{workParcelIds: ['parcel-1'], verdict: 'PASS_WITH_FINDINGS'}]); assert.equal(completed.immutable, true); assert.throws(() => setupResult.runs.update(completed), /historical_run_immutable/); assert.equal(setupResult.baselines.get('review', completed.repository!.identity, 'main')?.sha, completed.repository!.reviewedSha); });

test('branch movement during review cannot change frozen SHA and next success reviews the delta', async () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ac-delta-')), repo = repository(root), setupResult = setup(root, repo), first = await setupResult.engine.execute(setupResult.engine.runNow('review', 'operator').id), firstSha = first.repository!.reviewedSha; fs.writeFileSync(path.join(repo, 'index.ts'), 'export const answer = 42;\n'); command(repo, 'git', 'add', 'index.ts'); command(repo, 'git', 'commit', '-qm', 'change'); const secondSha = command(repo, 'git', 'rev-parse', 'HEAD'); setupResult.setTime(new Date('2026-09-01T01:00:00Z')); setupResult.executor.beforeReturn = () => { fs.writeFileSync(path.join(repo, 'later.ts'), 'export const later = true;\n'); command(repo, 'git', 'add', 'later.ts'); command(repo, 'git', 'commit', '-qm', 'later'); }; const second = await setupResult.engine.execute(setupResult.engine.runNow('review', 'operator').id); assert.equal(second.repository?.reviewedSha, secondSha); assert.equal(second.repository?.comparisonSha, firstSha); assert.deepEqual(second.context?.changedFiles, ['index.ts']); assert.equal(setupResult.baselines.get('review', second.repository!.identity, 'main')?.sha, secondSha); });

test('failed review does not advance baseline and missing work parcel fails closed', async () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ac-fail-')), repo = repository(root), executor: RepositoryReviewExecutor = {execute: async () => ({result: {schema: 'agent-control.repository-review/v1', executiveSummary: 'none', findings: [], positiveObservations: [], areasReviewed: [], areasNotReviewed: [], verdict: 'PASS'}, usage: {source: 'unavailable'}, evidence: [], providerResponseIds: [], workParcelIds: []})}, setupResult = setup(root, repo, executor); const failed = await setupResult.engine.execute(setupResult.engine.runNow('review', 'operator').id); assert.equal(failed.status, 'FAILED'); assert.match(failed.errors[0], /work_parcel_missing/); assert.equal(setupResult.baselines.get('review', failed.repository!.identity, 'main'), undefined); });

test('logical route records explicit fallback and fallback can be disabled', async () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ac-route-')), repo = repository(root), setupResult = setup(root, repo, new FixtureExecutor(), new Date('2026-09-01T00:00:00Z'), models(false)); const completed = await setupResult.engine.execute(setupResult.engine.runNow('review', 'operator').id); assert.equal(completed.status, 'SUCCEEDED_WITH_FINDINGS'); assert.equal(completed.modelRoute?.modelId, 'deep'); assert.equal(completed.modelRoute?.fallback, true); assert.match(completed.fallbackHistory[0].reason, /fast/); const current = setupResult.saved.get('review'), changed = setupResult.saved.update('review', current.revision, {routing: {modelRole: 'review.default', allowFallback: false}}); setupResult.setTime(new Date('2026-09-01T01:00:00Z')); const failed = await setupResult.engine.execute(setupResult.engine.runNow(changed.id, 'operator').id); assert.equal(failed.status, 'FAILED'); assert.match(failed.errors[0], /model_fallback_disabled/); });

test('Saved Job account policy reaches the exact account-bound production route', async () => {
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-account-route-')),repo=repository(root),profile={id:'lawrence-pro',nodeId:'msi',label:'Lawrence Pro',credentialStore:{type:'codex-home-env' as const,env:'CODEX_HOME_LAWRENCE_PRO'},qualification:{state:'QUALIFIED' as const,version:'account-q1',checkedAt:'2026-09-02T00:00:00Z',qualifiedAt:'2026-09-02T00:00:00Z',capabilities:['codex-chatgpt'],evidence:['interactive-login']}},registry=new ModelRegistry([{id:'codex',kind:'cli',accountProfiles:[profile]}],[{id:'sol-pro',provider:'codex',accountProfile:'lawrence-pro',providerModel:'gpt-5.6-sol',capabilities:['repository-review'],qualification:{state:'QUALIFIED',version:'model-q1',capabilities:['repository-review'],nodes:['msi']}}],{roles:{'review.default':{primary:'sol-pro',requires:['repository-review']}}}),fixture=new FixtureExecutor(),setupResult=setup(root,repo,fixture,new Date('2026-09-02T00:00:00Z'),registry),current=setupResult.saved.get('review');
  setupResult.saved.update('review',current.revision,{routing:{model:'sol-pro',accountProfile:'lawrence-pro',allowFallback:false},budgets:{timeoutMinutes:3}});
  const completed=await setupResult.engine.execute(setupResult.engine.runNow('review','operator').id);
  assert.equal(completed.modelRoute?.providerId,'codex');assert.equal(completed.modelRoute?.accountProfileId,'lawrence-pro');assert.equal(completed.modelRoute?.modelId,'sol-pro');assert.equal(completed.modelRoute?.nodeId,'msi');assert.equal(completed.repository?.nodeId,'controller');assert.equal(fixture.requests[0].route.accountProfileId,'lawrence-pro');assert.equal(fixture.requests[0].run.definition.budgets.timeoutMinutes,3);
  const latest=setupResult.saved.get('review');assert.throws(()=>setupResult.saved.update('review',latest.revision,{routing:{model:'sol-pro',accountProfile:'invalid profile',allowFallback:false}}),/saved_job_account_profile_invalid/);
});

test('scheduler persists occurrence identity, prevents duplicate delivery, honours disable and uses manual run path', async () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ac-schedule-')), repo = repository(root), setupResult = setup(root, repo), scheduled = setupResult.saved.update('review', 1, {schedule: {kind: 'cron', cron: '0 2 * * *', timezone: 'Europe/London', enabled: true, missedRunPolicy: 'run-once-immediately'}}); setupResult.setTime(new Date('2026-09-01T01:00:00Z')); assert.equal((await setupResult.engine.tickSchedules()).length, 1); assert.equal((await setupResult.engine.tickSchedules()).length, 0); assert.equal(setupResult.runs.list().length, 1); await setupResult.engine.executeNext(); assert.equal(setupResult.runs.list()[0].status, 'SUCCEEDED_WITH_FINDINGS'); setupResult.saved.setEnabled('review', false, scheduled.revision); setupResult.setTime(new Date('2026-09-02T01:00:00Z')); assert.equal((await setupResult.engine.tickSchedules()).length, 0); const restored = new ParameterizedRunStore(path.join(root, 'runs.json')); assert.equal(restored.list().length, 1); });

test('run-once-immediately retains the deterministic due occurrence while advancing past missed backlog',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-run-once-')),repo=repository(root),setupResult=setup(root,repo);setupResult.saved.update('review',1,{schedule:{kind:'cron',cron:'0 2 * * *',timezone:'Europe/London',enabled:true,missedRunPolicy:'run-once-immediately'}});setupResult.setTime(new Date('2026-09-03T12:00:00Z'));const [run]=await setupResult.engine.tickSchedules();assert.equal(run.trigger.scheduledFor,'2026-09-01T01:00:00.000Z');assert.equal(run.trigger.scheduleCursor,'2026-09-03T12:00:00.000Z');assert.equal((await setupResult.engine.tickSchedules()).length,0);const restored=new ParameterizedRunStore(path.join(root,'runs.json'));assert.equal(restored.get(run.id)?.occurrenceId,run.occurrenceId)});

test('missed skip occurrences are durably consumed and interrupted frozen runs resume one identity and monotonic execution sequence', async () => { const root = fs.mkdtempSync(path.join(os.tmpdir(), 'ac-restart-')), repo = repository(root), setupResult = setup(root, repo); setupResult.saved.update('review', 1, {schedule: {kind: 'cron', cron: '0 2 * * *', timezone: 'Europe/London', enabled: true, missedRunPolicy: 'skip'}}); setupResult.setTime(new Date('2026-09-03T12:00:00Z')); const skipped = await setupResult.engine.tickSchedules(); assert.equal(skipped[0].status, 'CANCELLED'); assert.match(skipped[0].errors[0], /missed-schedule-skip/); const second = await setupResult.engine.tickSchedules(); assert.equal(second[0].status, 'CANCELLED'); assert.notEqual(second[0].occurrenceId, skipped[0].occurrenceId); const manual = setupResult.engine.runNow('review', 'operator'), mutable = setupResult.runs.get(manual.id)!; mutable.status = 'RUNNING'; mutable.executionSequence = 3; mutable.transitions.push({status: 'RUNNING', at: '2026-09-03T12:00:00Z'}); setupResult.runs.update(mutable); const recovered = new ParameterizedJobEngine(setupResult.definitions, setupResult.saved, setupResult.runs, setupResult.baselines, setupResult.engine.models, setupResult.executor, setupResult.engine.options); assert.equal(recovered.runs.get(manual.id)?.status, 'QUEUED'); assert.equal(recovered.runs.get(manual.id)?.id, manual.id); const completed = await recovered.execute(manual.id); assert.equal(completed.executionSequence, 4); assert.equal(setupResult.executor.requests.at(-1)?.executionAttempt, 4); });

test('retry remains within one Run and cost budget failure preserves evidence without baseline advancement',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-budget-')),repo=repository(root),fixture=new FixtureExecutor(),original=fixture.execute.bind(fixture);let attempts=0;fixture.execute=async request=>{attempts++;if(attempts===1)throw Object.assign(new Error('provider_unavailable'),{workParcelIds:['failed-parcel']});return original(request)};const setupResult=setup(root,repo,fixture),current=setupResult.saved.get('review');setupResult.saved.update('review',current.revision,{budgets:{maximumRetries:1,maxCost:.001}});const completed=await setupResult.engine.execute(setupResult.engine.runNow('review','operator').id);assert.equal(attempts,2);assert.equal(completed.retryHistory.length,1);assert.deepEqual(completed.workParcelIds,['failed-parcel','parcel-1']);assert.deepEqual(fixture.verification,[]);assert.equal(completed.status,'FAILED');assert.match(completed.errors[0],/cost_budget_exceeded/);assert.equal(setupResult.baselines.get('review',completed.repository!.identity,'main'),undefined)});

test('configured cost budget fails closed when authoritative and calculated cost are unavailable',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-budget-unknown-')),repo=repository(root),fixture=new FixtureExecutor(),original=fixture.execute.bind(fixture);fixture.execute=async request=>{const response=await original(request);response.usage={inputTokens:100,outputTokens:20,totalTokens:120,source:'unavailable'};return response};const setupResult=setup(root,repo,fixture),current=setupResult.saved.get('review');setupResult.saved.update('review',current.revision,{budgets:{maximumRetries:0,maxCost:1}});const completed=await setupResult.engine.execute(setupResult.engine.runNow('review','operator').id);assert.equal(completed.status,'FAILED');assert.match(completed.errors[0],/cost_budget_unenforceable/);assert.deepEqual(fixture.verification,[])});

test('timeout and operator cancellation are distinct durable terminal outcomes',async()=>{const waitExecutor:RepositoryReviewExecutor={execute:request=>new Promise((_resolve,reject)=>request.signal.addEventListener('abort',()=>reject(new Error('aborted')),{once:true}))};const timeoutRoot=fs.mkdtempSync(path.join(os.tmpdir(),'ac-timeout-')),timeoutRepo=repository(timeoutRoot),timed=setup(timeoutRoot,timeoutRepo,waitExecutor),timedJob=timed.saved.get('review');timed.saved.update('review',timedJob.revision,{budgets:{timeoutMinutes:.0002,maximumRetries:0}});const timeoutRun=await timed.engine.execute(timed.engine.runNow('review','operator').id);assert.equal(timeoutRun.status,'FAILED');assert.deepEqual(timeoutRun.errors,['job_timeout_budget_exceeded']);const cancelRoot=fs.mkdtempSync(path.join(os.tmpdir(),'ac-cancel-')),cancelRepo=repository(cancelRoot),cancelled=setup(cancelRoot,cancelRepo,waitExecutor),created=cancelled.engine.runNow('review','operator'),pending=cancelled.engine.execute(created.id);while(cancelled.runs.get(created.id)?.status!=='RUNNING')await new Promise(resolve=>setTimeout(resolve,1));cancelled.engine.cancel(created.id,'operator');const cancelRun=await pending;assert.equal(cancelRun.status,'CANCELLED');assert.match(cancelRun.errors[0],/cancelled_by:operator/)});

test('forbid-overlap rejects a second active Run and rewritten history never uses a non-ancestor baseline',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'ac-rewrite-')),repo=repository(root),setupResult=setup(root,repo),queued=setupResult.engine.runNow('review','operator');assert.throws(()=>setupResult.engine.runNow('review','operator'),/overlap_forbidden/);await setupResult.engine.execute(queued.id);const first=setupResult.runs.get(queued.id)!.repository!.reviewedSha;command(repo,'git','checkout','--orphan','rewritten');for(const file of fs.readdirSync(repo))if(file!=='.git')fs.rmSync(path.join(repo,file),{recursive:true,force:true});fs.writeFileSync(path.join(repo,'new.ts'),'export const rewritten = true;\n');command(repo,'git','add','-A');command(repo,'git','commit','-qm','rewrite');command(repo,'git','branch','-M','main');setupResult.setTime(new Date('2026-09-02T00:00:00Z'));const second=await setupResult.engine.execute(setupResult.engine.runNow('review','operator').id);assert.notEqual(second.repository?.reviewedSha,first);assert.equal(second.repository?.comparisonSha,undefined);assert.ok(['SUCCEEDED','SUCCEEDED_WITH_FINDINGS'].includes(second.status))});
