import fs from 'node:fs';
import path from 'node:path';
import {ActionFailure,ActionRegistry,ArtifactStore,JobRuntime,ResourceLockManager,RunLedger,WorkerRegistry} from './job-runtime.js';
import {JobCatalog} from './job-catalog.js';
import type {JobDefinition,ParameterDefinition} from './job-types.js';
import type {ModelRegistry} from './model-registry.js';
import type {ProviderConfig,ModelConfig} from './config.js';
import {OpenAICompatibleProviderClient} from './openai-compatible-provider.js';
import {WorkParcelCoordinator,WorkParcelStore,type VoiceWorkOrigin,type WorkParcelPlan} from './work-parcels.js';
import type {GovernedVoiceWorkPort} from './conversational-work.js';

const codeAction='voice.sandbox-python-script@1.0.0',windowAction='voice.refinement-window@1.0.0';
const job=(id:string,name:string,action:string,requires:string[],parameters?:Record<string,ParameterDefinition>,outputs?:Array<{name:string;type:string;schema:string;version:string}>):JobDefinition=>({apiVersion:'agent-control/v1',kind:'Job',metadata:{id,name,version:'1.0.0'},spec:{priority:'normal',concurrency:'queue',parameters,steps:[{id:'execute',action,requires,resources:['voice-qualification-workspace'],outputs,verification:outputs?['sandbox-tests-passed']:[]}]}});
const sanitizeCode=(value:string)=>{let text=value.trim();text=text.replace(/^```(?:python)?\s*/i,'').replace(/\s*```$/,'').trim();if(!text||text.length>40_000)throw new ActionFailure('voice_coding_output_invalid','verification');return text+'\n';};

export class RealtimeGovernedWorkRuntime implements GovernedVoiceWorkPort {
  readonly coordinator:WorkParcelCoordinator;readonly runtime:JobRuntime;private active=false;private timer:ReturnType<typeof setInterval>;
  constructor(private root:string,private models:ModelRegistry,private provider:ProviderConfig,private model:ModelConfig,private options:{refinementSeconds?:number;tickMs?:number}={}){
    fs.mkdirSync(root,{recursive:true,mode:0o700});const actions=new ActionRegistry();
    actions.register(windowAction,async context=>{const seconds=Number(context.parameters.seconds??35);const result=await context.ownedExecution.runProcess({command:process.execPath,args:['-e','setTimeout(()=>{},Number(process.argv[1])*1000)',String(seconds)],maxOutputBytes:4096},context.signal);if(result.exitCode!==0)throw new ActionFailure('voice_refinement_window_failed','execution');return{evidence:[`Conversational refinement window remained open for ${seconds} seconds`],verification:[],detail:'Refinement window completed'};});
    actions.register(codeAction,async context=>{
      const instructions=context.run.trigger.parcelContext?.effectiveInstructions??[],request=String(context.parameters.effectiveRequest??'');if(!request.trim())throw new ActionFailure('voice_effective_request_required','configuration');
      const prompt={schema:'agent-control.provider-prompt/v1' as const,cacheScope:'voice-sandbox-coding-v1',blocks:[{type:'text' as const,stability:'volatile' as const,text:`Create the requested Python 3 utility. Return only source code, with no markdown. Use the standard library only. Never delete, move, rename, or overwrite input files. Request: ${request}\nAppend-only steering: ${instructions.join(' | ')||'none'}\nThe program must accept an input directory and an output report path. It must identify duplicate regular files by SHA-256 and write a useful report. If steering asks for CSV, emit CSV.`}]};
      const result=await new OpenAICompatibleProviderClient(this.provider).invoke(this.model,prompt,{timeoutMs:180_000,maximumOutputTokens:700,systemPrompt:'You are a coding worker inside an isolated governed test. Return concise, complete Python source only. Avoid comments and explanatory prose.',temperature:.1,signal:context.signal}),code=sanitizeCode(result.output),workspace=path.join(this.root,'workspaces',context.run.id.replace(/[^a-zA-Z0-9_.-]/g,'_'));
      fs.mkdirSync(path.join(workspace,'fixture'),{recursive:true,mode:0o700});const fixture=path.join(workspace,'fixture');fs.writeFileSync(path.join(fixture,'a.bin'),'same');fs.writeFileSync(path.join(fixture,'b.bin'),'same');fs.writeFileSync(path.join(fixture,'unique.bin'),'different');const script=path.join(workspace,'duplicate_report.py'),report=path.join(workspace,'report.csv');fs.writeFileSync(script,code,{mode:0o600});
      const base=['--unshare-all','--die-with-parent','--new-session','--ro-bind','/usr','/usr','--ro-bind','/lib','/lib','--ro-bind','/lib64','/lib64','--ro-bind','/bin','/bin','--proc','/proc','--dev','/dev','--tmpfs','/tmp','--bind',workspace,'/work','--chdir','/work','--setenv','PATH','/usr/bin:/bin'];
      const compile=await context.ownedExecution.runProcess({command:'/usr/bin/bwrap',args:[...base,'python3','-m','py_compile','/work/duplicate_report.py'],maxOutputBytes:32_768},context.signal);if(compile.exitCode!==0)throw new ActionFailure('voice_generated_script_compile_failed','verification');
      const run=await context.ownedExecution.runProcess({command:'/usr/bin/bwrap',args:[...base,'python3','/work/duplicate_report.py','/work/fixture','/work/report.csv'],maxOutputBytes:32_768},context.signal);if(run.exitCode!==0||!fs.existsSync(report))throw new ActionFailure('voice_generated_script_test_failed','verification');const reportText=fs.readFileSync(report,'utf8');if(!reportText.includes('a.bin')||!reportText.includes('b.bin')||reportText.includes('unique.bin')||!['a.bin','b.bin','unique.bin'].every(name=>fs.existsSync(path.join(fixture,name))))throw new ActionFailure('voice_generated_script_behavior_failed','verification');
      return{artifacts:[{name:'python-script',value:{path:script,source:code}},{name:'duplicate-report',value:{path:report,content:reportText}}],evidence:['Generated source compiled inside bubblewrap with network and host filesystem isolated','Fixture duplicates reported and all input files preserved'],verification:['sandbox-tests-passed'],detail:`Script and report retained in ${workspace}`};
    });
    const catalog=new JobCatalog(actions.ids());catalog.addJob(job('voice-refinement-window','Voice request refinement window',windowAction,['voice.refinement'],{seconds:{type:'number',default:35,minimum:0,maximum:60}}));catalog.addJob(job('voice-sandbox-python-script','Sandbox Python script generation and verification',codeAction,['coding'],{effectiveRequest:{type:'string',required:true}},[{name:'python-script',type:'text/x-python',schema:'agent-control.voice-python-script/v1',version:'1.0.0'},{name:'duplicate-report',type:'text/csv',schema:'agent-control.voice-duplicate-report/v1',version:'1.0.0'}]));
    const workers=new WorkerRegistry().register({id:'controller',capabilities:['voice.refinement','coding'],health:'healthy',capacity:1,active:0,observedAt:new Date().toISOString()});this.runtime=new JobRuntime(catalog,actions,workers,new RunLedger(path.join(root,'runs.json')),new ArtifactStore(path.join(root,'artifacts')),new ResourceLockManager(path.join(root,'locks.json')),{approval:()=>true});this.coordinator=new WorkParcelCoordinator(this.runtime,new WorkParcelStore(path.join(root,'parcels.json')),{plan:()=>{throw new Error('voice_uses_approved_plan');}},undefined,models);this.timer=setInterval(()=>void this.tick(),this.options.tickMs??500);this.timer.unref();
  }
  async start(input:{origin:VoiceWorkOrigin;actor:string}){const plan:WorkParcelPlan={objective:input.origin.effectiveRequest,planner:{kind:'deterministic',reason:'Authenticated low-risk fixture request mapped to registered voice sandbox coding Job'},stages:[{id:'refine',name:'Conversational refinement window',job:'voice-refinement-window@1.0.0',parameters:{seconds:this.options.refinementSeconds??35},requiredCapabilities:['voice.refinement'],outputs:[]},{id:'code',name:'Generate and test duplicate report utility',job:'voice-sandbox-python-script@1.0.0',dependsOn:['refine'],parameters:{effectiveRequest:input.origin.effectiveRequest},requiredCapabilities:['coding'],outputs:['python-script','duplicate-report'],requestedRoute:{modelRole:'voice.coding',allowFallback:false,reason:'Use separately qualified coding route'}}]};const parcel=this.coordinator.submitApprovedVoicePlan(input.origin,input.actor,plan);void this.tick();return{id:parcel.id,status:parcel.status,workModel:this.model.id,routeReason:'Qualified voice.coding route; execution isolated by bubblewrap'};}
  async status(id:string){const parcel=this.coordinator.get(id),stage=parcel.stages.find(item=>item.status==='RUNNING')??parcel.stages.find(item=>item.status==='QUEUED');return{status:parcel.status,phase:stage?.name,summary:parcel.status==='SUCCEEDED'?'The generated script compiled and passed the duplicate-file fixture test.':parcel.status==='FAILED'?parcel.decision?.summary:stage?`${stage.name}.`:undefined};}
  async steer(id:string,instruction:string,actor:string){return this.coordinator.steer(id,{instruction,constraints:['Preserve all input files','Use isolated qualification workspace'],affectedStageIds:['code'],actor});}
  async cancel(id:string,actor:string){return this.coordinator.cancel(id,actor);}
  close(){clearInterval(this.timer);}
  private async tick(){if(this.active)return;this.active=true;try{await this.coordinator.tick();for(;;){const dispatched=this.runtime.dispatch();if(!dispatched)break;void dispatched.completion.finally(()=>void this.tick());}}finally{this.active=false;}}
}
