import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {RealtimeVoiceSession,VoiceSessionStore,type VoiceSessionOptions,type RealtimeVoiceTransport} from './realtime-voice.js';

const caller={identity:{channel:'fixture',account:'account',sender:'operator',conversation:'operator'},display:'Enrolled test operator'};
const voice={id:'fixed',provider:'fixture-tts',kind:'generic' as const,modelRevision:'revision',seed:1};
const wait=()=>new Promise(r=>setTimeout(r,10));
function setup(t:test.TestContext){
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'realtime-voice-')),file=path.join(dir,'voice.sqlite'),store=new VoiceSessionStore(file);let sent=0,stopped=0,hangups=0,allowed=true;
  const transport:RealtimeVoiceTransport={id:'fixture',capabilities:{duplex:true,interrupt:true,isolatedCallerAudio:true,reconnect:false},async accept(){},async reject(){},async health(){return {state:'ready'};},async sendAudio(){sent++;return {};},async interruptOutput(){stopped++;return {};},async hangup(){hangups++;}};
  const options:VoiceSessionOptions={store,transport,voice,authorize:()=>allowed?{actor:'operator',tools:['status']}:undefined,recognition:{id:'fixture-stt',mode:'utterance-buffered',async transcribe(){return 'status please';}},speech:{id:'fixture-tts',mode:'buffered-then-framed',async *frames(){yield new Int16Array(320);}},orchestration:{async respond(){return {text:'Ready.',model:'model-a',routeReason:'qualified low-cost route'};},async invokeTool(){return 'healthy';}}};
  let sequence=0;
  const feed=(s:RealtimeVoiceSession,n:number,amplitude:number)=>{for(let i=0;i<n;i++)s.receive({sequence:sequence++,sampleRate:16000,pcm:new Int16Array(320).fill(amplitude)});};
  const utterance=(s:RealtimeVoiceSession)=>{feed(s,5,2000);feed(s,25,0);};
  t.after(()=>{store.close();fs.rmSync(dir,{recursive:true,force:true});});
  return {store,file,options,transport,feed,utterance,counts:()=>({sent,stopped,hangups}),revoke:()=>{allowed=false;}};
}
async function connect(options:VoiceSessionOptions){const r=await RealtimeVoiceSession.incoming(options,'call',caller);assert.equal(r.duplicate,false);if(r.duplicate)throw Error();return r.session;}
test('unknown caller and transport without media are rejected before accept',async t=>{const h=setup(t);let accepted=0;h.transport.accept=async()=>{accepted++;};h.revoke();await assert.rejects(()=>connect(h.options));assert.equal(accepted,0);assert.equal(h.store.projection().length,0);});
test('duplex capability alone is insufficient without output interruption',async t=>{const h=setup(t);h.transport.capabilities.interrupt=false;await assert.rejects(()=>connect(h.options));});
test('a caller cannot create overlapping sessions or change transport identity',async t=>{const h=setup(t),s=await connect(h.options);await assert.rejects(()=>RealtimeVoiceSession.incoming(h.options,'second',caller),/capacity/);await assert.rejects(()=>RealtimeVoiceSession.incoming(h.options,'other',{...caller,identity:{...caller.identity,channel:'different'}}));await s.end('test');});
test('duplicate call never accepts twice, including after termination',async t=>{const h=setup(t),s=await connect(h.options);assert.equal((await RealtimeVoiceSession.incoming(h.options,'call',caller)).duplicate,true);await s.end('caller_disconnect');assert.equal((await RealtimeVoiceSession.incoming(h.options,'call',caller)).duplicate,true);});
test('PCM silence creates no turn; invalid/partial and duplicate frames do not create commands',async t=>{const h=setup(t),s=await connect(h.options);h.feed(s,30,0);s.receive({sequence:0,sampleRate:16000,pcm:new Int16Array(320)});s.receive({sequence:31,sampleRate:16000,pcm:new Int16Array(12)});await wait();assert.equal(h.counts().sent,0);await s.end('test');});
test('real pipeline contract records final STT/model/voice without invented latency or usage',async t=>{const h=setup(t),s=await connect(h.options);h.utterance(s);await wait();const events=h.store.events(s.id);assert.ok(events.some(e=>e.type==='STT'));assert.equal(events.find(e=>e.type==='TTS FIRST AUDIO')?.detail.endOfUtteranceToAudibleMs,null);assert.equal((events.find(e=>e.type==='MODEL')?.detail.usage as any).inputTokens,null);assert.equal(h.counts().sent,1);await s.end('test');});
test('barge-in suppresses output while a provider ignores cancellation; late generation is fenced',async t=>{const h=setup(t);let release!:(v:any)=>void;h.options.orchestration.respond=()=>new Promise(r=>release=r);const s=await connect(h.options);h.utterance(s);await wait();h.feed(s,3,2000);await wait();release({text:'stale reply',model:'a',routeReason:'fixture'});await wait();assert.equal(h.counts().sent,0);assert.equal(h.counts().stopped,1);assert.ok(h.store.events(s.id).some(e=>e.type==='INTERRUPTION'));await s.end('test');});
test('barge-in during actual output delivery aborts the output signal',async t=>{const h=setup(t);let audioSignal:AbortSignal|undefined;h.transport.sendAudio=async(_id,_frame,_generation,signal)=>{audioSignal=signal;await new Promise<void>(r=>signal.addEventListener('abort',()=>r(),{once:true}));return {};};const s=await connect(h.options);h.utterance(s);await wait();assert.ok(audioSignal);h.feed(s,3,2000);await wait();assert.equal(audioSignal.aborted,true);assert.equal(h.store.events(s.id).find(e=>e.type==='INTERRUPTION')?.detail.wasSpeaking,true);await s.end('test');});
test('authorized read-only tool is correlated and denied tool never reaches dispatcher',async t=>{const h=setup(t);let invokes=0;h.options.orchestration.invokeTool=async()=>{invokes++;return 'healthy';};h.options.orchestration.respond=async input=>{await assert.rejects(()=>input.tool('shell',{}));assert.equal(await input.tool('status',{}),'healthy');return {text:'Healthy.',model:'a',routeReason:'existing qualified route'};};const s=await connect(h.options);h.utterance(s);await wait();assert.equal(invokes,1);assert.ok(h.store.transcript(s.id).includes('TOOL RESULT'));await s.end('test');});
test('model change retains session context and configured voice, labelled as a contract fixture',async t=>{const h=setup(t);let calls=0;const voices:string[]=[];h.options.speech.frames=async function*(_text,v){voices.push(v.id);yield new Int16Array(320);};h.options.orchestration.respond=async input=>{calls++;if(calls===2)assert.equal(input.turns.length,3);return {text:'Response.',model:calls===1?'small':'larger',routeReason:'fixture route decision, not live escalation'};};const s=await connect(h.options);h.utterance(s);await wait();h.utterance(s);await wait();assert.deepEqual(voices,['fixed','fixed']);assert.equal(h.store.events(s.id).filter(e=>e.type==='MODEL HANDOFF').length,1);await s.end('test');});
for(const stage of ['stt','model','tts'] as const)test(`${stage} failure preserves independent messaging and ends the turn safely`,async t=>{const h=setup(t);if(stage==='stt')h.options.recognition.transcribe=async()=>{throw Error();};if(stage==='model')h.options.orchestration.respond=async()=>{throw Error();};if(stage==='tts')h.options.speech.frames=async function*(){throw Error();};const s=await connect(h.options);h.utterance(s);await wait();assert.ok(h.store.events(s.id).some(e=>e.type==='TURN FAILED'));assert.equal(h.counts().sent,0);await s.end('test');});
test('model timeout is bounded even when provider ignores AbortSignal',async t=>{const h=setup(t);h.options.stageTimeoutMs=15;h.options.orchestration.respond=()=>new Promise(()=>{});const s=await connect(h.options);h.utterance(s);await new Promise(r=>setTimeout(r,40));assert.ok(h.store.events(s.id).some(e=>e.type==='TURN FAILED'));await s.end('test');});
test('revocation fences audio and tools before further provider work',async t=>{const h=setup(t),s=await connect(h.options);h.revoke();h.utterance(s);await wait();assert.equal(h.counts().sent,0);assert.equal(h.store.projection()[0].state,'ENDED');});
test('caller disconnect cancels blocked model and no late response is sent',async t=>{const h=setup(t);let release!:(v:any)=>void;h.options.orchestration.respond=()=>new Promise(r=>release=r);const s=await connect(h.options);h.utterance(s);await wait();await s.end('caller_disconnect');release({text:'late',model:'a',routeReason:'fixture'});await wait();assert.equal(h.counts().sent,0);assert.equal(h.counts().hangups,1);});
test('restart retains transcript and marks live media unconfirmed rather than reconnecting',async t=>{const h=setup(t);h.store.create('orphan',{display:'fixture'});const other=new VoiceSessionStore(h.file);assert.equal(other.projection()[0].state,'ENDED');assert.match(other.transcript(other.projection()[0].id),/controller_restart_media_unconfirmed/);other.close();});
