import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import type {JobRuntime} from './job-runtime.js';
import type {ActionContext} from './job-types.js';
import {canExecuteTarget,type Candidate,type CoverageUnit,type Finding,type IndependenceGrade,type SecurityAuditRuntime,type SecurityAuditVerdict,type Verification} from './security-audit.js';

export const SECURITY_AUDIT_CAPABILITY='agent-control.security-audit.static';
export const SECURITY_AUDIT_WORKER='agent-control:security-auditor';
const CODE_EXTENSIONS=new Set(['.ts','.tsx','.js','.mjs','.cjs','.json','.yaml','.yml','.sh','.ps1','.html','.css']);
const IGNORE=new Set(['.git','node_modules','dist','coverage','.agent-control']);
const now=()=>new Date().toISOString();
const digest=(value:string)=>createHash('sha256').update(value).digest('hex');
function auditId(context:ActionContext){const value=context.parameters.auditId;if(typeof value!=='string'||!/^audit-[a-f0-9-]+$/i.test(value))throw Error('security_audit_id_invalid');return value;}
function invocation(context:ActionContext){return `${context.run.id}:${context.step.id}:${context.step.attempts.length}`;}
function walk(root:string,scope:string[]){const files:string[]=[];for(const item of scope){const start=path.resolve(root,item);if(start!==root&&!start.startsWith(`${root}${path.sep}`))throw Error('security_audit_scope_escape');if(!fs.existsSync(start))continue;const visit=(entry:string)=>{const stat=fs.lstatSync(entry);if(stat.isSymbolicLink())return;if(stat.isDirectory()){if(IGNORE.has(path.basename(entry)))return;for(const child of fs.readdirSync(entry).sort())visit(path.join(entry,child));return;}if(stat.isFile()&&stat.size<=2*1024*1024&&CODE_EXTENSIONS.has(path.extname(entry).toLowerCase()))files.push(entry);};visit(start);}return[...new Set(files)].sort();}
function lines(file:string){return fs.readFileSync(file,'utf8').split(/\r?\n/);}
const rules=[
 {id:'dynamic-code',category:'code-execution',pattern:/\b(?:eval|Function)\s*\(/,description:'Dynamic code construction may cross a code-execution trust boundary.'},
 {id:'shell-construction',category:'command-injection',pattern:/\b(?:exec|execSync)\s*\([^\n]*(?:\+|`|\$\{)/,description:'Shell command construction contains interpolation or concatenation.'},
 {id:'raw-html',category:'output-encoding',pattern:/(?:innerHTML\s*=|dangerouslySetInnerHTML)/,description:'Raw HTML rendering requires contextual output-encoding validation.'},
 {id:'credential-log',category:'secret-handling',pattern:/(?:console\.|logger\.)\w+\([^\n]*(?:token|password|secret|api.?key)/i,description:'Logging near credential vocabulary requires verification for secret disclosure.'},
 {id:'path-write',category:'filesystem-boundary',pattern:/\b(?:writeFileSync|writeFile|appendFileSync)\s*\([^\n]*(?:req\.|body\.|params\.|query\.)/,description:'Filesystem write appears influenced by request input.'},
];

function coverage(root:string,scope:string[],revision:string):CoverageUnit[]{const files=walk(root,scope),groups=new Map<string,string[]>();for(const file of files){const relative=path.relative(root,file).replaceAll('\\','/'),category=relative.startsWith('src/control/')?'control-plane':relative.startsWith('assets/')?'dashboard':relative.startsWith('scripts/')?'cli-tooling':relative.startsWith('android/')?'android-adapter':'other';groups.set(category,[...(groups.get(category)??[]),relative]);}return[...groups].map(([category,sourceFiles])=>({id:`coverage:${category}`,category,scope:scope.join(','),sourceFiles,status:'covered',methods:['deterministic-static-pattern-review','source-inventory'],evidence:[`files:${sourceFiles.length}`],sourceRevision:revision,updatedAt:now()}));}
function hunt(context:ActionContext,runtime:SecurityAuditRuntime){const audit=runtime.get(auditId(context)),files=walk(audit.repositoryRoot,audit.scope),found:Candidate[]=[];for(const file of files){const relative=path.relative(audit.repositoryRoot,file).replaceAll('\\','/');for(const [index,text] of lines(file).entries())for(const rule of rules)if(rule.pattern.test(text)){const trace=`${relative}:${index+1}`,id=`candidate-${digest(`${rule.id}:${trace}`).slice(0,16)}`;if(found.some(item=>item.id===id))continue;found.push({id,title:`${rule.category} candidate in ${relative}`,description:rule.description,category:rule.category,sourceTrace:[trace],preconditions:['Relevant code path is reachable with attacker-influenced input.'],trustBoundary:'Untrusted input to privileged Agent Control process',evidence:[`static-match:${rule.id}`,trace],finder:{invocationId:invocation(context),workerId:context.worker.id},createdAt:now()});}}return found;}
function verifyCandidate(context:ActionContext,auditRoot:string,candidate:Candidate):Verification{const [trace]=candidate.sourceTrace,match=trace?.match(/^(.*):(\d+)$/),file=match?path.resolve(auditRoot,match[1]):'',line=match?Number(match[2]):0;let verdict:SecurityAuditVerdict='needs_validation',reason='Candidate requires contextual or dynamic validation that static evidence alone cannot establish.',evidence=[...candidate.evidence];if(match&&file.startsWith(`${path.resolve(auditRoot)}${path.sep}`)&&fs.existsSync(file)){const source=lines(file),window=source.slice(Math.max(0,line-4),line+3).join('\n');evidence.push(`source-window-sha256:${digest(window)}`);if(/redactSensitive|textContent|escapeHtml|shell:false|spawn\(/.test(window)){verdict='rejected';reason='Fresh source-context validation found an explicit safer API or redaction/encoding control in the matched operation.';}}
 return{candidateId:candidate.id,verifier:{invocationId:invocation(context),workerId:context.worker.id},independence:'CONTEXT_INDEPENDENT' satisfies IndependenceGrade,verdict,reason,evidence,verifiedAt:now()};}
function finding(candidate:Candidate,verification:Verification,revision:string):Finding{return{schema:'agent-control.security-finding/v1',id:`finding-${candidate.id.replace(/^candidate-/,'')}`,candidateId:candidate.id,verdict:verification.verdict,title:candidate.title,category:candidate.category,sourceRevision:revision,sourceTrace:candidate.sourceTrace,preconditions:candidate.preconditions,trustBoundary:candidate.trustBoundary,reproduction:verification.verdict==='confirmed'?['Use the retained minimal reproduction under an approved sandbox.']:[],impact:verification.verdict==='rejected'?'Candidate was disproved by fresh contextual evidence.':'Static evidence identifies a plausible trust-boundary issue, but exploitability is not established.',finder:candidate.finder,verification,confidence:verification.verdict==='rejected'?'high':'low',scope:'Current audited source revision only',limitations:verification.verdict==='needs_validation'?['Dynamic validation blocked unless sandbox assurance passes.']:[],evidence:[...new Set([...candidate.evidence,...verification.evidence])],};}
function output(name:string,value:unknown){return{artifacts:[{name,value,type:'application/json',schema:`agent-control.security-audit.${name}/v1`,version:'1.0.0'}],evidence:[`${name}-recorded`],verification:[`${name}-recorded`]};}

export function registerSecurityAudit(runtime:JobRuntime,audits:SecurityAuditRuntime){
 runtime.workers.registerControllerInternal({id:SECURITY_AUDIT_WORKER,capabilities:[SECURITY_AUDIT_CAPABILITY],health:'healthy',capacity:1,active:0,labels:{origin:'agent-control-built-in',scope:'controller-local-read-only-security-audit'},observedAt:now()});
 runtime.actions.registerReadOnly('security-audit.reconnaissance@1.0.0',async context=>{const audit=audits.get(auditId(context)),units=coverage(audit.repositoryRoot,audit.scope,audit.sourceRevision);audits.recordCoverage(audit.id,units,context.run.trigger.actor);return output('reconnaissance',{auditId:audit.id,files:units.reduce((n,item)=>n+item.sourceFiles.length,0),coverage:units});});
 runtime.actions.registerReadOnly('security-audit.coverage-hunt@1.0.0',async context=>{const audit=audits.get(auditId(context)),candidates=hunt(context,audits);for(const candidate of candidates)audits.addCandidate(audit.id,candidate,context.run.trigger.actor);return output('candidate-inventory',{auditId:audit.id,candidates});});
 runtime.actions.registerReadOnly('security-audit.candidate-validation@1.0.0',async context=>{const audit=audits.get(auditId(context)),verifications=audit.candidates.map(candidate=>verifyCandidate(context,audit.repositoryRoot,candidate));for(const verification of verifications)audits.verify(audit.id,verification,context.run.trigger.actor);return output('candidate-verification',{auditId:audit.id,verifications,dynamicExecution:canExecuteTarget(audit.sandbox)?'permitted-but-not-required':'blocked-by-sandbox'});});
 runtime.actions.registerReadOnly('security-audit.structured-findings@1.0.0',async context=>{const audit=audits.get(auditId(context));for(const candidate of audit.candidates){const verification=[...audit.verifications].reverse().find(item=>item.candidateId===candidate.id);if(verification&&!audit.findings.some(item=>item.candidateId===candidate.id))audits.addFinding(audit.id,finding(candidate,verification,audit.sourceRevision),context.run.trigger.actor);}return output('findings',{auditId:audit.id,findings:audits.get(audit.id).findings});});
 runtime.actions.registerReadOnly('security-audit.record-verification@1.0.0',async context=>{const audit=audits.get(auditId(context));const invalid=audit.findings.filter(item=>item.finder.invocationId===item.verification.verifier.invocationId);if(invalid.length)throw Error('security_audit_independence_failed');return output('record-verification',{auditId:audit.id,status:'PASS',findingCount:audit.findings.length,independentInvocations:true});});
 runtime.actions.registerReadOnly('security-audit.reporting@1.0.0',async context=>{const audit=audits.complete(auditId(context),context.run.trigger.actor);return output('report-bundle',{auditId:audit.id,status:audit.status,artifacts:audit.artifacts});});
 for(const id of ['security-audit.reconnaissance@1.0.0','security-audit.coverage-hunt@1.0.0','security-audit.candidate-validation@1.0.0','security-audit.structured-findings@1.0.0','security-audit.record-verification@1.0.0','security-audit.reporting@1.0.0'])runtime.catalog.knownActions?.add(id);
 runtime.catalog.addJob({apiVersion:'agent-control/v1',kind:'Job',metadata:{id:'security-audit',name:'Governed security audit',version:'1.0.0',description:'Coverage-led, evidence-backed security audit with separate finder and verifier invocations.'},spec:{priority:'normal',concurrency:'queue',parameters:{auditId:{type:'string',required:true}},steps:[
  {id:'reconnaissance',action:'security-audit.reconnaissance@1.0.0',requires:[SECURITY_AUDIT_CAPABILITY],verification:['reconnaissance-recorded'],outputs:[{name:'reconnaissance',type:'application/json',schema:'agent-control.security-audit.reconnaissance/v1',version:'1.0.0'}]},
  {id:'coverage-hunting',action:'security-audit.coverage-hunt@1.0.0',dependsOn:['reconnaissance'],requires:[SECURITY_AUDIT_CAPABILITY],verification:['candidate-inventory-recorded'],outputs:[{name:'candidate-inventory',type:'application/json',schema:'agent-control.security-audit.candidate-inventory/v1',version:'1.0.0'}]},
  {id:'candidate-validation',action:'security-audit.candidate-validation@1.0.0',dependsOn:['coverage-hunting'],requires:[SECURITY_AUDIT_CAPABILITY],verification:['candidate-verification-recorded'],outputs:[{name:'candidate-verification',type:'application/json',schema:'agent-control.security-audit.candidate-verification/v1',version:'1.0.0'}]},
  {id:'structured-findings',action:'security-audit.structured-findings@1.0.0',dependsOn:['candidate-validation'],requires:[SECURITY_AUDIT_CAPABILITY],verification:['findings-recorded'],outputs:[{name:'findings',type:'application/json',schema:'agent-control.security-audit.findings/v1',version:'1.0.0'}]},
  {id:'record-verification',action:'security-audit.record-verification@1.0.0',dependsOn:['structured-findings'],requires:[SECURITY_AUDIT_CAPABILITY],verification:['record-verification-recorded'],outputs:[{name:'record-verification',type:'application/json',schema:'agent-control.security-audit.record-verification/v1',version:'1.0.0'}]},
  {id:'reporting',action:'security-audit.reporting@1.0.0',dependsOn:['record-verification'],requires:[SECURITY_AUDIT_CAPABILITY],verification:['report-bundle-recorded'],outputs:[{name:'report-bundle',type:'application/json',schema:'agent-control.security-audit.report-bundle/v1',version:'1.0.0'}]},
 ]}});
}
