import fs from 'node:fs';
import net from 'node:net';
import {createHash} from 'node:crypto';
import type {JobRuntime} from './job-runtime.js';
import type {ActionContext} from './job-types.js';

export type SpeculativeVerdict='BENEFICIAL'|'NEUTRAL'|'REGRESSION'|'INCOMPATIBLE'|'RESOURCE_BLOCKED'|'UNSUPPORTED';
export interface SpeculativeModelRef{id:string;path:string;sha256:string;quantisation:string;tokenizerFingerprint:string;bytes:number;}
export interface SpeculativeTrial{mode:'ORDINARY'|'SPECULATIVE';draftTokens:number|null;promptId:string;repetition:number;promptTokens:number|null;outputTokens:number|null;ttftMs:number;totalMs:number;tokensPerSecond:number|null;draftProposed:number|null;draftAccepted:number|null;acceptanceRatio:number|null;peakVramBytes:number|null;systemAvailableBytes:number|null;output:string;error?:string;}
export interface SpeculativeBenchmarkConfig{
 schema:'agent-control.speculative-decoding-benchmark/v1';node:{id:string;gpu:string};runtime:{implementation:string;path:string;sha256:string;version:string};main:SpeculativeModelRef;draft:SpeculativeModelRef;
 settings:{context:number;threads:number;batch:number;microBatch:number;gpuLayers:number;draftGpuLayers:number;maxTokens:number;temperature:number;seed:number;warmups:number;repetitions:number;draftTokenSettings:number[];prompts:Array<{id:string;text:string}>;timeoutMs:number};
 admission:{minimumFreeVramBytes:number;workspaceReserveBytes:number;benefitThresholdPct:number;maximumTemperatureCelsius:number};authority:{actor:string;expiresAt:string};
}
export interface SpeculativeReport{schema:'agent-control.speculative-decoding-report/v1';node:string;gpu:string;runtime:SpeculativeBenchmarkConfig['runtime'];main:Omit<SpeculativeModelRef,'path'>;draft:Omit<SpeculativeModelRef,'path'>;compatibility:{tokenizerCompatible:boolean;runtimeValidated:boolean};admission:unknown;trials:SpeculativeTrial[];summary:{baselineTokensPerSecond:number|null;bestSpeculativeTokensPerSecond:number|null;changePct:number|null;baselineTtftMs:number|null;bestSpeculativeTtftMs:number|null;ttftChangePct:number|null;bestDraftTokens:number|null;draftAcceptance:number|null;vramBaselineBytes:number|null;vramSpeculativeBytes:number|null;vramOverheadBytes:number|null;qualityEquivalent:boolean;energyPerToken:null;energyReason:string;thresholdPct:number;thresholdPolicy:'EXPERIMENTAL_CONFIGURED';};verdict:SpeculativeVerdict;recommendation:string;}

const sha=async(file:string)=>{const h=createHash('sha256');for await(const chunk of fs.createReadStream(file))h.update(chunk);return h.digest('hex');};
const mean=(values:number[])=>values.length?values.reduce((a,b)=>a+b,0)/values.length:null;
const finite=(value:unknown)=>typeof value==='number'&&Number.isFinite(value)?value:null;
const pause=(ms:number)=>new Promise(resolve=>setTimeout(resolve,ms));
const freePort=()=>new Promise<number>((resolve,reject)=>{const s=net.createServer();s.once('error',reject);s.listen(0,'127.0.0.1',()=>{const address=s.address() as net.AddressInfo;s.close(error=>error?reject(error):resolve(address.port));});});
function publicModel(model:SpeculativeModelRef){const {path:_path,...value}=model;return value;}

export function validateSpeculativeConfig(raw:SpeculativeBenchmarkConfig){const c=structuredClone(raw);if(c?.schema!=='agent-control.speculative-decoding-benchmark/v1'||!c.node?.id||!c.runtime?.implementation||!c.runtime.path?.startsWith('/')||!c.main?.path?.startsWith('/')||!c.draft?.path?.startsWith('/')||!c.authority?.actor||Date.parse(c.authority.expiresAt)<=Date.now())throw Error('speculative_configuration_invalid');for(const model of [c.main,c.draft])if(!/^[a-f0-9]{64}$/.test(model.sha256)||!/^[a-f0-9]{64}$/.test(model.tokenizerFingerprint)||!Number.isSafeInteger(model.bytes)||model.bytes<1)throw Error('speculative_model_identity_invalid');const s=c.settings,a=c.admission;if(!Number.isInteger(s.context)||s.context<256||!Number.isInteger(s.maxTokens)||s.maxTokens<8||s.repetitions<2||s.warmups<1||!s.prompts.length||!s.draftTokenSettings.length||s.draftTokenSettings.some(n=>!Number.isInteger(n)||n<1||n>32)||!Number.isSafeInteger(a.minimumFreeVramBytes)||a.minimumFreeVramBytes<c.main.bytes+c.draft.bytes||a.benefitThresholdPct<0||a.benefitThresholdPct>100||a.maximumTemperatureCelsius<20||a.maximumTemperatureCelsius>100)throw Error('speculative_policy_invalid');return c;}

export function summarizeSpeculative(config:SpeculativeBenchmarkConfig,trials:SpeculativeTrial[],compatibility={tokenizerCompatible:true,runtimeValidated:true},admission:unknown={}):SpeculativeReport{
 const good=trials.filter(t=>!t.error&&t.tokensPerSecond!==null),baseline=good.filter(t=>t.mode==='ORDINARY'),groups=new Map<number,SpeculativeTrial[]>();for(const trial of good.filter(t=>t.mode==='SPECULATIVE')){const n=trial.draftTokens!;groups.set(n,[...(groups.get(n)??[]),trial]);}
 const baseTps=mean(baseline.map(t=>t.tokensPerSecond!)),baseTtft=mean(baseline.map(t=>t.ttftMs));let bestN:number|null=null,best:SpeculativeTrial[]=[];for(const [n,rows] of groups){const value=mean(rows.map(r=>r.tokensPerSecond!));if(value!==null&&(bestN===null||value>(mean(best.map(r=>r.tokensPerSecond!))??-Infinity))){bestN=n;best=rows;}}
 const specTps=mean(best.map(t=>t.tokensPerSecond!)),specTtft=mean(best.map(t=>t.ttftMs)),change=baseTps&&specTps?(specTps/baseTps-1)*100:null,ttftChange=baseTtft&&specTtft?(specTtft/baseTtft-1)*100:null,accepted=best.reduce((n,t)=>n+(t.draftAccepted??0),0),proposed=best.reduce((n,t)=>n+(t.draftProposed??0),0),quality=best.length>0&&best.every(row=>baseline.some(base=>base.promptId===row.promptId&&base.output===row.output));
 const baselineVram=Math.max(0,...baseline.map(t=>t.peakVramBytes??0))||null,specVram=Math.max(0,...best.map(t=>t.peakVramBytes??0))||null;
 let verdict:SpeculativeVerdict;if(!compatibility.tokenizerCompatible||!compatibility.runtimeValidated)verdict='INCOMPATIBLE';else if(!baseline.length||!best.length)verdict='UNSUPPORTED';else if(!quality||change===null||change<=-config.admission.benefitThresholdPct)verdict='REGRESSION';else if(change>=config.admission.benefitThresholdPct)verdict='BENEFICIAL';else verdict='NEUTRAL';
 return{schema:'agent-control.speculative-decoding-report/v1',node:config.node.id,gpu:config.node.gpu,runtime:config.runtime,main:publicModel(config.main),draft:publicModel(config.draft),compatibility,admission,trials,summary:{baselineTokensPerSecond:baseTps,bestSpeculativeTokensPerSecond:specTps,changePct:change,baselineTtftMs:baseTtft,bestSpeculativeTtftMs:specTtft,ttftChangePct:ttftChange,bestDraftTokens:bestN,draftAcceptance:proposed?accepted/proposed:null,vramBaselineBytes:baselineVram,vramSpeculativeBytes:specVram,vramOverheadBytes:baselineVram!==null&&specVram!==null?specVram-baselineVram:null,qualityEquivalent:quality,energyPerToken:null,energyReason:'No approved whole-node energy sensor is bound to this invocation.',thresholdPct:config.admission.benefitThresholdPct,thresholdPolicy:'EXPERIMENTAL_CONFIGURED'},verdict,recommendation:verdict==='BENEFICIAL'?'Route through this exact qualified relationship only while admission remains satisfied.':'Retain ordinary decoding for this relationship.'};
}

async function command(c:ActionContext,command:string,args:string[],timeoutMs=10000){return c.ownedExecution.runProcess({command,args,maxOutputBytes:262144},AbortSignal.any([c.signal,AbortSignal.timeout(timeoutMs)]));}
async function gpu(c:ActionContext){const r=await command(c,'/usr/bin/nvidia-smi',['--query-gpu=memory.total,memory.used,memory.free,utilization.gpu,temperature.gpu,power.draw','--format=csv,noheader,nounits']);if(r.exitCode!==0)throw Error('speculative_gpu_telemetry_unavailable');const values=r.stdout.trim().split(',').map(x=>Number(x.trim()));if(values.length<6||values.some(x=>!Number.isFinite(x)))throw Error('speculative_gpu_telemetry_invalid');return{totalBytes:values[0]!*1024*1024,usedBytes:values[1]!*1024*1024,freeBytes:values[2]!*1024*1024,utilisation:values[3],temperatureCelsius:values[4],powerWatts:values[5]};}
function systemAvailable(){const match=fs.readFileSync('/proc/meminfo','utf8').match(/^MemAvailable:\s+(\d+) kB/m);return match?Number(match[1])*1024:null;}
async function streamCompletion(base:string,prompt:string,config:SpeculativeBenchmarkConfig,signal:AbortSignal){const started=performance.now(),response=await fetch(base+'/completion',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt,n_predict:config.settings.maxTokens,temperature:config.settings.temperature,seed:config.settings.seed,cache_prompt:false,stream:true}),signal});if(!response.ok||!response.body)throw Error('speculative_inference_http_'+response.status);const reader=response.body.getReader(),decoder=new TextDecoder();let buffer='',output='',first:number|null=null,final:any={};for(;;){const {done,value}=await reader.read();if(done)break;buffer+=decoder.decode(value,{stream:true});for(;;){const split=buffer.indexOf('\n\n');if(split<0)break;const event=buffer.slice(0,split);buffer=buffer.slice(split+2);for(const line of event.split(/\r?\n/)){if(!line.startsWith('data:'))continue;const text=line.slice(5).trim();if(!text||text==='[DONE]')continue;const row=JSON.parse(text);if(typeof row.content==='string'&&row.content){if(first===null)first=performance.now();output+=row.content;}if(row.stop===true||row.timings)final=row;}}}const ended=performance.now(),tokens=finite(final.tokens_predicted??final.timings?.predicted_n),tps=finite(final.timings?.predicted_per_second);return{output,ttftMs:(first??ended)-started,totalMs:ended-started,promptTokens:finite(final.tokens_evaluated??final.timings?.prompt_n),outputTokens:tokens,tokensPerSecond:tps,draftProposed:finite(final.timings?.draft_n),draftAccepted:finite(final.timings?.draft_n_accepted)};}

export function registerSpeculativeDecoding(runtime:JobRuntime,raw:SpeculativeBenchmarkConfig){const config=validateSpeculativeConfig(raw),workerId='speculative-decoding:'+config.node.id;runtime.workers.registerControllerInternal({id:workerId,capabilities:['model.speculative.qualify'],health:'healthy',capacity:1,active:0,observedAt:new Date().toISOString()});runtime.actions.registerConsequentialControl('speculative-decoding.qualify@1.0.0',async c=>{
 if(c.worker.id!==workerId||Date.parse(config.authority.expiresAt)<=Date.now())throw Error('speculative_authority_invalid');const evidence=(name:string,value:unknown)=>c.recordEvidence?.(name,{schema:'agent-control.speculative-evidence/v1',at:new Date().toISOString(),node:config.node.id,...(value as object)});
 const identities=[];for(const [role,model] of [['main',config.main],['draft',config.draft]] as const){const stat=fs.statSync(model.path);if(stat.size!==model.bytes||await sha(model.path)!==model.sha256)throw Error('speculative_'+role+'_identity_mismatch');identities.push({role,id:model.id,sha256:model.sha256,bytes:model.bytes,quantisation:model.quantisation,tokenizerFingerprint:model.tokenizerFingerprint});}if(await sha(config.runtime.path)!==config.runtime.sha256)throw Error('speculative_runtime_identity_mismatch');const tokenizerCompatible=config.main.tokenizerFingerprint===config.draft.tokenizerFingerprint;evidence('speculative-capability-discovery',{runtime:config.runtime,identities,tokenizerCompatible});if(!tokenizerCompatible){const report=summarizeSpeculative(config,[],{tokenizerCompatible:false,runtimeValidated:false},{});return{artifacts:[{name:'speculative-decoding-report',value:report}],verification:['speculative-incompatibility-evidenced']};}
 const before=await gpu(c),required=Math.max(config.admission.minimumFreeVramBytes,config.main.bytes+config.draft.bytes+config.admission.workspaceReserveBytes),admission={decision:before.freeBytes>=required&&before.temperatureCelsius!<config.admission.maximumTemperatureCelsius?'ADMIT':'REFUSE',requiredFreeVramBytes:required,observation:before,protectedProcessesUntouched:true};evidence('speculative-resource-admission',admission);if(admission.decision==='REFUSE'){const report=summarizeSpeculative(config,[],undefined,admission);report.verdict='RESOURCE_BLOCKED';report.recommendation='Ordinary decoding remains selected; protected workloads were not changed.';return{artifacts:[{name:'speculative-decoding-report',value:report}],verification:['speculative-resource-block-recorded']};}
 const trials:SpeculativeTrial[]=[],ordinary=new Map<string,string>();const modes:Array<{mode:'ORDINARY'|'SPECULATIVE';draftTokens:number|null}>=[{mode:'ORDINARY',draftTokens:null},...config.settings.draftTokenSettings.map(draftTokens=>({mode:'SPECULATIVE' as const,draftTokens}))];let runtimeValidated=false;
 for(const mode of modes){const port=await freePort(),base='http://127.0.0.1:'+port,stop=new AbortController(),serverSignal=AbortSignal.any([c.signal,stop.signal]),args=['--model',config.main.path,'--host','127.0.0.1','--port',String(port),'--ctx-size',String(config.settings.context),'--threads',String(config.settings.threads),'--batch-size',String(config.settings.batch),'--ubatch-size',String(config.settings.microBatch),'--n-gpu-layers',String(config.settings.gpuLayers),'--parallel','1','--no-warmup'];if(mode.mode==='SPECULATIVE')args.push('--spec-type','draft-simple','--spec-draft-model',config.draft.path,'--spec-draft-n-max',String(mode.draftTokens),'--spec-draft-ngl',String(config.settings.draftGpuLayers));const server=c.ownedExecution.runProcess({command:config.runtime.path,args,maxOutputBytes:2*1024*1024,env:{PATH:process.env.PATH,HOME:process.env.HOME,LANG:'C.UTF-8',CUDA_VISIBLE_DEVICES:process.env.CUDA_VISIBLE_DEVICES}},serverSignal).then(value=>({value}),error=>({error:String(error)}));let peak=before.usedBytes,ready=false;
  try{for(let i=0;i<240;i++){const state=await gpu(c);peak=Math.max(peak,state.usedBytes);if(state.temperatureCelsius>=config.admission.maximumTemperatureCelsius)throw Error('speculative_temperature_limit');try{const response=await fetch(base+'/health',{signal:AbortSignal.timeout(500)});if(response.ok){ready=true;break;}}catch{}await pause(250);}if(!ready)throw Error('speculative_runtime_start_failed');runtimeValidated=true;evidence('speculative-runtime-ready',{mode:mode.mode,draftTokens:mode.draftTokens,portRef:createHash('sha256').update(String(port)).digest('hex').slice(0,16),peakVramBytes:peak});
   for(let warm=0;warm<config.settings.warmups;warm++)for(const prompt of config.settings.prompts)await streamCompletion(base,prompt.text,config,AbortSignal.any([c.signal,AbortSignal.timeout(config.settings.timeoutMs)]));
   for(const prompt of config.settings.prompts)for(let repetition=1;repetition<=config.settings.repetitions;repetition++){const result=await streamCompletion(base,prompt.text,config,AbortSignal.any([c.signal,AbortSignal.timeout(config.settings.timeoutMs)])),state=await gpu(c);peak=Math.max(peak,state.usedBytes);const proposed=result.draftProposed,accepted=result.draftAccepted,trial:SpeculativeTrial={mode:mode.mode,draftTokens:mode.draftTokens,promptId:prompt.id,repetition,promptTokens:result.promptTokens,outputTokens:result.outputTokens,ttftMs:result.ttftMs,totalMs:result.totalMs,tokensPerSecond:result.tokensPerSecond,draftProposed:proposed,draftAccepted:accepted,acceptanceRatio:proposed?accepted!/proposed:null,peakVramBytes:peak,systemAvailableBytes:systemAvailable(),output:result.output};if(mode.mode==='ORDINARY')ordinary.set(prompt.id+':'+repetition,result.output);trials.push(trial);evidence('speculative-trial',{...trial,outputSha256:createHash('sha256').update(trial.output).digest('hex')});}
  }catch(error){trials.push({mode:mode.mode,draftTokens:mode.draftTokens,promptId:'runtime',repetition:0,promptTokens:null,outputTokens:null,ttftMs:0,totalMs:0,tokensPerSecond:null,draftProposed:null,draftAccepted:null,acceptanceRatio:null,peakVramBytes:peak,systemAvailableBytes:systemAvailable(),output:'',error:error instanceof Error?error.message:String(error)});evidence('speculative-runtime-failure',{mode:mode.mode,draftTokens:mode.draftTokens,error:error instanceof Error?error.message:'unknown',peakVramBytes:peak});}
  finally{stop.abort('speculative_mode_complete');await server;const cleanup=await c.ownedExecution.terminateAll('speculative-mode-complete');if(cleanup.outcome!=='confirmed')throw Error('speculative_cleanup_unconfirmed');}
 }
 const report=summarizeSpeculative(config,trials,{tokenizerCompatible,runtimeValidated},admission),artifact=evidence('speculative-final-report',report);return{artifacts:[{name:'speculative-decoding-report',value:{...report,evidenceRef:artifact?{id:artifact.id,sha256:artifact.sha256}:null}}],verification:['speculative-ab-complete','speculative-cleanup-confirmed']};
 },['FILESYSTEM_WRITE']);runtime.catalog.knownActions?.add('speculative-decoding.qualify@1.0.0');runtime.catalog.addJob({apiVersion:'agent-control/v1',kind:'Job',metadata:{id:'speculative-decoding-qualification',version:'1.0.0',name:'Qualify speculative decoding'},spec:{priority:'low',concurrency:'no-overlap',parameters:{},steps:[{id:'qualify',action:'speculative-decoding.qualify@1.0.0',requires:['model.speculative.qualify'],resources:['lab/qualification-window','gpu/'+config.node.id],timeoutSeconds:7200,verification:['speculative-ab-complete','speculative-cleanup-confirmed'],outputs:[{name:'speculative-decoding-report',type:'application/json',schema:'agent-control.speculative-decoding-report/v1',version:'1.0.0'}]}]}});return{workerId};}
