import test from 'node:test';
import assert from 'node:assert/strict';
import {TargetLlamaRuntime,validateRuntimeTarget} from './target-llama-runtime.js';
const target:any={resource:{id:'fixture',transport:{type:'local'}},environment:'fixture-linux',telemetry:'linux',stateDirectory:'/tmp/runtime-fixture'};
test('target adapters reject invalid transport and unsafe state paths',()=>{assert.throws(()=>validateRuntimeTarget({...target,stateDirectory:'/tmp/../escape'}));assert.throws(()=>validateRuntimeTarget({...target,resource:{id:'x',transport:{type:'ssh',host:'host;injection'}}}));});
test('Android battery and thermal parsing comes from actual adapter output with worker provenance',async()=>{const rows:any[]=[];const adapter=new TargetLlamaRuntime({...target,telemetry:'android-termux',adb:{executable:'/fixture/adb',host:'127.0.0.1',port:5037,serial:'fixture',expectedSerial:'expected'}});const c:any={signal:new AbortController().signal,worker:{id:'runtime-worker'},run:{id:'run'},step:{id:'probe'},recordEvidence:(name:string,value:any)=>{rows.push({name,value});return{id:name};},ownedExecution:{runProcess:async(req:any)=>({pid:123,exitCode:0,stdout:req.args.includes('ro.serialno')?'expected':req.args.includes('battery')?'  USB powered: true\n  level: 81\n  temperature: 295':'Thermal Status: 0',stderr:''})}};const o=await adapter.platform(c);assert.equal(o.batteryPercent,81);assert.equal(o.charging,true);assert.equal(o.thermalCelsius,29.5);assert.equal(o.thermalStatus,0);assert.ok(rows.some(x=>x.name==='runtime-telemetry-response'&&x.value.field==='battery'&&x.value.producer.worker==='runtime-worker'));});
test('Linux adapter preserves unsupported telemetry as null without Android commands',async()=>{const adapter=new TargetLlamaRuntime(target);let called=false;const c:any={ownedExecution:{runProcess:()=>{called=true;}}};assert.equal((await adapter.platform(c)).batteryPercent,null);assert.equal(called,false);});
test('wrong Android device identity fails closed',async()=>{const adapter=new TargetLlamaRuntime({...target,telemetry:'android-termux',adb:{executable:'/fixture/adb',host:'127.0.0.1',port:5037,serial:'fixture',expectedSerial:'expected'}});const c:any={signal:new AbortController().signal,worker:{id:'w'},run:{id:'r'},step:{id:'s'},recordEvidence:()=>({}),ownedExecution:{runProcess:async()=>({pid:1,exitCode:0,stdout:'wrong',stderr:''})}};await assert.rejects(adapter.platform(c),/identity_mismatch/);});

import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {OwnedProcessManager} from './owned-process.js';import {ExecutionSessionRuntime} from './execution-session.js';
test('target adapter request satisfies real execution-session identity contract',async()=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'target-session-'));const sessions=new ExecutionSessionRuntime(root),manager=new OwnedProcessManager(undefined,sessions,{runId:'run',jobId:'job',jobVersion:'1.0.0',stepId:'probe',actionId:'test@1.0.0',workerId:'worker',nodeId:'controller'});try{const c:any={signal:new AbortController().signal,worker:{id:'worker'},run:{id:'run'},step:{id:'probe'},recordEvidence:()=>({}),ownedExecution:{runProcess:(request:any,signal:AbortSignal)=>manager.runProcess({...request,command:process.execPath,args:['-e','console.log(JSON.stringify({runtimeResult:{availableRamBytes:123}}))'],input:undefined},signal)}};assert.equal((await new TargetLlamaRuntime(target).execute('observe',c)).availableRamBytes,123);assert.equal(sessions.list()[0].adapterId,'target-llama-runtime-v1');}finally{await manager.terminateAll('test completed');fs.rmSync(root,{recursive:true,force:true});}});
