import assert from 'node:assert/strict';
import test from 'node:test';
import {once} from 'node:events';
import type {AddressInfo} from 'node:net';
import path from 'node:path';
import {defaultCapabilities, type LaneState, type WorkspaceState} from '../state.js';
import {AgentControlService} from './application-service.js';
import {PtyRegistry} from './pty.js';
import {startWebDashboard} from './web-server.js';
import fs from 'node:fs';
import os from 'node:os';
import {JobCatalog} from './job-catalog.js';
import {ActionRegistry, ArtifactStore, JobRuntime, ResourceLockManager, RunLedger, WorkerRegistry} from './job-runtime.js';
import {COMMAND_RESULT_SCHEMA, MemoryCommandResultStore, TokenAwareOutputService, type OutputAuthorityScope} from './token-aware-output.js';
import {MemoryHarnessEfficiencyLedger, createInvocationObservation} from './harness-efficiency.js';

const now = () => new Date().toISOString();
function service() { const lane: LaneState = {id: 1, name: 'Primary', status: 'waiting', model: 'model-a', reasoning: 'medium', context: '0', lines: [], contract: {version: 2, laneId: 1, goal: 'safe task', constraints: [], cwd: '/tmp', priority: 1, mode: 'auto', capabilities: defaultCapabilities(), resourceLocks: {}, modelLock: null, sharedTaskIds: [], updatedAt: now()}, baton: {version: 1, laneId: 1, revision: 1, status: 'waiting', progress: [], hypothesis: '', evidence: [], changes: [], nextAction: 'schedule', openQuestions: [], model: 'model-a', reasoning: 'medium', updatedAt: now()}, lease: {laneId: 1, holder: null, acquiredAt: null, expiresAt: null}}; return new AgentControlService({version: 1, paused: false, lastRestorePoint: null, lanes: [lane]}, new PtyRegistry(), undefined, '3.1.0-test', () => {}); }
async function running(operatorToken?: string) { const control = service(); const server = startWebDashboard(control, {host: '127.0.0.1', port: 0, operatorToken, assetsDir: path.resolve('assets/dashboard')}); await once(server, 'listening'); const port = (server.address() as AddressInfo).port; return {control, server, base: `http://127.0.0.1:${port}`}; }
function serviceWithJobs() { const control = service(), root = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-control-web-jobs-')), actions = new ActionRegistry(); actions.register('test.run@1.0.0', async () => ({verification: ['ok']})); const catalog = new JobCatalog(actions.ids()); catalog.addJob({apiVersion: 'agent-control/v1', kind: 'Job', metadata: {id: 'web-job', name: 'Web Job', version: '1.0.0'}, spec: {priority: 'normal', concurrency: 'queue', parameters: {count: {type: 'integer', default: 2}, ratio: {type: 'number', default: 1.5}, enabled: {type: 'boolean', default: false}, label: {type: 'string', default: 'fixture'}}, steps: [{id: 'run', action: 'test.run@1.0.0', requires: ['test'], approval: 'release', verification: ['ok']}]}}); const workers = new WorkerRegistry(); workers.register({id: 'worker', capabilities: ['test'], health: 'healthy', capacity: 1, active: 0, observedAt: now()}); const runtime = new JobRuntime(catalog, actions, workers, new RunLedger(path.join(root, 'ledger.json')), new ArtifactStore(path.join(root, 'artifacts')), new ResourceLockManager(path.join(root, 'locks.json'))); control.configureProjection({jobRuntime: runtime, resources: [{id: 'worker', name: 'Worker', platform: 'linux', transport: 'ssh', capabilities: ['test']}]}); return {control, runtime}; }
async function runningJobs(operatorToken?: string) { const value = serviceWithJobs(), server = startWebDashboard(value.control, {host: '127.0.0.1', port: 0, operatorToken, assetsDir: path.resolve('assets/dashboard')}); await once(server, 'listening'); return {...value, server, base: `http://127.0.0.1:${(server.address() as AddressInfo).port}`}; }

test('observer and status command can read the same versioned projection as dashboard assets', async t => { const {server, base} = await running(); t.after(() => server.close()); const status = await fetch(`${base}/api/status`); assert.equal(status.status, 200); const projection = await status.json(); assert.equal(projection.schema, 'agent-control.system-status/v1'); assert.equal(projection.authority, 'AgentControlService'); assert.equal(projection.lanes[0].task, 'safe task'); const html = await fetch(base); assert.equal(html.status, 200); assert.match(await html.text(), /Agent Control/); });
test('mutations fail closed when operator authentication is not configured', async t => { const {server, base} = await running(); t.after(() => server.close()); const response = await fetch(`${base}/api/lanes/1/pause`, {method: 'POST', headers: {'Content-Type': 'application/json'}, body: '{}'}); assert.equal(response.status, 503); assert.equal((await response.json()).error, 'operator_auth_not_configured'); });
test('authenticated mutation uses the control service and rejects invalid origin', async t => { const {server, base, control} = await running('test-token'); t.after(() => server.close()); const denied = await fetch(`${base}/api/lanes/1/pause`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token', Origin: 'https://evil.invalid'}, body: '{}'}); assert.equal(denied.status, 403); const response = await fetch(`${base}/api/lanes/1/pause`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: JSON.stringify({actor: 'test-operator'})}); assert.equal(response.status, 200); assert.equal(control.state.lanes[0].status, 'paused'); });
test('no API route permits direct lease, scheduler, or PTY writes', async t => { const {server, base} = await running('test-token'); t.after(() => server.close()); for (const route of ['lease', 'scheduler', 'pty-input']) { const response = await fetch(`${base}/api/lanes/1/${route}`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: '{}'}); assert.equal(response.status, 404); } });
test('typed SSE stream replays authoritative control events', async t => { const {server, base, control} = await running(); t.after(() => server.close()); control.pauseLane(1, 'test'); const abort = new AbortController(); const response = await fetch(`${base}/api/events`, {headers: {'Last-Event-ID': '0'}, signal: abort.signal}); const reader = response.body!.getReader(); const first = await reader.read(); const text = new TextDecoder().decode(first.value); abort.abort(); assert.match(text, /event: lane\.status_changed/); assert.match(text, /"type":"lane.status_changed"/); });
test('Jobs, queue, workers, locks, artifacts and Run history share the authoritative runtime', async t => { const {server, base, runtime} = await runningJobs(); t.after(() => server.close()); assert.equal((await (await fetch(`${base}/api/jobs`)).json())[0].metadata.id, 'web-job'); assert.deepEqual(await (await fetch(`${base}/api/runs`)).json(), []); assert.deepEqual(await (await fetch(`${base}/api/queue`)).json(), []); assert.equal((await (await fetch(`${base}/api/workers`)).json())[0].id, 'worker'); const status = await (await fetch(`${base}/api/status`)).json(); assert.equal(status.resources[0].health, 'healthy'); assert.equal(status.resources[0].capacity, 1); runtime.workers.setHealth('worker', 'offline'); assert.equal((await (await fetch(`${base}/api/status`)).json()).health, 'degraded'); assert.deepEqual(await (await fetch(`${base}/api/resources`)).json(), []); assert.deepEqual(await (await fetch(`${base}/api/artifacts`)).json(), []); const css = await fetch(`${base}/dashboard-jobs.css`), javascript = await fetch(`${base}/dashboard-enhancements.js`), parameters = await fetch(`${base}/dashboard-parameters.js`), runningState = await fetch(`${base}/dashboard-running-state.js`); assert.equal(css.status, 200); assert.equal(parameters.status, 200); assert.equal(runningState.status, 200); const styles = await css.text(); assert.match(styles, /authority-note/); assert.match(styles, /agent-control-status-pulse/); assert.match(styles, /prefers-reduced-motion:reduce/); assert.match(styles, /running-summary:focus-visible/); assert.match(styles, /lane-live/); assert.match(styles, /workflow-preview/); const source = await javascript.text(), stateSource = await runningState.text(); assert.match(source, /renderWorkersAndLocks/); assert.match(source, /Last meaningful activity|Unavailable until provider reports/); assert.match(source, /running-inspector/); assert.match(stateSource, /Usage reported on completion/); assert.match(source, /Latest actual events/); assert.match(source, /Why this model \/ route/); assert.match(source, /Invocation → Job → Stage → Parcel accounting/); assert.match(source, /Planner selecting route/); assert.match(source, /renderWorkflowPreview/); assert.match(source, /Selected workflow details/); assert.match(source, /aria-expanded/); });
test('authenticated Run Now uses createRun and Job failure cannot mutate lane authority', async t => { const {server, base, control, runtime} = await runningJobs('test-token'); t.after(() => server.close()); const before = structuredClone(control.state.lanes[0]), response = await fetch(`${base}/api/jobs/web-job/run`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: JSON.stringify({actor: 'operator'})}); assert.equal(response.status, 201); const created = await response.json(); assert.equal(runtime.ledger.get(created.id)?.trigger.type, 'manual'); assert.deepEqual(control.state.lanes[0].lease, before.lease); assert.equal(control.state.lanes[0].status, before.status); assert.deepEqual(control.state.lanes[0].baton, before.baton); });
test('Run Now preserves typed parameters and returns safe validation detail', async t => { const {server, base} = await runningJobs('test-token'); t.after(() => server.close()); const headers = {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}; const accepted = await fetch(`${base}/api/jobs/web-job/run`, {method: 'POST', headers, body: JSON.stringify({parameters: {count: 3, ratio: .25, enabled: true, label: 'typed'}})}); assert.equal(accepted.status, 201); assert.deepEqual((await accepted.json()).parameters, {count: 3, ratio: .25, enabled: true, label: 'typed'}); const rejected = await fetch(`${base}/api/jobs/web-job/run`, {method: 'POST', headers, body: JSON.stringify({parameters: {count: '3'}})}); assert.equal(rejected.status, 400); const body = await rejected.json(); assert.equal(body.error, 'invalid_parameter_type:count'); assert.deepEqual(body.issues, ['invalid_parameter_type:count']); });
test('artifact collection exposes provenance and checksum but not managed storage paths', async t => { const {server, base, runtime} = await runningJobs('test-token'); t.after(() => server.close()); const response = await fetch(`${base}/api/jobs/web-job/run`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: '{}'}), created = await response.json(), run = runtime.ledger.get(created.id)!; runtime.artifacts.create(run, 'run', 'worker', {name: 'report', type: 'application/json', schema: 'report/v1', version: '1.0.0'}, {ok: true}); const artifacts = await (await fetch(`${base}/api/artifacts?runId=${encodeURIComponent(created.id)}`)).json(); assert.equal(artifacts.length, 1); assert.match(artifacts[0].sha256, /^[a-f0-9]{64}$/); assert.equal(artifacts[0].provenance.workerId, 'worker'); assert.equal(artifacts[0].storage, 'agent-control-managed'); assert.equal('storageRef' in artifacts[0], false); });
test('Job mutations fail closed without operator authentication and expose no PTY input route', async t => { const deniedServer = await runningJobs(); t.after(() => deniedServer.server.close()); const denied = await fetch(`${deniedServer.base}/api/jobs/web-job/run`, {method: 'POST', headers: {'Content-Type': 'application/json'}, body: '{}'}); assert.equal(denied.status, 503); const authenticated = await runningJobs('test-token'); t.after(() => authenticated.server.close()); const pty = await fetch(`${authenticated.base}/api/jobs/web-job/pty-input`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: '{}'}); assert.equal(pty.status, 404); });
test('approval is a typed control event and cannot approve a policy that is not waiting', async t => { const {server, base, control, runtime} = await runningJobs('test-token'); t.after(() => server.close()); const createdResponse = await fetch(`${base}/api/jobs/web-job/run`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: '{}'}), created = await createdResponse.json(); await runtime.tick(); assert.equal(runtime.ledger.get(created.id)?.steps[0].status, 'WAITING_FOR_APPROVAL'); const wrong = await fetch(`${base}/api/runs/${created.id}/approve`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: JSON.stringify({policy: 'different'})}); assert.equal(wrong.status, 409); assert.equal((await wrong.json()).error, 'approval_policy_not_waiting'); assert.equal(runtime.ledger.get(created.id)?.approvals.length, 0); const approved = await fetch(`${base}/api/runs/${created.id}/approve`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: JSON.stringify({policy: 'release', actor: 'reviewer'})}); assert.equal(approved.status, 200); assert.deepEqual(runtime.ledger.get(created.id)?.approvals, ['release']); assert.equal(control.events.history().at(-1)?.type, 'job.run_approved'); });

test('token-aware metrics are readable while expansion remains authenticated and scope-bound', async t => {
  const control = service(), output = new TokenAwareOutputService(new MemoryCommandResultStore(), {policy: {completeMaxLines: 0}, now: () => new Date('2026-08-27T10:00:00.000Z'), handleFactory: () => 'output:WEB'});
  const scope: OutputAuthorityScope = {taskId: 'web-task', laneId: '1', workerId: 'worker', leaseGeneration: 1, ownershipGeneration: 1};
  const captured = output.capture({schema: COMMAND_RESULT_SCHEMA, command: 'build', args: [], cwd: '/workspace', stdout: Array.from({length: 1000}, (_, index) => `line ${index} ${'x'.repeat(80)}`).join('\n'), stderr: '', exitCode: 0, startedAt: '2026-08-27T10:00:00.000Z', completedAt: '2026-08-27T10:00:01.000Z', backend: 'local'}, scope);
  control.configureProjection({tokenAwareOutput: output});
  const server = startWebDashboard(control, {host: '127.0.0.1', port: 0, operatorToken: 'test-token', assetsDir: path.resolve('assets/dashboard')});
  await once(server, 'listening'); t.after(() => server.close()); const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const metrics = await (await fetch(`${base}/api/command-output/metrics`)).json(); assert.equal(metrics.commandsCompacted, 1); assert.ok(metrics.contextTokensAvoided > 0);
  const records = await (await fetch(`${base}/api/command-output`)).json(); assert.equal(records[0].handle, captured.handle); assert.equal('storageRef' in records[0], false);
  const denied = await fetch(`${base}/api/command-output/${encodeURIComponent(captured.handle)}/expand`, {method: 'POST', headers: {'Content-Type': 'application/json'}, body: '{}'}); assert.equal(denied.status, 401);
  const allowed = await fetch(`${base}/api/command-output/${encodeURIComponent(captured.handle)}/expand`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: JSON.stringify({scope, expansion: {mode: 'all'}})}); assert.equal(allowed.status, 200); assert.equal((await allowed.json()).disposition, 'COMPLETE');
});

test('harness efficiency metrics and redacted invocation telemetry are projected read-only', async t => {
  const control = service(), ledger = new MemoryHarnessEfficiencyLedger();
  const item = createInvocationObservation({id: 'inv-web', jobId: 'job-web', runId: 'run-web', taskId: 'task-web', laneId: '1', model: 'model-a', provider: 'provider-a', harnessProfile: 'THIN', executionStrategy: 'fixture', startedAt: '2026-08-27T10:00:00.000Z', completedAt: '2026-08-27T10:00:01.000Z', rawUsage: {input_tokens: 100, input_tokens_details: {cached_tokens: 75}, output_tokens: 20, total_tokens: 120}, recipeFingerprint: 'recipe-web'});
  ledger.record(item); ledger.markVerification([item.id], 'PASS', 'SUCCEEDED'); control.configureProjection({harnessEfficiency: ledger});
  const server = startWebDashboard(control, {host: '127.0.0.1', port: 0, assetsDir: path.resolve('assets/dashboard')}); await once(server, 'listening'); t.after(() => server.close()); const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const metrics = await (await fetch(`${base}/api/efficiency`)).json(); assert.equal(metrics.overall.verifiedSuccesses, 1); assert.equal(metrics.overall.cachedInputTokens, 75);
  const invocations = await (await fetch(`${base}/api/efficiency/invocations`)).json(); assert.equal(invocations[0].usage.freshInputTokens, 25); assert.equal(invocations[0].harnessProfile, 'THIN'); assert.equal(typeof invocations[0].startup.components[0].estimatedTokens, 'number');
  assert.equal((await (await fetch(`${base}/api/efficiency/invocations?limit=1&runId=run-web`)).json()).length, 1);
  const html = await (await fetch(base)).text(); assert.match(html, /Harness Efficiency/);
});
