import assert from 'node:assert/strict';
import test from 'node:test';
import {once} from 'node:events';
import type {AddressInfo} from 'node:net';
import path from 'node:path';
import {defaultCapabilities, type LaneState, type WorkspaceState} from '../state.js';
import {AgentControlService} from './application-service.js';
import {PtyRegistry} from './pty.js';
import {startWebDashboard} from './web-server.js';

const now = () => new Date().toISOString();
function service() { const lane: LaneState = {id: 1, name: 'Primary', status: 'waiting', model: 'model-a', reasoning: 'medium', context: '0', lines: [], contract: {version: 2, laneId: 1, goal: 'safe task', constraints: [], cwd: '/tmp', priority: 1, mode: 'auto', capabilities: defaultCapabilities(), resourceLocks: {}, modelLock: null, sharedTaskIds: [], updatedAt: now()}, baton: {version: 1, laneId: 1, revision: 1, status: 'waiting', progress: [], hypothesis: '', evidence: [], changes: [], nextAction: 'schedule', openQuestions: [], model: 'model-a', reasoning: 'medium', updatedAt: now()}, lease: {laneId: 1, holder: null, acquiredAt: null, expiresAt: null}}; return new AgentControlService({version: 1, paused: false, lastRestorePoint: null, lanes: [lane]}, new PtyRegistry(), undefined, '3.1.0-test', () => {}); }
async function running(operatorToken?: string) { const control = service(); const server = startWebDashboard(control, {host: '127.0.0.1', port: 0, operatorToken, assetsDir: path.resolve('assets/dashboard')}); await once(server, 'listening'); const port = (server.address() as AddressInfo).port; return {control, server, base: `http://127.0.0.1:${port}`}; }

test('observer can read the same projection and dashboard assets', async t => { const {server, base} = await running(); t.after(() => server.close()); const status = await fetch(`${base}/api/status`); assert.equal(status.status, 200); assert.equal((await status.json()).lanes[0].task, 'safe task'); const html = await fetch(base); assert.equal(html.status, 200); assert.match(await html.text(), /Agent Control/); });
test('mutations fail closed when operator authentication is not configured', async t => { const {server, base} = await running(); t.after(() => server.close()); const response = await fetch(`${base}/api/lanes/1/pause`, {method: 'POST', headers: {'Content-Type': 'application/json'}, body: '{}'}); assert.equal(response.status, 503); assert.equal((await response.json()).error, 'operator_auth_not_configured'); });
test('authenticated mutation uses the control service and rejects invalid origin', async t => { const {server, base, control} = await running('test-token'); t.after(() => server.close()); const denied = await fetch(`${base}/api/lanes/1/pause`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token', Origin: 'https://evil.invalid'}, body: '{}'}); assert.equal(denied.status, 403); const response = await fetch(`${base}/api/lanes/1/pause`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: JSON.stringify({actor: 'test-operator'})}); assert.equal(response.status, 200); assert.equal(control.state.lanes[0].status, 'paused'); });
test('no API route permits direct lease, scheduler, or PTY writes', async t => { const {server, base} = await running('test-token'); t.after(() => server.close()); for (const route of ['lease', 'scheduler', 'pty-input']) { const response = await fetch(`${base}/api/lanes/1/${route}`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: '{}'}); assert.equal(response.status, 404); } });
test('typed SSE stream replays authoritative control events', async t => { const {server, base, control} = await running(); t.after(() => server.close()); control.pauseLane(1, 'test'); const abort = new AbortController(); const response = await fetch(`${base}/api/events`, {headers: {'Last-Event-ID': '0'}, signal: abort.signal}); const reader = response.body!.getReader(); const first = await reader.read(); const text = new TextDecoder().decode(first.value); abort.abort(); assert.match(text, /event: lane\.status_changed/); assert.match(text, /"type":"lane.status_changed"/); });
