import assert from 'node:assert/strict';
import test from 'node:test';
import {once} from 'node:events';
import http from 'node:http';
import type {AddressInfo} from 'node:net';
import path from 'node:path';
import {defaultCapabilities, type LaneState, type WorkspaceState} from '../state.js';
import {AgentControlService} from './application-service.js';
import {PtyRegistry} from './pty.js';
import {startWebDashboard} from './web-server.js';
import fs from 'node:fs';
import os from 'node:os';
import {JobCatalog} from './job-catalog.js';
import {ActionRegistry, ArtifactStore, JobRuntime, ResourceLockManager, RunLedger, WorkerRegistry} from './job-runtime.js';
import {COMMAND_RESULT_SCHEMA, MemoryCommandResultStore, TokenAwareOutputService, type OutputAuthorityScope} from './token-aware-output.js';
import {MemoryHarnessEfficiencyLedger, createInvocationObservation} from './harness-efficiency.js';
import {WorkParcelCoordinator, WorkParcelStore, type WorkParcelPlanner} from './work-parcels.js';
import {ProviderRegistry} from './providers.js';
import {ModelRegistry} from './model-registry.js';
import {ParameterizedJobRegistry, ParameterizedRunStore, SavedJobStore} from './parameterized-job-registry.js';
import {repositoryCodeReviewDefinition} from './repository-review-definition.js';
import {ParameterizedJobEngine} from './parameterized-job-engine.js';
import {ReviewBaselineStore} from './repository-review-runtime.js';
import type {RepositoryReviewExecutor} from './parameterized-job-types.js';
import {IdentityControlPlane} from './identity-control-plane.js';
import {TokenAwareBatonRuntime} from './token-aware-baton-routing.js';
import {GovernedRetrievalRuntime, type RetrievalProvider} from './governed-retrieval.js';

const now = () => new Date().toISOString();
function service() { const lane: LaneState = {id: 1, name: 'Primary', status: 'waiting', model: 'model-a', reasoning: 'medium', context: '0', lines: [], contract: {version: 2, laneId: 1, goal: 'safe task', constraints: [], cwd: '/tmp', priority: 1, mode: 'auto', capabilities: defaultCapabilities(), resourceLocks: {}, modelLock: null, sharedTaskIds: [], updatedAt: now()}, baton: {version: 1, laneId: 1, revision: 1, status: 'waiting', progress: [], hypothesis: '', evidence: [], changes: [], nextAction: 'schedule', openQuestions: [], model: 'model-a', reasoning: 'medium', updatedAt: now()}, lease: {laneId: 1, holder: null, acquiredAt: null, expiresAt: null}}; return new AgentControlService({version: 1, paused: false, lastRestorePoint: null, lanes: [lane]}, new PtyRegistry(), undefined, '3.1.0-test', () => {}); }
async function running(operatorToken?: string) { const control = service(); const server = startWebDashboard(control, {host: '127.0.0.1', port: 0, operatorToken, assetsDir: path.resolve('assets/dashboard')}); await once(server, 'listening'); const port = (server.address() as AddressInfo).port; return {control, server, base: `http://127.0.0.1:${port}`}; }
async function runningWithControl(control:AgentControlService){const server=startWebDashboard(control,{host:'127.0.0.1',port:0,assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');return{control,server,base:`http://127.0.0.1:${(server.address() as AddressInfo).port}`};}
function serviceWithJobs() { const control = service(), root = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-control-web-jobs-')), actions = new ActionRegistry(); actions.register('test.run@1.0.0', async () => ({verification: ['ok']})); const catalog = new JobCatalog(actions.ids()); catalog.addJob({apiVersion: 'agent-control/v1', kind: 'Job', metadata: {id: 'web-job', name: 'Web Job', version: '1.0.0'}, spec: {priority: 'normal', concurrency: 'queue', parameters: {count: {type: 'integer', default: 2}, ratio: {type: 'number', default: 1.5}, enabled: {type: 'boolean', default: false}, label: {type: 'string', default: 'fixture'}, maximumOutputTokens: {type: 'integer', default: 32768}}, steps: [{id: 'run', action: 'test.run@1.0.0', requires: ['test'], approval: 'release', verification: ['ok']}]}}); const workers = new WorkerRegistry(); workers.register({id: 'worker', capabilities: ['test'], health: 'healthy', capacity: 1, active: 0, observedAt: now()}); const runtime = new JobRuntime(catalog, actions, workers, new RunLedger(path.join(root, 'ledger.json')), new ArtifactStore(path.join(root, 'artifacts')), new ResourceLockManager(path.join(root, 'locks.json'))); control.configureProjection({jobRuntime: runtime, resources: [{id: 'worker', name: 'Worker', platform: 'linux', transport: 'ssh', capabilities: ['test']}]}); return {control, runtime}; }
async function runningJobs(operatorToken?: string) { const value = serviceWithJobs(), server = startWebDashboard(value.control, {host: '127.0.0.1', port: 0, operatorToken, assetsDir: path.resolve('assets/dashboard')}); await once(server, 'listening'); return {...value, server, base: `http://127.0.0.1:${(server.address() as AddressInfo).port}`}; }
async function runningParcels(operatorToken?: string) { const value = await runningJobs(operatorToken), root = fs.mkdtempSync(path.join(os.tmpdir(), 'agent-control-web-parcels-')); const planner: WorkParcelPlanner = {plan: prompt => ({objective: prompt, planner: {kind: 'deterministic', reason: 'web fixture'}, stages: [{id: 'inspect', name: 'Inspect', job: 'web-job@1.0.0'}]})}; value.control.configureProjection({workParcels: new WorkParcelCoordinator(value.runtime, new WorkParcelStore(path.join(root, 'parcels.json')), planner)}); return value; }
async function runningParameterizedJobs(operatorToken='test-token') { const control=service(),root=fs.mkdtempSync(path.join(os.tmpdir(),'agent-control-web-parameterized-')),definitions=new ParameterizedJobRegistry();definitions.register(repositoryCodeReviewDefinition);const models=new ModelRegistry([],[],{roles:{}}),executor:RepositoryReviewExecutor={execute:async()=>{throw new Error('not_executed_by_api_test')}};const engine=new ParameterizedJobEngine(definitions,new SavedJobStore(path.join(root,'saved.json'),definitions),new ParameterizedRunStore(path.join(root,'runs.json')),new ReviewBaselineStore(path.join(root,'baselines.json')),models,executor,{allowedRepositoryRoots:[root],snapshotsRoot:path.join(root,'snapshots'),nodeHealthy:()=>true});control.configureProjection({parameterizedJobs:engine,modelRegistry:models});const server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken,assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');return{control,engine,server,base:`http://127.0.0.1:${(server.address() as AddressInfo).port}`};}

test('observer and status command can read the same versioned projection as dashboard assets', async t => { const {server, base} = await running(); t.after(() => server.close()); const status = await fetch(`${base}/api/status`); assert.equal(status.status, 200); const projection = await status.json(); assert.equal(projection.schema, 'agent-control.system-status/v1'); assert.equal(projection.authority, 'AgentControlService'); assert.equal(projection.lanes[0].task, 'safe task'); const html = await fetch(base); assert.equal(html.status, 200); assert.match(await html.text(), /Agent Control/); });
test('mutations fail closed when operator authentication is not configured', async t => { const {server, base} = await running(); t.after(() => server.close()); const response = await fetch(`${base}/api/lanes/1/pause`, {method: 'POST', headers: {'Content-Type': 'application/json'}, body: '{}'}); assert.equal(response.status, 503); assert.equal((await response.json()).error, 'operator_auth_not_configured'); });
test('authenticated mutation uses the control service and rejects invalid origin', async t => { const {server, base, control} = await running('test-token'); t.after(() => server.close()); const denied = await fetch(`${base}/api/lanes/1/pause`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token', Origin: 'https://evil.invalid'}, body: '{}'}); assert.equal(denied.status, 403); const response = await fetch(`${base}/api/lanes/1/pause`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: JSON.stringify({actor: 'test-operator'})}); assert.equal(response.status, 200); assert.equal(control.state.lanes[0].status, 'paused'); });
test('no API route permits direct lease, scheduler, or PTY writes', async t => { const {server, base} = await running('test-token'); t.after(() => server.close()); for (const route of ['lease', 'scheduler', 'pty-input']) { const response = await fetch(`${base}/api/lanes/1/${route}`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: '{}'}); assert.equal(response.status, 404); } });
test('typed SSE stream replays authoritative control events', async t => { const {server, base, control} = await running(); t.after(() => server.close()); control.pauseLane(1, 'test'); const abort = new AbortController(); const response = await fetch(`${base}/api/events`, {headers: {'Last-Event-ID': '0'}, signal: abort.signal}); const reader = response.body!.getReader(); const first = await reader.read(); const text = new TextDecoder().decode(first.value); abort.abort(); assert.match(text, /event: lane\.status_changed/); assert.match(text, /"type":"lane.status_changed"/); });
test('token routing projection is served and live telemetry is published through the SSE event stream', async t => { const {server, base, control} = await running(); t.after(() => server.close()); const routing = new TokenAwareBatonRuntime(); control.configureProjection({tokenBatonRouting: routing}); routing.subscribe(event => control.events.emit(event.type === 'telemetry' ? 'token.telemetry' : event.type === 'context.lifecycle' ? 'token.context_lifecycle' : 'token.governor_transition', {threadId: event.threadId, parcelId: event.parcelId}, undefined, 'test')); routing.observe({threadId: 'thread:one', parcelId: 'parcel:one', agentId: 'agent:one', providerId: 'openai', modelId: 'sol', elapsedMs: 1_000, cumulative: {inputTokens: 100, outputTokens: 20, totalTokens: 120}, context: {tokens: 80, limitTokens: 100, authority: 'authoritative', source: 'provider'}}); routing.recordContextLifecycle('thread:one', {kind: 'COMPACTION', authority: 'authoritative', source: 'provider'}); const projection = await (await fetch(`${base}/api/token-routing`)).json(); assert.equal(projection.threads[0].latest.context.tokens, 80); assert.equal(projection.threads[0].governor.state, 'PREPARE_BATON'); assert.equal(projection.contextLifecycle[0].kind, 'COMPACTION'); const abort = new AbortController(), response = await fetch(`${base}/api/events`, {headers: {'Last-Event-ID': '0'}, signal: abort.signal}), reader = response.body!.getReader(), first = await reader.read(), text = new TextDecoder().decode(first.value); abort.abort(); assert.match(text, /event: token\.telemetry/); assert.match(text, /event: token\.context_lifecycle/); assert.match(text, /"threadId":"thread:one"/); assert.match(text, /"tokens":80/); });

test('governed retrieval projection is redacted and streams over the existing SSE transport',async t=>{const root=fs.mkdtempSync(path.join(os.tmpdir(),'agent-control-web-retrieval-'));fs.writeFileSync(path.join(root,'source.ts'),'export const Needle = true;\n');t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const provider:RetrievalProvider={descriptor:()=>({id:'fixture',name:'fixture',locality:'LOCAL',strategies:['EXACT'],capabilities:['retrieval.search'],index:{required:false}}),retrieve:async()=>({providerId:'fixture',strategy:'EXACT',evidence:[{path:'source.ts',text:'export const Needle = true;',score:1}],latencyMs:2,cost:{amount:0,currency:'USD',authority:'authoritative'},index:{state:'NOT_REQUIRED'},rawBytesConsidered:100})};const retrieval=new GovernedRetrievalRuntime([provider],{enabled:true,progression:['EXACT'],minimumConfidence:0,requiredCoverage:0}),control=service();control.configureProjection({governedRetrieval:retrieval});retrieval.subscribe(event=>control.events.emit(event.type,{parcelId:event.parcelId,intentId:event.intentId},undefined,'test'));const {server,base}=await runningWithControl(control);t.after(()=>server.close());await retrieval.retrieve({id:'intent:web',parcelId:'parcel:web',taskType:'test',query:'Needle',repository:{repositoryId:'repo',root,gitSha:'abc',dirty:false}});const projection=await(await fetch(`${base}/api/retrieval`)).json();assert.equal(projection.totals.evidenceCount,1);assert.equal(JSON.stringify(projection).includes('export const Needle'),false);assert.match(fs.readFileSync(path.resolve('assets/dashboard/dashboard.js'),'utf8'),/retrieval\.evidence/);});
test('Jobs, queue, workers, locks, artifacts and Run history share the authoritative runtime', async t => { const {server, base, runtime} = await runningJobs(); t.after(() => server.close()); assert.equal((await (await fetch(`${base}/api/jobs`)).json())[0].metadata.id, 'web-job'); assert.deepEqual(await (await fetch(`${base}/api/runs`)).json(), []); assert.deepEqual(await (await fetch(`${base}/api/queue`)).json(), []); assert.equal((await (await fetch(`${base}/api/workers`)).json())[0].id, 'worker'); const status = await (await fetch(`${base}/api/status`)).json(); assert.equal(status.resources[0].health, 'healthy'); assert.equal(status.resources[0].capacity, 1); runtime.workers.setHealth('worker', 'offline'); assert.equal((await (await fetch(`${base}/api/status`)).json()).health, 'degraded'); assert.deepEqual(await (await fetch(`${base}/api/resources`)).json(), []); assert.deepEqual(await (await fetch(`${base}/api/artifacts`)).json(), []); const css = await fetch(`${base}/dashboard-jobs.css`), javascript = await fetch(`${base}/dashboard-enhancements.js`), parameters = await fetch(`${base}/dashboard-parameters.js`), runningState = await fetch(`${base}/dashboard-running-state.js`); assert.equal(css.status, 200); assert.equal(parameters.status, 200); assert.equal(runningState.status, 200); const styles = await css.text(); assert.match(styles, /authority-note/); assert.match(styles, /agent-control-status-pulse/); assert.match(styles, /prefers-reduced-motion:reduce/); assert.match(styles, /running-summary:focus-visible/); assert.match(styles, /lane-live/); assert.match(styles, /workflow-preview/); const source = await javascript.text(), stateSource = await runningState.text(); assert.match(source, /renderWorkersAndLocks/); assert.match(source, /Last meaningful activity|Unavailable until provider reports/); assert.match(source, /running-inspector/); assert.match(stateSource, /Usage reported on completion/); assert.match(source, /Latest actual events/); assert.match(source, /Why this model \/ route/); assert.match(source, /Invocation → Job → Stage → Parcel accounting/); assert.match(source, /Planner selecting route/); assert.match(source, /renderWorkflowPreview/); assert.match(source, /Selected workflow details/); assert.match(source, /aria-expanded/); });
test('parameterised Job APIs create, export, run and expose first-class dashboard views',async t=>{const{server,base,engine}=await runningParameterizedJobs();t.after(()=>server.close());const headers={'Content-Type':'application/json',Authorization:'Bearer test-token'},definitions=await(await fetch(`${base}/api/job-definitions`)).json();assert.equal(definitions[0].id,'repository-code-review');const createdResponse=await fetch(`${base}/api/saved-jobs`,{method:'POST',headers,body:JSON.stringify({id:'repo-review',name:'Repo Review',definition:{id:'repository-code-review',version:1,follow:'latest-compatible'},parameters:{node:'controller',repository:'/tmp/repo',ref:'main',scope:'changes'},routing:{modelRole:'review.default',allowFallback:true},contextProfile:'STANDARD',concurrency:'forbid-overlap',enabled:true})});assert.equal(createdResponse.status,201);const created=await createdResponse.json();assert.equal(created.revision,1);const runResponse=await fetch(`${base}/api/saved-jobs/repo-review/run`,{method:'POST',headers,body:'{}'});assert.equal(runResponse.status,201);assert.equal(engine.runs.list()[0].trigger.type,'manual');const exported=await(await fetch(`${base}/api/saved-jobs/repo-review/export`)).json();assert.equal(exported.name,'Repo Review');assert.doesNotMatch(JSON.stringify(exported),/token|password|credential/i);const asset=await fetch(`${base}/dashboard-parameterized-jobs.js`),html=await(await fetch(base)).text();assert.equal(asset.status,200);assert.match(await asset.text(),/Job Definitions|job-platform-definitions/);assert.match(html,/Saved Jobs/);assert.match(html,/Schedules/);assert.match(html,/job-platform-runs/);});
test('authenticated Run Now uses createRun and Job failure cannot mutate lane authority', async t => { const {server, base, control, runtime} = await runningJobs('test-token'); t.after(() => server.close()); const before = structuredClone(control.state.lanes[0]), response = await fetch(`${base}/api/jobs/web-job/run`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: JSON.stringify({actor: 'operator'})}); assert.equal(response.status, 201); const created = await response.json(); assert.equal(runtime.ledger.get(created.id)?.trigger.type, 'manual'); assert.deepEqual(control.state.lanes[0].lease, before.lease); assert.equal(control.state.lanes[0].status, before.status); assert.deepEqual(control.state.lanes[0].baton, before.baton); });
test('Run Now preserves typed parameters and returns safe validation detail', async t => { const {server, base} = await runningJobs('test-token'); t.after(() => server.close()); const headers = {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}; const accepted = await fetch(`${base}/api/jobs/web-job/run`, {method: 'POST', headers, body: JSON.stringify({parameters: {count: 3, ratio: .25, enabled: true, label: 'typed'}})}); assert.equal(accepted.status, 201); assert.deepEqual((await accepted.json()).parameters, {count: 3, ratio: .25, enabled: true, label: 'typed', maximumOutputTokens: 32768}); const rejected = await fetch(`${base}/api/jobs/web-job/run`, {method: 'POST', headers, body: JSON.stringify({parameters: {count: '3'}})}); assert.equal(rejected.status, 400); const body = await rejected.json(); assert.equal(body.error, 'invalid_parameter_type:count'); assert.deepEqual(body.issues, ['invalid_parameter_type:count']); });
test('artifact collection exposes provenance and checksum but not managed storage paths', async t => { const {server, base, runtime} = await runningJobs('test-token'); t.after(() => server.close()); const response = await fetch(`${base}/api/jobs/web-job/run`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: '{}'}), created = await response.json(), run = runtime.ledger.get(created.id)!; runtime.artifacts.create(run, 'run', 'worker', {name: 'report', type: 'application/json', schema: 'report/v1', version: '1.0.0'}, {ok: true}); const artifacts = await (await fetch(`${base}/api/artifacts?runId=${encodeURIComponent(created.id)}`)).json(); assert.equal(artifacts.length, 1); assert.match(artifacts[0].sha256, /^[a-f0-9]{64}$/); assert.equal(artifacts[0].provenance.workerId, 'worker'); assert.equal(artifacts[0].storage, 'agent-control-managed'); assert.equal('storageRef' in artifacts[0], false); });
test('Job mutations fail closed without operator authentication and expose no PTY input route', async t => { const deniedServer = await runningJobs(); t.after(() => deniedServer.server.close()); const denied = await fetch(`${deniedServer.base}/api/jobs/web-job/run`, {method: 'POST', headers: {'Content-Type': 'application/json'}, body: '{}'}); assert.equal(denied.status, 503); const authenticated = await runningJobs('test-token'); t.after(() => authenticated.server.close()); const pty = await fetch(`${authenticated.base}/api/jobs/web-job/pty-input`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: '{}'}); assert.equal(pty.status, 404); });
test('operator authentication projection distinguishes disabled required and authenticated', async t => { const disabled = await running(); t.after(() => disabled.server.close()); assert.equal((await (await fetch(`${disabled.base}/api/operator-auth`)).json()).state, 'disabled'); const configured = await running('test-token'); t.after(() => configured.server.close()); assert.equal((await (await fetch(`${configured.base}/api/operator-auth`)).json()).state, 'authentication_required'); assert.equal((await (await fetch(`${configured.base}/api/operator-auth`, {headers:{Authorization:'Bearer test-token'}})).json()).state, 'authenticated'); });
test('operator configuration API safely adds systems and retains credential references without exposing key values', async t => {
  const root=fs.mkdtempSync(path.join(os.tmpdir(),'agent-control-web-config-')),configFile=path.join(root,'config.json');t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
  fs.writeFileSync(configFile,JSON.stringify({schemaVersion:1,resources:[],providers:[{id:'external',kind:'responses',baseUrl:'https://provider.example/v1',requiresAuth:true,credentialEnv:'EXTERNAL_API_KEY'}],services:[],lanes:[]}));
  const control=service(),server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:'test-token',assetsDir:path.resolve('assets/dashboard'),configFile});await once(server,'listening');t.after(()=>server.close());const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  assert.equal((await fetch(`${base}/api/configuration`)).status,401);
  const headers={Authorization:'Bearer test-token'},current=await (await fetch(`${base}/api/configuration`,{headers})).json();assert.equal(current.providers[0].credentialEnv,'EXTERNAL_API_KEY');assert.doesNotMatch(JSON.stringify(current),/sk-live-secret/);
  const saved=await fetch(`${base}/api/configuration/systems`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({revision:current.revision,kind:'resource',item:{id:'remote-host',name:'Remote host',platform:'linux',transport:{type:'ssh',host:'remote-host',user:'operator'},capabilities:[]}})});assert.equal(saved.status,200);assert.equal((await saved.json()).restartRequired,true);assert.equal(JSON.parse(fs.readFileSync(configFile,'utf8')).resources[0].id,'remote-host');
  const latest=await (await fetch(`${base}/api/configuration`,{headers})).json(),unsafe=await fetch(`${base}/api/configuration/systems`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({revision:latest.revision,kind:'provider',item:{id:'unsafe',kind:'responses',apiKey:'sk-live-secret'}})});assert.equal(unsafe.status,400);assert.equal(JSON.parse(fs.readFileSync(configFile,'utf8')).providers.length,1);
  const spark=await fetch(`${base}/api/configuration/spark`,{method:'POST',headers:{...headers,'Content-Type':'application/json'},body:JSON.stringify({revision:latest.revision,spark:{enabled:false,model:'gpt-5.3-codex-spark',modelRole:'fast-execution',maximumFiles:1,maximumChangedLines:80,maximumAttempts:1,maximumSubagents:0,maximumContextTokens:2048,verificationRequired:true}})});assert.equal(spark.status,200);assert.equal((await spark.json()).spark.enabled,false);assert.equal(JSON.parse(fs.readFileSync(configFile,'utf8')).spark.maximumAttempts,1);
});
test('model registry APIs expose safe identity and governed deterministic routes', async t => {
  const control=service(),registry=new ModelRegistry([{id:'external',name:'External',kind:'openai-compatible',baseUrl:'https://models.example/v1',wireApi:'responses',auth:{type:'bearer-env',env:'SECRET_ENV_NAME'}}],[{id:'fast',provider:'external',providerModel:'vendor/fast',capabilities:['coding'],qualification:{state:'QUALIFIED',version:'q1',qualifiedAt:'2026-09-01T00:00:00Z',capabilities:['coding'],nodes:['worker']}}],{roles:{'coding.fast':{primary:'fast'}}});control.configureProjection({modelRegistry:registry});
  const server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:'test-token',assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');t.after(()=>server.close());const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const providers=await (await fetch(`${base}/api/models/providers`)).json();assert.equal(providers[0].auth.type,'bearer-env');assert.equal('env' in providers[0].auth,false);assert.equal(JSON.stringify(providers).includes('SECRET_ENV_NAME'),false);
  const models=await (await fetch(`${base}/api/models`)).json();assert.equal(models[0].providerModel,'vendor/fast');assert.equal(models[0].qualification.state,'QUALIFIED');
  const routed=await fetch(`${base}/api/models/fast/route`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer test-token'},body:JSON.stringify({nodeId:'worker',requiredCapabilities:['coding']})});assert.equal(routed.status,200);assert.equal((await routed.json()).qualificationVersion,'q1');
});
test('account-aware model APIs expose labels, plan and qualification without credential locations', async t => {
  const account={id:'lawrence-pro',label:'Lawrence Pro',plan:'ChatGPT Pro',planAuthority:'operator-configured' as const,credentialStore:{type:'codex-home-env' as const,env:'CODEX_HOME_LAWRENCE_PRO'},qualification:{state:'QUALIFIED' as const,version:'account-q1',checkedAt:'2026-09-02T00:00:00Z',qualifiedAt:'2026-09-02T00:00:00Z',capabilities:['codex-chatgpt'],evidence:['interactive-login']}};
  const registry=new ModelRegistry([{id:'codex',name:'OpenAI Codex',kind:'cli',accountProfiles:[account]}],[{id:'sol-pro',provider:'codex',accountProfile:'lawrence-pro',providerModel:'sol',capabilities:['coding'],qualification:{state:'QUALIFIED',version:'model-q1',capabilities:['coding'],nodes:['controller']}}],{roles:{review:{primary:'sol-pro'}}},undefined,undefined,{CODEX_HOME_LAWRENCE_PRO:process.cwd()}),control=service();control.configureProjection({modelRegistry:registry});
  const server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:'test-token',assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');t.after(()=>server.close());const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const accounts=await(await fetch(`${base}/api/models/accounts`)).json(),models=await(await fetch(`${base}/api/models`)).json(),providers=await(await fetch(`${base}/api/models/providers`)).json();
  assert.deepEqual({id:accounts[0].id,label:accounts[0].label,plan:accounts[0].plan,availability:accounts[0].availability},{id:'lawrence-pro',label:'Lawrence Pro',plan:'ChatGPT Pro',availability:'AVAILABLE'});
  assert.equal(models[0].account.id,'lawrence-pro');assert.equal(providers[0].accountProfiles[0].qualification.state,'QUALIFIED');
  const serialized=JSON.stringify({accounts,models,providers});assert.equal(serialized.includes('CODEX_HOME_LAWRENCE_PRO'),false);assert.equal(serialized.includes(process.cwd()),false);assert.equal(serialized.includes('@'),false);
  const dashboard=await(await fetch(`${base}/dashboard-models.js`)).text();assert.match(dashboard,/Account qualification/);assert.match(dashboard,/not reliably known/);assert.match(dashboard,/models\/accounts/);
});
test('unauthenticated natural-language submission creates no parcel', async t => { const {server,base,control}=await runningParcels('test-token'); t.after(()=>server.close()); const response=await fetch(`${base}/api/parcels`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({prompt:'run web-job without authority'})}); assert.equal(response.status,401); assert.equal((await response.json()).error,'operator_authentication_required'); assert.deepEqual(control.parcels(),[]); });
test('authenticated natural-language submission immediately returns an attributed auditable PLANNING parcel and preserves prompt verbatim', async t => { const {server,base}=await runningParcels('test-token'); t.after(()=>server.close()); const prompt='  run web-job and preserve these spaces  '; const response=await fetch(`${base}/api/parcels`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer test-token'},body:JSON.stringify({prompt,actor:'spoofed-actor'})}); assert.equal(response.status,201); const parcel=await response.json(); assert.equal(parcel.status,'PLANNING'); assert.equal(parcel.prompt,prompt); assert.equal(parcel.actor,'web-operator'); assert.equal(parcel.attribution.legacy,true); assert.equal(parcel.attribution.parcelId,parcel.id); assert.equal(parcel.audit.timeline[0].type,'task.received'); });
test('maximumOutputTokens schema survives API redaction and dashboard auth controls use validated state', async t => { const {server,base}=await runningJobs(); t.after(()=>server.close()); const jobs=await (await fetch(`${base}/api/jobs`)).json(); assert.deepEqual(jobs[0].spec.parameters.maximumOutputTokens,{type:'integer',default:32768}); const source=await (await fetch(`${base}/dashboard.js`)).text(), html=await (await fetch(base)).text(); assert.match(source,/operatorAuthentication/); assert.match(source,/Operator authentication required/); assert.match(html,/natural-task-submit[^>]+disabled/); assert.match(html,/Systems/); });
test('governed Check now updates canonical provider readiness', async t => { const upstream=http.createServer((_request,response)=>{response.writeHead(200);response.end('ok')}); upstream.listen(0,'127.0.0.1'); await once(upstream,'listening'); t.after(()=>upstream.close()); const upstreamPort=(upstream.address() as AddressInfo).port, baseControl=service(), providers=new ProviderRegistry(); providers.register({id:'provider-check',name:'Provider Check',kind:'responses',baseUrl:`http://127.0.0.1:${upstreamPort}/v1`,requiresAuth:false,credentialConfigured:true,parallelism:1,costClass:'included',capabilities:['model.execute'],qualification:{status:'qualified'}}); const control=new AgentControlService(baseControl.state,baseControl.ptys,providers,'3.3.1-test',()=>{}), server=startWebDashboard(control,{host:'127.0.0.1',port:0,operatorToken:'test-token',assetsDir:path.resolve('assets/dashboard')}); await once(server,'listening'); t.after(()=>server.close()); const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`; assert.equal((await (await fetch(`${base}/api/systems`)).json())[0].execution,'UNKNOWN'); const checked=await fetch(`${base}/api/systems/provider-check/check`,{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer test-token'},body:'{}'}); assert.equal(checked.status,200); const system=await checked.json(); assert.equal(system.execution,'AVAILABLE'); assert.equal(system.reachable,'yes'); assert.ok(system.lastSuccessfulProbeAt); });
test('approval is a typed control event and cannot approve a policy that is not waiting', async t => { const {server, base, control, runtime} = await runningJobs('test-token'); t.after(() => server.close()); const createdResponse = await fetch(`${base}/api/jobs/web-job/run`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: '{}'}), created = await createdResponse.json(); await runtime.tick(); assert.equal(runtime.ledger.get(created.id)?.steps[0].status, 'WAITING_FOR_APPROVAL'); const wrong = await fetch(`${base}/api/runs/${created.id}/approve`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: JSON.stringify({policy: 'different'})}); assert.equal(wrong.status, 409); assert.equal((await wrong.json()).error, 'approval_policy_not_waiting'); assert.equal(runtime.ledger.get(created.id)?.approvals.length, 0); const approved = await fetch(`${base}/api/runs/${created.id}/approve`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: JSON.stringify({policy: 'release', actor: 'reviewer'})}); assert.equal(approved.status, 200); assert.deepEqual(runtime.ledger.get(created.id)?.approvals, ['release']); assert.equal(control.events.history().at(-1)?.type, 'job.run_approved'); });

test('token-aware metrics are readable while expansion remains authenticated and scope-bound', async t => {
  const control = service(), output = new TokenAwareOutputService(new MemoryCommandResultStore(), {policy: {completeMaxLines: 0}, now: () => new Date('2026-08-27T10:00:00.000Z'), handleFactory: () => 'output:WEB'});
  const scope: OutputAuthorityScope = {taskId: 'web-task', laneId: '1', workerId: 'worker', leaseGeneration: 1, ownershipGeneration: 1};
  const captured = output.capture({schema: COMMAND_RESULT_SCHEMA, command: 'build', args: [], cwd: '/workspace', stdout: Array.from({length: 1000}, (_, index) => `line ${index} ${'x'.repeat(80)}`).join('\n'), stderr: '', exitCode: 0, startedAt: '2026-08-27T10:00:00.000Z', completedAt: '2026-08-27T10:00:01.000Z', backend: 'local'}, scope);
  control.configureProjection({tokenAwareOutput: output});
  const server = startWebDashboard(control, {host: '127.0.0.1', port: 0, operatorToken: 'test-token', assetsDir: path.resolve('assets/dashboard')});
  await once(server, 'listening'); t.after(() => server.close()); const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const metrics = await (await fetch(`${base}/api/command-output/metrics`)).json(); assert.equal(metrics.commandsCompacted, 1); assert.ok(metrics.contextTokensAvoided > 0);
  const records = await (await fetch(`${base}/api/command-output`)).json(); assert.equal(records[0].handle, captured.handle); assert.equal('storageRef' in records[0], false);
  const denied = await fetch(`${base}/api/command-output/${encodeURIComponent(captured.handle)}/expand`, {method: 'POST', headers: {'Content-Type': 'application/json'}, body: '{}'}); assert.equal(denied.status, 401);
  const allowed = await fetch(`${base}/api/command-output/${encodeURIComponent(captured.handle)}/expand`, {method: 'POST', headers: {'Content-Type': 'application/json', Authorization: 'Bearer test-token'}, body: JSON.stringify({scope, expansion: {mode: 'all'}})}); assert.equal(allowed.status, 200); assert.equal((await allowed.json()).disposition, 'COMPLETE');
});

test('harness efficiency metrics and redacted invocation telemetry are projected read-only', async t => {
  const control = service(), ledger = new MemoryHarnessEfficiencyLedger();
  const item = createInvocationObservation({id: 'inv-web', jobId: 'job-web', runId: 'run-web', taskId: 'task-web', laneId: '1', model: 'model-a', provider: 'provider-a', harnessProfile: 'THIN', executionStrategy: 'fixture', startedAt: '2026-08-27T10:00:00.000Z', completedAt: '2026-08-27T10:00:01.000Z', rawUsage: {input_tokens: 100, input_tokens_details: {cached_tokens: 75}, output_tokens: 20, total_tokens: 120}, recipeFingerprint: 'recipe-web'});
  ledger.record(item); ledger.markVerification([item.id], 'PASS', 'SUCCEEDED'); control.configureProjection({harnessEfficiency: ledger});
  const server = startWebDashboard(control, {host: '127.0.0.1', port: 0, assetsDir: path.resolve('assets/dashboard')}); await once(server, 'listening'); t.after(() => server.close()); const base = `http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const metrics = await (await fetch(`${base}/api/efficiency`)).json(); assert.equal(metrics.overall.verifiedSuccesses, 1); assert.equal(metrics.overall.cachedInputTokens, 75);
  const invocations = await (await fetch(`${base}/api/efficiency/invocations`)).json(); assert.equal(invocations[0].usage.freshInputTokens, 25); assert.equal(invocations[0].harnessProfile, 'THIN'); assert.equal(typeof invocations[0].startup.components[0].estimatedTokens, 'number');
  assert.equal((await (await fetch(`${base}/api/efficiency/invocations?limit=1&runId=run-web`)).json()).length, 1);
  const html = await (await fetch(base)).text(); assert.match(html, /Harness Efficiency/);
});

test('governed run cards route from Lanes to the authoritative Jobs detail', () => {
  const source=fs.readFileSync(path.resolve('assets/dashboard/dashboard-enhancements.js'),'utf8');
  assert.match(source,/data-view="jobs"/);
  assert.match(source,/Last provider \/ control signal/);
  assert.match(source,/phaseUpdatedAt/);
  assert.match(source,/Unavailable \(mixed currencies\)/);
  assert.match(source,/response received/);
});

test('dashboard exposes an operator configuration view with API-key references and restart semantics', () => {
  const html=fs.readFileSync(path.resolve('assets/dashboard/index.html'),'utf8'),source=fs.readFileSync(path.resolve('assets/dashboard/dashboard-enhancements.js'),'utf8');
  assert.match(html,/data-view="configuration">Configuration/);assert.match(html,/Add machine/);assert.match(html,/Fast execution/);assert.match(html,/credentialEnv/);assert.match(source,/\/api\/configuration\/systems/);assert.match(source,/\/api\/configuration\/spark/);assert.match(source,/RESTART REQUIRED/);
});

test('dashboard renders workload provider-execution and credential-residency locality separately', () => {
  const models=fs.readFileSync(path.resolve('assets/dashboard/dashboard-models.js'),'utf8'),runs=fs.readFileSync(path.resolve('assets/dashboard/dashboard-parameterized-jobs.js'),'utf8'),tokens=fs.readFileSync(path.resolve('assets/dashboard/dashboard-enhancements.js'),'utf8');
  for (const source of [models,runs,tokens]) assert.match(source,/providerExecutionNodeId/);
  for (const source of [models,runs,tokens]) assert.match(source,/credentialNodeId/);
  assert.match(runs,/workloadNodeId/); assert.match(tokens,/workloadNodeId/);
});

test('Sessions dashboard reads authoritative identity execution and 3.6 runtime provenance', async t => {
  const control=service(),identity=new IdentityControlPlane();identity.registerActor({id:'web-operator',type:'human',displayName:'Web operator',principalId:'operator:web',authenticationSource:'dashboard-bearer',roles:['operator'],capabilities:[],metadata:{}});identity.createSession({id:'session:web',creatorActorId:'web-operator',mode:'operator-controlled',permissions:{capabilities:['session.observe','session.manage','parcel.create'],filesystem:'none',network:'none'},contextPolicy:'compiled'});control.configureProjection({identity,defaultSessionId:'session:web'});
  const server=startWebDashboard(control,{host:'127.0.0.1',port:0,assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');t.after(()=>server.close());const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;
  const sessions=await(await fetch(`${base}/api/sessions`)).json();assert.equal(sessions[0].creatorActorId,'web-operator');assert.deepEqual(await(await fetch(`${base}/api/context-transfers`)).json(),[]);assert.deepEqual(await(await fetch(`${base}/api/delegations`)).json(),[]);assert.deepEqual(await(await fetch(`${base}/api/executions`)).json(),[]);assert.deepEqual(await(await fetch(`${base}/api/fast-execution-attempts`)).json(),[]);assert.equal((await(await fetch(`${base}/api/runtime`)).json()).schema,'agent-control.runtime-observability/v1');const html=await(await fetch(base)).text(),source=await(await fetch(`${base}/dashboard-sessions.js`)).text();assert.match(html,/data-view="sessions">Sessions/);assert.match(source,/Actor → Session → Work Parcel → Agent → Model → Provider → Runtime → Node\/Resource → Evidence/);assert.match(source,/Context transfers/);assert.match(source,/Active parcels/);assert.match(source,/Execution class \/ actual model \/ verification \/ escalation/);assert.match(source,/Contract-owned execution/);assert.match(source,/Transport \/ connection \/ authentication/);
});
