import {sshApiRequest} from './cli-ssh.mjs';
import {resolveStatusTarget} from './status-client.mjs';

export const EXIT={OK:0,USAGE:2,AUTH:3,NOT_FOUND:4,PERMISSION:5,JOB_FAILED:6,UNAVAILABLE:7,INTERRUPTED:130};
export class CliError extends Error {constructor(code,message){super(message);this.code=code;}}
export function endpointUrl(value){let u;try{u=new URL(value);}catch{throw new CliError(EXIT.USAGE,'Invalid endpoint. Use an HTTPS controller or a loopback SSH tunnel.');}if(!['http:','https:'].includes(u.protocol)||u.username||u.password||u.search||u.hash||!['','/','/api/status'].includes(u.pathname)||u.protocol==='http:'&&!['localhost','127.0.0.1','[::1]'].includes(u.hostname))throw new CliError(EXIT.USAGE,'Endpoint must use HTTPS or loopback HTTP, without credentials, query or a path prefix.');u.pathname='/';return u;}
export function clean(value,token=''){if(typeof value==='string')return token?value.split(token).join('[REDACTED]'):value;if(Array.isArray(value))return value.map(x=>clean(x,token));if(value&&typeof value==='object')return Object.fromEntries(Object.entries(value).map(([k,v])=>[k,clean(v,token)]));return value;}
export function terminal(value){return String(value??'unavailable').replace(/[\x00-\x08\x0b-\x1f\x7f-\x9f]/g,'').replace(/\r/g,'');}
export function httpError(status){const code=status===401?EXIT.AUTH:status===403?EXIT.PERMISSION:status===404?EXIT.NOT_FOUND:status>=500||status===429?EXIT.UNAVAILABLE:EXIT.USAGE;return new CliError(code,({401:'Authentication failed. Configure the existing AGENT_CONTROL_WEB_OPERATOR_TOKEN for this controller.',403:'Permission denied by the controller. Use the existing approval/authority workflow.',404:'Not found. Check the ID with `ac jobs`, `ac jobs catalog` or `ac nodes`.'})[status]??`Controller returned HTTP ${status}. Check the endpoint and command parameters; no automatic retry was made.`);}
export async function boundedJson(response){if(!response.ok)throw httpError(response.status);const chunks=[];let bytes=0;for await(const chunk of response.body){bytes+=chunk.length;if(bytes>16*1024*1024)throw new CliError(EXIT.UNAVAILABLE,'Controller response exceeds the 16 MiB limit.');chunks.push(chunk);}try{return JSON.parse(Buffer.concat(chunks).toString('utf8'));}catch{throw new CliError(EXIT.UNAVAILABLE,'Controller returned invalid JSON.');}}
export async function createClient(options={},deps={}){
 const environment=deps.environment??process.env,request=deps.request??fetch,signal=deps.signal;
 let target,link;const explicit=options.endpoint??environment.AGENT_CONTROL_WEB_URL??environment.AGENT_CONTROL_WEB_BASE_URL;
 try{target=explicit?{transport:'http',url:endpointUrl(explicit).href}:resolveStatusTarget({environment,...(deps.platform?{platform:deps.platform}:{})});}catch(error){throw error instanceof CliError?error:new CliError(EXIT.USAGE,'Invalid existing status-client configuration. Check its documented schema; do not store credentials in it.');}

 const base=endpointUrl(target.transport==='ssh'?`http://${target.statusHost}:${target.statusPort}`:target.url),token=environment.AGENT_CONTROL_WEB_OPERATOR_TOKEN?.trim()??'';
 const endpoint=target.transport==='ssh'?`ssh://${target.host}:${target.port} (controller port ${target.statusPort})`:base.origin;
 async function raw(path,init={},stream=false){if(!path.startsWith('/api/')||path.startsWith('//'))throw new CliError(EXIT.USAGE,'Invalid API path.');const active=init.signal??signal;const requestSignal=stream?active:AbortSignal.any([AbortSignal.timeout(15000),...(active?[active]:[])]);try{const options={...init,redirect:'error',signal:requestSignal,headers:{Accept:stream?'text/event-stream':'application/json',...(token?{Authorization:`Bearer ${token}`}:{ } ),...init.headers}};return target.transport==='ssh'?await sshApiRequest(target,path,options,deps.spawn):await request(new URL(path,base),options);}catch{if(signal?.aborted)throw new CliError(EXIT.INTERRUPTED,'Stopped watching; the governed job continues.');throw new CliError(EXIT.UNAVAILABLE,'Controller unavailable or request timed out. Check the endpoint/transport. No mutation was retried.');}}
 return {base:base.origin,endpoint,token,close:link?.close??(()=>{}),raw,async get(path){return clean(await boundedJson(await raw(path)),token);},async post(path,body){if(!token)throw new CliError(EXIT.AUTH,'Set the existing AGENT_CONTROL_WEB_OPERATOR_TOKEN before running a governed job.');return clean(await boundedJson(await raw(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...body,actor:'cli-operator'})})),token);}};
}
// The existing stream invalidates retained state. It does not become a second job ledger.
export async function* events(response,signal){if(!response.ok)throw httpError(response.status);if(!response.headers.get('content-type')?.includes('text/event-stream'))throw new CliError(EXIT.UNAVAILABLE,'Controller did not return its governed event stream.');const reader=response.body.getReader(),decoder=new TextDecoder();let pending='';const cancel=()=>reader.cancel().catch(()=>{});signal?.addEventListener('abort',cancel,{once:true});try{while(!signal?.aborted){const {value,done}=await reader.read();if(done)break;pending+=decoder.decode(value,{stream:true});pending=pending.replace(/\r\n/g,'\n');if(pending.length>2*1024*1024)throw new CliError(EXIT.UNAVAILABLE,'Event frame exceeds limit.');let end;while((end=pending.indexOf('\n\n'))>=0){const frame=pending.slice(0,end);pending=pending.slice(end+2);const lines=frame.split('\n'),data=lines.filter(l=>l.startsWith('data:')).map(l=>l.slice(5).trimStart()).join('\n');if(data){let parsed;try{parsed=JSON.parse(data);}catch{throw new CliError(EXIT.UNAVAILABLE,'Invalid controller event frame.');}yield {id:lines.find(l=>l.startsWith('id:'))?.slice(3).trim(),type:lines.find(l=>l.startsWith('event:'))?.slice(6).trim(),data:parsed};}}}}finally{signal?.removeEventListener('abort',cancel);await reader.cancel().catch(()=>{});reader.releaseLock();}}
