import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {once} from 'node:events';
import {cliMain,parseArgs,version} from './cli.mjs';
import {createClient,endpointUrl,EXIT,events} from './cli-client.mjs';
const hash=s=>createHash('sha256').update(s).digest('hex');
const token='test-cli-authority';
function removeFixture(dir){const resolved=path.resolve(dir);assert.ok(resolved.startsWith(path.resolve(os.tmpdir())+path.sep));fs.rmSync(resolved,{recursive:true,force:true});}
async function fixture(t){
 const state={status:'SUCCEEDED',requests:[],deny:0,streams:[],inputs:[]};const history='# History\n12:00 input\n12:01 output\n';
 const inspector=()=>({id:'run-real',status:state.status,title:'Actual fixture',history:{content:history,sha256:hash(history)},events:[{id:'event-1',at:'12:00',summary:'Observed'}],calls:[],operations:[],limitations:[],usage:{totals:{input:{value:20,reported:1,total:1},cached:{value:10},fresh:{value:10},output:{value:4},tokens:{value:24},cacheHit:{value:.5},apiCost:state.cost??{currencies:{},reported:0,total:1}}}});
 const core={metadata:{id:'observe',name:'Observe'},spec:{parameters:{count:{type:'integer',minimum:1,maximum:5,default:2}},steps:[]}};
 const definition={id:'analyse',version:3,displayName:'Analyse',parameters:{repository:{type:'repository',required:true},scope:{type:'enum',values:['full','changes'],default:'full'}},outputs:{schema:'existing'}};
 const server=http.createServer(async(req,res)=>{state.requests.push({url:req.url,method:req.method,auth:req.headers.authorization});const send=(d,status=200)=>{res.writeHead(status,{'content-type':'application/json'});res.end(JSON.stringify(d));};
 if(req.headers.authorization!=='Bearer '+token)return send({error:'denied '+token},401);if(state.deny)return send({error:'internal '+token},state.deny);
 if(req.method==='POST'){let body='';for await(const chunk of req)body+=chunk;state.inputs.push(JSON.parse(body));return send(req.url==='/api/saved-jobs'?{id:'saved'}:{id:'run-real',status:'QUEUED'},201);}
 const run={id:'run-real',jobId:'observe',status:state.status,requestedAt:'2026-09-14T12:00:00Z',steps:[{id:'observe',status:state.status}]};
 const routes={'/api/status':{schema:'agent-control.system-status/v1',version,health:'healthy',scheduler:{state:'READY'}},'/api/estate-map':{nodes:[{id:'machine:one',label:'One',type:'machine',state:'WAITING',detail:{nodeId:'one'}}]},'/api/observability/nodes/machine%3Aone':{nodeId:'one',node:{label:'One',state:'WAITING',subtitle:'stale inventory'},resources:[],work:[]},'/api/observability/nodes/machine%3Aone/resources':{native:{cpuModel:'CPU',cpuBusyPercent:{value:25,authority:'authoritative'},memoryTotalBytes:{value:1073741824},memoryAvailableBytes:{value:536870912},gpu:[]}},'/api/runs':[run],'/api/job-runs':[], '/api/runs/run-real':run,'/api/observability/runs/run-real':inspector(),'/api/jobs':[core],'/api/job-definitions':[definition],'/api/runtime-map?runId=run-real':{nodes:[{id:'op',label:'Read',state:'SUCCEEDED'}]},'/api/models':[{id:'model',provider:'configured',status:'AVAILABLE'}],'/api/workers':[{id:'worker',health:'healthy'}],'/api/providers':[{id:'provider',health:'healthy'}],'/api/models/routes':{roles:{review:'model'}},'/api/runtime-safety':[]};
 if(req.url==='/api/events'){res.writeHead(200,{'content-type':'text/event-stream'});state.streams.push(res);res.write('event: system.snapshot\ndata: {}\n\n');req.on('close',()=>{state.streams=state.streams.filter(r=>r!==res);});return;}
 if(req.url==='/api/observability/runs/run-real/outputs')return send({defaultProfile:'simple',profiles:[{id:'simple',view:'simple'},{id:'detailed',view:'detailed'},{id:'evidence',view:'evidence'}]});
 if(req.url.startsWith('/api/observability/runs/run-real/outputs/')){const profile=req.url.split('/').at(-1),content=profile==='evidence'?'{}':'# Same recorded result';return send({runId:'run-real',profile,sourceSha256:'sourcehash',content,sha256:hash(content),filename:`run-real-${profile}-report.${profile==='evidence'?'json':'md'}`});}
 if(req.url in routes)return send(routes[req.url]);return send({error:'missing'},404);
 });server.listen(0,'127.0.0.1');await once(server,'listening');t.after(()=>{for(const r of state.streams)r.end();server.closeAllConnections();server.close();});const url=`http://127.0.0.1:${server.address().port}`;
 const execute=async(args,options={})=>{const out=[],err=[];const code=await cliMain(args,{out:s=>out.push(s),error:s=>err.push(s)},{environment:{AGENT_CONTROL_WEB_URL:url,AGENT_CONTROL_WEB_OPERATOR_TOKEN:token},...options});return {code,out:out.join('\n'),err:err.join('\n')};};return {state,execute,url};
}
test('help/version and malformed options do not contact a controller',async()=>{for(const args of [['--help'],['help'],['job','--help'],['run','--help'],['--version']]){const out=[];assert.equal(await cliMain(args,{out:s=>out.push(s),error:()=>{}},{createClient:()=>{throw Error('must not connect');}}),0);assert.ok(out.length);}assert.throws(()=>parseArgs(['--json=false']));assert.throws(()=>parseArgs(['--endpoint']));assert.throws(()=>parseArgs(['--json','--quiet']));});
test('status uses authenticated API and stable machine envelope',async t=>{const f=await fixture(t),r=await f.execute(['status','--json']);assert.equal(r.code,0);assert.equal(JSON.parse(r.out).schema,'agent-control.cli/v1');assert.equal(JSON.parse(r.out).data.health,'healthy');assert.equal(f.state.requests[0].auth,'Bearer '+token);assert.doesNotMatch(r.out,new RegExp(token));});
test('estate nodes and detail preserve stale state and omit GPU on CPU-only nodes',async t=>{const f=await fixture(t);for(const args of [['estate'],['nodes'],['node','one']]){const r=await f.execute(args);assert.equal(r.code,0);assert.match(r.out,/WAITING/);}const d=await f.execute(['node','one']);assert.match(d.out,/RAM used \/ total: 0.5 GiB \/ 1.0 GiB/);assert.doesNotMatch(d.out,/GPU|VRAM/);assert.equal((await f.execute(['node','missing'])).code,EXIT.NOT_FOUND);});
test('job list filters, detail, processes and telemetry use retained state',async t=>{const f=await fixture(t);f.state.status='RUNNING';assert.match((await f.execute(['jobs','running'])).out,/RUNNING/);assert.equal(JSON.parse((await f.execute(['jobs','completed','--json'])).out).data.length,0);for(const args of [['job','run-real'],['job','run-real','process'],['job','run-real','tokens']])assert.equal((await f.execute(args)).code,0);const r=await f.execute(['job','run-real','tokens']);assert.match(r.out,/Cached input\s+10/);assert.match(r.out,/50.0% \(derived\)/);assert.match(r.out,/Cost\s+unavailable/);assert.equal(f.state.requests.filter(x=>x.method==='POST').length,0);});
test('workers models providers routes policies and catalogue are inspectable',async t=>{const f=await fixture(t);for(const command of ['workers','models','providers','routes','policies'])assert.equal((await f.execute([command,'--json'])).code,0);assert.match((await f.execute(['jobs','catalog'])).out,/observe/);});
test('catalogue-driven execution validates manifest parameters and uses one governed POST',async t=>{const f=await fixture(t);assert.equal((await f.execute(['run','observe','--count','8'])).code,EXIT.USAGE);assert.equal(f.state.inputs.length,0);const help=await f.execute(['run','observe','--help']);assert.match(help.out,/--count/);assert.equal((await f.execute(['run','observe','--count','3','--json'])).code,0);assert.deepEqual(f.state.inputs,[{parameters:{count:3},actor:'cli-operator'}]);assert.equal((await f.execute(['run','unknown'])).code,EXIT.NOT_FOUND);});
test('parameterized catalogue execution creates a frozen Saved Job then submits it',async t=>{const f=await fixture(t);assert.equal((await f.execute(['run','analyse'])).code,EXIT.USAGE);const r=await f.execute(['run','analyse','--repository','/source','--context','DEEP','--model','existing','--max-input-tokens','18000','--max-output-tokens','4000','--timeout','5','--retries','0']);assert.equal(r.code,0);assert.equal(f.state.inputs.length,2);assert.deepEqual(f.state.inputs[0].definition,{id:'analyse',version:3,follow:'pinned'});assert.deepEqual(f.state.inputs[0].routing,{model:'existing',allowFallback:false});assert.equal(f.state.inputs[0].contextProfile,'DEEP');assert.deepEqual(f.state.inputs[0].budgets,{maximumInputTokens:18000,maximumOutputTokens:4000,timeoutMinutes:5,maximumRetries:0});assert.deepEqual(f.state.inputs[0].parameters,{repository:'/source',scope:'full'});});
test('history tail and profile downloads preserve hashes and never rerun work',async t=>{const f=await fixture(t),directory=fs.mkdtempSync(path.join(os.tmpdir(),'cli-download-'));t.after(()=>removeFixture(directory));const h=await f.execute(['job','run-real','history','--tail','2']);assert.match(h.out,/12:01 output/);for(const profile of ['simple','detailed','evidence']){assert.equal((await f.execute(['job','run-real','output','--profile',profile,'--download','--directory',directory])).code,0);}assert.equal(fs.readdirSync(directory).length,3);assert.equal((await f.execute(['job','run-real','history','--download','--directory',directory])).code,0);assert.equal((await f.execute(['job','run-real','output','--download','--directory',directory])).code,EXIT.USAGE);assert.equal(f.state.inputs.length,0);assert.equal((await f.execute(['job','run-real','tokens','--download'])).code,EXIT.USAGE);});
test('authentication permission missing transport and usage failures have distinct non-secret exits',async t=>{const f=await fixture(t);for(const [status,code] of [[401,3],[403,5],[404,4],[503,7]]){f.state.deny=status;const r=await f.execute(['status','--json']);assert.equal(r.code,code);assert.equal(JSON.parse(r.out).exitCode,code);assert.doesNotMatch(r.out+r.err,new RegExp(token));}f.state.deny=0;assert.equal((await f.execute(['job','missing'])).code,4);assert.equal((await f.execute(['job','../escape'])).code,2);assert.equal((await f.execute(['status','--unsupported'])).code,2);assert.equal((await f.execute(['status','--endpoint','http://127.0.0.1:1'])).code,7);});
test('narrow terminal needs no colour and cannot interpret source escape sequences',async t=>{const f=await fixture(t),r=await f.execute(['job','run-real'],{width:32});assert.ok(r.out.split('\n').every(l=>l.length<=32));assert.doesNotMatch(r.out,/\x1b/);});
test('endpoint validation rejects credential URLs, nonlocal cleartext and redirects',async t=>{for(const u of ['http://remote.test','https://user:secret@host','https://host?token=secret','file:///tmp/x'])assert.throws(()=>endpointUrl(u));let init;const client=await createClient({endpoint:'https://controller.example'},{environment:{AGENT_CONTROL_WEB_OPERATOR_TOKEN:token},request:async(_u,i)=>{init=i;return new Response('{}',{status:302,headers:{location:'https://other.example'}});}});await assert.rejects(client.get('/api/status'));assert.equal(init.redirect,'error');});
test('saved HTTP status-client configuration supplies the same API endpoint without secrets',async t=>{const f=await fixture(t),dir=fs.mkdtempSync(path.join(os.tmpdir(),'cli-config-')),file=path.join(dir,'status-client.json');t.after(()=>removeFixture(dir));fs.writeFileSync(file,JSON.stringify({schema:'agent-control.status-client/v1',controller:{transport:'http',url:f.url+'/api/status'}}));const client=await createClient({},{environment:{AGENT_CONTROL_STATUS_CONFIG:file,AGENT_CONTROL_WEB_OPERATOR_TOKEN:token}});assert.equal((await client.get('/api/status')).health,'healthy');client.close();fs.writeFileSync(file,JSON.stringify({schema:'agent-control.status-client/v1',token:'secret',controller:{transport:'http',url:f.url}}));await assert.rejects(createClient({},{environment:{AGENT_CONTROL_STATUS_CONFIG:file}}));});
test('watch drains duplicate events, shows final failure, and does not cancel the job',async t=>{const f=await fixture(t);f.state.status='RUNNING';const promise=f.execute(['watch','run-real','--json']);while(!f.state.streams.length)await new Promise(r=>setTimeout(r,10));const stream=f.state.streams[0];for(let i=0;i<50;i++)stream.write(`id: ${i}\nevent: job.run_changed\ndata: {}\n\n`);setTimeout(()=>{f.state.status='FAILED';stream.write('event: job.run_changed\ndata: {}\n\n');},250);const r=await promise;assert.equal(r.code,6);const rows=r.out.split('\n').map(JSON.parse);assert.equal(rows.at(-1).data.run.status,'FAILED');assert.ok(rows.length<=3);assert.ok(f.state.requests.length<30);assert.equal(f.state.inputs.length,0);});
test('Ctrl-C stops watch without a cancellation mutation; disconnected stream is unavailable',async t=>{const f=await fixture(t);f.state.status='RUNNING';const controller=new AbortController(),promise=f.execute(['watch','run-real'],{signal:controller.signal});while(!f.state.streams.length)await new Promise(r=>setTimeout(r,10));controller.abort();assert.equal((await promise).code,130);assert.equal(f.state.inputs.length,0);await new Promise(r=>setTimeout(r,30));const p=f.execute(['watch','run-real']);while(!f.state.streams.length)await new Promise(r=>setTimeout(r,10));f.state.streams[0].end();assert.equal((await p).code,7);});

test('cost preserves currencies, recorded authority and partial coverage without inventing billing',async t=>{const f=await fixture(t);f.state.cost={currencies:{USD:{amount:'0.0123',observations:1,authorities:['MEASURED']},EUR:{amount:'0.01',observations:1,authorities:['DERIVED']}},reported:2,total:3};const r=await f.execute(['job','run-real','tokens']);assert.match(r.out,/USD 0.0123/);assert.match(r.out,/EUR 0.01/);assert.match(r.out,/2\/3 calls/);assert.match(r.out,/MEASURED/);});
