import {timingSafeEqual} from 'node:crypto';
import fs from 'node:fs';
import net from 'node:net';
import path from 'node:path';
import {JobCatalog} from '../src/control/job-catalog.js';
import {ActionRegistry,ArtifactStore,JobRuntime,ResourceLockManager,RunLedger,WorkerRegistry} from '../src/control/job-runtime.js';
import {AgentControlBackgroundJobPort} from '../src/control/mallow-job-port.js';
import {ASK_COLLINGHAM_JOB,AskCollinghamClient,registerAskCollinghamJob} from '../src/control/mallow-ask-collingham.js';
import {BufferedPhysicalSpeech,PhysicalPcmInput} from '../src/control/mallow-physical-audio.js';
import {MallowPresenceStore,MallowRealtimePresenceRuntime,type BackgroundJobReference,type FastRoute,type PresenceEvent} from '../src/control/mallow-realtime-presence.js';
import {GovernedSpeechCache} from '../src/control/mallow-speech-cache.js';
import {PrivateSpeechProvider} from '../src/control/speech-http-provider.js';
import {SharedSpeechServiceProvider} from '../src/control/shared-speech-service-provider.js';

const state=process.env.AGENT_CONTROL_MALLOW_PHYSICAL_STATE,operatorToken=process.env.AGENT_CONTROL_WEB_OPERATOR_TOKEN,speechToken=process.env.AGENT_CONTROL_SPEECH_TOKEN,sharedSpeechUrl=process.env.AGENT_CONTROL_SHARED_SPEECH_URL,sharedSpeechToken=process.env.AGENT_CONTROL_SHARED_SPEECH_TOKEN,voiceFile=process.env.AGENT_CONTROL_REALTIME_VOICE_FILE;
if(!state||!operatorToken||operatorToken.length<24||!voiceFile||sharedSpeechUrl&&(!sharedSpeechToken||sharedSpeechToken.length<32)||!sharedSpeechUrl&&(!speechToken||speechToken.length<32))throw Error('mallow_physical_configuration_required');
fs.mkdirSync(state,{recursive:true,mode:0o700});
const voice=JSON.parse(fs.readFileSync(voiceFile,'utf8')).voice,speechUrl=process.env.AGENT_CONTROL_SPEECH_URL??'http://127.0.0.1:19197',sttUrl=process.env.AGENT_CONTROL_REALTIME_STT_URL??'http://127.0.0.1:19224';
const shared=sharedSpeechUrl?new SharedSpeechServiceProvider(sharedSpeechUrl,sharedSpeechToken!,voice):undefined,synthesizer=shared??new PrivateSpeechProvider('omnivoice-buffered',speechUrl,speechToken!,voice),recognizer=shared??new PrivateSpeechProvider('faster-whisper-small.en',sttUrl,speechToken!,voice),speechProviderId=shared?'shared-speech-services':'omnivoice-buffered';
const speech=new GovernedSpeechCache(new BufferedPhysicalSpeech(speechProviderId,synthesizer,voice),path.join(state,'speech-cache'),['Yes — I’ll check that for you.','Certainly.','I’m checking that now.']);
const actions=new ActionRegistry(),catalog=new JobCatalog(new Set(['mallow.ask-collingham@1.0.0'])),ask=new AskCollinghamClient({baseUrl:process.env.AGENT_CONTROL_ASK_COLLINGHAM_URL??'http://127.0.0.1:18127',streamPath:process.env.AGENT_CONTROL_ASK_COLLINGHAM_PATH??'/api/ask-collingham/embed/0c369c9c-ce85-476f-9eb4-d44915ea1d13/stream-chat',stack:{conversationProvider:'AnythingLLM',model:'Qwen2.5-3B Q4_K_M',runtime:'llama.cpp',retrieval:'LanceDB',qualificationReference:'localwalks:ask-collingham-baseline-20260921'}});registerAskCollinghamJob(actions,catalog,ask);
const workers=new WorkerRegistry();workers.registerControllerInternal({id:'mallow-collingham-worker',capabilities:['collingham.query'],health:'healthy',capacity:2,active:0,observedAt:new Date().toISOString()});
const jobs=new JobRuntime(catalog,actions,workers,new RunLedger(path.join(state,'ledger.json')),new ArtifactStore(path.join(state,'artifacts')),new ResourceLockManager(path.join(state,'locks.json'))),background=new AgentControlBackgroundJobPort(jobs,(_route,text)=>({job:ASK_COLLINGHAM_JOB,parameters:{question:text,sessionId:'voice_'+Date.now()},laneId:'collingham-knowledge',skill:'ask-collingham',tool:'mallow.ask-collingham',model:'Qwen2.5-3B Q4_K_M'}),(_runId,evidence)=>{if(!evidence)return null;const value=jobs.artifacts.read(evidence) as {answer?:string};return value.answer??null;});
const router={id:'mallow-physical-router',route:({text,activeJobs}:{text:string;activeJobs:BackgroundJobReference[]}):FastRoute=>/found it yet|getting on|progress|still checking/i.test(text)?{kind:'progress',intent:'job_progress',reason:'explicit spoken progress request resolved from Agent Control run state'}:/collingham|station road|a1133|planning|community centre|village|church|history/i.test(text)?{kind:'background',intent:'ask_collingham',skill:'ask-collingham',acknowledgement:'Yes — I’ll check that for you.',jobRequest:{question:text},...(activeJobs.length&&/\b(no|sorry|meant|correction)\b/i.test(text)?{supersedesJobId:activeJobs.at(-1)!.jobId}:{}),reason:'local Collingham knowledge requires the registered governed Ask Collingham Job'}:{kind:'direct',intent:'conversation',reason:'bounded local conversational control does not require knowledge retrieval'}};
const conversation={id:'mallow-physical-control',respond:async({text}:{text:string})=>/hello|hi mallow/i.test(text)?{text:'Hello. I am listening.',provider:'deterministic conversation control',model:'rules'}:/thank/i.test(text)?{text:'You’re welcome.',provider:'deterministic conversation control',model:'rules'}:{text:'I am still listening while the background check continues.',provider:'deterministic conversation control',model:'rules'}};
type Message={type:string;[key:string]:unknown};
const server=net.createServer(socket=>{socket.setNoDelay(true);let buffer='',ready=false,input:PhysicalPcmInput|undefined,runtime:MallowRealtimePresenceRuntime|undefined,session='',unsubscribe:undefined|(()=>void);const first=new Map<number,(at:number)=>void>(),stops=new Map<number,(at:number)=>void>();
  const send=async(message:Message)=>{if(socket.destroyed)throw Error('media_socket_closed');if(!socket.write(JSON.stringify(message)+'\n'))await new Promise<void>(resolve=>socket.once('drain',resolve));};
  const stateEvent=(event:PresenceEvent)=>{const names:Partial<Record<PresenceEvent['type'],string>>={'voice.user_speech.started':'USER SPEECH','voice.transcript.final':'STT','voice.intent.detected':'INTENT','agent.job.created':'JOB CREATED','agent.job.progress':'JOB PROGRESS','agent.job.completed':'JOB COMPLETED','voice.response.started':'MODEL','voice.response.interrupted':'INTERRUPTION','speech.tts.started':'TTS','speech.tts.completed':'TTS COMPLETE'};const name=names[event.type];if(name)void send({type:'state',event:name,detail:event.detail}).catch(()=>{});};
  const close=async(reason:string)=>{if(!ready)return;ready=false;unsubscribe?.();input?.end();await runtime?.close(session).catch(()=>{});};socket.on('close',()=>void close('transport_disconnect'));socket.on('error',()=>void close('transport_error'));
  const started=new Set<number>();socket.on('data',chunk=>{buffer+=chunk.toString('utf8');if(buffer.length>2*1024*1024){socket.destroy();return;}for(;;){const split=buffer.indexOf('\n');if(split<0)break;const line=buffer.slice(0,split);buffer=buffer.slice(split+1);void(async()=>{try{const message=JSON.parse(line) as Message;if(!ready){if(message.type!=='hello'||typeof message.token!=='string'||message.token.length!==operatorToken.length||!timingSafeEqual(Buffer.from(message.token),Buffer.from(operatorToken))||typeof message.callId!=='string')throw Error('authentication_failed');session=String(message.callId);const store=new MallowPresenceStore(path.join(state,'events.jsonl'));unsubscribe=store.subscribe(stateEvent);runtime=new MallowRealtimePresenceRuntime({store,router,conversation,speech,background,monitorMs:100,audioSink:async({generation,chunk})=>{await send({type:'audio',generation,sequence:Date.now(),pcm:Buffer.from(chunk.bytes).toString('base64')});if(started.has(generation))return;started.add(generation);return await new Promise(resolve=>first.set(generation,at=>resolve({playbackStartedAtMs:at,outputDevice:'browser-selected output'})));},audioComplete:async({generation})=>{await send({type:'audio_end',generation});},audioCancel:async({generation})=>{await send({type:'interrupt',generation});return await new Promise(resolve=>stops.set(generation,at=>resolve({stopRequestedAtMs:at,queuedFramesDiscarded:null})));}});runtime.start(session);input=new PhysicalPcmInput('browser-webrtc-physical',recognizer,{device:'browser getUserMedia with WebRTC AEC/noise suppression',threshold:.015,startFrames:5,endFrames:30,maxFrames:500});void runtime.attachInput(session,input);ready=true;await send({type:'accepted',callId:session});if(shared)await send({type:'speech_status',detail:await shared.status()});return;}
      if(message.type==='audio'&&input&&typeof message.pcm==='string'){const raw=Buffer.from(message.pcm,'base64');input.push(raw,Date.now());}
      else if(message.type==='playback'){const generation=Number(message.generation);first.get(generation)?.(Number(message.at??Date.now()));first.delete(generation);}
      else if(message.type==='interrupt_ack'){const generation=Number(message.generation);stops.get(generation)?.(Number(message.at??Date.now()));stops.delete(generation);}
      else if(message.type==='hangup'){await close('caller_disconnect');socket.end();}
    }catch{socket.destroy();}})();}});
});
server.listen(Number(process.env.AGENT_CONTROL_MALLOW_PHYSICAL_BRIDGE_PORT??19322),'127.0.0.1',()=>process.stdout.write('Mallow physical bridge ready on private loopback.\n'));
