import fs from 'node:fs';
import path from 'node:path';
import {execFile} from 'node:child_process';
import {promisify} from 'node:util';
import {WorkQueueStore} from '../src/control/work-queue-store.ts';
import {ensureAndroidProvisioningMission, runAndroidProvisioning, provisioningSummary} from '../src/control/android-provisioning-runtime.ts';
const exec = promisify(execFile), stateDir = process.env.AGENT_CONTROL_STATE_DIR || path.resolve('.agent-control'), artifactDir = path.join(stateDir, 'android-artifacts'), timeout = Number(process.env.AGENT_CONTROL_COMMAND_TIMEOUT_MS || 30000), packageTimeout = Number(process.env.AGENT_CONTROL_PACKAGE_TIMEOUT_MS || 300000);
async function command(file, args, options = {}) { const r = await exec(file, args, {timeout, maxBuffer: 4 * 1024 * 1024, ...options}); return r.stdout.trim(); }
async function adb(args) { return command('adb', args); }
const PRIVILEGED_HELPER = process.env.AGENT_CONTROL_PRIVILEGED_HELPER || '/usr/local/libexec/agent-control-privileged';
const ops = {
  async detectAdb() { try { await command('adb', ['version']); return true; } catch { return false; } },
  async installPackage(spec) { if (spec.manager !== 'apt' || spec.packageName !== 'adb') return {installed: false}; if (process.env.AGENT_CONTROL_ALLOW_ADB_INSTALL !== '1') throw new Error('PRIVILEGE_UNAVAILABLE: explicit AGENT_CONTROL_ALLOW_ADB_INSTALL=1 is required'); let helperError; try { await command('sudo', ['-n', PRIVILEGED_HELPER, 'install-adb'], {timeout: packageTimeout}); } catch (error) { helperError=error; } const installed=await this.detectAdb(); if(installed)return{installed:true}; if(helperError)throw new Error(`PRIVILEGE_UNAVAILABLE: fixed helper failed and adb remains absent (${helperError instanceof Error ? helperError.message : String(helperError)})`); return {installed:false}; },
  async qualifyAdb() { try { const out = await adb(['devices']); return {qualified: out.split(/\r?\n/).slice(1).some(line => /^\S+\s+device\s*$/.test(line))}; } catch { return {qualified: false}; } },
  async obtainTermuxBoot() { fs.mkdirSync(artifactDir, {recursive: true}); const api = JSON.parse(await command('curl', ['-fsSL', '--max-time', '20', 'https://api.github.com/repos/termux/termux-boot/releases/latest'])); const asset = api.assets?.find(a => String(a.name).endsWith('.apk')); if (!asset?.browser_download_url) throw new Error('termux_boot_github_apk_asset_missing'); const file = path.join(artifactDir, 'termux-boot.apk'); await command('curl', ['-fsSL', '--max-time', '60', '-o', file, asset.browser_download_url]); const sha256 = (await command('sha256sum', [file])).split(/\s+/)[0]; this.artifact = {artifactRef: file, sha256}; return this.artifact; },
  async verifyTermuxBoot(spec, artifact) { if (spec.host !== 'github.com' || spec.repository !== 'termux/termux-boot' || !artifact.artifactRef.startsWith(artifactDir)) return {verified: false, sha256: artifact.sha256}; const sha256 = (await command('sha256sum', [artifact.artifactRef])).split(/\s+/)[0]; return {verified: sha256 === artifact.sha256, sha256}; },
  async installTermuxBoot() { if (!this.artifact?.artifactRef) throw new Error('termux_boot_artifact_not_obtained'); await adb(['install', '-r', this.artifact.artifactRef]); return {installed: true}; },
  async verifyTermuxBootPackage(packageName) { try { return {installed: /package:/.test(await adb(['shell', 'pm', 'path', packageName])), signingSource: 'github'}; } catch { return {installed: false, signingSource: 'other'}; } },
  async installBootHook() { return {installed: false}; }, async verifyBootHook() { try { await adb(['shell', 'test', '-x', '/data/data/com.termux/files/home/.termux/boot/agent-control.sh']); return {verified: true}; } catch { return {verified: false}; } }, async qualifyRebootRecovery() { return {qualified: false}; }
};
const approveInstall = process.argv.includes('--approve-install'), approvePairing = process.argv.includes('--approve-pairing'), store = new WorkQueueStore(path.join(stateDir, 'work-queue.json')), queue = store.load(), added = ensureAndroidProvisioningMission(queue); store.save(queue); const missionItems = queue.all().filter(item => item.id.startsWith('android.pixel.provision.')); console.log(`Pixel provisioning mission ${added ? 'created' : 'restored'} (${missionItems.length} items)`); const result = await runAndroidProvisioning({queue, store, ops, approveInstall, approvePairing, onEvent: e => console.log(`[${e.kind}] ${e.workId || ''} ${e.detail}`)}); console.log(provisioningSummary(result.queue)); const install = result.queue.get('android.pixel.provision.install-adb'); if (install?.status === 'human-review') console.log('\nNEEDS PRIVILEGE\nA one-time root-owned helper must be installed and narrowly sudo-authorized for exactly apt install adb. No password is captured or stored. Resume with:\n  AGENT_CONTROL_ALLOW_ADB_INSTALL=1 npm run provision:pixel -- --approve-install'); const review = result.queue.get('android.pixel.provision.pairing-approval'); if (review?.status === 'human-review') console.log('\nHUMAN REVIEW\nPixel Wireless Debugging pairing required\n\nApprove pairing on the Pixel, then resume with:\n  npm run provision:pixel -- --approve-pairing'); if (result.events.some(e => e.kind === 'failed')) process.exitCode = 1;
