import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {WindowsSkyComputerProvider} from '../src/control/computer-use-windows.js';
import {ComputerManagedRunController,DeterministicComputerVerifier,verifyComputerEventStream,type ComputerManagedRunResult,type ComputerProviderAdvertisement} from '../src/control/computer-use-managed.js';
import {DefaultComputerAuthority} from '../src/control/computer-use.js';

const required=(name:string)=>{const value=process.env[name];if(!value)throw Error(`missing_environment:${name}`);return value;};
const output=path.resolve(process.argv[2]??'docs/evidence/agent-control-4.19-computer-use/windows-sky-qualification.json');
const specification=path.resolve('config/computer-use-benchmark-4.19.json'),specificationBytes=fs.readFileSync(specification),specificationSha256=createHash('sha256').update(specificationBytes).digest('hex');
const provider=new WindowsSkyComputerProvider({url:required('AGENT_CONTROL_SKY_URL'),token:required('AGENT_CONTROL_SKY_TOKEN')});
const target={machine:'controller-local',application:'Notepad',window:required('AGENT_CONTROL_SKY_WINDOW')};
const advertisement:ComputerProviderAdvertisement={id:provider.id,levels:['STEP','MANAGED_RUN'],capabilities:['observe','inspect','screenshot','click','doubleClick','typeText','pressKey','focusWindow','wait'],streamingObservations:false,cancellation:true,humanTakeover:false,nativeVerification:false,persistentSession:true,externalApi:false,estimatedCost:0};
const base={target,maximumElapsedMs:30000,maximumProviderSpend:0,provider,providerAdvertisement:advertisement,verifier:new DeterministicComputerVerifier(),authority:new DefaultComputerAuthority()};
const startedAt=new Date().toISOString();
const step=await new ComputerManagedRunController().execute({...base,runId:'ac-4.19-windows-sky-step',level:'STEP',objective:'Place the exact frozen token in a disposable editable workspace and make it independently observable',workflow:[{id:'write-step-token',kind:'ACTION',action:{operation:'typeText',text:'AC-4.19-FROZEN'}}],verification:[{kind:'text',value:'AC-4.19-FROZEN'}]});
assert.equal(step.state,'VERIFIED',JSON.stringify({state:step.state,reason:step.reason,events:step.events}));
assert.equal(verifyComputerEventStream(step.events),true);
const managed=await new ComputerManagedRunController().execute({...base,runId:'ac-4.19-windows-sky-managed',level:'MANAGED_RUN',objective:'Append the frozen MANAGED_RUN qualification token in the disposable untitled document',workflow:[{id:'new-line',kind:'ACTION',action:{operation:'pressKey',key:'Return'}},{id:'write-managed-token',kind:'ACTION',action:{operation:'typeText',text:'AC-4.19-MANAGED'}}],verification:[{kind:'text',value:'AC-4.19-FROZEN'},{kind:'text',value:'AC-4.19-MANAGED'}]});
assert.equal(managed.state,'VERIFIED',JSON.stringify({state:managed.state,reason:managed.reason,events:managed.events}));
assert.equal(verifyComputerEventStream(managed.events),true);
const sanitize=(result:ComputerManagedRunResult):ComputerManagedRunResult=>({...result,observation:result.observation?{revision:result.observation.revision,at:result.observation.at,target:{machine:result.observation.target.machine,application:'Notepad',window:'redacted-ephemeral-window'},title:'Disposable untitled Notepad qualification surface',text:['AC-4.19-FROZEN','AC-4.19-MANAGED'].filter(token=>result.observation?.text?.includes(token)).join('\n'),elements:[{id:'redacted-document',role:'document',name:'Text editor'}],...(result.observation.screenshot?{screenshot:result.observation.screenshot}:{})}:null});
const stepElapsed=Date.parse(step.endedAt)-Date.parse(step.startedAt),benchmarkAttempt={id:'cu-mp-001-windows-sky',taskId:'CU-MP-001',taskClass:'text-entry',provider:provider.id,worker:'controller-local',runtime:'Codex @oai/sky Windows adapter',level:'STEP',providerReportedStatus:'COMPLETED',verification:'PASSED',terminal:'VERIFIED',actions:step.actions,retries:step.retries,elapsedMs:stepElapsed,providerCharge:0,localComputeCost:null,energyWh:null,hardwareTimeMs:stepElapsed,humanIntervention:false,humanDurationMs:null,cancellation:false,evidence:[`run:${step.runId}`,`event-tip:${step.events.at(-1)?.hash??'none'}`],failureClass:null,adversarialFalseSuccess:false};
const report={schema:'agent-control.computer-use-provider-qualification/v1',qualificationId:'agent-control-4.19-windows-sky',frozenSpecification:{path:'config/computer-use-benchmark-4.19.json',sha256:specificationSha256},startedAt,completedAt:new Date().toISOString(),provider:{id:provider.id,worker:'controller-local',runtime:'Codex @oai/sky Windows adapter',application:'Notepad',applicationState:'disposable unsaved tab',externalApi:false,providerCharge:0},environment:{platform:process.platform,release:os.release(),arch:process.arch,hostnameHash:createHash('sha256').update(os.hostname()).digest('hex')},results:[sanitize(step),sanitize(managed)],benchmarkAttempt,summary:{attempts:2,providerCompletions:2,verifiedSuccesses:2,falseSuccesses:0,humanInterventions:0,providerCharge:0},limitations:['Qualification covers native Windows text entry and observation only.','No file was saved and no production service was changed.','Open-tab names and unrelated document content were excluded from the public evidence.','Visual-model verification was not used.']};
fs.mkdirSync(path.dirname(output),{recursive:true});
fs.writeFileSync(output,`${JSON.stringify(report,null,2)}\n`,{mode:0o600});
process.stdout.write(`${JSON.stringify({output,provider:provider.id,step:step.state,managed:managed.state,events:step.events.length+managed.events.length,sha256:createHash('sha256').update(fs.readFileSync(output)).digest('hex')},null,2)}\n`);
