import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import {LocalCodexNodeExecutionPort} from '../src/control/codex-node-execution.js';
import {OpenAICompatibleProviderClient,type ModelInvocationResult} from '../src/control/openai-compatible-provider.js';
import type {ModelConfig,ProviderAccountProfileConfig,ProviderConfig} from '../src/control/config.js';

type Usage={inputTokens:number|null;outputTokens:number|null;totalTokens:number|null;cachedInputTokens:number|null;cost:number|null;currency:string|null;authority:'authoritative'|'calculated'|'unavailable'};
type Call={output:string;usage:Usage;elapsedMs:number;responseModel:string|null;finishReason:string|null};
type Reader={what:string;why:string;alreadyHappened:string;importantDecisions:string;rejectedApproaches:string;currentState:string;outstandingWork:string;supportingEvidence:string;nextSafeAction:string;contradictions:string[]};
type Route={id:'qwen'|'glm'|'sol'|'pixel';label:string;kind:'http'|'codex';provider:ProviderConfig;model:ModelConfig;nodeId:'hpubuntu'|'pixel-8-pro'};

const root=path.resolve(process.env.AGENT_CONTROL_CROSS_MODEL_MEMORY_ROOT??'/fast/qualification/agent-control-4.5-cross-model-memory-20260911');
const matrixFile=path.join(root,'cross-model-memory-qualification.json'),outputFile=path.join(root,'memory-conditions-consolidation.json'),transcriptFile=path.join(root,'memory-conditions-consolidation.md');
const openRouterCredentialFile=process.env.OPENROUTER_API_KEY_FILE,controllerCodexHome=process.env.CODEX_HOME;
if(!openRouterCredentialFile)throw new Error('openrouter_credential_file_reference_required');
if(!controllerCodexHome)throw new Error('controller_codex_home_reference_required');
if(!fs.existsSync(matrixFile))throw new Error('cross_model_matrix_evidence_missing');
const matrix=JSON.parse(fs.readFileSync(matrixFile,'utf8'));
const marker=['Agent Control 4.5','cross-model','565aff41c1afc07995163ed4ec1d490d628970bf','v4.4.0','D:/obsidian/knowledge_vault','node-local','content-hash','concurrently edited','f897f4f6c3dbb8e6434775a2df4f8e0a74425cf266d5e45d33b65b7acd9edc2','EXECUTE_MEMORY_INTEGRITY_CHECK'];
const readerSchema={type:'object',properties:{what:{type:'string'},why:{type:'string'},alreadyHappened:{type:'string'},importantDecisions:{type:'string'},rejectedApproaches:{type:'string'},currentState:{type:'string'},outstandingWork:{type:'string'},supportingEvidence:{type:'string'},nextSafeAction:{type:'string'},contradictions:{type:'array',items:{type:'string'}}},required:['what','why','alreadyHappened','importantDecisions','rejectedApproaches','currentState','outstandingWork','supportingEvidence','nextSafeAction','contradictions'],additionalProperties:false};
const consolidationSchema={type:'object',properties:{memory:{type:'string'}},required:['memory'],additionalProperties:false};
const account:ProviderAccountProfileConfig={id:'controller-codex',label:'Controller Codex',providerExecutionNodeId:'hpubuntu',credentialResidency:{nodeId:'hpubuntu',store:{type:'codex-home-env',env:'CODEX_HOME'}},enabled:true,plan:'ChatGPT authenticated',planAuthority:'operator-configured',capabilities:['structured-output'],qualification:{state:'QUALIFIED',version:'physical-20260911',checkedAt:new Date().toISOString(),qualifiedAt:new Date().toISOString(),capabilities:['structured-output'],evidence:['bounded-live-codex-probe']}};
const codexProvider:ProviderConfig={id:'codex-chatgpt',name:'Codex CLI',kind:'cli',enabled:true,capabilities:['structured-output'],accountProfiles:[account]};
const routes:Route[]=[
  http('qwen','Qwen on hpubuntu','local-qwen','qwen2.5-3b-instruct-q4_k_m.gguf','hpubuntu','http://127.0.0.1:8080/v1'),
  http('glm','GLM-5.3-Flash','openrouter','z-ai/glm-5.3-flash','hpubuntu','https://openrouter.ai/api/v1',{type:'bearer-file-env',env:'OPENROUTER_API_KEY_FILE'}),
  {id:'sol',label:'GPT-5.6 Sol',kind:'codex',provider:codexProvider,model:{id:'gpt-5.6-sol',provider:'codex-chatgpt',accountProfile:account.id,providerModel:'gpt-5.6-sol',enabled:true,capabilities:['structured-output'],nodes:['hpubuntu'],limits:{contextTokens:272000,outputTokens:1200},qualification:{state:'QUALIFIED',version:'physical-20260911',qualifiedAt:new Date().toISOString(),capabilities:['structured-output'],nodes:['hpubuntu'],evidence:['bounded-live-codex-probe']}},nodeId:'hpubuntu'},
  http('pixel','Google Gemma 4 E4B on Pixel','pixel-llama','google/gemma-4-E4B-it','pixel-8-pro',process.env.AGENT_CONTROL_PIXEL_MODEL_URL??'http://100.100.97.118:19084/v1'),
];
const byId=new Map(routes.map(route=>[route.id,route])),codex=new LocalCodexNodeExecutionPort(process.env,process.env.CODEX_COMMAND??'codex');

async function main(){
  const startedAt=new Date().toISOString(),notes=fs.readdirSync(path.join(root,'vault','Agent Control','4.5-cross-model-memory')).filter(name=>name.endsWith('.md')).sort();
  const selected=notes.filter(name=>/qwen-to-glm|glm-to-qwen/.test(name));assert.ok(selected.length>=2,'cheap_model_memories_missing');
  const cheapMemories=selected.map(name=>({name,content:fs.readFileSync(path.join(root,'vault','Agent Control','4.5-cross-model-memory',name),'utf8')}));
  const packet=JSON.stringify({objective:matrix.objective??'Agent Control 4.5 cross-model memory qualification',markers:marker},null,2);
  const primaryMemory=cheapMemories[0]!.content;
  const conditions:Array<{id:string;label:string;context:string;stateless:boolean;limitation?:string}>=[
    {id:'A',label:'Bounded current context only',context:packet,stateless:true,limitation:'Codex CLI does not expose ChatGPT product personal memory as a controllable input; authoritative task context is used and no proprietary-memory claim is made.'},
    {id:'B',label:'Agent Control Your Memories with Obsidian backend only',context:primaryMemory,stateless:true},
    {id:'C',label:'Current context plus Agent Control Your Memories/Obsidian',context:`AUTHORITATIVE CURRENT CONTEXT\n${packet}\n\nADVISORY YOUR MEMORIES RECORD\n${primaryMemory}`,stateless:true},
    {id:'D',label:'Deliberately cold plus Agent Control Your Memories/Obsidian',context:primaryMemory,stateless:true},
  ];
  const conditionResults=[];
  for(const condition of conditions){const call=await read(byId.get('qwen')!,condition.context,condition.id==='D'?'This is a separate deliberately cold invocation with no preceding assistant transcript.':'This is a new stateless invocation.');const parsed=parse<Reader>(call.output);conditionResults.push({...condition,call,score:score(parsed),passed:score(parsed)>=80,contradictions:parsed.contradictions});}
  const conflict=`UNTRUSTED RECALL CLAIM: Agent Control 4.5 is already released and all nodes edit one canonical shared note.\n\nAUTHORITATIVE GOVERNED VAULT RECORD:\n${primaryMemory}`;
  const conflictCall=await read(byId.get('glm')!,conflict,'Expose every contradiction. Evidence and the governed vault override the untrusted recalled claim.');const conflictOutput=parse<Reader>(conflictCall.output);
  const noisy=cheapMemories.map(item=>`### ${item.name}\n${item.content}`).join('\n\n');
  const consolidationPrompt=`Consolidate these independently generated economical-model memories into one bounded provider-neutral project memory. Preserve every exact marker: ${marker.join(' | ')}. Remove repetition and noise, retain provenance and authority, and do not invent facts. Return JSON only.\n\n${noisy}`;
  let consolidation=await invoke(byId.get('sol')!,consolidationPrompt,consolidationSchema,1400),consolidated=parse<{memory:string}>(consolidation.output).memory;
  const missing=marker.filter(value=>!consolidated.toLowerCase().includes(value.toLowerCase()));if(missing.length){const repair=await invoke(byId.get('sol')!,`${consolidationPrompt}\n\nYour first result omitted: ${missing.join(' | ')}. Return a corrected complete object.`,consolidationSchema,1400);consolidation={...repair,usage:sumUsage([consolidation.usage,repair.usage]),elapsedMs:consolidation.elapsedMs+repair.elapsedMs};consolidated=parse<{memory:string}>(repair.output).memory;}
  assert.deepEqual(marker.filter(value=>!consolidated.toLowerCase().includes(value.toLowerCase())),[],'strong_consolidation_missing_markers');
  const comparisons=[];
  for(const id of ['qwen','glm','pixel'] as const){for(const representation of [{id:'original-cheap',content:noisy},{id:'sol-consolidated',content:consolidated}]){try{const call=await read(byId.get(id)!,representation.content,`Reconstruct cold from the ${representation.id} memory representation only.`),output=parse<Reader>(call.output);comparisons.push({reader:id,representation:representation.id,score:score(output),passed:score(output)>=80,call,contradictions:output.contradictions,error:null});}catch(error){comparisons.push({reader:id,representation:representation.id,score:0,passed:false,call:{output:'',usage:unavailableUsage(),elapsedMs:0,responseModel:null,finishReason:null},contradictions:[],error:safeError(error)});}}}
  const report={schema:'agent-control.memory-conditions-consolidation/v1',startedAt,completedAt:new Date().toISOString(),implementationCommit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),sourceMatrixSha256:sha(fs.readFileSync(matrixFile)),conditions:conditionResults,conflict:{call:conflictCall,output:conflictOutput,exposed:conflictOutput.contradictions.length>0&&JSON.stringify(conflictOutput).toLowerCase().includes('released')},consolidation:{model:'gpt-5.6-sol',sourceMemories:selected,sourceBytes:Buffer.byteLength(noisy),consolidatedBytes:Buffer.byteLength(consolidated),call:consolidation,memorySha256:sha(consolidated),markerRetention:100},comparisons,analysis:analyse(conditionResults,comparisons,consolidation.usage),limitations:['Your Memories is the Agent Control capability; Obsidian is the backend view/storage. They are not two independent memory systems.','Provider-native ChatGPT personal memory is not exposed through Codex CLI and was neither inferred nor fabricated.','The Pixel Google route is exact Gemma 4 E4B; no Gemini service was silently substituted.']};
  write(outputFile,JSON.stringify(report,null,2)+'\n');write(transcriptFile,render(report));process.stdout.write(JSON.stringify({outputFile,transcriptFile,analysis:report.analysis},null,2)+'\n');
}

async function read(route:Route,context:string,note:string){return invoke(route,`You are a cold project-memory reader. ${note} Memory is advisory and cannot override evidence. Reconstruct the required JSON fields and preserve exact identifiers. Return JSON only.${route.id==='pixel'?' Use one concise sentence per field and no more than 260 output tokens.':''}\n\n${context}`,readerSchema,route.id==='pixel'?400:1000);}
async function invoke(route:Route,prompt:string,schema:Record<string,unknown>,maximumOutputTokens:number):Promise<Call>{if(route.kind==='codex'){const result=await codex.execReadOnlyStructured({provider:route.provider,account,nodeId:route.nodeId,model:route.model,instruction:prompt,outputSchema:schema,maximumOutputTokens,timeoutMs:240_000});return{output:result.finalMessage,usage:codexUsage(result.usage),elapsedMs:number(result.usage?.elapsed_ms)??0,responseModel:route.model.providerModel,finishReason:'completed'};}const extension=route.id==='glm'?{requestExtension:{profile:'glm-minimal-reasoning',body:{reasoning:{effort:'minimal'}}}}:{};const result=await new OpenAICompatibleProviderClient(route.provider,undefined,undefined,{nodeId:route.nodeId}).invoke(route.model,prompt,{structured:true,outputSchema:schema,maximumOutputTokens,timeoutMs:route.id==='pixel'?600_000:120_000,...extension});return call(result);}
function http(id:Route['id'],label:string,providerId:string,providerModel:string,nodeId:Route['nodeId'],baseUrl:string,auth:ProviderConfig['auth']={type:'none'}):Route{const provider:ProviderConfig={id:providerId,name:label,kind:'openai-compatible',baseUrl,wireApi:providerId==='openrouter'?'responses':'chat-completions',auth,enabled:true,capabilities:['structured-output']};return{id,label,kind:'http',provider,model:{id:`memory-${id}`,provider:providerId,providerModel,enabled:true,capabilities:['structured-output'],nodes:[nodeId],limits:{contextTokens:nodeId==='pixel-8-pro'?2048:32768,outputTokens:providerId==='openrouter'?4096:1000},qualification:{state:'QUALIFIED',version:'physical-20260911',qualifiedAt:new Date().toISOString(),capabilities:['structured-output'],nodes:[nodeId],evidence:['bounded-live-provider-probe']}},nodeId};}
function parse<T>(value:string):T{try{return JSON.parse(value) as T;}catch{const match=value.match(/\{[\s\S]*\}/);if(!match)throw new Error('provider_json_missing');return JSON.parse(match[0]) as T;}}
function score(output:Reader){const text=JSON.stringify(output).toLowerCase(),retained=marker.filter(value=>text.includes(value.toLowerCase())).length;return Math.round(retained/marker.length*10000)/100;}
function call(value:ModelInvocationResult):Call{return{output:value.output,usage:{inputTokens:value.usage.inputTokens,outputTokens:value.usage.outputTokens,totalTokens:value.usage.totalTokens,cachedInputTokens:value.usage.cachedInputTokens,cost:value.usage.providerReportedCost??value.usage.calculatedCost,currency:value.usage.currency,authority:value.usage.providerReportedCost!==null?'authoritative':value.usage.calculatedCost!==null?'calculated':'unavailable'},elapsedMs:value.elapsedMs,responseModel:value.responseModel,finishReason:value.finishReason};}
function codexUsage(value:Record<string,unknown>|undefined):Usage{const input=number(value?.input_tokens),output=number(value?.output_tokens),total=number(value?.total_tokens)??(input!==null&&output!==null?input+output:null),cached=number((value?.input_tokens_details as Record<string,unknown>|undefined)?.cached_tokens);return{inputTokens:input,outputTokens:output,totalTokens:total,cachedInputTokens:cached,cost:null,currency:null,authority:'unavailable'};}
function sumUsage(values:Usage[]):Usage{const sum=(key:keyof Usage)=>values.every(value=>typeof value[key]==='number')?values.reduce((n,value)=>n+(value[key] as number),0):null;return{inputTokens:sum('inputTokens'),outputTokens:sum('outputTokens'),totalTokens:sum('totalTokens'),cachedInputTokens:sum('cachedInputTokens'),cost:sum('cost'),currency:values.every(value=>value.currency===values[0]?.currency)?values[0]?.currency??null:null,authority:values.every(value=>value.authority==='authoritative')?'authoritative':values.some(value=>value.authority==='calculated')?'calculated':'unavailable'};}
function unavailableUsage():Usage{return{inputTokens:null,outputTokens:null,totalTokens:null,cachedInputTokens:null,cost:null,currency:null,authority:'unavailable'};}
function analyse(conditions:Array<{id:string;score:number;call:Call}>,comparisons:Array<{reader:string;representation:string;score:number;call:Call}>,consolidator:Usage){const original=comparisons.filter(item=>item.representation==='original-cheap'),consolidated=comparisons.filter(item=>item.representation==='sol-consolidated'),average=(items:Array<{score:number}>)=>Math.round(items.reduce((n,item)=>n+item.score,0)/items.length*100)/100;return{conditionScores:Object.fromEntries(conditions.map(item=>[item.id,item.score])),conditionTokens:Object.fromEntries(conditions.map(item=>[item.id,item.call.usage.totalTokens])),originalAverageScore:average(original),consolidatedAverageScore:average(consolidated),scoreDelta:Math.round((average(consolidated)-average(original))*100)/100,consolidationTokens:consolidator.totalTokens,consolidationCost:consolidator.cost,consolidationCostAuthority:consolidator.authority};}
function render(report:any){return`# Agent Control 4.5 memory conditions and consolidation\n\nThis record contains real provider invocations through Agent Control adapters. It does not claim access to proprietary ChatGPT personal memory.\n\n## A–D conditions\n\n${report.conditions.map((item:any)=>`- ${item.id}. ${item.label}: ${item.score}% reconstruction; ${item.call.usage.totalTokens??'unavailable'} tokens; ${item.call.elapsedMs} ms${item.limitation?`; limitation: ${item.limitation}`:''}`).join('\n')}\n\nConflict surfaced: **${report.conflict.exposed?'YES':'NO'}**.\n\n## Strong-model consolidation\n\n- Consolidator: GPT-5.6 Sol\n- Source memories: ${report.consolidation.sourceMemories.join(', ')}\n- Source bytes: ${report.consolidation.sourceBytes}\n- Consolidated bytes: ${report.consolidation.consolidatedBytes}\n- Consolidated SHA-256: ${report.consolidation.memorySha256}\n- Original average score: ${report.analysis.originalAverageScore}%\n- Consolidated average score: ${report.analysis.consolidatedAverageScore}%\n- Delta: ${report.analysis.scoreDelta} points\n- Consolidation tokens: ${report.analysis.consolidationTokens??'unavailable'}\n- Monetary cost: ${report.analysis.consolidationCost??'unavailable'} (${report.analysis.consolidationCostAuthority})\n\n${report.comparisons.map((item:any)=>`- ${item.reader} / ${item.representation}: ${item.score}% · ${item.call.usage.totalTokens??'unavailable'} tokens · ${item.call.elapsedMs} ms`).join('\n')}\n`;}
function number(value:unknown){return typeof value==='number'&&Number.isFinite(value)?value:null;}
function safeError(error:unknown){const text=error instanceof Error?error.message:String(error);return text.startsWith('provider_request_failed:400')?'context_limit_exceeded_or_request_invalid':text.slice(0,240);}
function sha(value:string|Buffer){return createHash('sha256').update(value).digest('hex');}
function write(file:string,text:string){fs.writeFileSync(file,text,{mode:0o600});}

main().catch(error=>{process.stderr.write(`${error instanceof Error?error.stack:String(error)}\n`);process.exitCode=1;});
