import assert from 'node:assert/strict';
import {randomBytes} from 'node:crypto';
import fs from 'node:fs';
import {once} from 'node:events';
import path from 'node:path';
import {chromium} from 'playwright-core';
import {MallowPresenceStore} from '../src/control/mallow-realtime-presence.js';
import {startWebDashboard} from '../src/control/web-server.js';

const evidence=path.resolve(process.argv[2]??'.agent-control/evidence/mallow-realtime-presence'),events=path.join(evidence,'events.jsonl'),output=path.join(evidence,'browser');if(!fs.existsSync(events))throw Error('mallow_demo_events_missing');fs.mkdirSync(output,{recursive:true});
const token=randomBytes(32).toString('hex'),store=new MallowPresenceStore(events),server=startWebDashboard({} as never,{host:'127.0.0.1',port:0,operatorToken:token,assetsDir:path.resolve('assets/dashboard'),mallowPresence:store});await once(server,'listening');const address=server.address();if(!address||typeof address==='string')throw Error('mallow_browser_address_missing');const base=`http://127.0.0.1:${address.port}`;
let browser;const errors:string[]=[];try{browser=await chromium.launch({headless:true,executablePath:process.env.AGENT_CONTROL_CHROMIUM??'/snap/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});const page=await browser.newPage({viewport:{width:1440,height:1000},colorScheme:'dark'});page.on('pageerror',error=>errors.push(error.message));page.on('console',message=>{if(message.type()==='error'&&!message.text().startsWith('Failed to load resource:'))errors.push(message.text());});await page.goto(`${base}/mallow-presence.html`,{waitUntil:'domcontentloaded'});await page.locator('#auth').waitFor();await page.fill('#token',token);await page.click('#auth-form button');await page.locator('#workspace').waitFor();await page.getByText('COMPLETED',{exact:true}).first().waitFor();assert.equal(await page.locator('.job').count(),1);assert.match(await page.locator('#timeline').innerText(),/agent\.job\.completed/);assert.match(await page.locator('#timeline').innerText(),/voice\.response\.interrupted/);await page.screenshot({path:path.join(output,'01-mallow-presence-desktop.png'),fullPage:true});
  await page.setViewportSize({width:390,height:844});await page.screenshot({path:path.join(output,'02-mallow-presence-mobile-portrait.png'),fullPage:true});const portrait=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth,visible:!document.querySelector('#workspace')?.hasAttribute('hidden')}));assert.ok(portrait.scrollWidth<=portrait.width);assert.equal(portrait.visible,true);
  await page.setViewportSize({width:844,height:390});await page.screenshot({path:path.join(output,'03-mallow-presence-mobile-landscape.png'),fullPage:true});const landscape=await page.evaluate(()=>({width:innerWidth,scrollWidth:document.documentElement.scrollWidth}));assert.ok(landscape.scrollWidth<=landscape.width);assert.deepEqual(errors,[]);
  const report={schema:'agent-control.mallow-presence-browser-qualification/v1',classification:'EXPERIMENTAL',qualifiedAt:new Date().toISOString(),sourceEvents:path.relative(process.cwd(),events),eventCount:store.list().length,viewports:['1440x1000','390x844','844x390'],portrait,landscape,browserErrors:errors,screenshots:fs.readdirSync(output).filter(name=>name.endsWith('.png')).sort(),boundaries:['Headless Chromium viewport qualification, not physical mobile qualification','Synthetic audio event source, not audible voice qualification']};fs.writeFileSync(path.join(output,'browser-qualification.json'),JSON.stringify(report,null,2)+'\n');process.stdout.write(JSON.stringify({verdict:'PASS',output,report},null,2)+'\n');
}finally{await browser?.close();await new Promise<void>(resolve=>server.close(()=>resolve()));}
