import {createHash,randomUUID} from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {emptyConfig,type AgentControlConfig,type ModelConfig,type ProviderConfig} from '../src/control/config.js';
import {buildJobRuntime} from '../src/control/job-bootstrap.js';
import {ModelRegistry} from '../src/control/model-registry.js';
import type {WorkParcelPlan} from '../src/control/work-parcels.js';

type Arm='plain'|'original'|'revised';
interface Cli {lab:string;baseUrl:string;providerModel:string;modelId:string;output:string;partition:'development'|'qualification';arm:Arm|'all';repetitions:number;keepState:boolean}
interface CaseRecord {id:string;job_id:string;partition:'development'|'qualification';scenario:string;worker_contract:unknown;expected:{outcome:string;facts:Record<string,unknown>;allowed_actions:string[];required_evidence:string[]}}

function args(argv:string[]):Cli {
  const values=new Map<string,string>();
  for(let index=0;index<argv.length;index++){
    const key=argv[index]!;
    if(key==='--keep-state'){values.set(key,'true');continue;}
    if(!key.startsWith('--')||!argv[index+1])throw Error(`invalid_argument:${key}`);
    values.set(key,argv[++index]!);
  }
  const lab=values.get('--lab'),output=values.get('--output');
  if(!lab||!output)throw Error('usage: --lab <Agent-Control-Lab> --output <report.json> [--partition development|qualification] [--arm plain|original|revised|all] [--repetitions 3]');
  const partition=(values.get('--partition')??'qualification') as Cli['partition'],arm=(values.get('--arm')??'all') as Cli['arm'],repetitions=Number(values.get('--repetitions')??'3');
  if(!['development','qualification'].includes(partition)||!['plain','original','revised','all'].includes(arm)||!Number.isInteger(repetitions)||repetitions<1||repetitions>20)throw Error('qualification_arguments_invalid');
  return{lab:path.resolve(lab),output:path.resolve(output),partition,arm,repetitions,keepState:values.get('--keep-state')==='true',baseUrl:values.get('--base-url')??'http://127.0.0.1:8080/v1',providerModel:values.get('--provider-model')??'qwen2.5-3b-instruct-q4_k_m.gguf',modelId:values.get('--model-id')??'local-qwen25-3b-template-qualification'};
}

const sha=(value:string)=>createHash('sha256').update(value).digest('hex');
const stable=(value:unknown):string=>Array.isArray(value)?`[${value.map(stable).join(',')}]`:value&&typeof value==='object'?`{${Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([key,item])=>`${JSON.stringify(key)}:${stable(item)}`).join(',')}}`:JSON.stringify(value)??'null';
const terminal=new Set(['SUCCEEDED','FAILED','DEGRADED','CANCELLED','MISSED','DISCONNECTED']);
function leaves(value:unknown,prefix=''):Array<{path:string;value:unknown}>{if(!value||typeof value!=='object'||Array.isArray(value))return[{path:prefix,value}];const entries=Object.entries(value as Record<string,unknown>);return entries.length?entries.flatMap(([key,item])=>leaves(item,prefix?`${prefix}.${key}`:key)):[];}
function assess(candidate:unknown,verification:unknown,expected:CaseRecord['expected']){
  const parsed=(candidate as {parsed?:unknown}|null)?.parsed,verdict=verification as {formatCompliant?:boolean}|null;
  if(!parsed||typeof parsed!=='object'||Array.isArray(parsed))return{completed:false,formatCompliant:false,substantiveAccepted:false,fullAcceptance:false,qualityScore:0,correctFacts:0,totalFacts:leaves(expected.facts).length,unsupportedClaims:[],missingOrIncorrectFacts:leaves(expected.facts).map(item=>item.path)};
  const output=parsed as Record<string,unknown>,actualFacts=output.facts&&typeof output.facts==='object'&&!Array.isArray(output.facts)?output.facts as Record<string,unknown>:{},expectedLeaves=leaves(expected.facts),actualLeaves=leaves(actualFacts),actualByPath=new Map(actualLeaves.map(item=>[item.path,item.value])),expectedByPath=new Map(expectedLeaves.map(item=>[item.path,item.value])),correctFacts=expectedLeaves.filter(item=>actualByPath.has(item.path)&&stable(actualByPath.get(item.path))===stable(item.value)).length,missingOrIncorrectFacts=expectedLeaves.filter(item=>!actualByPath.has(item.path)||stable(actualByPath.get(item.path))!==stable(item.value)).map(item=>item.path),unsupportedClaims=actualLeaves.filter(item=>item.value!==null&&(!expectedByPath.has(item.path)||stable(expectedByPath.get(item.path))!==stable(item.value))).map(item=>item.path),substantiveAccepted=output.outcome===expected.outcome&&correctFacts===expectedLeaves.length&&Array.isArray(output.evidence)&&expected.required_evidence.every(item=>output.evidence!.includes(item))&&Array.isArray(output.actions)&&output.actions.every(item=>typeof item==='string'&&expected.allowed_actions.includes(item));
  return{completed:true,formatCompliant:verdict?.formatCompliant===true,substantiveAccepted,fullAcceptance:verdict?.formatCompliant===true&&substantiveAccepted,qualityScore:expectedLeaves.length?correctFacts/expectedLeaves.length:1,correctFacts,totalFacts:expectedLeaves.length,unsupportedClaims,missingOrIncorrectFacts};
}
function summarize(runs:Array<Record<string,unknown>>){const groups=new Map<string,Array<Record<string,unknown>>>();for(const run of runs){const key=String(run.arm),values=groups.get(key)??[];values.push(run);groups.set(key,values);}return[...groups.entries()].map(([arm,values])=>{const assessments=values.map(value=>value.assessment as ReturnType<typeof assess>),metrics=values.map(value=>value.metrics as Record<string,unknown>);return{arm,runs:values.length,completed:assessments.filter(value=>value.completed).length,formatCompliant:assessments.filter(value=>value.formatCompliant).length,accepted:assessments.filter(value=>value.fullAcceptance).length,meanQualityScore:assessments.reduce((sum,value)=>sum+value.qualityScore,0)/values.length,unsupportedClaims:assessments.reduce((sum,value)=>sum+value.unsupportedClaims.length,0),inputTokens:metrics.reduce((sum,value)=>sum+Number(value.inputTokens??0),0),cachedInputTokens:metrics.reduce((sum,value)=>sum+Number(value.cachedInputTokens??0),0),outputTokens:metrics.reduce((sum,value)=>sum+Number(value.outputTokens??0),0),elapsedMs:metrics.reduce((sum,value)=>sum+Number(value.elapsedMs??0),0),authoritativeCost:metrics.every(value=>value.providerReportedCost===null)?null:metrics.reduce((sum,value)=>sum+Number(value.providerReportedCost??0),0)};});}
async function execute(runtime:ReturnType<typeof buildJobRuntime>,parcelId:string){for(let turn=0;turn<20;turn++){await runtime.workParcels.tick();const parcel=runtime.workParcels.get(parcelId),stage=parcel.stages[0];if(stage?.runId){let run=runtime.ledger.get(stage.runId);for(const step of run?.steps.filter(value=>value.status==='WAITING_FOR_APPROVAL')??[]){const policy=step.approval;if(!policy?.startsWith('runtime-safety:'))throw Error(`unexpected_approval_required:${policy??'missing'}`);runtime.approve(run!.id,policy,'operator-authorized-evidence-verifier-qualification');run=runtime.ledger.get(stage.runId);}if(run&&!terminal.has(run.status))await runtime.tick();}const current=runtime.workParcels.get(parcelId);if(['SUCCEEDED','FAILED','CANCELLED'].includes(current.status))return current;}throw Error(`qualification_did_not_settle:${parcelId}`);}

async function main(){
  const cli=args(process.argv.slice(2)),casePath=path.join(cli.lab,'qualifications','native-execution','cases-v2.json'),caseFile=JSON.parse(fs.readFileSync(casePath,'utf8')) as {schema:string;protocol:string;cases:CaseRecord[]};
  if(caseFile.schema!=='agent-control.agent-template-cases/v2')throw Error('evidence_verifier_cases_v2_required');
  const cases=caseFile.cases.filter(item=>item.job_id==='hallucination-resistance'&&item.partition===cli.partition);
  if(!cases.length)throw Error(`qualification_partition_empty:${cli.partition}`);
  process.env.AGENT_CONTROL_LAB_DIR=cli.lab;process.env.AGENT_CONTROL_TEMPLATE_DIR=path.join(cli.lab,'agent-templates');
  const stateRoot=fs.mkdtempSync(path.join(os.tmpdir(),'evidence-verifier-native-')),provider:ProviderConfig={id:'local-template-qualification',name:'Existing local OpenAI-compatible service',kind:'local',enabled:true,baseUrl:cli.baseUrl,wireApi:'chat-completions',auth:{type:'none'},requiresAuth:false,parallelism:1,costClass:'free',capabilities:['structured-output','text']},model:ModelConfig={id:cli.modelId,provider:provider.id,providerModel:cli.providerModel,enabled:true,routingEligible:true,capabilities:['structured-output','text'],nodes:['controller'],limits:{contextTokens:32768,outputTokens:2048},qualification:{state:'QUALIFIED',version:`operator-authorized-existing-backend:${sha(`${cli.baseUrl}\0${cli.providerModel}`).slice(0,16)}`,qualifiedAt:new Date().toISOString(),evidence:[`${cli.baseUrl}/models`],capabilities:['structured-output','text'],nodes:['controller']}},config:AgentControlConfig={...emptyConfig(),resources:[{id:'controller',name:'Qualification controller',platform:process.platform==='win32'?'windows':'linux',transport:{type:'local'},capabilities:['model.invoke','evidence.report'],controller:true}],providers:[provider],models:[model],jobs:{repositoryRoots:[path.resolve('.')]}},models=new ModelRegistry(config.providers,config.models,config.modelRouting),runtime=buildJobRuntime(config,stateRoot,path.join(stateRoot,'empty-jobs'),undefined,models),job=runtime.labJobs.get('hallucination-resistance@1.0.0'),armNames:Arm[]=cli.arm==='all'?['plain','original','revised']:[cli.arm],runs:Array<Record<string,unknown>>=[];
  try{
    for(const item of cases){const acceptance=runtime.labJobs.case('hallucination-resistance@1.0.0',item.id);if(acceptance.scenario!==item.scenario)throw Error(`case_identity_mismatch:${item.id}`);for(let repetition=1;repetition<=cli.repetitions;repetition++)for(const arm of armNames){const templateVersion=arm==='original'?'1.0.0':arm==='revised'?'1.2.0':null,template=templateVersion?runtime.agentTemplates.get(`evidence-verifier@${templateVersion}`):null;if(template){const readiness=runtime.agentTemplates.readiness(`evidence-verifier@${templateVersion}`,job.native,runtime.workers.list(),template.manifest.requirements.permissions);if(readiness.state!=='READY')throw Error(`template_not_ready:${templateVersion}:${readiness.reasons.join(',')}`);}const selection=template?{id:'evidence-verifier',version:template.manifest.version,digest:template.manifest.content_digest,jobDigest:job.digest}:undefined,plan:WorkParcelPlan={objective:`Evidence verifier ${cli.partition} ${item.id} ${arm} repetition ${repetition}`,planner:{kind:'deterministic',reason:'Pinned three-arm evidence-verifier qualification protocol'},stages:[{id:'execute',name:job.manifest.name,job:'hallucination-resistance@1.0.0',parameters:{scenario:item.scenario,caseId:item.id,maximumOutputTokens:512,timeoutMs:120000},...(selection?{template:selection}:{}),requestedRoute:{model:cli.modelId,allowFallback:false,purpose:'QUALIFICATION',profile:'THIN',reason:'Matched model, tools, budget and generation settings'}}]},submitted=runtime.workParcels.submitNativePlan(plan.objective,'evidence-verifier-qualification',sha(`${item.id}\0${arm}\0${repetition}\0${randomUUID()}`),plan),started=Date.now(),parcel=await execute(runtime,submitted.id),stage=parcel.stages[0]!,run=runtime.ledger.get(stage.runId!)!,artifacts=runtime.artifacts.list(run.id),candidateMeta=artifacts.find(value=>value.name==='candidate-result'),verificationMeta=artifacts.find(value=>value.name==='verification-report'),candidate=candidateMeta?runtime.artifacts.read(candidateMeta.id):null,verification=verificationMeta?runtime.artifacts.read(verificationMeta.id):null,invocations=runtime.harnessEfficiency.list().filter(value=>value.runId===run.id);
        runs.push({caseId:item.id,partition:item.partition,arm,repetition,job:{id:job.manifest.id,version:job.manifest.version,digest:job.digest,runtimeDigest:run.jobDigest},template:template?{id:'evidence-verifier',version:template.manifest.version,digest:template.manifest.content_digest}:null,input:{digest:run.inputsDigest,scenarioSha256:sha(item.scenario),workerContractSha256:sha(stable(item.worker_contract)),caseDigest:sha(stable(acceptance))},model:{providerId:provider.id,modelId:cli.modelId,providerModel:cli.providerModel,baseUrl:cli.baseUrl,qualificationVersion:run.trigger.modelRoute?.qualificationVersion},runtime:{parcelId:parcel.id,runId:run.id,status:run.status,parcelStatus:parcel.status,sourceJobDigest:run.sourceJobDigest,elapsedMs:Date.now()-started,approvals:run.approvals,governance:run.provenance.filter(value=>value.type==='runtime-safety')},adaptation:null,candidate,verification,assessment:assess(candidate,verification,item.expected),artifacts:artifacts.map(value=>({id:value.id,name:value.name,sha256:value.sha256})),metrics:{inputTokens:parcel.telemetry.inputTokens??null,freshInputTokens:parcel.telemetry.freshInputTokens,cachedInputTokens:parcel.telemetry.cachedInputTokens,outputTokens:parcel.telemetry.outputTokens,totalTokens:parcel.telemetry.totalTokens,elapsedMs:parcel.telemetry.elapsedMs,providerReportedCost:parcel.audit.totals.providerReportedCost,cost:parcel.telemetry.cost,currency:parcel.telemetry.currency,invocations:invocations.map(value=>({id:value.id,outcome:value.outcome,verification:value.verifierResult,inputTokens:value.usage.inputTokens,cachedInputTokens:value.usage.cachedInputTokens,outputTokens:value.usage.outputTokens,totalTokens:value.usage.totalProcessedTokens,elapsedMs:value.elapsedMs,providerReportedCost:value.providerReportedCost,calculatedCost:value.calculatedCost,currency:value.currency,harnessProfile:value.harnessProfile,recipeFingerprint:value.provenance.recipeFingerprint}))},errors:run.errors});
        process.stderr.write(`${item.id} ${arm} ${repetition}/${cli.repetitions}: ${run.status}\n`);
      }
    }
    const report={schema:'agent-control.evidence-verifier-native-qualification/v2',generatedAt:new Date().toISOString(),protocol:{id:caseFile.protocol,partition:cli.partition,answerKeysExcludedFromWorkerContext:true,responseContractContainsStructureNotAnswers:true,sameEvidenceToolsBudgetsModelAndGenerationSettings:true,sequence:'sequential',arms:{plain:'Job prompt and response contract only',original:'evidence-verifier@1.0.0',revised:'evidence-verifier@1.2.0'},limitations:['Development cases informed versions 1.1.0 and the single final decision-table refinement in 1.2.0; qualification cases were held out until 1.2.0 was frozen.','Small samples on one existing local backend do not establish general effectiveness.']},backend:{baseUrl:cli.baseUrl,providerModel:cli.providerModel,modelId:cli.modelId,downloaded:false,reconfigured:false,restarted:false},stateRoot:cli.keepState?stateRoot:null,summary:summarize(runs),runs};
    fs.mkdirSync(path.dirname(cli.output),{recursive:true});fs.writeFileSync(cli.output,`${JSON.stringify(report,null,2)}\n`,{mode:0o600});process.stdout.write(`${cli.output}\n`);
  }finally{if(!cli.keepState)fs.rmSync(stateRoot,{recursive:true,force:true});}
}
await main();
