import fs from 'node:fs';
import path from 'node:path';
import {createHash} from 'node:crypto';
import {ActionRegistry,WorkerRegistry,createJobRuntime} from '../src/control/job-runtime.js';
import {JobCatalog} from '../src/control/job-catalog.js';
import {extractBlenderProcedure,replayBlenderProcedure,type BlenderProcedure,type BlenderProcedurePort,type BlenderProcedureStep,type BlenderSupervisedTrace} from '../src/control/blender-procedure.js';
import type {BlenderExecutionReceipt} from '../src/control/blender-skill.js';

const arg=(name:string)=>{const i=process.argv.indexOf(name),value=i>=0?process.argv[i+1]:undefined;if(!value)throw Error(`argument_required:${name}`);return value;};
const blender=path.resolve(arg('--blender')),output=path.resolve(arg('--output')),state=path.resolve(arg('--state')),sourceCommit=arg('--source-commit');
fs.mkdirSync(output,{recursive:true});fs.mkdirSync(state,{recursive:true});
const digest=(file:string)=>createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const saveJson=(name:string,value:unknown)=>fs.writeFileSync(path.join(output,name),`${JSON.stringify(value,null,2)}\n`);
const steps:BlenderProcedureStep[]=[
 {id:'shell',capability:'blender.scene.create',parameters:{assembly:'warehouse-shell'},checkpoint:['floor-present','walls-present'],recovery:{onFailure:'STOP',validation:['partial-scene-retained']}},
 {id:'mezzanine',capability:'blender.object.create',parameters:{assembly:'luxury-mezzanine'},checkpoint:['mezzanine-present','supports-present','stairs-present'],recovery:{onFailure:'RETRY_ONCE',validation:['assembly-retry-safe']}},
 {id:'computers',capability:'blender.object.create',parameters:{assembly:'retro-computer-room'},checkpoint:['desks-present','computers-present','screens-present'],recovery:{onFailure:'RETRY_ONCE',validation:['assembly-retry-safe']}},
 {id:'materials',capability:'blender.material.apply',parameters:{palette:'industrial-accent'},checkpoint:['materials-present'],recovery:{onFailure:'RETRY_ONCE',validation:['materials-idempotent']}},
 {id:'view',capability:'blender.camera.configure',parameters:{view:'qualification-overview'},checkpoint:['camera-present','lights-present'],recovery:{onFailure:'STOP',validation:['camera-reset-safe']}},
 {id:'export',capability:'blender.export',parameters:{format:'GLB'},checkpoint:['scene-reopened','object-count-valid','dimensions-valid','collections-valid','export-present','job-marker-valid'],recovery:{onFailure:'STOP',validation:['partial-export-removed']}}
];
const common=[
 'import bpy,json','from mathutils import Vector',
 "def box(name,loc,scale,collection):",
 " bpy.ops.mesh.primitive_cube_add(location=loc); o=bpy.context.active_object; o.name=name; o.scale=scale; bpy.ops.object.transform_apply(location=False,rotation=False,scale=True)",
 " for c in list(o.users_collection): c.objects.unlink(o)",
 " collection.objects.link(o); return o",
 "def mat(name,color,metallic=0.0):",
 " m=bpy.data.materials.get(name) or bpy.data.materials.new(name); m.diffuse_color=(*color,1); m.metallic=metallic; m.roughness=.45; return m",
 "def look(obj,target): obj.rotation_euler=(Vector(target)-obj.location).to_track_quat('-Z','Y').to_euler()"
];
type Parameters={width:number;depth:number;mezzanineHeight:number;accent:[number,number,number];blend:string;glb:string;marker:string};
function source(step:BlenderProcedureStep,p:Parameters){const w=p.width,d=p.depth,h=p.mezzanineHeight,lines=[...common];
 if(step.id==='shell')lines.push("bpy.ops.object.select_all(action='SELECT')","bpy.ops.object.delete(use_global=False)","[bpy.data.collections.remove(c) for c in list(bpy.data.collections) if c.name!='Collection']","shell=bpy.data.collections.new('WarehouseShell'); bpy.context.scene.collection.children.link(shell)","mezz=bpy.data.collections.new('LuxuryMezzanine'); bpy.context.scene.collection.children.link(mezz)","retro=bpy.data.collections.new('RetroComputerRoom'); bpy.context.scene.collection.children.link(retro)",`box('WarehouseFloor',(0,0,.1),(${w}/2,${d}/2,.1),shell)`,`box('WarehouseBackWall',(0,${d}/2,2.5),(${w}/2,.1,2.5),shell)`,`box('WarehouseLeftWall',(-${w}/2,0,2.5),(.1,${d}/2,2.5),shell)`);
 if(step.id==='mezzanine')lines.push("mezz=bpy.data.collections['LuxuryMezzanine']",`box('MezzaninePlatform',(${w}*.23,${d}*.2,${h}),(${w}*.25,${d}*.25,.15),mezz)`,`[box(f'MezzanineSupport_{i}',(x,${d}*.2,${h}/2),(.12,.12,${h}/2),mezz) for i,x in enumerate((-${w}*.02,${w}*.47))]`,`[box(f'Stair_{i}',(-${w}*.06-i*.35,${d}*.2,.25+i*${h}/12),(.3,1.0,.12),mezz) for i in range(6)]`);
 if(step.id==='computers')lines.push("retro=bpy.data.collections['RetroComputerRoom']","[(box(f'RetroDesk_{i}',(0,y,1.0),(1.4,.65,.08),retro),box(f'RetroComputer_{i}',(0,y,1.35),(.38,.3,.32),retro),box(f'RetroScreen_{i}',(0,y-.31,1.38),(.25,.04,.18),retro)) for i,y in enumerate((-1.8,0,1.8))]");
 if(step.id==='materials')lines.push("steel=mat('WarehouseSteel',(.12,.14,.16),.5)",`accent=mat('QualificationAccent',${JSON.stringify(p.accent)},.15)`,"glow=mat('ScreenGlow',(.05,.55,.35),.05)","[o.data.materials.append(steel) for o in bpy.data.collections['WarehouseShell'].objects]","[o.data.materials.append(accent) for o in bpy.data.collections['LuxuryMezzanine'].objects]","[o.data.materials.append(glow if 'Screen' in o.name else steel) for o in bpy.data.collections['RetroComputerRoom'].objects]");
 if(step.id==='view')lines.push(`bpy.ops.object.camera_add(location=(${w}*.72,-${d}*.82,7))`,"cam=bpy.context.active_object; cam.name='QualificationCamera'; look(cam,(0,0,1.5)); bpy.context.scene.camera=cam","bpy.ops.object.light_add(type='AREA',location=(0,-1,7))","bpy.context.active_object.name='QualificationKey'; bpy.context.active_object.data.energy=1600; bpy.context.active_object.data.size=6",`bpy.ops.object.light_add(type='AREA',location=(${w}*.25,${d}*.25,4.8))`,"bpy.context.active_object.name='MezzanineLight'; bpy.context.active_object.data.energy=700");
 if(step.id==='export')lines.push(`bpy.ops.export_scene.gltf(filepath=${JSON.stringify(p.glb.replace(/\\/g,'/'))},export_format='GLB',use_selection=False)`);
 lines.push(`bpy.context.scene['agent_control_job']=${JSON.stringify(p.marker)}`,`bpy.context.scene['warehouse_dimensions']=[${w},${d},${h}]`,`bpy.ops.wm.save_as_mainfile(filepath=${JSON.stringify(p.blend.replace(/\\/g,'/'))})`);
 const checks:Record<string,string>={shell:"{'floor-present':bpy.data.objects.get('WarehouseFloor') is not None,'walls-present':bpy.data.objects.get('WarehouseBackWall') is not None and bpy.data.objects.get('WarehouseLeftWall') is not None}",mezzanine:"{'mezzanine-present':bpy.data.objects.get('MezzaninePlatform') is not None,'supports-present':len([o for o in bpy.data.objects if o.name.startswith('MezzanineSupport_')])==2,'stairs-present':len([o for o in bpy.data.objects if o.name.startswith('Stair_')])==6}",computers:"{'desks-present':len([o for o in bpy.data.objects if o.name.startswith('RetroDesk_')])==3,'computers-present':len([o for o in bpy.data.objects if o.name.startswith('RetroComputer_')])==3,'screens-present':len([o for o in bpy.data.objects if o.name.startswith('RetroScreen_')])==3}",materials:"{'materials-present':all(bpy.data.materials.get(n) is not None for n in ['WarehouseSteel','QualificationAccent','ScreenGlow'])}",view:"{'camera-present':bpy.context.scene.camera is not None,'lights-present':len([o for o in bpy.data.objects if o.type=='LIGHT'])==2}",export:`{'scene-reopened':bool(bpy.data.filepath),'object-count-valid':len(bpy.data.objects)>=23,'dimensions-valid':list(bpy.context.scene['warehouse_dimensions'])==[${w},${d},${h}],'collections-valid':all(bpy.data.collections.get(n) is not None for n in ['WarehouseShell','LuxuryMezzanine','RetroComputerRoom']),'export-present':True,'job-marker-valid':bpy.context.scene.get('agent_control_job')==${JSON.stringify(p.marker)}}`};
 lines.push(`print('AGENT_CONTROL_STEP:'+json.dumps(${checks[step.id]},sort_keys=True))`);return lines.join('\n');}

const action='blender.semantic-procedure@1.0.0';
function actionRegistry(procedure:()=>BlenderProcedure){const actions=new ActionRegistry();actions.registerControl(action,async context=>{const p=JSON.parse(String(context.parameters.parameters)) as Parameters;let active=false;const port:BlenderProcedurePort={execute:async(step,_parameters,signal)=>{const script=path.join(state,`${context.run.id}-${step.id}.py`);fs.writeFileSync(script,source(step,p));active=true;try{const result=await context.ownedExecution.runProcess({command:blender,args:[...(fs.existsSync(p.blend)?[p.blend]:['--factory-startup']),'--background','--python',script],maxOutputBytes:2*1024*1024},signal);if(result.exitCode!==0)throw Error(`blender_step_failed:${step.id}:${result.exitCode}:${result.stderr}`);const line=result.stdout.split(/\r?\n/).find(value=>value.startsWith('AGENT_CONTROL_STEP:'));if(!line)throw Error(`blender_step_marker_missing:${step.id}`);const checks=JSON.parse(line.slice('AGENT_CONTROL_STEP:'.length)) as Record<string,boolean>,validation=Object.entries(checks).filter(([,ok])=>ok).map(([name])=>name);return{validation,sceneSha256:digest(p.blend),artifacts:step.id==='export'?[{name:'scene.blend',sha256:digest(p.blend)},{name:'scene.glb',sha256:digest(p.glb)}]:[]};}finally{active=false;}},cancel:async()=>({clean:!active})};const replay=await replayBlenderProcedure({jobId:context.run.id,procedure:procedure(),parameters:p,port,signal:context.signal,humanIntervention:false,supervisorOperationalActions:Number(context.parameters.supervisorOperationalActions??0)});if(replay.status!=='SUCCEEDED')throw Error(`blender_replay_${replay.status.toLowerCase()}`);return{artifacts:[{name:'blender-procedure-replay',type:'application/json',schema:replay.schema,version:'1.0.0',retention:'release-evidence',value:replay}],evidence:replay.artifacts.map(item=>`${item.name}:${item.sha256}`),verification:replay.steps.flatMap(item=>item.validation)};});return actions;}
function catalogue(actions:ActionRegistry,id:string){const catalog=new JobCatalog(actions.ids());catalog.addJob({apiVersion:'agent-control/v1',kind:'Job',metadata:{id,name:id,version:'1.0.0'},spec:{priority:'normal',concurrency:'no-overlap',parameters:{parameters:{type:'string',required:true},supervisorOperationalActions:{type:'integer',required:true}},steps:[{id:'execute',action,requires:['blender.procedure'],resources:['blender'],outputs:[{name:'blender-procedure-replay',type:'application/json',schema:'agent-control.blender-procedure-replay/v1',version:'1.0.0',retention:'release-evidence'}],timeoutSeconds:300,verification:steps.flatMap(item=>item.checkpoint)}]}});return catalog;}
function runtimeFor(procedure:()=>BlenderProcedure,id:string){const actions=actionRegistry(procedure),workers=new WorkerRegistry().registerControllerInternal({id:'controller-local-blender',capabilities:['blender.procedure'],health:'healthy',capacity:1,active:0,labels:{platform:process.platform},observedAt:new Date().toISOString()});return createJobRuntime(path.join(state,id),catalogue(actions,id),actions,workers);}
const provisional:BlenderProcedure={schema:'agent-control.blender-procedure/v1',id:'supervised-industrial-room',version:'1.0.0',sourceJobs:['supervisor-seed'],prerequisites:['Blender 4.5+'],parameters:['width','depth','mezzanineHeight','accent','blend','glb','marker'],steps,completionCriteria:steps.flatMap(item=>item.checkpoint),cancellation:'STOP_AND_VERIFY_NO_OWNED_PROCESS',limitations:['Supervised source procedure.'],sha256:''};
const stable=(value:unknown):string=>JSON.stringify(value&&typeof value==='object'&&!Array.isArray(value)?Object.fromEntries(Object.entries(value as Record<string,unknown>).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>[k,JSON.parse(stable(v))])):value),{sha256:_,...unsigned}=provisional;provisional.sha256=createHash('sha256').update(stable(unsigned)).digest('hex');
const supervised=runtimeFor(()=>provisional,'blender-supervised-learning'),traces:BlenderSupervisedTrace[]=[];
for(const [i,p0] of [{width:12,depth:9,mezzanineHeight:3,accent:[.65,.16,.05] as [number,number,number]},{width:13,depth:10,mezzanineHeight:3.2,accent:[.1,.28,.7] as [number,number,number]}].entries()){const p:Parameters={...p0,blend:path.join(output,`supervised-${i+1}.blend`),glb:path.join(output,`supervised-${i+1}.glb`),marker:`4.17-supervised-${i+1}`},run=supervised.createRun('blender-supervised-learning@1.0.0',{parameters:JSON.stringify(p),supervisorOperationalActions:1},{type:'manual',actor:'qualification:4.17-supervised'});await supervised.tick();const final=supervised.ledger.get(run.id)!,record=supervised.artifacts.list(run.id).find(item=>item.name==='blender-procedure-replay');if(final.status!=='SUCCEEDED'||!record)throw Error(`supervised_job_failed:${final.errors.join(',')}`);const replay=supervised.artifacts.read(record.id) as {steps:Array<{validation:string[]}>;artifacts:Array<{name:string;sha256:string}>};const receipt:BlenderExecutionReceipt={schema:'agent-control.blender-execution/v1',jobId:run.id,capability:'blender.scene.create',sourceSha256:null,targetBlendSha256:null,parameterSha256:createHash('sha256').update(stable(p)).digest('hex'),inputArtifacts:[],stdout:'',stderr:'',resultingSceneSha256:digest(p.blend),artifacts:replay.artifacts,validation:replay.steps.flatMap(item=>item.validation),rollbackRef:null};traces.push({jobId:run.id,receipt,decomposition:structuredClone(steps),failures:[],humanIntervention:false,supervisor:'Codex-supervised-decomposition'});saveJson(`supervised-${i+1}-report.json`,{sourceCommit,job:final,receipt,files:[p.blend,p.glb].map(file=>({name:path.basename(file),size:fs.statSync(file).size,sha256:digest(file)}))});}
const learned=extractBlenderProcedure({id:'bounded-industrial-mezzanine-room',traces,prerequisites:['Blender 4.5+ with glTF export','Fresh writable scene path'],parameters:provisional.parameters,completionCriteria:provisional.completionCriteria,limitations:['Bounded warehouse/mezzanine/computer-room layouts only.','One physical replay does not establish general Blender autonomy.']});saveJson('learned-procedure.json',learned);
const replayRuntime=runtimeFor(()=>learned,'blender-independent-replay'),p:Parameters={width:14,depth:11,mezzanineHeight:3.4,accent:[.12,.58,.28],blend:path.join(output,'independent-replay.blend'),glb:path.join(output,'independent-replay.glb'),marker:'4.17-independent-replay'},run=replayRuntime.createRun('blender-independent-replay@1.0.0',{parameters:JSON.stringify(p),supervisorOperationalActions:0},{type:'manual',actor:'qualification:4.17-independent-replay'});await replayRuntime.tick();const final=replayRuntime.ledger.get(run.id)!,record=replayRuntime.artifacts.list(run.id).find(item=>item.name==='blender-procedure-replay'),replay=record?replayRuntime.artifacts.read(record.id):null;saveJson('independent-replay-report.json',{schema:'agent-control.blender-learned-skill-qualification/v1',sourceCommit,supervisedJobs:traces.map(item=>item.jobId),procedure:{id:learned.id,sha256:learned.sha256,sourceJobs:learned.sourceJobs},job:final,replay,files:[p.blend,p.glb].filter(fs.existsSync).map(file=>({name:path.basename(file),size:fs.statSync(file).size,sha256:digest(file)})),humanIntervention:false,supervisorOperationalActions:0});console.log(JSON.stringify({sourceCommit,procedure:learned.sha256,replayJob:run.id,status:final.status,classification:(replay as {classification?:string}|null)?.classification},null,2));if(final.status!=='SUCCEEDED')process.exitCode=1;
