import {createHash,randomUUID} from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {emptyConfig,type AgentControlConfig,type ModelConfig,type ProviderConfig} from '../src/control/config.js';
import {buildJobRuntime} from '../src/control/job-bootstrap.js';
import {ModelRegistry} from '../src/control/model-registry.js';
import type {WorkParcelPlan} from '../src/control/work-parcels.js';

interface Cli {lab:string;baseUrl:string;providerModel:string;modelId:string;output:string;caseId?:string;arm?:'plain'|'template'|'both';repetitions?:number;keepState:boolean}
const CASES=[
  {caseId:'research-supported-unsupported',job:'technical-research',template:'researcher',repetitions:3},
  {caseId:'review-known-defect',job:'review-pull-request',template:'code-reviewer',repetitions:3},
  {caseId:'review-clean',job:'review-pull-request',template:'code-reviewer',repetitions:1},
  {caseId:'evidence-missing',job:'hallucination-resistance',template:'evidence-verifier',repetitions:3},
  {caseId:'docs-conflict',job:'documentation-consistency',template:'documentation-writer',repetitions:3},
  {caseId:'docs-agree',job:'documentation-consistency',template:'documentation-writer',repetitions:1},
  {caseId:'compare-failures-missing-tradeoffs',job:'compare-models',template:'model-evaluator',repetitions:3},
] as const;

function args(argv:string[]):Cli{const values=new Map<string,string>();for(let index=0;index<argv.length;index++){const key=argv[index]!;if(key==='--keep-state'){values.set(key,'true');continue;}if(!key.startsWith('--')||!argv[index+1])throw Error(`invalid_argument:${key}`);values.set(key,argv[++index]!);}const lab=values.get('--lab'),output=values.get('--output');if(!lab||!output)throw Error('usage: --lab <Agent-Control-Lab> --output <report.json> [--base-url http://127.0.0.1:8080/v1] [--provider-model model] [--model-id id] [--case id] [--arm plain|template|both] [--repetitions n] [--keep-state]');const arm=(values.get('--arm')??'both') as Cli['arm'];if(!['plain','template','both'].includes(arm!))throw Error('invalid_arm');const repetitions=values.has('--repetitions')?Number(values.get('--repetitions')):undefined;if(repetitions!==undefined&&(!Number.isInteger(repetitions)||repetitions<1||repetitions>20))throw Error('invalid_repetitions');return{lab:path.resolve(lab),output:path.resolve(output),baseUrl:values.get('--base-url')??'http://127.0.0.1:8080/v1',providerModel:values.get('--provider-model')??'qwen2.5-3b-instruct-q4_k_m.gguf',modelId:values.get('--model-id')??'local-qwen25-3b-template-qualification',caseId:values.get('--case'),arm, repetitions,keepState:values.get('--keep-state')==='true'};}
const sha=(value:string)=>createHash('sha256').update(value).digest('hex');
const terminal=new Set(['SUCCEEDED','FAILED','DEGRADED','CANCELLED','MISSED','DISCONNECTED']);
async function execute(runtime:ReturnType<typeof buildJobRuntime>,parcelId:string){for(let turn=0;turn<20;turn++){await runtime.workParcels.tick();const parcel=runtime.workParcels.get(parcelId),stage=parcel.stages[0];if(stage?.runId){let run=runtime.ledger.get(stage.runId);for(const step of run?.steps.filter(value=>value.status==='WAITING_FOR_APPROVAL')??[]){const policy=step.approval;if(!policy?.startsWith('runtime-safety:'))throw Error(`unexpected_approval_required:${policy??'missing'}`);runtime.approve(run!.id,policy,'operator-authorized-template-qualification');run=runtime.ledger.get(stage.runId);}if(run&&!terminal.has(run.status))await runtime.tick();}const current=runtime.workParcels.get(parcelId);if(['SUCCEEDED','FAILED','CANCELLED'].includes(current.status))return current;}const parcel=runtime.workParcels.get(parcelId),run=parcel.stages[0]?.runId?runtime.ledger.get(parcel.stages[0]!.runId!):undefined;throw Error(`qualification_did_not_settle:${JSON.stringify({parcelId,status:parcel.status,stage:parcel.stages[0],run:run?{id:run.id,status:run.status,steps:run.steps.map(step=>({id:step.id,status:step.status,waitingReason:step.waitingReason,error:step.error})),errors:run.errors}:null})}`);}

async function main(){
  const cli=args(process.argv.slice(2));if(!fs.existsSync(path.join(cli.lab,'qualifications','native-execution','cases.json')))throw Error('lab_native_cases_missing');
  process.env.AGENT_CONTROL_LAB_DIR=cli.lab;process.env.AGENT_CONTROL_TEMPLATE_DIR=path.join(cli.lab,'agent-templates');
  const stateRoot=fs.mkdtempSync(path.join(os.tmpdir(),'agent-template-native-')),provider:ProviderConfig={id:'local-template-qualification',name:'Existing local OpenAI-compatible service',kind:'local',enabled:true,baseUrl:cli.baseUrl,wireApi:'chat-completions',auth:{type:'none'},requiresAuth:false,parallelism:1,costClass:'free',capabilities:['structured-output','text']},model:ModelConfig={id:cli.modelId,provider:provider.id,providerModel:cli.providerModel,enabled:true,routingEligible:true,capabilities:['structured-output','text'],nodes:['controller'],limits:{contextTokens:32768,outputTokens:2048},qualification:{state:'QUALIFIED',version:`operator-authorized-existing-backend:${sha(`${cli.baseUrl}\0${cli.providerModel}`).slice(0,16)}`,qualifiedAt:new Date().toISOString(),evidence:[`${cli.baseUrl}/models`],capabilities:['structured-output','text'],nodes:['controller']}},config:AgentControlConfig={...emptyConfig(),resources:[{id:'controller',name:'Qualification controller',platform:process.platform==='win32'?'windows':'linux',transport:{type:'local'},capabilities:['model.invoke','evidence.report'],controller:true}],providers:[provider],models:[model],jobs:{repositoryRoots:[path.resolve('.')]}},models=new ModelRegistry(config.providers,config.models,config.modelRouting),runtime=buildJobRuntime(config,stateRoot,path.join(stateRoot,'empty-jobs'),undefined,models),caseFile=JSON.parse(fs.readFileSync(path.join(cli.lab,'qualifications','native-execution','cases.json'),'utf8')) as {cases:Array<{id:string;job_id:string;scenario:string}>},selected=CASES.filter(item=>!cli.caseId||item.caseId===cli.caseId);
  if(!selected.length)throw Error(`qualification_case_missing:${cli.caseId}`);
  const runs:Array<Record<string,unknown>>=[];
  try{
    for(const item of selected){const acceptance=runtime.labJobs.case(`${item.job}@1.0.0`,item.caseId),job=runtime.labJobs.get(`${item.job}@1.0.0`),template=runtime.agentTemplates.get(`${item.template}@1.0.0`),readiness=runtime.agentTemplates.readiness(`${item.template}@1.0.0`,job.native,runtime.workers.list(),template.manifest.requirements.permissions);if(readiness.state!=='READY')throw Error(`template_not_ready:${item.template}:${readiness.reasons.join(',')}`);const sourceCase=caseFile.cases.find(candidate=>candidate.id===item.caseId);if(!sourceCase||sourceCase.scenario!==acceptance.scenario)throw Error(`case_identity_mismatch:${item.caseId}`);const repetitions=cli.repetitions??item.repetitions,arms=cli.arm==='both'?['plain','template'] as const:[cli.arm!] as const;
      for(let repetition=1;repetition<=repetitions;repetition++)for(const arm of arms){const selection=arm==='template'?{id:item.template,version:template.manifest.version,digest:template.manifest.content_digest,jobDigest:job.digest}:undefined,plan:WorkParcelPlan={objective:`Native qualification ${item.caseId} ${arm} repetition ${repetition}`,planner:{kind:'deterministic',reason:'Pinned Agent Template native qualification protocol'},stages:[{id:'execute',name:job.manifest.name,job:`${item.job}@${job.manifest.version}`,parameters:{scenario:acceptance.scenario,caseId:item.caseId,maximumOutputTokens:512,timeoutMs:120000},...(selection?{template:selection}:{}),requestedRoute:{model:cli.modelId,allowFallback:false,purpose:'QUALIFICATION',profile:'THIN',reason:'Same pinned local model and generation budget for both arms'}}]},requestKey=sha(`${item.caseId}\0${arm}\0${repetition}\0${randomUUID()}`),submitted=runtime.workParcels.submitNativePlan(plan.objective,'agent-template-qualification',requestKey,plan),started=Date.now(),parcel=await execute(runtime,submitted.id),stage=parcel.stages[0]!,run=runtime.ledger.get(stage.runId!)!,artifacts=runtime.artifacts.list(run.id),candidateMeta=artifacts.find(value=>value.name==='candidate-result'),verificationMeta=artifacts.find(value=>value.name==='verification-report'),candidate=candidateMeta?runtime.artifacts.read(candidateMeta.id):null,verification=verificationMeta?runtime.artifacts.read(verificationMeta.id):null,invocations=runtime.harnessEfficiency.list().filter(value=>value.runId===run.id);
        runs.push({caseId:item.caseId,job:{id:item.job,version:job.manifest.version,digest:job.digest,runtimeDigest:run.jobDigest},template:selection?{id:item.template,version:template.manifest.version,digest:template.manifest.content_digest}:null,input:{digest:run.inputsDigest,caseDigest:sha(JSON.stringify(acceptance))},model:{providerId:provider.id,modelId:cli.modelId,providerModel:cli.providerModel,baseUrl:cli.baseUrl,qualificationVersion:run.trigger.modelRoute?.qualificationVersion},runtime:{parcelId:parcel.id,runId:run.id,status:run.status,parcelStatus:parcel.status,sourceJobDigest:run.sourceJobDigest,elapsedMs:Date.now()-started},adaptation:null,arm,repetition,candidate,verification,artifacts:artifacts.map(value=>({id:value.id,name:value.name,sha256:value.sha256})),metrics:{inputTokens:parcel.telemetry.inputTokens??null,freshInputTokens:parcel.telemetry.freshInputTokens,cachedInputTokens:parcel.telemetry.cachedInputTokens,outputTokens:parcel.telemetry.outputTokens,totalTokens:parcel.telemetry.totalTokens,elapsedMs:parcel.telemetry.elapsedMs,providerReportedCost:parcel.audit.totals.providerReportedCost,cost:parcel.telemetry.cost,currency:parcel.telemetry.currency,invocations:invocations.map(value=>({id:value.id,outcome:value.outcome,verification:value.verification,inputTokens:value.usage.inputTokens,cachedInputTokens:value.usage.cachedInputTokens,outputTokens:value.usage.outputTokens,totalTokens:value.usage.totalTokens,elapsedMs:value.elapsedMs,providerReportedCost:value.cost.providerReportedCost,calculatedCost:value.cost.calculated,currency:value.cost.currency,harnessProfile:value.harnessProfile,recipeFingerprint:value.recipeFingerprint}))},errors:run.errors});
        process.stderr.write(`${item.caseId} ${arm} ${repetition}/${repetitions}: ${run.status}\n`);
      }
    }
    const report={schema:'agent-control.agent-template-native-qualification/v1',generatedAt:new Date().toISOString(),protocol:{answerKeysExcludedFromWorkerContext:true,sameModelToolsBudgetsAndGenerationSettings:true,sequence:'sequential',repetitions:'Primary cases use three repetitions per arm; clean and agreement controls use one per arm unless overridden.',limitations:['Small samples do not establish general model effectiveness.','One existing authorized local backend was tested.','Deterministic exact-fact acceptance is bounded to the declared cases.']},backend:{baseUrl:cli.baseUrl,providerModel:cli.providerModel,modelId:cli.modelId,downloaded:false,reconfigured:false,restarted:false},stateRoot:cli.keepState?stateRoot:null,runs};fs.mkdirSync(path.dirname(cli.output),{recursive:true});fs.writeFileSync(cli.output,`${JSON.stringify(report,null,2)}\n`,{mode:0o600});process.stdout.write(`${cli.output}\n`);
  }finally{if(!cli.keepState)fs.rmSync(stateRoot,{recursive:true,force:true});}
}
await main();
