import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';
import {JobCatalog} from '../src/control/job-catalog.js';
import {ActionRegistry,ArtifactStore,JobRuntime,ResourceLockManager,RunLedger,WorkerRegistry} from '../src/control/job-runtime.js';
import type {JobDefinition,ActionContext} from '../src/control/job-types.js';
import {LocalCodexNodeExecutionPort,ResourceCodexNodeExecutionPort,type CodexNodeExecutionPort} from '../src/control/codex-node-execution.js';
import {ModelRegistry} from '../src/control/model-registry.js';
import {OpenAICompatibleProviderClient,type ModelInvocationResult} from '../src/control/openai-compatible-provider.js';
import {MarkdownProjectMemoryPort,PROJECT_MEMORY_EXCHANGE_SCHEMA,projectMemoryExchangeFailures,renderProjectMemoryExchange,type MemoryCandidate,type ProjectMemoryExchange,type ProjectMemoryRecord} from '../src/control/project-memory.js';
import {PoeRuntime} from '../src/control/poe.js';
import {governedRequestOrigin} from '../src/control/request-origin.js';
import type {ModelConfig,ProviderAccountProfileConfig,ProviderConfig,ResourceConfig} from '../src/control/config.js';
import {WorkParcelCoordinator,WorkParcelStore,type WorkParcelPlan,type WorkParcelPlanStage} from '../src/control/work-parcels.js';
import {redactSensitiveText} from '../src/control/security-redaction.js';

type Usage={inputTokens:number|null;outputTokens:number|null;totalTokens:number|null;cachedInputTokens:number|null;cost:number|null;currency:string|null;authority:'authoritative'|'calculated'|'unavailable'};
type Route={id:string;label:string;provider:ProviderConfig;model:ModelConfig;nodeId:'hpubuntu'|'pixel-8-pro'|'windows-codex-node';runtime:string;endpoint:string;credentialResidency:string;adapter:string;availability:'AVAILABLE'|'BLOCKED';blocker?:string};
type WriterOutput=ProjectMemoryExchange;
type ReaderOutput=ProjectMemoryExchange&{contradictions:string[]};
type ModelCall={output:string;usage:Usage;elapsedMs:number;responseModel:string|null;finishReason:string|null;threadIdHash:string|null};
type AttemptEvidence={attempt:number;responseReceived:boolean;bytes:number;sha256:string|null;finishReason:string|null;responseModel:string|null;validJson:boolean;applicationSchemaValid:boolean;schemaFailures:string[];semanticFailures:string[];sanitizedOutput:string};
type PairState={id:string;writer:string;reader:string;writerCall?:ModelCall;writerOutput?:WriterOutput;writerAttempts:AttemptEvidence[];memory?:ProjectMemoryRecord;recall?:{accepted:string[];rejected:Array<{id:string;reason:string}>;bytesInjected:number;estimatedTokens:number;latencyMs:number};readerCall?:ModelCall;readerOutput?:ReaderOutput;readerAttempts:AttemptEvidence[];writerScore?:number;readerScore?:number;continuation?:'PASS'|'FAIL';failures:string[]};

const hash=(value:string|Buffer)=>createHash('sha256').update(value).digest('hex');
const now=()=>new Date().toISOString();
const root=path.resolve(process.env.AGENT_CONTROL_CROSS_MODEL_MEMORY_ROOT??'/fast/qualification/agent-control-4.5-cross-model-memory-20260911');
const memoryRoot=path.join(root,'vault','Agent Control','4.5-cross-model-memory');
const stateRoot=path.join(root,'runtime');
const reportFile=path.join(root,'cross-model-memory-qualification.json');
const transcriptFile=path.join(root,'cross-model-memory-transcript.md');
const pixelUrl=process.env.AGENT_CONTROL_PIXEL_MODEL_URL??'http://100.100.97.118:19084/v1';
const openRouterCredentialFile=process.env.OPENROUTER_API_KEY_FILE;
const controllerCodexHome=process.env.CODEX_HOME;
const msiHost=process.env.AGENT_CONTROL_WINDOWS_QUALIFICATION_HOST,msiIdentityFile=process.env.AGENT_CONTROL_WINDOWS_QUALIFICATION_IDENTITY_FILE;
const msiConfigured=Boolean(msiHost&&msiIdentityFile);
const requestedWindowsTimeout=Number(process.env.AGENT_CONTROL_WINDOWS_CODEX_TIMEOUT_MS??600_000);
const windowsCodexTimeoutMs=Number.isFinite(requestedWindowsTimeout)?Math.max(30_000,Math.min(600_000,requestedWindowsTimeout)):600_000;

const startedAt=now(),implementationCommit=git(['rev-parse','HEAD']);
const evidencePacket={
  schema:'agent-control.cross-model-memory-evidence/v1',
  project:'Agent Control',
  task:'Agent Control 4.5 physical cross-model memory qualification',
  objective:'Agent Control 4.5 cross-model cold memory reconstruction without the writer transcript.',
  completedWork:'ProjectMemoryPort is implemented; hpubuntu to MSI transfer into D:/obsidian/knowledge_vault is physically proven.',
  decision:'Use node-local vaults with governed content-hash synchronization.',
  rejectedApproach:'Reject one concurrently edited canonical note because of split-brain and write-conflict risk.',
  currentState:`Candidate ${implementationCommit} is on public main; stable baseline v4.4.0; v4.5.0 is not tagged or released.`,
  outstandingWork:'Complete the writer-to-cold-reader matrix and verify every continuation.',
  evidence:'Checkpoint 565aff41c1afc07995163ed4ec1d490d628970bf; topology SHA-256 f897f4f6c3dbb8e6434775a2df4f8e0a74425cf266d5e45d33b65b7acd9edc2.',
  nextSafeAction:'EXECUTE_MEMORY_INTEGRITY_CHECK',
  authority:'Repository and physical qualification evidence override remembered claims.',
};
const packetText=JSON.stringify(evidencePacket,null,2),packetSha256=hash(packetText);
const requiredMemory=['Agent Control 4.5','cross-model',implementationCommit,'565aff41c1afc07995163ed4ec1d490d628970bf','v4.4.0','D:/obsidian/knowledge_vault','node-local','content-hash','concurrently edited','f897f4f6c3dbb8e6434775a2df4f8e0a74425cf266d5e45d33b65b7acd9edc2','EXECUTE_MEMORY_INTEGRITY_CHECK'];

const account:ProviderAccountProfileConfig={id:'controller-codex',label:'Controller Codex',providerExecutionNodeId:'hpubuntu',credentialResidency:{nodeId:'hpubuntu',store:{type:'codex-home-env',env:'CODEX_HOME'}},enabled:true,plan:'ChatGPT authenticated',planAuthority:'operator-configured',capabilities:['structured-output'],qualification:{state:'QUALIFIED',version:'physical-20260911',checkedAt:startedAt,qualifiedAt:startedAt,capabilities:['structured-output'],evidence:['bounded-codex-sol-probe']}};
const msiAccounts=[msiAccount('cottage-plus','Cottage Plus','CODEX_HOME_COTTAGE_PLUS'),msiAccount('lawrence-pro','Lawrence Pro','CODEX_HOME_LAWRENCE_PRO')];
const codexProvider:ProviderConfig={id:'codex-chatgpt',name:'Codex CLI with ChatGPT authentication',kind:'cli',enabled:true,capabilities:['structured-output'],accountProfiles:[account,...msiAccounts]};
const routes:Route[]=[
  httpRoute('qwen-hpubuntu','Qwen on hpubuntu','local-qwen','qwen2.5-3b-instruct-q4_k_m.gguf','hpubuntu','http://127.0.0.1:8080/v1','llama.cpp OpenAI-compatible adapter'),
  httpRoute('glm-5.3-flash','GLM-5.3-Flash','openrouter','z-ai/glm-5.3-flash','hpubuntu','https://openrouter.ai/api/v1','OpenAI-compatible Responses adapter',{type:'bearer-file-env',env:'OPENROUTER_API_KEY_FILE'}),
  codexRoute('codex-luna','Codex CLI / Luna','gpt-5.6-luna'),
  codexRoute('gpt-5.6-sol','GPT-5.6 Sol','gpt-5.6-sol'),
  httpRoute('pixel-gemma-e4b','Google Gemma 4 E4B on Pixel 8 Pro','pixel-llama','google/gemma-4-E4B-it','pixel-8-pro',pixelUrl,'llama.cpp OpenAI-compatible adapter'),
];
if(msiConfigured){routes.push(remoteCodexRoute('msi-cottage-luna','MSI Codex / Cottage Plus / Luna','cottage-plus','gpt-5.6-luna'));routes.push(remoteCodexRoute('msi-lawrence-sol','MSI Codex / Lawrence Pro / Sol','lawrence-pro','gpt-5.6-sol'));}
const routeMap=new Map(routes.map(route=>[route.id,route]));
const allPairs=[
  pair('glm-to-qwen','glm-5.3-flash','qwen-hpubuntu'),pair('qwen-to-glm','qwen-hpubuntu','glm-5.3-flash'),
  pair('codex-to-qwen','codex-luna','qwen-hpubuntu'),pair('qwen-to-codex','qwen-hpubuntu','codex-luna'),
  pair('sol-to-glm','gpt-5.6-sol','glm-5.3-flash'),pair('glm-to-sol','glm-5.3-flash','gpt-5.6-sol'),
  pair('codex-to-sol','codex-luna','gpt-5.6-sol'),pair('sol-to-codex','gpt-5.6-sol','codex-luna'),
  pair('pixel-to-hpubuntu','pixel-gemma-e4b','qwen-hpubuntu'),pair('hpubuntu-to-pixel','qwen-hpubuntu','pixel-gemma-e4b'),
  pair('gemma-e4b-to-local','pixel-gemma-e4b','qwen-hpubuntu'),pair('local-to-gemma-e4b','qwen-hpubuntu','pixel-gemma-e4b'),
  ...(msiConfigured?[pair('msi-cottage-to-lawrence','msi-cottage-luna','msi-lawrence-sol'),pair('msi-lawrence-to-cottage','msi-lawrence-sol','msi-cottage-luna')]:[]),
];
const pairFilter=new Set((process.env.AGENT_CONTROL_MEMORY_PAIR_FILTER??'').split(',').filter(Boolean));
const poeFlow=process.env.AGENT_CONTROL_MEMORY_POE_FLOW==='1';
const pairs=pairFilter.size?allPairs.filter(value=>pairFilter.has(value.id)):allPairs;
if(!pairs.length)throw new Error('qualification_pair_filter_empty');
if(pairs.some(value=>value.writer==='glm-5.3-flash'||value.reader==='glm-5.3-flash')&&!openRouterCredentialFile)throw new Error('openrouter_credential_file_reference_required');
if(pairs.some(value=>['codex-luna','gpt-5.6-sol'].includes(value.writer)||['codex-luna','gpt-5.6-sol'].includes(value.reader))&&!controllerCodexHome)throw new Error('controller_codex_home_reference_required');
const pairStates=new Map(pairs.map(value=>[value.id,{...value,writerAttempts:[],readerAttempts:[],failures:[]} satisfies PairState]));
const memory=new MarkdownProjectMemoryPort(memoryRoot,'structured-markdown-vault');
const providers=routes.map(route=>route.provider).filter((provider,index,all)=>all.findIndex(item=>item.id===provider.id)===index);
const models=routes.map(route=>route.model);
const registry=new ModelRegistry(providers,models,{roles:{}},undefined,undefined,process.env);
const localCodexPort=new LocalCodexNodeExecutionPort(process.env,process.env.CODEX_COMMAND??'codex');
const remoteResource:ResourceConfig|undefined=msiConfigured?{id:'windows-codex-node',name:'MSI Windows Codex node',platform:'windows',capabilities:['harness.codex'],transport:{type:'ssh',host:msiHost!,port:Number(process.env.AGENT_CONTROL_WINDOWS_QUALIFICATION_PORT??22),user:process.env.AGENT_CONTROL_WINDOWS_QUALIFICATION_USER,identityFile:msiIdentityFile}}:undefined;
const remoteCodexPort:CodexNodeExecutionPort|undefined=remoteResource?new ResourceCodexNodeExecutionPort([remoteResource]):undefined;
let artifacts:ArtifactStore;

const writerSchema=PROJECT_MEMORY_EXCHANGE_SCHEMA;
const readerSchema={...PROJECT_MEMORY_EXCHANGE_SCHEMA,properties:{...PROJECT_MEMORY_EXCHANGE_SCHEMA.properties,contradictions:{type:'array',items:{type:'string'}}},required:[...PROJECT_MEMORY_EXCHANGE_SCHEMA.required,'contradictions']};

async function invoke(route:Route,instruction:string,schema:Record<string,unknown>,signal:AbortSignal):Promise<ModelCall>{
  if(route.provider.kind==='cli'){
    const selectedAccount=route.provider.accountProfiles?.find(candidate=>candidate.id===route.model.accountProfile);if(!selectedAccount)throw new Error('codex_account_profile_missing');
    const port=route.nodeId==='windows-codex-node'?remoteCodexPort:localCodexPort;if(!port)throw new Error('codex_remote_node_unconfigured');
    const result=await port.execReadOnlyStructured({provider:route.provider,account:selectedAccount,nodeId:route.nodeId,model:route.model,instruction,outputSchema:schema,maximumOutputTokens:900,timeoutMs:route.nodeId==='windows-codex-node'?windowsCodexTimeoutMs:240_000,signal});
    return{output:result.finalMessage,usage:codexUsage(result.usage),elapsedMs:extractNumber(result.usage,'elapsed_ms')??0,responseModel:route.model.providerModel,finishReason:'completed',threadIdHash:result.threadId?hash(result.threadId):null};
  }
  const maximumOutputTokens=route.id==='glm-5.3-flash'?4096:route.nodeId==='pixel-8-pro'?512:900;
  const requestExtension=route.id==='glm-5.3-flash'?{profile:'glm-minimal-reasoning',body:{reasoning:{effort:'minimal'}}}:undefined;
  const result=await new OpenAICompatibleProviderClient(route.provider,undefined,undefined,{nodeId:route.nodeId}).invoke(route.model,instruction,{structured:true,outputSchema:schema,maximumOutputTokens,timeoutMs:route.nodeId==='pixel-8-pro'?600_000:90_000,signal,...(requestExtension?{requestExtension}:{})});
  return invocation(result);
}

const actions=new ActionRegistry();
actions.registerReadOnly('qualification.cross-memory-writer@1.0.0',async context=>{
  const state=stateFor(context),route=routeFor(context);
  const prompt=`You are the memory WRITER in a governed Agent Control Work Parcel. Compress only the authoritative packet into the canonical JSON semantic sections. Do not duplicate a free-form summary. Preserve every exact marker in its matching field. objective: task and purpose; completedWork: proven nodes and exact vault; decisions: node-local namespace and content-hash synchronization; rejectedApproaches: concurrently edited canonical note plus split-brain/write-conflict risk; currentState: exact checkpoint, v4.4.0 baseline and unreleased state; outstandingWork: writer-to-cold-reader matrix; supportingEvidence: exact evidence SHA-256; nextAction: EXECUTE_MEMORY_INTEGRITY_CHECK; authority: evidence overrides memory. Return one complete JSON object only.${route.nodeId==='pixel-8-pro'?' Use one concise sentence per field and at most 480 output tokens.':''}\n\nAUTHORITATIVE EVIDENCE PACKET (sha256:${packetSha256})\n${packetText}`;
  let call=await invoke(route,prompt,writerSchema,context.signal),parsed=parseAttempt<WriterOutput>(call.output,projectMemoryExchangeFailures),output=parsed.value,failures=output?memoryFailures(output):parsed.failures;
  state.writerAttempts.push(attemptEvidence(1,call,parsed,output?failures:[]));
  if(failures.length){const repaired=await invoke(route,`${prompt}\n\nYour first independent attempt failed validation: ${failures.join('; ')}. Return one corrected complete JSON object with every fact in its named field.`,writerSchema,context.signal),repairedParsed=parseAttempt<WriterOutput>(repaired.output,projectMemoryExchangeFailures);call=combineCalls(call,repaired);output=repairedParsed.value;failures=output?memoryFailures(output):repairedParsed.failures;state.writerAttempts.push(attemptEvidence(2,repaired,repairedParsed,output?failures:[]));}
  state.writerCall=call;if(!output||failures.length)throw new Error(`writer_verification_failed:${failures.join('|')}`);
  state.writerCall=call;state.writerOutput=output;state.writerScore=scoreWriter(output);
  return{artifacts:[{name:'writer-memory',value:{pairId:state.id,route:identity(route),packetSha256,output,call},type:'agent-control-memory-writer',schema:'agent-control.memory-writer/v1',version:'1'}],evidence:[`writer:${identityText(route)}:sha256:${hash(call.output)}`],verification:['writer-output-verified'],detail:`${route.label} produced verified bounded memory`};
});
actions.registerConsequentialControl('qualification.cross-memory-persist@1.0.0',async context=>{
  const state=stateFor(context),writer=readBatonArtifact<{output:WriterOutput;route:{providerId:string;modelId:string;nodeId:string}}>(context,'writer-memory');
  const candidate:MemoryCandidate={id:`memory-${state.id}`,kind:'WORK_PARCEL_OUTCOME',title:`Cross-model memory ${state.id}`,content:renderWriterMemory(writer.output),factKey:`agent-control.4.5.cross-model.${state.id}`,projectId:'agent-control',repositoryId:'agent-control',sessionId:`writer-${state.id}`,originatingNodeId:writer.route.nodeId,originatingRoute:writer.route,source:'EXPERIMENT',confidence:.98,verification:'VERIFIED',provenance:[{id:`evidence-packet:${packetSha256}`,sha256:packetSha256,authority:'AUTHORITATIVE'}],supersedes:[]};
  state.memory=await memory.remember(candidate);
  return{artifacts:[{name:'governed-memory',value:{pairId:state.id,memoryId:state.memory.id,contentSha256:state.memory.contentSha256,provenance:state.memory.provenance},type:'agent-control-project-memory',schema:state.memory.schema,version:'1'}],evidence:[`memory:${state.memory.id}:sha256:${state.memory.contentSha256}`],verification:['memory-write-verified'],detail:'Verified writer output persisted atomically through ProjectMemoryPort'};
},['LOCAL_WRITE']);
actions.registerReadOnly('qualification.cross-memory-reader@1.0.0',async context=>{
  const state=stateFor(context),route=routeFor(context),recall=await memory.recall({projectId:'agent-control',repositoryId:'agent-control',sessionId:`writer-${state.id}`,query:'Agent Control 4.5 cross-model checkpoint node-local vault rejected concurrent canonical note evidence next safe action',limit:2,maximumBytes:8192});
  state.recall={accepted:recall.accepted.map(item=>item.memory.id),rejected:recall.rejected,bytesInjected:recall.bytesInjected,estimatedTokens:recall.estimatedTokens,latencyMs:recall.latencyMs};
  const supplied=recall.accepted.map(item=>`[ADVISORY GOVERNED MEMORY ${item.memory.id} sha256:${item.memory.contentSha256}]\n${item.memory.content}`).join('\n\n');
  assert.ok(supplied,'reader_memory_missing');
  const prompt=`You are a COLD memory READER in a NEW stateless execution. You have no writer transcript or prior provider context. Reconstruct the canonical semantic sections from bounded advisory memory only. Keep every fact in its matching field and list genuine contradictions; use an empty contradictions array when none exist. Return one complete JSON object only.${route.nodeId==='pixel-8-pro'?' Use one concise sentence per field and at most 480 output tokens.':''}\n\nProject: Agent Control\nTask: 4.5 cross-model memory qualification\n\n${supplied}`;
  let call=await invoke(route,prompt,readerSchema,context.signal),parsed=parseAttempt<ReaderOutput>(call.output,readerShapeFailures),output=parsed.value,failures=output?readerFailures(output):parsed.failures;
  state.readerAttempts.push(attemptEvidence(1,call,parsed,output?failures:[]));
  if(failures.length){const repaired=await invoke(route,`${prompt}\n\nYour first cold reconstruction failed validation: ${failures.join('; ')}. Return one corrected complete JSON object with every fact in its named field.`,readerSchema,context.signal),repairedParsed=parseAttempt<ReaderOutput>(repaired.output,readerShapeFailures);call=combineCalls(call,repaired);output=repairedParsed.value;failures=output?readerFailures(output):repairedParsed.failures;state.readerAttempts.push(attemptEvidence(2,repaired,repairedParsed,output?failures:[]));}
  state.readerCall=call;if(output){state.readerOutput=output;state.readerScore=scoreReader(output);}state.failures.push(...failures);
  if(!output||failures.length)throw new Error(`reader_verification_failed:${failures.join('|')}`);
  return{artifacts:[{name:'reader-reconstruction',value:{pairId:state.id,route:identity(route),coldExecution:true,originatingTranscriptSupplied:false,recall:state.recall,output,call},type:'agent-control-memory-reader',schema:'agent-control.memory-reader/v1',version:'1'}],evidence:[`reader:${identityText(route)}:sha256:${hash(call.output)}`],verification:['reader-reconstruction-verified'],detail:`${route.label} reconstructed the project cold from governed memory only`};
});
actions.registerReadOnly('qualification.cross-memory-continuation@1.0.0',async context=>{
  const state=stateFor(context),reader=readBatonArtifact<{output:ReaderOutput}>(context,'reader-reconstruction'),stored=memory.read(`memory-${state.id}`);
  const next=reader.output.nextAction.toLowerCase(),passed=next.includes('integrity')&&allText(reader.output).includes('f897f4f6c3dbb8e6434775a2df4f8e0a74425cf266d5e45d33b65b7acd9edc2')&&stored.contentSha256===hash(stored.content)&&stored.provenance.some(item=>item.sha256===packetSha256);
  state.continuation=passed?'PASS':'FAIL';if(!passed)throw new Error('continuation_integrity_verification_failed');
  return{artifacts:[{name:'continuation-result',value:{pairId:state.id,operation:evidencePacket.nextSafeAction,memoryId:stored.id,contentSha256:stored.contentSha256,provenanceSha256:packetSha256,result:'PASS'},type:'agent-control-memory-continuation',schema:'agent-control.memory-continuation/v1',version:'1'}],evidence:[`continuation:${state.id}:PASS`],verification:['continuation-verified'],detail:'Reader-selected next governed Work Parcel action completed and independently verified memory integrity'};
});

async function main(){
  fs.mkdirSync(root,{recursive:true,mode:0o700});fs.rmSync(stateRoot,{recursive:true,force:true});fs.rmSync(memoryRoot,{recursive:true,force:true});
  artifacts=new ArtifactStore(path.join(stateRoot,'artifacts'));
  const workers=new WorkerRegistry().register({id:'hpubuntu',capabilities:['route.hpubuntu','memory.control'],health:'healthy',capacity:1,active:0,observedAt:startedAt}).register({id:'pixel-8-pro',capabilities:['route.pixel-8-pro'],health:'healthy',capacity:1,active:0,observedAt:startedAt});
  if(msiConfigured)workers.register({id:'windows-codex-node',capabilities:['route.windows-codex-node'],health:'healthy',capacity:1,active:0,observedAt:startedAt});
  const catalog=new JobCatalog(actions.ids());
  for(const route of routes){const timeout=route.nodeId==='pixel-8-pro'?660:route.nodeId==='windows-codex-node'?720:300;catalog.addJob(modelJob(`cross-memory-writer-${route.id}`,`Memory writer · ${route.label}`,'qualification.cross-memory-writer@1.0.0',`route.${route.nodeId}`,timeout));catalog.addJob(modelJob(`cross-memory-reader-${route.id}`,`Cold memory reader · ${route.label}`,'qualification.cross-memory-reader@1.0.0',`route.${route.nodeId}`,timeout));}
  catalog.addJob(controlJob('cross-memory-persist','Persist governed memory','qualification.cross-memory-persist@1.0.0'));
  catalog.addJob(controlJob('cross-memory-continuation','Execute reader-selected integrity check','qualification.cross-memory-continuation@1.0.0'));
  const runtime=new JobRuntime(catalog,actions,workers,new RunLedger(path.join(stateRoot,'runs.json')),artifacts,new ResourceLockManager(path.join(stateRoot,'locks.json')));
  const plans=new Map(pairs.map(value=>[value.id,planFor(value)]));
  const store=new WorkParcelStore(path.join(stateRoot,'work-parcels.json')),coordinator=new WorkParcelCoordinator(runtime,store,{plan:async prompt=>{const id=pairs.find(value=>prompt.includes(`pair ${value.id}`))?.id,plan=id?plans.get(id):undefined;if(!plan)throw new Error('qualification_pair_plan_missing');return plan;}},undefined,registry),parcels=[];
  const poe=poeFlow?new PoeRuntime({file:path.join(stateRoot,'poe.json'),evidence:{overview:()=>({title:'Agent Control 4.5 memory qualification',summary:'The operator may submit an exact cross-model memory qualification through the governed Work Parcel runtime.',facts:[{label:'Qualification mode',value:'physical cross-model writer to cold reader',authority:'AGENT_CONTROL',evidence:['qualification:4.5:cross-model-memory']}],related:[]}),resolve:()=>({title:'Qualification Work Parcel',summary:'The exact Work Parcel is retained in Agent Control durable evidence.',facts:[],related:[]})},benchmark:{submit:input=>{const origin=governedRequestOrigin({channel:'poe/dashboard',modality:'dashboard',receivedAt:new Date().toISOString(),authentication:'dashboard-bearer',actorId:input.actor,authority:[`conversation:${input.proposal.conversationId}`,`proposal:${input.proposal.id}`],messageReference:input.requestKey,identityReference:hash(input.actor),request:input.proposal.objective});const parcel=coordinator.submitApprovedPlan(input.proposal.objective,input.actor,input.requestKey,input.plan,origin);return{parcelId:parcel.id};}}}):undefined;
  const conversation=poe?.createConversation({actorId:'operator',channel:'dashboard'});if(conversation)poe!.greeting(conversation.id,'operator');
  const deadline=Date.now()+90*60_000;
  for(const value of pairs){const prompt=`POE, run the Agent Control 4.5 physical cross-model Your Memories pair ${value.id}. Have the writer persist governed project memory, start the different reader cold without its transcript, reconstruct the work, execute the exact next action, and independently verify it.`;let parcel;if(poe&&conversation){await poe.ask({conversationId:conversation.id,text:prompt,contentTrust:'OPERATOR_REQUEST'});const plan=plans.get(value.id)!,writer=routeMap.get(value.writer)!,reader=routeMap.get(value.reader)!,condition=(route:Route)=>({route:identity(route),tools:[],contextPolicy:'Cold reader receives project/task identity and bounded ProjectMemoryPort recall only.',fixtureSha256:packetSha256,softwareVersion:implementationCommit,hardwareClass:route.nodeId,quantization:null,cacheState:'COLD' as const,providerEndpoint:'governed-provider-adapter',authority:'physical qualification configuration',timeLimitMs:660_000});const draft=poe.proposeBenchmark(conversation.id,{decision:`Run cross-model memory pair ${value.id}`,objective:plan.objective,whyNewEvidenceIsNeeded:'Physical evidence is required that a new provider context can reconstruct and continue from provider-neutral governed memory.',conditions:[condition(writer),condition(reader)],stages:plan.stages,metrics:[{id:`criterion-${value.id}`,label:'Cold continuation',kind:'OBJECTIVE',successCriterion:'Reader reconstruction and exact next action pass independent verification.',stageId:`${value.id}-continue`}],repetitions:1,constraints:plan.constraints});const frozen=poe.freezeBenchmark(draft.id,draft.revision),approved=poe.approveBenchmark(frozen.id,{revision:frozen.revision,frozenSha256:frozen.frozenSha256!,actor:'operator'});parcel=coordinator.get(approved.execution!.parcelId);}else parcel=await coordinator.submit(prompt,'operator');parcels.push(parcel);const inFlight=new Set<Promise<unknown>>();while(Date.now()<deadline){await coordinator.tick();for(;;){const dispatch=runtime.dispatch();if(!dispatch)break;const completion=dispatch.completion.finally(()=>inFlight.delete(completion));inFlight.add(completion);}const current=coordinator.get(parcel.id);if(['SUCCEEDED','FAILED','CANCELLED'].includes(current.status)&&!inFlight.size)break;await new Promise(resolve=>setTimeout(resolve,50));}}
  const finals=new Map(parcels.map(parcel=>{const final=coordinator.get(parcel.id);return[String(final.stages[0]?.parameters?.pairId??''),final] as const;})),matrix=[...pairStates.values()].map(value=>matrixRow(value,finals.get(value.id)!));
  const usage=aggregate(matrix.map(row=>row.usage));
  const workParcels=[...finals.values()].map(final=>({id:final.id,status:final.status,stages:final.stages.map(stage=>({id:stage.id,status:stage.status,runId:stage.runId??null,batonSha256:stage.baton?.sha256??null,actualRoute:stage.actualRoute??null,error:stage.error??null}))}));
  const report={schema:'agent-control.cross-model-memory-qualification/v1',startedAt,completedAt:now(),implementationCommit,packetSha256,verdict:workParcels.every(parcel=>parcel.status==='SUCCEEDED')&&matrix.every(row=>row.result==='PASS')?'PASS_PHYSICAL_CROSS_MODEL_MEMORY':'PARTIAL',workParcels,routes:routes.map(route=>inventory(route)),blockedRoutes:msiConfigured?[]:[{id:'msi-cottage-plus',nodeId:'windows-codex-node',provider:'codex-chatgpt',model:'unavailable',status:'BLOCKED',reason:'MSI qualification resource not configured'},{id:'msi-lawrence-pro',nodeId:'windows-codex-node',provider:'codex-chatgpt',model:'unavailable',status:'BLOCKED',reason:'MSI qualification resource not configured'}],matrix,totals:usage,projectMemory:{backend:'structured Markdown directory viewed by Obsidian',namespace:memoryRoot,records:matrix.filter(row=>row.memoryId).length,commonSchema:'agent-control.project-memory/v1'},poe:poe&&conversation?{conversation:poe.conversation(conversation.id),transcript:poe.transcript(conversation.id),productionFlow:true}:null,pisper:{decision:'DEFER',reason:'Governed Turn Snapshot Branching is a useful immutable provenance primitive but is not required for stateless writer-to-reader qualification and would broaden 4.5 scope.'},limitations:['ChatGPT product-level personal memory is not exposed as a controllable Codex CLI input, so no claim is made for proprietary assistant-memory injection.','The requested Google/Gemini E4B route is physically the exact Google Gemma 4 E4B local artifact; Gemini was not silently substituted.'],security:{writerTranscriptSuppliedToReader:false,credentialValuesPersisted:false,providerOutputStoredAsSanitizedStructuredArtifacts:true}};
  writeJson(reportFile,report);fs.writeFileSync(transcriptFile,renderTranscript(report),{mode:0o600});
  process.stdout.write(`${JSON.stringify({reportFile,transcriptFile,verdict:report.verdict,parcelIds:workParcels.map(parcel=>parcel.id),passed:matrix.filter(row=>row.result==='PASS').length,total:matrix.length,totals:usage},null,2)}\n`);
  if(report.verdict!=='PASS_PHYSICAL_CROSS_MODEL_MEMORY')process.exitCode=2;
}

function httpRoute(id:string,label:string,providerId:string,providerModel:string,nodeId:Route['nodeId'],baseUrl:string,adapter:string,auth:ProviderConfig['auth']={type:'none'}):Route{const provider:ProviderConfig={id:providerId,name:label,kind:'openai-compatible',baseUrl,wireApi:providerId==='openrouter'?'responses':'chat-completions',auth,enabled:true,capabilities:['structured-output']};const model:ModelConfig={id,provider:providerId,providerModel,enabled:true,capabilities:['structured-output'],nodes:[nodeId],limits:{contextTokens:nodeId==='pixel-8-pro'?2048:32768,outputTokens:providerId==='openrouter'?4096:900},qualification:{state:'QUALIFIED',version:'physical-20260911',qualifiedAt:startedAt,capabilities:['structured-output'],nodes:[nodeId],evidence:['bounded-live-provider-probe']}};return{id,label,provider,model,nodeId,runtime:providerId==='openrouter'?'OpenRouter hosted runtime':'llama.cpp',endpoint:baseUrl,credentialResidency:providerId==='openrouter'?'hpubuntu owner-only file reference; value resolved only by adapter':'not required',adapter,availability:'AVAILABLE'};}
function codexRoute(id:string,label:string,providerModel:string):Route{const model:ModelConfig={id,provider:codexProvider.id,accountProfile:account.id,providerModel,enabled:true,capabilities:['structured-output'],nodes:['hpubuntu'],limits:{contextTokens:272000,outputTokens:900},qualification:{state:'QUALIFIED',version:'physical-20260911',qualifiedAt:startedAt,capabilities:['structured-output'],nodes:['hpubuntu'],evidence:['bounded-live-codex-probe']}};return{id,label,provider:codexProvider,model,nodeId:'hpubuntu',runtime:'Codex CLI',endpoint:'local executable discovered from PATH',credentialResidency:'opaque CODEX_HOME environment reference on hpubuntu',adapter:'LocalCodexNodeExecutionPort',availability:'AVAILABLE'};}
function msiAccount(id:string,label:string,environment:string):ProviderAccountProfileConfig{return{id,label,providerExecutionNodeId:'windows-codex-node',credentialResidency:{nodeId:'windows-codex-node',store:{type:'codex-home-env',env:environment}},enabled:true,plan:'ChatGPT authenticated',planAuthority:'operator-configured',capabilities:['structured-output'],qualification:{state:'QUALIFIED',version:'physical-20260912',checkedAt:startedAt,qualifiedAt:startedAt,capabilities:['structured-output'],evidence:['production-accountStatus']}};}
function remoteCodexRoute(id:string,label:string,accountProfile:string,providerModel:string):Route{const model:ModelConfig={id,provider:codexProvider.id,accountProfile,providerModel,enabled:true,capabilities:['structured-output'],nodes:['windows-codex-node'],limits:{contextTokens:272000,outputTokens:900},qualification:{state:'QUALIFIED',version:'physical-20260912',qualifiedAt:startedAt,capabilities:['structured-output'],nodes:['windows-codex-node'],evidence:['production-accountStatus']}};return{id,label,provider:codexProvider,model,nodeId:'windows-codex-node',runtime:'Codex Desktop bundled CLI',endpoint:'MSI executable discovered by governed node adapter',credentialResidency:`opaque ${codexProvider.accountProfiles?.find(value=>value.id===accountProfile)?.credentialResidency?.store.type??'codex-home-env'} reference resolved only on MSI`,adapter:'ResourceCodexNodeExecutionPort',availability:'AVAILABLE'};}
function pair(id:string,writer:string,reader:string){return{id,writer,reader};}
function identity(route:Route){return{providerId:route.provider.id,...(route.model.accountProfile?{accountProfileId:route.model.accountProfile}:{}),modelId:route.model.id,nodeId:route.nodeId};}
function identityText(route:Route){return`${route.provider.id}/${route.model.accountProfile??'default'}/${route.model.id}@${route.nodeId}`;}
function routeFor(context:ActionContext){const id=context.run.trigger.modelRoute?.modelId,route=id?routeMap.get(id):undefined;if(!route)throw new Error('physical_route_missing');return route;}
function stateFor(context:ActionContext){const id=String(context.parameters.pairId??''),state=pairStates.get(id);if(!state)throw new Error('qualification_pair_missing');return state;}
function readBatonArtifact<T>(context:ActionContext,name:string):T{const ids=context.run.trigger.parcelContext?.baton?.artifactIds??[];for(const id of ids){const value=artifacts.read(id) as Record<string,unknown>;const record=artifacts.get(id);if(record?.name===name)return value as T;}throw new Error(`baton_artifact_missing:${name}`);}
function parseAttempt<T>(value:string,shape:(value:unknown)=>string[]){let parsed:unknown;try{parsed=JSON.parse(value);}catch{const match=value.match(/\{[\s\S]*\}/);if(!match)return{value:undefined,validJson:false,failures:['provider_json_missing']};try{parsed=JSON.parse(match[0]);}catch{return{value:undefined,validJson:false,failures:['provider_json_invalid']};}}const failures=shape(parsed);return{value:failures.length?undefined:parsed as T,validJson:true,failures};}
function attemptEvidence<T>(attempt:number,call:ModelCall,parsed:{value:T|undefined;validJson:boolean;failures:string[]},semanticFailures:string[]):AttemptEvidence{return{attempt,responseReceived:call.output.length>0,bytes:Buffer.byteLength(call.output),sha256:call.output?hash(call.output):null,finishReason:call.finishReason,responseModel:call.responseModel,validJson:parsed.validJson,applicationSchemaValid:parsed.validJson&&parsed.failures.length===0,schemaFailures:parsed.failures,semanticFailures,sanitizedOutput:redactSensitiveText(call.output).slice(0,16_384)};}
function readerShapeFailures(value:unknown){const failures=projectMemoryExchangeFailures(value);if(record(value)&&(!Array.isArray(value.contradictions)||!value.contradictions.every(item=>typeof item==='string')))failures.push('application_schema:contradictions:type');return failures.filter(item=>item!=='application_schema:contradictions:additional_property');}
function record(value:unknown):value is Record<string,unknown>{return Boolean(value&&typeof value==='object'&&!Array.isArray(value));}
function allText(value:unknown){return JSON.stringify(value);}
function semanticFailures(output:ProjectMemoryExchange){const checks:Array<[keyof ProjectMemoryExchange,string[]]>= [['completedWork',['hpubuntu','MSI','D:/obsidian/knowledge_vault']],['decisions',['node-local','content-hash']],['rejectedApproaches',['concurrently edited','canonical note']],['currentState',[implementationCommit,'v4.4.0']],['outstandingWork',['writer-to-cold-reader','matrix']],['supportingEvidence',['565aff41c1afc07995163ed4ec1d490d628970bf','f897f4f6c3dbb8e6434775a2df4f8e0a74425cf266d5e45d33b65b7acd9edc2']],['nextAction',['integrity']]],failures=checks.flatMap(([field,terms])=>terms.filter(term=>!output[field].toLowerCase().includes(term.toLowerCase())).map(term=>`${field}:missing:${term}`));if(!/(cross[- ]model|different model|between models)/i.test(output.objective))failures.push('objective:semantic:cross_model_missing');if(!/(proven|verified|transferred)/i.test(output.completedWork))failures.push('completedWork:semantic:proof_missing');if(!/(sync|synchron)/i.test(output.decisions))failures.push('decisions:semantic:synchronization_missing');if(!/(split-brain|write-conflict|conflict)/i.test(output.rejectedApproaches))failures.push('rejectedApproaches:semantic:risk_missing');if(!/(not merged|not released|unreleased|experimental|candidate|not tagged)/i.test(output.currentState))failures.push('currentState:semantic:release_state_missing');if(output.nextAction.trim().toUpperCase()!=='EXECUTE_MEMORY_INTEGRITY_CHECK')failures.push('nextAction:semantic:exact_operation_required');if(!/(override|authoritative|authority)/i.test(output.authority))failures.push('authority:semantic:evidence_precedence_missing');return failures;}
function memoryFailures(output:WriterOutput){const rendered=renderProjectMemoryExchange(output);return[...semanticFailures(output),...(rendered.length<180?['memory-too-short']:[]),...(rendered.length>2400?['memory-too-long']:[])];}
function readerFailures(output:ReaderOutput){return semanticFailures(output);}
function scoreWriter(output:WriterOutput){const retained=requiredMemory.filter(term=>allText(output).toLowerCase().includes(term.toLowerCase())).length/requiredMemory.length,compression=Math.min(1,packetText.length/Math.max(renderProjectMemoryExchange(output).length,1)),structure=projectMemoryExchangeFailures(output).length?0:1;return round((retained*.65+compression*.15+structure*.2)*100);}
function scoreReader(output:ReaderOutput){const failures=readerFailures(output),accuracy=Math.max(0,1-failures.length/13),fields=PROJECT_MEMORY_EXCHANGE_SCHEMA.required.filter(key=>output[key].length>8).length/PROJECT_MEMORY_EXCHANGE_SCHEMA.required.length;return round((accuracy*.8+fields*.2)*100);}
function renderWriterMemory(output:WriterOutput){return renderProjectMemoryExchange(output);}
function invocation(result:ModelInvocationResult):ModelCall{return{output:result.output,usage:{inputTokens:result.usage.inputTokens,outputTokens:result.usage.outputTokens,totalTokens:result.usage.totalTokens,cachedInputTokens:result.usage.cachedInputTokens,cost:result.usage.providerReportedCost??result.usage.calculatedCost,currency:result.usage.currency,authority:result.usage.providerReportedCost!==null?'authoritative':result.usage.calculatedCost!==null?'calculated':'unavailable'},elapsedMs:result.elapsedMs,responseModel:result.responseModel,finishReason:result.finishReason,threadIdHash:null};}
function combineCalls(first:ModelCall,last:ModelCall):ModelCall{return{...last,usage:aggregate([first.usage,last.usage]),elapsedMs:first.elapsedMs+last.elapsedMs,threadIdHash:last.threadIdHash??first.threadIdHash};}
function codexUsage(value:Record<string,unknown>|undefined):Usage{const input=extractNumber(value,'input_tokens'),output=extractNumber(value,'output_tokens'),total=extractNumber(value,'total_tokens')??(input!==null&&output!==null?input+output:null),cached=extractNumber(value,'cached_input_tokens')??extractNested(value,['input_tokens_details','cached_tokens']);return{inputTokens:input,outputTokens:output,totalTokens:total,cachedInputTokens:cached,cost:null,currency:null,authority:'unavailable'};}
function extractNumber(value:Record<string,unknown>|undefined,key:string){const item=value?.[key];return typeof item==='number'&&Number.isFinite(item)?item:null;}
function extractNested(value:Record<string,unknown>|undefined,keys:string[]){let item:unknown=value;for(const key of keys)item=item&&typeof item==='object'&&!Array.isArray(item)?(item as Record<string,unknown>)[key]:undefined;return typeof item==='number'&&Number.isFinite(item)?item:null;}
function modelJob(id:string,name:string,action:string,capability:string,timeoutSeconds=300):JobDefinition{return job(id,name,action,capability,timeoutSeconds);}
function controlJob(id:string,name:string,action:string):JobDefinition{return job(id,name,action,'memory.control');}
function job(id:string,name:string,action:string,capability:string,timeoutSeconds=300):JobDefinition{const output=action.includes('writer')?{name:'writer-memory',type:'agent-control-memory-writer',schema:'agent-control.memory-writer/v1'}:action.includes('persist')?{name:'governed-memory',type:'agent-control-project-memory',schema:'agent-control.project-memory/v1'}:action.includes('reader')?{name:'reader-reconstruction',type:'agent-control-memory-reader',schema:'agent-control.memory-reader/v1'}:{name:'continuation-result',type:'agent-control-memory-continuation',schema:'agent-control.memory-continuation/v1'};return{apiVersion:'agent-control/v1',kind:'Job',metadata:{id,name,version:'1.0.0'},spec:{enabled:true,priority:'normal',concurrency:'allow',parameters:{pairId:{type:'string',required:true}},steps:[{id:'execute',name,action,requires:[capability],outputs:[{...output,version:'1'}],timeoutSeconds,verification:[action.includes('writer')?'writer-output-verified':action.includes('persist')?'memory-write-verified':action.includes('reader')?'reader-reconstruction-verified':'continuation-verified']}]}};}
function matrixRow(state:PairState,parcel:ReturnType<WorkParcelCoordinator['get']>){const writer=routeMap.get(state.writer)!,reader=routeMap.get(state.reader)!,readerStage=parcel.stages.find(stage=>stage.id===`${state.id}-reader`),persistStage=parcel.stages.find(stage=>stage.id===`${state.id}-persist`),continuationStage=parcel.stages.find(stage=>stage.id===`${state.id}-continue`),writerUsage=state.writerCall?.usage??unavailableUsage(),readerUsage=state.readerCall?.usage??unavailableUsage(),usage=aggregate([writerUsage,readerUsage]),result=state.continuation==='PASS'&&!state.failures.length?'PASS':'FAIL';return{writer:writer.label,reader:reader.label,writerRoute:identityText(writer),readerRoute:identityText(reader),writerNode:writer.nodeId,readerNode:reader.nodeId,memorySource:'ProjectMemoryPort / structured Markdown vault',memoryId:state.memory?.id??null,memorySha256:state.memory?.contentSha256??null,reconstructionAccuracy:state.readerScore??0,writerScore:state.writerScore??0,continuationSuccess:state.continuation==='PASS',contextInjectedTokens:state.recall?.estimatedTokens??null,writerUsage,readerUsage,usage,latencyMs:(state.writerCall?.elapsedMs??0)+(state.recall?.latencyMs??0)+(state.readerCall?.elapsedMs??0),contradictionsDetected:state.readerOutput?.contradictions??[],writerRunId:parcel.stages.find(stage=>stage.id===`${state.id}-writer`)?.runId??null,readerRunId:readerStage?.runId??null,batonSha256:readerStage?.baton?.sha256??null,persistBatonSha256:persistStage?.baton?.sha256??null,continuationBatonSha256:continuationStage?.baton?.sha256??null,writerAttempts:state.writerAttempts,readerAttempts:state.readerAttempts,failures:state.failures,failureClass:result==='PASS'?null:classifyFailure(state,parcel),result};}
function classifyFailure(state:PairState,parcel:ReturnType<WorkParcelCoordinator['get']>){const errors=parcel.stages.map(stage=>stage.error??'').join(' '),attempts=[...state.writerAttempts,...state.readerAttempts];if(/auth/i.test(errors))return'authentication unavailable';if(/transport|timeout/i.test(errors))return'transport/runtime failure';if(attempts.some(item=>!item.responseReceived||!item.validJson))return'structured-output compliance';if(attempts.some(item=>!item.applicationSchemaValid))return'prompt or schema defect';if(state.failures.length)return'model capability';if(/verif/i.test(errors))return'evidence or verification defect';return'model capability';}
function aggregate(values:Usage[]):Usage{const sum=(key:keyof Usage)=>values.length&&values.every(value=>typeof value[key]==='number')?values.reduce((total,value)=>total+(value[key] as number),0):null;const costs=values.map(value=>value.cost),currency=values.length&&values.every(value=>value.currency===values[0].currency)?values[0].currency:null;return{inputTokens:sum('inputTokens'),outputTokens:sum('outputTokens'),totalTokens:sum('totalTokens'),cachedInputTokens:sum('cachedInputTokens'),cost:costs.every(value=>typeof value==='number')?costs.reduce((a,b)=>a!+b!,0):null,currency,authority:values.length&&values.every(value=>value.authority==='authoritative')?'authoritative':values.some(value=>value.authority==='calculated')?'calculated':'unavailable'};}
function unavailableUsage():Usage{return{inputTokens:null,outputTokens:null,totalTokens:null,cachedInputTokens:null,cost:null,currency:null,authority:'unavailable'};}
function inventory(route:Route){return{id:route.id,label:route.label,provider:route.provider.id,exactModel:route.model.providerModel,qualificationVersion:route.model.qualification.version,node:route.nodeId,endpoint:route.endpoint,runtime:route.runtime,credentialResidency:route.credentialResidency,adapter:route.adapter,physicalAvailability:route.availability};}
function planFor(value:{id:string;writer:string;reader:string}):WorkParcelPlan{const writer=routeMap.get(value.writer)!,reader=routeMap.get(value.reader)!;const stages:WorkParcelPlanStage[]=[{id:`${value.id}-writer`,name:`${writer.label} writes governed memory`,job:`cross-memory-writer-${writer.id}@1.0.0`,parameters:{pairId:value.id},requestedRoute:{model:writer.model.id,reason:'Explicit physical writer route; substitution forbidden'}},{id:`${value.id}-persist`,name:'ProjectMemoryPort verifies and persists memory',job:'cross-memory-persist@1.0.0',parameters:{pairId:value.id},dependsOn:[`${value.id}-writer`]},{id:`${value.id}-reader`,name:`${reader.label} reconstructs cold`,job:`cross-memory-reader-${reader.id}@1.0.0`,parameters:{pairId:value.id},dependsOn:[`${value.id}-persist`],requestedRoute:{model:reader.model.id,reason:'Explicit physically distinct cold-reader route; substitution forbidden'}},{id:`${value.id}-continue`,name:'Execute and independently verify next Work Parcel',job:'cross-memory-continuation@1.0.0',parameters:{pairId:value.id},dependsOn:[`${value.id}-reader`,`${value.id}-persist`]}];return{objective:`Physically prove provider-neutral project-memory reconstruction and continuation for ${value.id}.`,constraints:['No model substitution','Reader execution is stateless and receives no writer transcript','Memories are advisory and cannot override evidence','No merge, tag, release or deployment'],planner:{kind:'deterministic',reason:'Operator supplied the exact physical writer/reader matrix'},stages,successCriteria:[{id:`criterion-${value.id}`,kind:'STAGE_VERIFIED',description:`${value.id} cold continuation passes`,stageId:`${value.id}-continue`,requiredEvidence:[`stage:${value.id}-continue:verified`]}]};}
function renderTranscript(report:any){const rows=report.matrix.map((row:any,index:number)=>`${index+1}. ${row.writerRoute} → ${row.readerRoute}\n   Writer run: ${row.writerRunId}; reader run: ${row.readerRunId}; baton: ${row.batonSha256}\n   Memory: ${row.memoryId} sha256:${row.memorySha256}; cold context: ${row.contextInjectedTokens} estimated tokens\n   Usage: input ${row.usage.inputTokens??'unavailable'}; output ${row.usage.outputTokens??'unavailable'}; total ${row.usage.totalTokens??'unavailable'}; cost ${row.usage.cost??'unavailable'} (${row.usage.authority})\n   Scores: writer ${row.writerScore}%; reader ${row.reconstructionAccuracy}%; continuation ${row.continuationSuccess?'PASS':'FAIL'}; result ${row.result}`).join('\n\n');return`# Agent Control 4.5 physical cross-model memory transcript\n\nThis human-readable record is derived from genuine Work Parcels, provider results, sealed batons and independent verification. It is not a simulated conversation.\n\n- Operator requests: ${report.workParcels.length} explicit POE-attributed cross-model pairs\n- Work Parcels: ${report.workParcels.map((item:any)=>`${item.id} (${item.status})`).join(', ')}\n- Evidence packet: sha256:${report.packetSha256}\n- Started: ${report.startedAt}\n- Completed: ${report.completedAt}\n\n## Natural execution record\n\n${rows}\n\n## Blocked physical routes\n\n${report.blockedRoutes.map((item:any)=>`- ${item.id}@${item.nodeId}: ${item.reason}`).join('\n')}\n\n## Verdict\n\n${report.verdict}\n`;}
function writeJson(file:string,value:unknown){fs.mkdirSync(path.dirname(file),{recursive:true,mode:0o700});const temporary=`${file}.${process.pid}.tmp`;fs.writeFileSync(temporary,`${JSON.stringify(value,null,2)}\n`,{mode:0o600});fs.renameSync(temporary,file);}
function git(args:string[]){return execFileSync('git',args,{encoding:'utf8',stdio:['ignore','pipe','ignore']}).trim();}
function round(value:number){return Math.round(value*100)/100;}

main().catch(error=>{process.stderr.write(`${error instanceof Error?error.stack:String(error)}\n`);process.exitCode=1;});
