import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {once} from 'node:events';
import {AgentControlService} from '../src/control/application-service.js';
import {buildParameterizedJobRuntime} from '../src/control/job-bootstrap.js';
import {ModelRegistry} from '../src/control/model-registry.js';
import {JobCatalog} from '../src/control/job-catalog.js';
import {ActionFailure,ActionRegistry,ArtifactStore,JobRuntime,ResourceLockManager,RunLedger,WorkerRegistry} from '../src/control/job-runtime.js';
import {WorkParcelCoordinator,WorkParcelStore} from '../src/control/work-parcels.js';
import {TokenAwareBatonRuntime} from '../src/control/token-aware-baton-routing.js';
import {CapabilityIntelligenceStore,registerAgentControlCoreCapabilities} from '../src/control/capability-intelligence.js';
import {ModelIntelligenceLedger,loadFrozenQualificationSuite} from '../src/control/model-intelligence.js';
import {ProviderCatalogRuntime,ProviderCatalogStore} from '../src/control/provider-catalog.js';
import {PtyRegistry} from '../src/control/pty.js';
import {startWebDashboard} from '../src/control/web-server.js';
import type {AgentControlConfig} from '../src/control/config.js';
import type {RepositoryReviewQualityGate} from '../src/control/direct-repository-review-executor.js';

const settings=JSON.parse(fs.readFileSync(process.argv[2],'utf8'));
const root=path.resolve(settings.stateDir);
assert(!fs.existsSync(root),'Use a fresh evidence directory for each attempt');
assert(process.env.AGENT_CONTROL_QUALIFICATION_OPERATOR_TOKEN,'Authenticated operator token required');
assert(new URL(settings.baseUrl).hostname==='127.0.0.1','Private SSH loopback forward required');
const health=await fetch(settings.baseUrl+'/health',{signal:AbortSignal.timeout(5000)});assert(health.ok,'Pixel inference endpoint unavailable');
const inventory=await (await fetch(settings.baseUrl+'/v1/models',{signal:AbortSignal.timeout(5000)})).json() as {data:Array<{id:string}>};assert(inventory.data.some(m=>m.id===settings.providerModel),'Physical model identity mismatch');
fs.mkdirSync(root,{recursive:true,mode:0o700});
const fixture=path.join(root,'arithmetic-fixture'); fs.mkdirSync(fixture);
fs.writeFileSync(path.join(fixture,'arithmetic.py'),'def add(a, b):\n    return a - b\n');
fs.writeFileSync(path.join(fixture,'README.md'),'The add function must return the sum of two integers. Review only; do not modify files.\n');
const git=(...args:string[])=>execFileSync('git',['-C',fixture,...args],{encoding:'utf8'}).trim();
git('init','-b','qualification');git('add','.');git('-c','user.name=Qualification','-c','user.email=qualification@example.invalid','commit','-m','Frozen arithmetic fixture');
const commit=git('rev-parse','HEAD');
const at=new Date().toISOString();
const config:AgentControlConfig={schemaVersion:1,resources:[{id:'controller',name:'Qualification controller',platform:'linux',transport:{type:'local'},capabilities:['qualification.review'],controller:true},{id:settings.nodeId,name:settings.deviceName,platform:'android',transport:{type:'ssh',host:settings.sshHost,port:8022,user:settings.sshUser},capabilities:['model.execute'],metadata:{experimental:true,runtime:settings.runtimeVersion}}],providers:[{id:'private-inference',name:'Private experimental inference',kind:'openai-compatible',enabled:true,baseUrl:settings.baseUrl,wireApi:'chat-completions',auth:{type:'none'},requiresAuth:false,parallelism:1,costClass:'free',capabilities:['repository-review']}],models:[{id:settings.modelId,provider:'private-inference',providerModel:settings.providerModel,displayName:settings.modelId+' | '+settings.runtimeVersion+' | experimental',enabled:true,routingEligible:false,capabilities:['repository-review'],nodes:[settings.nodeId],limits:{contextTokens:settings.contextTokens,outputTokens:1024},qualification:{state:'UNTESTED',version:'physical-qualification-pending',evidence:[settings.artifactSha256]}}],modelRouting:{roles:{}},services:[],lanes:[],jobs:{repositoryRoots:[root]},retrieval:{enabled:false}};
const capabilityIntelligence=new CapabilityIntelligenceStore(path.join(root,'capabilities.json'));registerAgentControlCoreCapabilities(capabilityIntelligence);
const modelIntelligence=new ModelIntelligenceLedger(path.join(root,'model-intelligence.json'));
const registry=new ModelRegistry(config.providers,config.models,config.modelRouting,undefined,undefined,process.env,capabilityIntelligence,modelIntelligence);
const providerCatalog=new ProviderCatalogRuntime(config.providers,new ProviderCatalogStore(path.join(root,'provider-catalog.json')),registry,modelIntelligence);
const qualificationSuite=loadFrozenQualificationSuite(path.resolve('config/qualification-suite-v1.json'));
assert.throws(()=>registry.route({model:settings.modelId,nodeId:settings.nodeId,requiredCapabilities:['repository-review'],allowFallback:false,purpose:'EXECUTION'}),'Experimental model must be excluded from execution routing');
const tokenRouting=new TokenAwareBatonRuntime(path.join(root,'token-routing.json'));
const actions=new ActionRegistry();
let jobs:ReturnType<typeof buildParameterizedJobRuntime>;
let runId:string|undefined;
const quality:Array<unknown>=[];
const gate:RepositoryReviewQualityGate={evaluate(input){const accepted=input.result.findings.some(f=>f.file==='arithmetic.py'&&/subtract|minus|a\s*-\s*b/i.test(f.evidence+' '+f.reasoning));const result={accepted,code:'arithmetic-subtraction-v1',summary:accepted?'Identified subtraction instead of addition':'Required root cause not demonstrated',evidence:['fixture:'+commit],unresolvedCriteria:accepted?[]:['Explain subtraction instead of addition'],nextAction:'No fallback configured; preserve failure'};quality.push({at:new Date().toISOString(),route:input.route,result,responseHash:input.responseHash,output:input.result});fs.writeFileSync(path.join(root,'quality.json'),JSON.stringify(quality,null,2));return result;}};
actions.register('qualification.review@1.0.0',async context=>{const parent=parcels.get(context.run.trigger.parcelContext!.parcelId);const run=jobs.runNow('experimental-inference-review','work-parcel:'+parent.id,undefined,parent.origin);runId=run.id;const done=await jobs.execute(run.id);if(!['SUCCEEDED','SUCCEEDED_WITH_FINDINGS'].includes(done.status))throw new ActionFailure('Review failed: '+done.status,'verification');return {artifacts:[{name:'result',value:done.result}],verification:['root-cause-verified']};});
const catalog=new JobCatalog(actions.ids());catalog.addJob({apiVersion:'agent-control/v1',kind:'Job',metadata:{id:'experimental-review',name:'Experimental Pixel inference review',version:'1.0.0'},spec:{priority:'normal',concurrency:'queue',steps:[{id:'review',action:'qualification.review@1.0.0',requires:['qualification.review'],timeoutSeconds:300,verification:['root-cause-verified'],outputs:[{name:'result',type:'application/json',schema:'review/v1',version:'1'}]}]}});
const workers=new WorkerRegistry().register({id:'controller',capabilities:['qualification.review'],health:'healthy',capacity:1,active:0,observedAt:at}).register({id:settings.nodeId,capabilities:['model.execute'],health:'healthy',capacity:1,active:0,observedAt:at,labels:{experimental:'true',runtime:settings.runtimeVersion,model:settings.providerModel}});
const runtime=new JobRuntime(catalog,actions,workers,new RunLedger(path.join(root,'runs.json')),new ArtifactStore(path.join(root,'artifacts')),new ResourceLockManager(path.join(root,'locks.json')));
const prompt='Review the frozen arithmetic fixture. Explain why add(2, 3) returns the wrong answer, identify the exact faulty expression, and recommend a correction. Do not modify any files. Verify the finding. Run only on the experimental Pixel model; do not substitute another model.';
const parcels=new WorkParcelCoordinator(runtime,new WorkParcelStore(path.join(root,'parcels.json')),{plan:async incoming=>{assert.equal(incoming,prompt);return {objective:incoming,planner:{kind:'deterministic',reason:'Frozen qualification request'},stages:[{id:'review',name:'Pixel-backed arithmetic review',job:'experimental-review@1.0.0'}]};}},undefined,registry);
jobs=buildParameterizedJobRuntime(config,registry,parcels,path.join(root,'parameterized'),tokenRouting,undefined,undefined,undefined,undefined,undefined,gate);
jobs.savedJobs.create({id:'experimental-inference-review',name:'Experimental Pixel inference',definition:{id:'repository-code-review',version:1,follow:'pinned'},parameters:{node:'controller',repository:fixture,ref:commit,scope:'full'},routing:{model:settings.modelId,purpose:'QUALIFICATION',allowFallback:false},contextProfile:'THIN',budgets:{timeoutMinutes:4,maximumRetries:1,retryBackoffSeconds:settings.cancelOnReconnect?20:2,maximumInputTokens:settings.contextTokens-1100,maximumOutputTokens:1024},concurrency:'forbid-overlap',enabled:true});
const service=new AgentControlService({version:1,paused:false,lastRestorePoint:null,lanes:[]},new PtyRegistry(),undefined,'4.0.0',()=>{}).configureProjection({jobRuntime:runtime,workParcels:parcels,modelRegistry:registry,capabilityIntelligence,modelIntelligence,providerCatalog,qualificationSuite,parameterizedJobs:jobs,tokenBatonRouting:tokenRouting,resources:config.resources.map(r=>({id:r.id,name:r.name??r.id,platform:r.platform,capabilities:r.capabilities,transport:r.transport.type}))});
runtime.ledger.subscribe((runId,type,status)=>service.events.emit('job.run_changed',{runId,type,status},undefined,'job-runtime'));
jobs.runs.subscribe(run=>service.events.emit('job.run_changed',{runId:run.id,status:run.status,kind:'parameterized'},undefined,'job-runtime'));
tokenRouting.subscribe(event=>service.events.emit('token.telemetry',{threadId:event.threadId,parcelId:event.parcelId},undefined,'token-runtime'));
const server=startWebDashboard(service,{host:'127.0.0.1',port:settings.dashboardPort,operatorToken:process.env.AGENT_CONTROL_QUALIFICATION_OPERATOR_TOKEN,assetsDir:path.resolve('assets/dashboard')});await once(server,'listening');
fs.writeFileSync(path.join(root,'ready.json'),JSON.stringify({prompt,cancelOnReconnect:settings.cancelOnReconnect===true,port:settings.dashboardPort,fixtureCommit:commit,config},null,2));
console.log('DASHBOARD_READY');
const until=Date.now()+900000;const pending=new Set<Promise<unknown>>();
while(Date.now()<until){await parcels.tick();for(;;){const d=runtime.dispatch();if(!d)break;const p=d.completion.finally(()=>pending.delete(p));pending.add(p);}if(runId){if(!pending.size&&['DISCONNECTED','CANCELLING'].includes(jobs.runs.get(runId)!.status))await jobs.reconcileInterrupted();const run=jobs.runs.get(runId)!;if(['DISCONNECTED','CANCELLING','SUCCEEDED','SUCCEEDED_WITH_FINDINGS','FAILED','CANCELLED','DEGRADED'].includes(run.status)&&!pending.size){const transcript=jobs.transcripts!.read(runId);fs.writeFileSync(path.join(root,'transcript.md'),transcript.content);fs.writeFileSync(path.join(root,'result.json'),JSON.stringify({run,parcels:parcels.list(),quality,events:service.events.history(),observation: ['DISCONNECTED','CANCELLING'].includes(run.status)?'Bounded observation ended with unresolved execution; no terminal cancellation claimed':'Terminal execution observed',sourceCommit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),fixtureUnchanged:git('status','--porcelain')==='',routingEligible:false},null,2));console.log('QUALIFICATION_COMPLETE '+run.status);await new Promise(r=>setTimeout(r,90000));break;}}await new Promise(r=>setTimeout(r,200));}
await Promise.allSettled(pending);jobs.transcripts?.dispose();server.close();