import {execFileSync} from 'node:child_process';
import {createHash} from 'node:crypto';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {AutomaticEvidenceRuntime,bindAutomaticEvidenceToJobs,defaultEvidencePolicy} from '../src/control/automatic-evidence.js';
import {FfmpegWindowsEvidenceProvider} from '../src/control/ffmpeg-evidence-provider.js';
import {JobCatalog} from '../src/control/job-catalog.js';
import {ActionRegistry,WorkerRegistry,createJobRuntime} from '../src/control/job-runtime.js';

const argument=(name:string)=>{const index=process.argv.indexOf(name);if(index<0||!process.argv[index+1])throw Error(`argument_required:${name}`);return path.resolve(process.argv[index+1]!);};
const blender=argument('--blender'),ffmpeg=argument('--ffmpeg'),output=argument('--output'),state=argument('--state');
fs.mkdirSync(output,{recursive:true});fs.mkdirSync(state,{recursive:true});
const ffprobe=path.join(path.dirname(ffmpeg),process.platform==='win32'?'ffprobe.exe':'ffprobe');
const action='blender.automatic-evidence-qualification@1.0.0';
const sha=(value:Buffer|string)=>createHash('sha256').update(value).digest('hex');
const sceneScript=(runId:string,holdSeconds:number)=>`import bpy, math\nfrom mathutils import Vector\nbpy.ops.object.select_all(action='SELECT')\nbpy.ops.object.delete(use_global=False)\nbpy.ops.mesh.primitive_cube_add(location=(0,0,0))\ncube=bpy.context.object\ncube.name='AgentControlEvidenceCube'\ncube.scale=(2.2,2.2,2.2)\nmat=bpy.data.materials.new('AgentControlBlue')\nmat.diffuse_color=(0.03,0.25,0.8,1)\ncube.data.materials.append(mat)\nbpy.ops.object.text_add(location=(-3.8,0,3.1),rotation=(math.pi/2,0,0))\nlabel=bpy.context.object\nlabel.data.body='AGENT CONTROL 4.17'\nlabel.data.align_x='LEFT'\nlabel.data.size=0.7\nlabel.data.extrude=0.04\nbpy.ops.object.camera_add(location=(8,-10,7),rotation=(math.radians(67),0,math.radians(38)))\ncam=bpy.context.object\nbpy.context.scene.camera=cam\ndef track(obj,point): obj.rotation_euler=(Vector(point)-obj.location).to_track_quat('-Z','Y').to_euler()\ntrack(cam,(0,0,0.5))\nbpy.ops.object.light_add(type='AREA',location=(4,-3,7))\nbpy.context.object.data.energy=1100\nbpy.context.object.data.shape='DISK'\nbpy.context.object.data.size=5\nbpy.ops.object.light_add(type='AREA',location=(-4,-1,4))\nbpy.context.object.data.energy=700\nbpy.context.object.data.color=(0.15,0.35,1.0)\ntrack(bpy.context.object,(0,0,0))\nscene=bpy.context.scene\nscene.render.engine='BLENDER_EEVEE_NEXT'\nscene.render.resolution_x=960\nscene.render.resolution_y=540\nscene.render.resolution_percentage=100\nscene.render.filepath=r'${path.join(output,`${runId}.png`).replace(/\\/g,'\\\\')}'\nscene.render.image_settings.file_format='PNG'\nbpy.ops.wm.save_as_mainfile(filepath=r'${path.join(output,`${runId}.blend`).replace(/\\/g,'\\\\')}')\nbpy.ops.render.render(write_still=True)\nfor area in bpy.context.screen.areas:\n    if area.type=='VIEW_3D':\n        area.type='IMAGE_EDITOR'\n        area.spaces.active.image=bpy.data.images.get('Render Result')\n        break\ndef finish():\n    bpy.ops.wm.quit_blender()\n    return None\nbpy.app.timers.register(finish, first_interval=${holdSeconds})\n`;

function makeRuntime(root:string,evidence:AutomaticEvidenceRuntime){
 const actions=new ActionRegistry().registerControl(action,async context=>{const hold=Number(context.parameters.holdSeconds??6),script=path.join(root,`${context.run.id}.py`);fs.writeFileSync(script,sceneScript(context.run.id,hold),'utf8');const result=await context.ownedExecution.runProcess({command:blender,args:['--factory-startup','--python',script],maxOutputBytes:2*1024*1024},context.signal);if(result.exitCode!==0)throw Error(`blender_failed:${result.exitCode}:${result.stderr.slice(-500)}`);const blend=path.join(output,`${context.run.id}.blend`),image=path.join(output,`${context.run.id}.png`);if(!fs.existsSync(blend)||!fs.existsSync(image))throw Error('blender_outputs_missing');return{verification:['blender-completed','scene-saved','render-saved'],evidence:[`scene-sha256:${sha(fs.readFileSync(blend))}`,`render-sha256:${sha(fs.readFileSync(image))}`]};});
 const catalog=new JobCatalog(actions.ids());catalog.addJob({apiVersion:'agent-control/v1',kind:'Job',metadata:{id:'automatic-evidence-blender',name:'Automatic evidence Blender qualification',version:'1.0.0'},spec:{priority:'normal',concurrency:'no-overlap',parameters:{holdSeconds:{type:'number',required:true}},steps:[{id:'render',action,requires:['blender.execute'],resources:['blender'],timeoutSeconds:90,verification:['blender-completed','scene-saved','render-saved']}]}});
 const workers=new WorkerRegistry().registerControllerInternal({id:'controller-local-blender',capabilities:['blender.execute'],health:'healthy',capacity:1,active:0,labels:{platform:process.platform},observedAt:new Date().toISOString()}),runtime=createJobRuntime(root,catalog,actions,workers);bindAutomaticEvidenceToJobs(runtime,evidence);return runtime;
}
function requiredEvidence(){return new AutomaticEvidenceRuntime({...defaultEvidencePolicy(),mode:'ON',captureRequired:true,continueWhenUnavailable:false,maximumMs:90000,maximumBytes:256*1024*1024,retention:'release-evidence'}).register(new FfmpegWindowsEvidenceProvider({executable:ffmpeg,frameRate:10,startupDeadlineMs:10000,stopDeadlineMs:15000,temporaryRoot:state}));}
function retainVideo(runtime:ReturnType<typeof makeRuntime>,runId:string,name:string){const record=runtime.artifacts.list(runId).find(item=>item.name==='automatic-visual-evidence');if(!record)throw Error('automatic_evidence_artifact_missing');const value=runtime.artifacts.read(record.id) as {manifest:{sha256:string;state:string;outcome:string;startedAt:string;endedAt:string;sourceHashes:string[];overlays:unknown[]};encoding:string;content:string};if(value.encoding!=='base64')throw Error('automatic_evidence_encoding_invalid');const bytes=Buffer.from(value.content,'base64'),file=path.join(output,name);fs.writeFileSync(file,bytes);if(sha(bytes)!==value.manifest.sha256)throw Error('automatic_evidence_checksum_mismatch');const videoInfo=JSON.parse(execFileSync(ffprobe,['-v','error','-show_entries','format=duration,size:stream=codec_name,width,height,r_frame_rate','-of','json',file],{encoding:'utf8'}));return{artifact:record,manifest:value.manifest,file,sizeBytes:bytes.length,sha256:sha(bytes),videoInfo};}

const positiveEvidence=requiredEvidence(),positiveRuntime=makeRuntime(path.join(state,'positive'),positiveEvidence),positive=positiveRuntime.createRun('automatic-evidence-blender@1.0.0',{holdSeconds:6},{type:'manual',actor:'qualification:4.17'});await positiveRuntime.tick();const positiveFinal=positiveRuntime.ledger.get(positive.id)!;if(positiveFinal.status!=='SUCCEEDED')throw Error(`positive_run_failed:${JSON.stringify(positiveFinal.errors)}`);const positiveVideo=retainVideo(positiveRuntime,positive.id,'automatic-evidence-blender-success.mp4');
let overwriteRefused=false;try{await positiveEvidence.begin({jobId:positive.id,taskType:'blender',task:'overwrite check',stage:'none',worker:'none',status:'ADMITTED'});}catch(error){overwriteRefused=(error as Error).message==='automatic_evidence_job_invalid';}
if(!overwriteRefused)throw Error('automatic_evidence_overwrite_not_refused');

const cancellationEvidence=requiredEvidence(),cancellationRuntime=makeRuntime(path.join(state,'cancellation'),cancellationEvidence),cancelled=cancellationRuntime.createRun('automatic-evidence-blender@1.0.0',{holdSeconds:60},{type:'manual',actor:'qualification:4.17'}),cancelTimer=setTimeout(()=>cancellationRuntime.cancel(cancelled.id,'qualification_cancellation'),5000);await cancellationRuntime.tick();clearTimeout(cancelTimer);const cancelledFinal=cancellationRuntime.ledger.get(cancelled.id)!;if(cancelledFinal.status!=='CANCELLED')throw Error(`cancellation_run_failed:${cancelledFinal.status}:${JSON.stringify(cancelledFinal.errors)}`);const cancellationVideo=retainVideo(cancellationRuntime,cancelled.id,'automatic-evidence-blender-cancelled.mp4');

let operationalCalls=0;const negativeEvidence=new AutomaticEvidenceRuntime({...defaultEvidencePolicy(),mode:'ON',captureRequired:true,continueWhenUnavailable:false,maximumMs:90000,maximumBytes:256*1024*1024,retention:'release-evidence'}),negativeActions=new ActionRegistry().registerControl(action,async()=>{operationalCalls++;return{verification:['blender-completed','scene-saved','render-saved']};}),negativeCatalog=new JobCatalog(negativeActions.ids());negativeCatalog.addJob({apiVersion:'agent-control/v1',kind:'Job',metadata:{id:'negative-evidence',name:'Required evidence unavailable',version:'1.0.0'},spec:{priority:'normal',concurrency:'queue',parameters:{},steps:[{id:'render',action,requires:['blender.execute'],verification:['blender-completed','scene-saved','render-saved']}]}});const negativeWorkers=new WorkerRegistry().registerControllerInternal({id:'negative-worker',capabilities:['blender.execute'],health:'healthy',capacity:1,active:0,labels:{},observedAt:new Date().toISOString()}),negativeRuntime=createJobRuntime(path.join(state,'negative'),negativeCatalog,negativeActions,negativeWorkers);bindAutomaticEvidenceToJobs(negativeRuntime,negativeEvidence);const negative=negativeRuntime.createRun('negative-evidence@1.0.0',{}, {type:'manual',actor:'qualification:4.17'});await negativeRuntime.tick();const negativeFinal=negativeRuntime.ledger.get(negative.id)!;if(negativeFinal.status!=='FAILED'||operationalCalls!==0||negativeFinal.steps[0]!.attempts.length!==0)throw Error('negative_admission_gate_failed');

const report={schema:'agent-control.automatic-evidence-physical-qualification/v1',verdict:'PASS',qualifiedAt:new Date().toISOString(),host:os.hostname(),platform:process.platform,sourceCommit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),executables:{blender,ffmpeg,ffprobe},policy:{mode:'ON',captureRequired:true,continueWhenUnavailable:false,maximumMs:90000,maximumBytes:256*1024*1024,retention:'release-evidence'},positive:{run:{id:positive.id,status:positiveFinal.status,startedAt:positiveFinal.startedAt,endedAt:positiveFinal.endedAt,attempts:positiveFinal.steps[0]!.attempts.length,selectedWorkers:positiveFinal.selectedWorkers},video:positiveVideo,overwriteRefused},cancellation:{run:{id:cancelled.id,status:cancelledFinal.status,startedAt:cancelledFinal.startedAt,endedAt:cancelledFinal.endedAt,errors:cancelledFinal.errors,cleanup:cancelledFinal.steps[0]!.cleanup},video:cancellationVideo},negative:{run:{id:negative.id,status:negativeFinal.status,errors:negativeFinal.errors,attempts:negativeFinal.steps[0]!.attempts.length},operationalCalls,manifest:negativeEvidence.list()[0]},checks:{normalJobLifecycle:true,providerRegistered:true,capturePreDispatch:Date.parse(positiveVideo.manifest.startedAt)<=Date.parse(positiveFinal.steps[0]!.attempts[0]!.startedAt),playableMp4:true,overlaySourceHashes:positiveVideo.manifest.sourceHashes.length>0,immutableOverwriteRefused:overwriteRefused,cancellationFinalized:cancellationVideo.manifest.outcome==='CANCELLED',requiredUnavailableZeroDispatch:operationalCalls===0&&negativeFinal.steps[0]!.attempts.length===0}};
if(Object.values(report.checks).some(value=>!value))throw Error(`qualification_check_failed:${JSON.stringify(report.checks)}`);fs.writeFileSync(path.join(output,'automatic-evidence-physical-qualification.json'),`${JSON.stringify(report,null,2)}\n`);process.stdout.write(`${JSON.stringify(report,null,2)}\n`);
