import assert from 'node:assert/strict';
import {createHash,randomBytes} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import {createRequire} from 'node:module';
import {once} from 'node:events';
import type {AddressInfo} from 'node:net';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {startWebDashboard} from '../src/control/web-server.js';
import {sealUxSession,UxSessionAnnotationStore,UxSessionShareStore,UxSessionStore,type UxSessionEvent,type UxSessionLane} from '../src/control/ux-session.js';

const require=createRequire(import.meta.url),sourceRoot=path.resolve(process.env.AGENT_CONTROL_MEMORY_POE_ROOT??'/fast/qualification/agent-control-4.5-cross-model-memory-poe-20260911'),reportFile=path.join(sourceRoot,'cross-model-memory-qualification.json'),runsFile=path.join(sourceRoot,'runtime','runs.json');
const output=path.join(sourceRoot,'ux-evidence'),temporary=fs.mkdtempSync(path.join(os.tmpdir(),'agent-control-memory-video-')),rawVideo=path.join(temporary,'video');fs.mkdirSync(output,{recursive:true});fs.mkdirSync(rawVideo,{recursive:true});
const sourceBytes=fs.readFileSync(reportFile),report=JSON.parse(sourceBytes.toString('utf8')),runStore=JSON.parse(fs.readFileSync(runsFile,'utf8')),runs:Array<any>=Array.isArray(runStore)?runStore:(runStore.runs??Object.values(runStore));
assert.equal(report.poe?.productionFlow,true,'production_poe_flow_missing');assert.equal(report.matrix.length,1,'poe_video_requires_one_pair');
const row=report.matrix[0],parcel=report.workParcels[0],conversation=report.poe.conversation,events:UxSessionEvent[]=[];
const push=(event:Omit<UxSessionEvent,'parentIds'|'evidenceRefs'>&{parentIds?:string[];evidenceRefs?:string[]})=>events.push({...event,parentIds:event.parentIds??[],evidenceRefs:event.evidenceRefs??[]});
for(const turn of conversation.turns){push({id:turn.id,at:turn.at,layer:'UX',kind:turn.actor==='operator'?'USER_INTERACTION':'POE',title:turn.actor==='operator'?'Operator typed the qualification request into POE':'POE responded from governed evidence',summary:turn.text,outcome:'INFO',interaction:{actor:turn.actor,action:turn.actor==='operator'?'submit request':'reply'}});}
push({id:`${parcel.id}:accepted`,at:report.startedAt,layer:'AGENT_CONTROL',kind:'WORK_PARCEL',title:'POE-created Work Parcel accepted',summary:`${parcel.id} entered the normal governed coordinator with an immutable cross-model plan.`,outcome:'RUNNING',parentIds:conversation.turns.map((turn:any)=>turn.id),evidenceRefs:[report.packetSha256]});
const writerRun=runs.find(run=>run.id===row.writerRunId),readerRun=runs.find(run=>run.id===row.readerRunId),writerAt=writerRun?.startedAt??report.startedAt,writerEnd=writerRun?.endedAt??writerRun?.completedAt??report.completedAt,readerAt=readerRun?.startedAt??writerEnd,readerEnd=readerRun?.endedAt??readerRun?.completedAt??report.completedAt;
push({id:`${row.writerRunId}:writer`,at:writerAt,layer:'AGENT_CONTROL',kind:'MODEL',title:`Writer invoked — ${row.writer}`,summary:`${row.writerRoute} performed real compression work.`,outcome:'RUNNING',laneId:'writer',provider:routeProvider(row.writerRoute),model:row.writer,parentIds:[`${parcel.id}:accepted`],evidenceRefs:[report.packetSha256]});
push({id:`${row.writerRunId}:usage`,at:writerEnd,layer:'TELEMETRY',kind:'TELEMETRY',title:'Writer usage retained',summary:'Provider/model usage is recorded separately from the later reader leg.',outcome:'PASSED',laneId:'writer',provider:routeProvider(row.writerRoute),model:row.writer,parentIds:[`${row.writerRunId}:writer`],telemetry:telemetry(row.writerUsage)});
push({id:`${row.memoryId}:memory`,at:writerEnd,layer:'AGENT_CONTROL',kind:'MEMORY',title:'Your Memories record verified and persisted',summary:`ProjectMemoryPort atomically persisted ${row.memoryId}; SHA-256 ${row.memorySha256}. The writer transcript is not supplied to the reader.`,outcome:'PASSED',laneId:'memory',parentIds:[`${row.writerRunId}:usage`],evidenceRefs:[row.memorySha256],memory:{operation:'SUPPLIED',contentExposed:false,provenance:[report.packetSha256,row.memorySha256]}});
push({id:`${row.batonSha256}:baton`,at:readerAt,layer:'AGENT_CONTROL',kind:'BATON',title:'Sealed baton handed to the cold-reader stage',summary:`The baton SHA-256 ${row.batonSha256} carries bounded artifact references and route identity, not the originating model transcript.`,outcome:'PASSED',laneId:'memory',parentIds:[`${row.memoryId}:memory`],evidenceRefs:[row.batonSha256]});
push({id:`${row.readerRunId}:reader`,at:readerAt,layer:'AGENT_CONTROL',kind:'MODEL',title:`Cold reader invoked — ${row.reader}`,summary:`${row.readerRoute} started as a new stateless provider execution with ${row.contextInjectedTokens} estimated retrieval tokens.`,outcome:'RUNNING',laneId:'reader',provider:routeProvider(row.readerRoute),model:row.reader,parentIds:[`${row.batonSha256}:baton`],evidenceRefs:[row.memorySha256]});
push({id:`${row.readerRunId}:usage`,at:readerEnd,layer:'TELEMETRY',kind:'TELEMETRY',title:'Cold-reader reconstruction measured',summary:`Reconstruction score ${row.reconstructionAccuracy}%. Continuation ${row.continuationSuccess?'passed':'failed'}.`,outcome:row.result==='PASS'?'PASSED':'FAILED',laneId:'reader',provider:routeProvider(row.readerRoute),model:row.reader,parentIds:[`${row.readerRunId}:reader`],telemetry:telemetry(row.readerUsage)});
push({id:`${parcel.id}:verification`,at:report.completedAt,layer:'AGENT_CONTROL',kind:'OUTCOME',title:`Independent verification — ${row.result}`,summary:row.result==='PASS'?'The cold reader recovered the required state and its selected integrity action passed independent deterministic verification.':`The result remained failed closed: ${row.failures.join('; ')||'a required stage failed'}.`,outcome:row.result==='PASS'?'PASSED':'FAILED',laneId:'verification',parentIds:[`${row.readerRunId}:usage`],evidenceRefs:[row.continuationBatonSha256??row.batonSha256]});
push({id:`${parcel.id}:accounting`,at:report.completedAt,layer:'TELEMETRY',kind:'TELEMETRY',title:'Writer + reader accounting reconciled',summary:`${row.writer} ${row.writerUsage.totalTokens??'unavailable'} → ${row.reader} ${row.readerUsage.totalTokens??'unavailable'} = ${row.usage.totalTokens??'unavailable'} total tokens. Monetary cost remains unavailable where a provider did not report or price it.`,outcome:'PASSED',parentIds:[`${parcel.id}:verification`],telemetry:telemetry(row.usage)});
const lanes:UxSessionLane[]=[lane('writer','Memory Writer',routeProvider(row.writerRoute),row.writer,row.writerUsage,row.writerScore),lane('memory','Your Memories','Agent Control','ProjectMemoryPort',{inputTokens:0,outputTokens:0,totalTokens:0,cachedInputTokens:0,cost:0,currency:null,authority:'authoritative'},100),lane('reader','Cold Reader',routeProvider(row.readerRoute),row.reader,row.readerUsage,row.reconstructionAccuracy),lane('verification','Independent Verifier','Agent Control','deterministic integrity gate',{inputTokens:0,outputTokens:0,totalTokens:0,cachedInputTokens:0,cost:0,currency:null,authority:'authoritative'},row.continuationSuccess?100:0)];
const session=sealUxSession({id:'ux-agent-control-4.5-cross-model-memory',title:'Your Memories — Real Cross-Model Continuation',startedAt:report.startedAt,completedAt:report.completedAt,sources:[{kind:'qualification-evidence',reference:reportFile,sha256:sha(sourceBytes),authority:'Physical Agent Control Work Parcel, POE conversation, provider calls, sealed batons and deterministic verification'}],events,lanes,outcome:{verdict:row.result,summary:`${row.writer} wrote governed memory; ${row.reader} reconstructed cold and continuation ${row.continuationSuccess?'passed':'failed'}.`,selectedLaneId:'reader',escalationInvoked:false},totals:{inputTokens:row.usage.inputTokens,outputTokens:row.usage.outputTokens,totalTokens:row.usage.totalTokens,cost:row.usage.cost,currency:row.usage.currency,authority:row.usage.authority==='authoritative'?'AUTHORITATIVE':'PARTIAL'},artifacts:[]});
const stores={sessions:new UxSessionStore(path.join(temporary,'sessions')),shares:new UxSessionShareStore(path.join(temporary,'shares.json')),annotations:new UxSessionAnnotationStore(path.join(temporary,'annotations.json'))};stores.sessions.write(session);const share=stores.shares.create(session,'SANITISED_DIAGNOSTIC',{expiresAt:'2026-12-31T23:59:59.000Z'}),token=randomBytes(32).toString('hex'),server=startWebDashboard({} as never,{host:'127.0.0.1',port:0,operatorToken:token,assetsDir:path.resolve('assets/dashboard'),uxSessions:stores.sessions,uxSessionShares:stores.shares,uxSessionAnnotations:stores.annotations,uxSessionPlayerDir:path.resolve('assets/session-player')});await once(server,'listening');const base=`http://127.0.0.1:${(server.address() as AddressInfo).port}`;
let browser:any,context:any,video:any;const errors:string[]=[];try{const {chromium}=require('playwright-core');browser=await chromium.launch({headless:true,executablePath:process.env.AGENT_CONTROL_CHROMIUM??'/snap/bin/chromium',args:['--no-sandbox','--disable-dev-shm-usage']});context=await browser.newContext({viewport:{width:1920,height:1080},recordVideo:{dir:rawVideo,size:{width:1920,height:1080}},colorScheme:'dark'});const page=await context.newPage();video=page.video();page.on('pageerror',(error:any)=>errors.push(error.message));page.on('console',(message:any)=>{if(message.type()==='error')errors.push(message.text())});await page.goto(`${base}${share.url}`,{waitUntil:'networkidle'});await page.waitForSelector('.lane');assert.equal(await page.locator('.lane').count(),4);await page.screenshot({path:path.join(output,'cross-model-memory-replay.png'),fullPage:true});await page.click('#play');await page.waitForTimeout(Math.max(20_000,events.length*1_600));await page.selectOption('#layer','TELEMETRY');await page.waitForTimeout(3_000);await page.selectOption('#layer','ALL');await page.locator('button[data-index]').last().click();await page.waitForTimeout(3_000);await context.close();context=undefined;const raw=await video.path();await browser.close();browser=undefined;execFileSync('ffmpeg',['-nostdin','-y','-loglevel','error','-i',raw,'-an','-c:v','libx264','-preset','medium','-crf','18','-pix_fmt','yuv420p','-movflags','+faststart',path.join(output,'agent-control-4.5-cross-model-memory.mp4')]);}finally{if(context)await context.close().catch(()=>{});if(browser)await browser.close().catch(()=>{});server.close();fs.rmSync(temporary,{recursive:true,force:true});}
assert.deepEqual(errors,[]);fs.writeFileSync(path.join(output,'canonical-session.json'),JSON.stringify(session,null,2)+'\n');fs.writeFileSync(path.join(output,'complete-human-readable-transcript.md'),renderTranscript(session,report.poe.transcript));const generated=['canonical-session.json','complete-human-readable-transcript.md','cross-model-memory-replay.png','agent-control-4.5-cross-model-memory.mp4'].map(file=>{const bytes=fs.readFileSync(path.join(output,file));return{file,bytes:bytes.length,sha256:sha(bytes)}}),videoInfo=JSON.parse(execFileSync('ffprobe',['-v','error','-show_entries','format=duration,size:stream=codec_name,width,height,r_frame_rate','-of','json',path.join(output,'agent-control-4.5-cross-model-memory.mp4')],{encoding:'utf8'})),manifest={schema:'agent-control.cross-model-memory-ux-evidence/v1',verdict:row.result==='PASS'?'PASS_PHYSICAL_POE_CROSS_MODEL_MEMORY_UX':'PARTIAL',qualifiedAt:new Date().toISOString(),implementationCommit:report.implementationCommit,source:{file:reportFile,sha256:sha(sourceBytes),parcelId:parcel.id,writerRunId:row.writerRunId,readerRunId:row.readerRunId,memorySha256:row.memorySha256,batonSha256:row.batonSha256},session:{id:session.id,sha256:session.sha256},generated,videoInfo,browserErrors:errors};fs.writeFileSync(path.join(output,'evidence-manifest.json'),JSON.stringify(manifest,null,2)+'\n');process.stdout.write(JSON.stringify({output,verdict:manifest.verdict,video:generated.find(item=>item.file.endsWith('.mp4')),transcript:generated.find(item=>item.file.endsWith('.md'))},null,2)+'\n');

function lane(id:string,name:string,provider:string,model:string,usage:any,score:number):UxSessionLane{return{id,name,provider,model,outcome:score>=80?'PASSED':'FAILED',inputTokens:usage.inputTokens,outputTokens:usage.outputTokens,totalTokens:usage.totalTokens,cost:usage.cost,currency:usage.currency};}
function telemetry(usage:any){return{inputTokens:usage.inputTokens,outputTokens:usage.outputTokens,totalTokens:usage.totalTokens,cachedTokens:usage.cachedInputTokens,cost:usage.cost,currency:usage.currency,authority:(usage.authority==='authoritative'?'AUTHORITATIVE':usage.totalTokens!==null?'ESTIMATED':'UNAVAILABLE') as 'AUTHORITATIVE'|'ESTIMATED'|'UNAVAILABLE'};}
function routeProvider(value:string){return String(value).split('/')[0]||'unavailable';}
function renderTranscript(session:any,poeTranscript:string){return`# Agent Control 4.5 complete cross-model memory transcript\n\n## Natural POE conversation\n\n${poeTranscript}\n\n## Governed execution\n\n${session.events.map((event:any,index:number)=>`### ${String(index+1).padStart(2,'0')} · ${event.at} · ${event.title}\n\n- Kind: ${event.kind}\n- Lane: ${event.laneId??'none'}\n- Provider/model: ${event.provider??'unavailable'} / ${event.model??'unavailable'}\n- Outcome: ${event.outcome??'INFO'}\n- Evidence: ${event.evidenceRefs.join(', ')||'none'}\n\n${event.summary}`).join('\n\n')}\n\n## Integrity\n\nCanonical UX session: \`${session.id}\` / \`${session.sha256}\`. This transcript excludes private reasoning and credentials.\n`;}
function sha(value:string|Buffer){return createHash('sha256').update(value).digest('hex');}
