import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {execFileSync} from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const root=path.resolve('qualification/agent-control-4.5-release-gate-20260912'),sources=path.join(root,'source-reruns');fs.mkdirSync(sources,{recursive:true,mode:0o700});
const historical=read('docs/evidence/agent-control-4.5-cross-model-memory-qualification-20260911.json');
const v2=read('/fast/qualification/agent-control-4.5-memory-gap-rerun-v2-20260912/cross-model-memory-qualification.json');
const v3=read('/fast/qualification/agent-control-4.5-memory-gap-rerun-v3-20260912/cross-model-memory-qualification.json');
const glm=read('/fast/qualification/agent-control-4.5-memory-gap-glm-final-20260912/cross-model-memory-qualification.json');
const pixel=read('/fast/qualification/agent-control-4.5-memory-gap-pixel-rerun-20260912/cross-model-memory-qualification.json');
const msi=read('qualification/agent-control-4.5-msi-memory-20260912/msi-memory-transition.json'),residency=read('qualification/agent-control-4.5-residency-20260912/residency.json');
compactLiveSnapshots();
for(const [name,value] of [['prompt-repair-v2',v2],['field-mapping-v3',v3],['glm-final',glm],['pixel-final',pixel]])write(path.join(sources,`${name}.json`),value);
const hfail=historical.matrix.filter(row=>row.result!=='PASS'),by=(report,writer,reader)=>report.matrix.find(row=>row.writerRoute.includes(writer)&&row.readerRoute.includes(reader));
const lunaQwen=by(v3,'codex-luna','local-qwen'),qwenLuna=by(v2,'local-qwen','codex-luna'),glmQwen=glm.matrix[0];
let pixelWriter=0,pixelReader=0;
const failures=hfail.map((row,index)=>{let classification,latest,reason;if(row.writerRoute.includes('pixel-gemma')){latest=pixel.matrix.filter(item=>item.writerRoute.includes('pixel-gemma'))[pixelWriter++];classification='structured-output compliance';reason='The exact Pixel Gemma E4B writer returned no application-valid structured writer record after the bounded repair path.';}else if(row.readerRoute.includes('pixel-gemma')){latest=pixel.matrix.filter(item=>item.readerRoute.includes('pixel-gemma'))[pixelReader++];classification='model capability';reason='The exact Pixel Gemma E4B reader was reached but did not reconstruct the complete semantic contract.';}else if(row.writerRoute.includes('glm-5.3')){latest=glmQwen;classification='model capability';reason='GLM returned a complete schema-valid memory; Qwen returned schema-valid reader JSON twice but omitted required semantics.';}else if(row.writerRoute.includes('codex-luna')){latest=lunaQwen;classification='prompt or schema defect';reason='The same routes passed after explicit provider-neutral semantic field mapping, with the verifier unchanged or strengthened.';}else{latest=qwenLuna;classification='prompt or schema defect';reason='The same routes passed after governed repair and explicit field mapping, with exact semantic verification retained.';}return{id:`historical-failure-${index+1}`,writerRoute:row.writerRoute,readerRoute:row.readerRoute,historicalResult:row.result,classification,reason,latestResult:latest?.result??'NOT TESTED',latestFailureClass:latest?.failureClass??null,latestFailures:latest?.failures??[],writerAttempts:latest?.writerAttempts??[],readerAttempts:latest?.readerAttempts??[],reconstructionAccuracy:latest?.reconstructionAccuracy??null,continuationSuccess:latest?.continuationSuccess??false,usage:latest?.usage??null};});
assert.equal(failures.length,7);assert.ok(failures.every(item=>['model capability','structured-output compliance','prompt or schema defect','transport/runtime failure','authentication unavailable','node unavailable','evidence or verification defect'].includes(item.classification)));
const matrix={schema:'agent-control.4.5-memory-gap-matrix/v1',generatedAt:new Date().toISOString(),historical:{passed:historical.matrix.filter(row=>row.result==='PASS').length,total:historical.matrix.length},failedCells:failures,rerunSummary:{resolved:failures.filter(item=>item.latestResult==='PASS').length,stillFailed:failures.filter(item=>item.latestResult==='FAIL').length,notTested:failures.filter(item=>item.latestResult==='NOT TESTED').length},contract:{semanticReconstructionRequired:true,keywordOnlyPassForbidden:true,verificationWeakened:false}};write(path.join(root,'memory-matrix.json'),matrix);write(path.join(root,'failure-analysis.json'),{schema:'agent-control.4.5-failure-analysis/v1',categories:['model capability','structured-output compliance','prompt or schema defect','transport/runtime failure','authentication unavailable','node unavailable','evidence or verification defect'],failures});write(path.join(root,'energy-evidence.json'),{schema:'agent-control.4.5-energy-reconciliation/v1',specialistEnergy:{status:'DISPROVEN',source:'docs/evidence/agent-control-4.5-specialist-energy-qualification-20260911.json',reason:'The qualified specialist used more measured-component energy per verified result than warm Qwen.'},residency:{status:'PARTIAL',...residency},wholeNode:{status:'BLOCKED',reason:'No synchronized whole-node meter was available; component measurements are not relabelled as whole-system energy.'},routingPolicyChanged:false});
const gates=[gate('Governed deterministic-skill lifecycle','PROVEN','45/45 promoted deterministic executions passed; changed input rejected and governed fallback passed.'),gate('Your Memories cross-model matrix','PARTIAL',`${matrix.historical.passed}/${matrix.historical.total} historical cells passed; ${matrix.rerunSummary.resolved} failed cells were repaired and rerun successfully, while genuine model limitations remain.`),gate('MSI cross-node memory transition','BLOCKED','Both governed node-local Codex profiles returned codex_chatgpt_auth_required; no transition was claimed.'),gate('Strong-model memory consolidation','DISPROVEN','The measured consolidated-memory average fell from 66.67% to 50%.'),gate('Specialist-model energy advantage','DISPROVEN','The retained specialist consumed more measured-component energy per verified result than warm Qwen.'),gate('Deterministic reuse benefit','PROVEN','Repository/test skills reduced measured-component joules per verified result by 99.37–99.45%; baton check reached zero incremental after baseline subtraction.'),gate('Fallback after deterministic rejection','PROVEN','Novel input was rejected before deterministic execution and the ordinary model fallback passed independent verification.'),gate('Production POE Work Parcel','PROVEN','A real POE request created a Job/Work Parcel, executed the selected route, sealed batons and passed independent verification.'),gate('Warm residency route effect','PARTIAL',`Measured component delta ${residency.deltaWatts??'unavailable'} W was smaller than the approximate 95% uncertainty ${residency.uncertaintyWatts95Approx??'unavailable'} W; no policy change was admitted.`),gate('Whole-node power claim','BLOCKED','The available RAPL plus GPU-board boundary excludes motherboard, storage, PSU losses, networking and peripherals.')];
const liveManifest=read(path.join(root,'live-poe-run','live-evidence-manifest.json')),liveReport=read(path.join(root,'live-poe-run','cross-model-memory-qualification.json'));
gates.push(gate('Fresh genuine-runtime HD evidence','PROVEN',`Live observer recorded the real POE-created Work Parcel while durable stages changed; ${liveManifest.video.streams?.[0]?.width??1920}×${liveManifest.video.streams?.[0]?.height??1080}.`));
const runtimeSourceFiles=['scripts/qualify-cross-model-memory-4.5.ts','scripts/record-live-memory-qualification-4.5.mjs'].map(file=>({file,sha256:sha(fs.readFileSync(file))}));
const report={schema:'agent-control.4.5-release-gate/v1',generatedAt:new Date().toISOString(),branch:exec('git',['branch','--show-current']),implementationHead:exec('git',['rev-parse','HEAD']),runtimeSourceFiles,releasedBaseline:'v4.4.0',recommendation:'EXPERIMENTAL',gates,summary:{proven:gates.filter(x=>x.status==='PROVEN').length,partial:gates.filter(x=>x.status==='PARTIAL').length,disproven:gates.filter(x=>x.status==='DISPROVEN').length,blocked:gates.filter(x=>x.status==='BLOCKED').length,notTested:gates.filter(x=>x.status==='NOT TESTED').length},msi,memory:matrix,security:{credentialValuesPersisted:false,privateReasoningPersisted:false,providerOutputsSanitized:true},releaseActions:{merge:false,tag:false,release:false,deploy:false}};write(path.join(root,'release-gate.json'),report);
fs.writeFileSync(path.join(root,'complete-human-readable-transcript.md'),transcript(report),{mode:0o600});fs.writeFileSync('docs/evidence/agent-control-4.5-release-gate-20260912.md',markdown(report),{mode:0o644});
const files=walk(root).filter(file=>!file.endsWith('evidence-manifest.json')).map(file=>{const bytes=fs.readFileSync(file);return{file:path.relative(root,file),bytes:bytes.length,sha256:sha(bytes)};});write(path.join(root,'evidence-manifest.json'),{schema:'agent-control.4.5-evidence-manifest/v1',generatedAt:new Date().toISOString(),implementationHead:report.implementationHead,files});
console.log(JSON.stringify({root,report:path.resolve(root,'release-gate.json'),documentation:path.resolve('docs/evidence/agent-control-4.5-release-gate-20260912.md'),recommendation:report.recommendation,summary:report.summary,files:files.length},null,2));
function gate(name,status,evidence){return{name,status,evidence};}function read(file){return JSON.parse(fs.readFileSync(file,'utf8'));}function write(file,value){fs.mkdirSync(path.dirname(file),{recursive:true,mode:0o700});fs.writeFileSync(file,JSON.stringify(value,null,2)+'\n',{mode:0o600});}function sha(value){return createHash('sha256').update(value).digest('hex');}function exec(command,args){return execFileSync(command,args,{encoding:'utf8'}).trim();}function walk(directory){return fs.readdirSync(directory,{withFileTypes:true}).flatMap(entry=>{const file=path.join(directory,entry.name);return entry.isDirectory()?walk(file):[file];});}
function compactLiveSnapshots(){const file=path.join(root,'live-poe-run','live-runtime-snapshots.json'),record=read(file);if(record.schema==='agent-control.live-memory-observer-compacted/v1')return;const transitions=[],seen=new Set();for(const item of record.snapshots??[]){const projection={at:item.at,parcel:item.parcel?{id:item.parcel.id,status:item.parcel.status,stages:item.parcel.stages.map(stage=>({id:stage.id,status:stage.status,runId:stage.runId??null,batonSha256:stage.baton?.sha256??null,route:stage.actualRoute?{provider:stage.actualRoute.provider,model:stage.actualRoute.model,node:stage.actualRoute.providerExecutionNodeId??stage.actualRoute.workloadNodeId}:null}))}:null,runs:item.runs,report:item.report?{verdict:item.report.verdict,totals:item.report.totals,matrix:item.report.matrix.map(row=>({writerRoute:row.writerRoute,readerRoute:row.readerRoute,result:row.result,reconstructionAccuracy:row.reconstructionAccuracy,continuationSuccess:row.continuationSuccess,usage:row.usage,memorySha256:row.memorySha256,batonSha256:row.batonSha256}))}:null},signature=JSON.stringify({...projection,at:undefined});if(seen.has(signature))continue;seen.add(signature);transitions.push(projection);}write(file,{schema:'agent-control.live-memory-observer-compacted/v1',startedAt:record.startedAt,completedAt:record.completedAt,prompt:record.prompt,sampleCount:record.snapshots?.length??0,transitions});const manifestFile=path.join(root,'live-poe-run','live-evidence-manifest.json'),manifest=read(manifestFile),bytes=fs.readFileSync(file),entry=manifest.files.find(item=>item.file==='live-runtime-snapshots.json');if(entry){entry.bytes=bytes.length;entry.sha256=sha(bytes);}manifest.liveObservation={rawSampleCount:record.snapshots?.length??0,durableTransitions:transitions.length,compaction:'Consecutive and repeated full-store observations reduced to distinct state transitions; final durable stores remain preserved.'};write(manifestFile,manifest);}
function transcript(report){const live=liveReport.matrix[0];return`# Agent Control 4.5 complete release-gate transcript\n\nThis transcript is rendered from real governed Work Parcels and sanitized provider results. It excludes credentials and private reasoning. Failures are retained.\n\n## Fresh natural POE execution\n\n${liveReport.poe?.transcript??'[POE transcript unavailable]'}\n\n- Work Parcel: ${liveReport.workParcels[0].id} (${liveReport.workParcels[0].status})\n- Route: ${live.writerRoute} → ${live.readerRoute}\n- Batons: ${liveReport.workParcels[0].stages.map(stage=>`${stage.id}=${stage.batonSha256??'none'}`).join('; ')}\n- Memory SHA-256: ${live.memorySha256}\n- Usage: writer ${live.writerUsage.totalTokens??'unavailable'} + reader ${live.readerUsage.totalTokens??'unavailable'} = ${live.usage.totalTokens??'unavailable'} tokens\n- Monetary cost: ${live.usage.cost??'unavailable'} (${live.usage.authority})\n- Reconstruction: ${live.reconstructionAccuracy}%\n- Continuation and independent verification: ${live.continuationSuccess?'PASS':'FAIL'}\n\n${[...live.writerAttempts.map(x=>['Writer',x]),...live.readerAttempts.map(x=>['Cold reader',x])].map(([role,a])=>`### ${role} attempt ${a.attempt}\n\n- Response received: ${a.responseReceived}\n- Finish reason: ${a.finishReason??'unavailable'}\n- Valid JSON/application schema: ${a.validJson}/${a.applicationSchemaValid}\n- Semantic failures: ${a.semanticFailures.join('; ')||'none'}\n- Response SHA-256: ${a.sha256??'unavailable'}\n\n\`\`\`json\n${cleanOutput(a.sanitizedOutput)}\n\`\`\``).join('\n\n')}\n\n## Release-gate decisions\n\n${report.gates.map((item,index)=>`### ${index+1}. ${item.name} — ${item.status}\n\n${item.evidence}`).join('\n\n')}\n\n## Cross-model failed-cell evidence\n\n${failures.map((item,index)=>`### ${index+1}. ${item.writerRoute} → ${item.readerRoute}\n\n- Classification: **${item.classification}**\n- Historical result: ${item.historicalResult}\n- Latest result: ${item.latestResult}\n- Reconstruction: ${item.reconstructionAccuracy??'unavailable'}%\n- Continuation: ${item.continuationSuccess?'PASS':'FAIL'}\n- Reason: ${item.reason}\n- Exact failures: ${item.latestFailures.join('; ')||'none'}\n\n${[...item.writerAttempts.map(x=>['Writer',x]),...item.readerAttempts.map(x=>['Reader',x])].map(([role,a])=>`#### ${role} attempt ${a.attempt}\n\n- Response received: ${a.responseReceived}\n- Complete/finish reason: ${a.finishReason??'unavailable'}\n- Valid JSON: ${a.validJson}\n- Application schema valid: ${a.applicationSchemaValid}\n- Schema failures: ${a.schemaFailures.join('; ')||'none'}\n- Semantic failures: ${a.semanticFailures.join('; ')||'none'}\n- Response SHA-256: ${a.sha256??'unavailable'}\n\n\`\`\`json\n${cleanOutput(a.sanitizedOutput)}\n\`\`\``).join('\n\n')}`).join('\n\n')}\n\n## Final recommendation\n\n**EXPERIMENTAL** — no merge, tag, release or deployment is authorized by this evidence.\n`;}
function cleanOutput(value){return(value||'[no provider response retained]').split('\n').map(line=>line.trimEnd()).join('\n');}
function markdown(report){return`# Agent Control 4.5 authoritative release-gate reconciliation\n\nStatus: **EXPERIMENTAL**. This report does not authorize merge, tag, release or deployment.\n\n## Results\n\n| Gate | Status | Evidence |\n| --- | --- | --- |\n${report.gates.map(x=>`| ${x.name} | **${x.status}** | ${x.evidence.replace(/\|/g,'\\|')} |`).join('\n')}\n\n## Memory failure classification\n\nAll seven historical failed cells are classified in the [machine-readable matrix](../../qualification/agent-control-4.5-release-gate-20260912/memory-matrix.json). Provider-neutral field mapping and a governed repair attempt resolved Luna→Qwen and Qwen→Luna without weakening semantic verification. GLM→Qwen remains a schema-valid semantic failure. Pixel E4B failures remain preserved rather than simulated or counted as passes.\n\n## MSI\n\nBoth configured MSI Codex profiles were checked through the production governed node port. Both returned \`codex_chatgpt_auth_required\`; therefore cross-node model continuation is **BLOCKED**, not failed or passed. No credential material or node-local credential path was persisted.\n\n## Power and residency\n\nThe follow-up measured synchronized Intel package + DRAM and NVIDIA board samples for idle and a warm resident specialist. The observed difference was within uncertainty, so residency break-even is unavailable and no routing policy changed. This is not whole-node evidence.\n\n## Fresh POE runtime evidence\n\nThe [HD video](../../qualification/agent-control-4.5-release-gate-20260912/live-poe-run/agent-control-4.5-live-poe-memory-qualification.mp4) records a fresh genuine POE-created Work Parcel while the durable runtime changes. The page is explicitly a read-only qualification observer, not a replay or a substitute production dashboard. It shows the real operator request, Job/Run identities, stages, provider/model routes, sealed baton hashes, verification and final token accounting. See the [complete transcript](../../qualification/agent-control-4.5-release-gate-20260912/complete-human-readable-transcript.md) and [manifest](../../qualification/agent-control-4.5-release-gate-20260912/evidence-manifest.json).\n\n## Recommendation\n\n**EXPERIMENTAL**. Useful deterministic-skill and provider-neutral memory mechanisms are proven, but model capability failures, blocked MSI authentication, disproven specialist energy advantage and unavailable whole-node power evidence keep mandatory gates open.\n`;}
